obj-$(CONFIG_MACH_JAVA_GARNET_SONY_KIVU2) += board-bcm59xxx_kivu.o \
	board-kivu.o

obj-$(CONFIG_INPUT_LSM303DLHC_ACCELEROMETER) += board-kivu-accel.o
obj-$(CONFIG_INPUT_LSM303DLH_MAGNETOMETER) += board-kivu-magnetometer.o
obj-$(CONFIG_INPUT_L3G4200D) += board-kivu-gyro.o
obj-$(CONFIG_LEDS_LM3530) += board-kivu-backlight.o
obj-$(CONFIG_SENSORS_BMP18X_I2C) += board-kivu-barometer.o
obj-$(CONFIG_INPUT_APDS9702) += board-kivu-proximity.o
