obj-$(CONFIG_MACH_JAVA_KIVU) += board-bcm59xxx_kivu.o \
	board-kivu.o

obj-$(CONFIG_INPUT_LSM303DLHC_ACCELEROMETER) += board-kivu-accel.o
obj-$(CONFIG_INPUT_LSM303DLH_MAGNETOMETER) += board-kivu-magnetometer.o
obj-$(CONFIG_INPUT_L3G4200D) += board-kivu-gyro.o
obj-$(CONFIG_LEDS_LM3530) += board-kivu-backlight.o
obj-$(CONFIG_SENSORS_BMP18X_I2C) += board-kivu-barometer.o
obj-$(CONFIG_INPUT_APDS9702) += board-kivu-proximity.o
#Kivu 3
obj-$(CONFIG_INPUT_AKM09911) += board-kivu3-magnetometer.o
obj-$(CONFIG_INPUT_BMG160) += board-kivu3-gyro.o
obj-$(CONFIG_BACKLIGHT_LM3630) += board-kivu3-backlight.o
obj-$(CONFIG_SENSORS_BH1721FVC) += board-kivu3-als.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_RMI4_2) += board-kivu3-touch.o
obj-$(CONFIG_BMP280_I2C) += board-kivu-barometer.o
