# Makefile for the Samsung Electronics Incell Touchscreen driver

obj-$(CONFIG_TOUCHSCREEN_SEC_TS_INCELL) += sec_ts_drv.o
sec_ts_drv-y := sec_cmd.o sec_ts.o sec_ts_fw.o sec_ts_fn.o sec_ts_only_vendor.o
