obj-$(CONFIG_MACH_JAVA_GARNET_SONY_BROOKS) += board-bcm59xxx_brooks.o \
	board-brooks.o

obj-$(CONFIG_INPUT_LSM303DLH_MAGNETOMETER) += board-brooks-magnetometer.o
obj-$(CONFIG_INPUT_BMG160) += board-brooks-gyro.o
obj-$(CONFIG_LEDS_LM3530) += board-brooks-backlight.o
obj-$(CONFIG_SENSORS_BMP18X_I2C) += board-brooks-barometer.o
obj-$(CONFIG_INPUT_APDS9702) += board-brooks-proximity.o
