obj-$(CONFIG_MACH_JAVA_BROOKS) += board-bcm59xxx_brooks.o \
	board-brooks.o

obj-$(CONFIG_INPUT_AKM09911) += board-brooks-magnetometer.o
obj-$(CONFIG_INPUT_BMG160) += board-brooks-gyro.o
obj-$(CONFIG_BACKLIGHT_LM3630A) += board-brooks-backlight.o
obj-$(CONFIG_SENSORS_BMP18X_I2C) += board-brooks-barometer.o
obj-$(CONFIG_INPUT_APDS9702) += board-brooks-proximity.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_RMI4_2) += board-brooks-touch.o
obj-$(CONFIG_SENSORS_BH1721FVC) += board-brooks-als.o
obj-$(CONFIG_INPUT_EMMICRO) += board-brooks-sensor-hub.o
