EXTRA_CFLAGS  += -Wall -Wstrict-prototypes -Wno-trigraphs
EXTRA_CFLAGS  += -Werror
EXTRA_CFLAGS  += -Idrivers/videocore/host_support/include

obj-$(CONFIG_VC_HNFO) := vc-hnfo.o

vc-hnfo-objs := vc_hnfo.o

