#Makefile for CIB CAPI2 sources
#EXTRA_CFLAGS := -Werror

EXTRA_CFLAGS += -DUNDER_LINUX
EXTRA_CFLAGS += -DSTACK_wedge

obj-$(CONFIG_BRCM_FUSE_RIL_CIB) += \
            capi2/cc/ \
            capi2/gen/ \
            capi2/lcs/ \
            capi2/msc/ \
            capi2/pch/ \
            capi2/phonebk/ \
            capi2/sim/ \
            capi2/sms/ \
            capi2/ss/ \
            capi2/test/ \
            sysinterface/sysrpc/ \
            
            
            
                      
