ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/sensor/io
obj-$(CONFIG_MSM_CCI) += msm_cci.o
