#*****************************************************************************
# Copyright 2003 - 2008 Broadcom Corporation.  All rights reserved.
#
# Unless you and Broadcom execute a separate written software license
# agreement governing use of this software, this software is licensed to you
# under the terms of the GNU General Public License version 2, available at
# http://www.broadcom.com/licenses/GPLv2.php (the "GPL").
#
# Notwithstanding the above, under no circumstances may you combine this
# software in any way with any other Broadcom software provided under a
# license other than the GPL, without Broadcom's express prior written
# consent.
#*****************************************************************************

obj-y := io_map.o samoa.o common.o samoa_pinmux.o
obj-$(CONFIG_ARCH_SAMOA) += clock_samoa.o
obj-$(CONFIG_MACH_SAMOA_RAY) += samoa_ray.o samoa_ray_pinmux.o
obj-$(CONFIG_MFD_BCMSAMOA) += board-samoapmu.o 
obj-$(CONFIG_MACH_SAMOA_FPGA) += samoa_ray.o samoa_ray_pinmux.o
