/************************************************************************************************/
/*                                                                                              */
/*  Copyright 2011  Broadcom Corporation                                                        */
/*                                                                                              */
/*     Unless you and Broadcom execute a separate written software license agreement governing  */
/*     use of this software, this software is licensed to you under the terms of the GNU        */
/*     General Public License version 2 (the GPL), available at                                 */
/*                                                                                              */
/*          http://www.broadcom.com/licenses/GPLv2.php                                          */
/*                                                                                              */
/*     with the following added to such license:                                                */
/*                                                                                              */
/*     As a special exception, the copyright holders of this software give you permission to    */
/*     link this software with independent modules, and to copy and distribute the resulting    */
/*     executable under terms of your choice, provided that you also meet, for each linked      */
/*     independent module, the terms and conditions of the license of that module.              */
/*     An independent module is a module which is not derived from this software.  The special  */
/*     exception does not apply to any modifications of the software.                           */
/*                                                                                              */
/*     Notwithstanding the above, under no circumstances may you combine this software in any   */
/*     way with any other Broadcom software provided under a license other than the GPL,        */
/*     without Broadcom's express prior written consent.                                        */
/*                                                                                              */
/************************************************************************************************/
#include <linux/kernel.h>
#include <linux/init.h>

#include <mach/pinmux.h>
#include <mach/rdb/brcm_rdb_sysmap.h>
#include <mach/rdb/brcm_rdb_padctrlreg.h>

#define	PIN_DESC(ball, alt1, alt2, alt3, alt4, alt5, alt6)	 	\
	[PN_##ball] = {							\
		.name		=	PN_##ball,			\
		.reg_offset	=	PADCTRLREG_##ball##_OFFSET,	\
		.f_tbl		=	{				\
			PF_##alt1, PF_##alt2, PF_##alt3, 		\
			PF_##alt4, PF_##alt5, PF_##alt6, 		\
		},							\
	}

/*
 * SamoaA0 chip-level pin description table
 *  generated from
 *     http://mpgbu.broadcom.com/mobcom/3GULC/ASIC BB/top level/samoa_pinmuxing.xlsx
 */
static const struct pin_desc pin_desc_tbl[PN_MAX] = {
	PIN_DESC(ANA_CLK_REQ0, ANA_CLK_REQ0, RESERVED, RESERVED, RESERVED, GPIO, RESERVED),
	PIN_DESC(BSC1_CLK, BSC1_CLK, RESERVED, RESERVED, RESERVED, GPIO, RESERVED),
	PIN_DESC(BSC1_DAT, BSC1_DAT, RESERVED, RESERVED, RESERVED, GPIO, RESERVED),
	PIN_DESC(BSC2_CLK, BSC2_CLK, RESERVED, RESERVED, RESERVED, GPIO, RESERVED),
	PIN_DESC(BSC2_DAT, BSC2_DAT, RESERVED, RESERVED, RESERVED, GPIO, RESERVED),
	PIN_DESC(CAM_CS0, RESERVED, RESERVED, RESERVED, SRI_C, GPIO, MMCX_GPO),
	PIN_DESC(CLK_32K, CLK_32K, RESERVED, RESERVED, RESERVED, RESERVED, RESERVED),
	PIN_DESC(DCLK0, DCLK0, RESERVED, RESERVED, RESERVED, GPIO, RESERVED),
	PIN_DESC(DCLK_REQ0, DCLK_REQ0, RESERVED, RESERVED, RESERVED, GPIO, RESERVED),
	PIN_DESC(GPIO00, GPIO, KEY_R0, RESERVED, ACDATA, PTL_CLK, DEBUG_PORT),
	PIN_DESC(GPIO01, GPIO, KEY_R1, PWM2, CADATA, PTL_DAT3, DEBUG_PORT),
	PIN_DESC(GPIO02, GPIO, KEY_R2, PWM1, CAFLAG, RXD, DEBUG_PORT),
	PIN_DESC(GPIO03, GPIO, KEY_C0, PWM0, PWM3, DMIC0DQ, DEBUG_PORT),
	PIN_DESC(GPIO04, GPIO, KEY_R4, CAMPCLK, RESERVED, SSP1_SYN, DEBUG_PORT),
	PIN_DESC(GPIO05, GPIO, KEY_R5, CAMVS, GPEN12, SSP4_CLK, DEBUG_PORT),
	PIN_DESC(GPIO06, GPIO, KEY_R6, CAMD6, GPEN11, SSP4_SYN, DEBUG_PORT),
	PIN_DESC(GPIO07, GPIO, KEY_R3, CAMHS, GPEN13, SSP1_CLK, DEBUG_PORT),
	PIN_DESC(GPIO08, GPIO, KEY_R7, CAMD7, CAREADY, PTL_DAT2, DEBUG_PORT),
	PIN_DESC(GPIO09, GPIO, KEY_C1, ANA_CLK_REQ2, CAWAKE, DMIC0CLK, DEBUG_PORT),
	PIN_DESC(GPIO10, GPIO, KEY_C2, CAMD5, ACREADY, PTL_DAT0, DEBUG_PORT),
	PIN_DESC(GPIO11, GPIO, KEY_C3, CAMD4, PWM2, SSP1_DO, DEBUG_PORT),
	PIN_DESC(GPIO12, GPIO, KEY_C4, CAMD3, GPEN10, SSP1_DI, DEBUG_PORT),
	PIN_DESC(GPIO13, GPIO, KEY_C5, CAMD2, DCLK_REQ1, SSP4_DO, DEBUG_PORT),
	PIN_DESC(GPIO14, GPIO, KEY_C6, CAMD1, GPEN14, SSP4_DI, DEBUG_PORT),
	PIN_DESC(GPIO15, GPIO, KEY_C7, CAMD0, ACFLAG, PTL_DAT1, RESERVED),
	PIN_DESC(GPIO16, GPIO, GPEN10, GPEN13, BATREMI, SSP4_CLK, RESERVED),
	PIN_DESC(GPIO17, GPIO, DMIC0CLK, GPEN14, PWM3, SSP4_SYN, RESERVED),
	PIN_DESC(GPIO18, GPIO, DMIC0DQ, GPEN15, PWM2, SSP4_DO, RESERVED),
	PIN_DESC(GPIO19, GPIO, PWM2, GPEN12, BATREMO, SSP4_DI, RESERVED),
	PIN_DESC(GPIO20, GPIO, GPEN10, UB2TX, PWM3, KEY_R3, OSC2_OUT),
	PIN_DESC(GPIO21, GPIO, GPEN12, UB2RX, CLK32EXT, KEY_C3, RESERVED),
	PIN_DESC(GPIO22, GPIO, LCD_SCL, DCLK_REQ1, PWM2, KEY_C2, RESERVED),
	PIN_DESC(GPIO23, GPIO, DMIC0CLK, UB2CTSN, PWM1, KEY_C4, OSC1_OUT),
	PIN_DESC(GPIO24, GPIO, DMIC0DQ, UB2RTSN, PWM0, KEY_R4, RESERVED),
	PIN_DESC(LCD_CD, LCD_CD, LCD_SCL, RESERVED, RESERVED, GPIO, RF),
	PIN_DESC(LCD_CS0, LCD_CS0, RESERVED, RESERVED, RESERVED, GPIO, RF),
	PIN_DESC(LCD_CS1, LCD_CS1, RESERVED, LCD_D8, PWM1, GPIO, RF),
	PIN_DESC(LCD_D0, LCD_D0, LCD_SDA, RESERVED, CAWAKE, GPIO, RF),
	PIN_DESC(LCD_D1, LCD_D1, RESERVED, RESERVED, CAREADY, GPIO, RF),
	PIN_DESC(LCD_D2, LCD_D2, RESERVED, RESERVED, CAFLAG, GPIO, RF),
	PIN_DESC(LCD_D3, LCD_D3, RESERVED, RESERVED, CADATA, GPIO, RF),
	PIN_DESC(LCD_D4, LCD_D4, RESERVED, RESERVED, ACWAKE, GPIO, RF),
	PIN_DESC(LCD_D5, LCD_D5, RESERVED, RESERVED, ACREADY, GPIO, RF),
	PIN_DESC(LCD_D6, LCD_D6, RESERVED, RESERVED, ACFLAG, GPIO, RF),
	PIN_DESC(LCD_D7, LCD_D7, RESERVED, RESERVED, ACDATA, GPIO, RF),
	PIN_DESC(LCD_RE, LCD_RE, RESERVED, RESERVED, RESERVED, GPIO, RF),
	PIN_DESC(LCD_RST, LCD_RST, DMIC0CLK, RESERVED, PWM0, GPIO, RF),
	PIN_DESC(LCD_TE0, LCD_TE0, RESERVED, RESERVED, RESERVED, GPIO, RF),
	PIN_DESC(LCD_TE1, LCD_TE1, DMIC0DQ, LCD_SCL, GPEN14, GPIO, RF),
	PIN_DESC(LCD_WE, LCD_WE, RESERVED, RESERVED, RESERVED, GPIO, RF),
	PIN_DESC(MDM_GPIO00, GPEN0, RESERVED, RESERVED, RESERVED, GPIO, RESERVED),
	PIN_DESC(MDM_GPIO01, GPEN1, RESERVED, RESERVED, RESERVED, GPIO, AP),
	PIN_DESC(MDM_GPIO02, GPEN2, RESERVED, RESERVED, RESERVED, GPIO, AP),
	PIN_DESC(MDM_GPIO03, RFGPIO5, RESERVED, RESERVED, RESERVED, GPIO, AP),
	PIN_DESC(MDM_GPIO04, GPEN4, RESERVED, RESERVED, RESERVED, GPIO, AP),
	PIN_DESC(MDM_GPIO05, GPEN5, RESERVED, RESERVED, RESERVED, GPIO, AP),
	PIN_DESC(MDM_GPIO06, GPEN6, RESERVED, RESERVED, RESERVED, GPIO, AP),
	PIN_DESC(MDM_GPIO07, GPEN7, RESERVED, RESERVED, RESERVED, GPIO, AP),
	PIN_DESC(MDM_GPIO08, GPEN8, RESERVED, RESERVED, RESERVED, GPIO, RESERVED),
	PIN_DESC(MMC_CLK, MMC1_CLK, RESERVED, CAMPCLK, RESERVED, GPIO, RESERVED),
	PIN_DESC(MMC_CMD, MMC1_CMD, RESERVED, CAMVS, RESERVED, GPIO, RESERVED),
	PIN_DESC(MMC_DAT0, MMC1_DAT0, RESERVED, CAMD0, RESERVED, GPIO, RESERVED),
	PIN_DESC(MMC_DAT1, MMC1_DAT1, RESERVED, CAMD1, RESERVED, GPIO, RESERVED),
	PIN_DESC(MMC_DAT2, MMC1_DAT2, RESERVED, CAMD2, RESERVED, GPIO, RESERVED),
	PIN_DESC(MMC_DAT3, MMC1_DAT3, RESERVED, CAMD3, RESERVED, GPIO, RESERVED),
	PIN_DESC(MMC_DAT4, MMC1_DAT4, SSP4_DI, CAMD4, GPEN12, GPIO, RESERVED),
	PIN_DESC(MMC_DAT5, MMC1_DAT5, SSP4_DO, CAMD5, PWM1, GPIO, RESERVED),
	PIN_DESC(MMC_DAT6, MMC1_DAT6, SSP4_SYN, CAMD6, GPEN11, GPIO, RESERVED),
	PIN_DESC(MMC_DAT7, MMC1_DAT7, SSP4_CLK, CAMD7, GPEN10, GPIO, RESERVED),
	PIN_DESC(MMC_RST, MMC1_RST, CLK32EXT, CAMHS, ANA_CLK_REQ2, GPIO, RESERVED),
	PIN_DESC(PCM_CLK, SSP3_CLK, RESERVED, GPEN10, RESERVED, GPIO, RESERVED),
	PIN_DESC(PCM_DI, SSP3_DI, RESERVED, DCLK1, RESERVED, GPIO, RESERVED),
	PIN_DESC(PCM_DO, SSP3_DO, ANA_CLK_REQ1, RESERVED, RESERVED, GPIO, RESERVED),
	PIN_DESC(PCM_SYN, SSP3_SYN, RESERVED, GPEN12, RESERVED, GPIO, RESERVED),
	PIN_DESC(RESET_N, RESETN, PWM2, DCLK1, PWM3, GPIO, RESERVED),
	PIN_DESC(SD_CLK, MMC0_CLK, DSP_RTCK, PTL_CLK, RESERVED, GPIO, U1TXD),
	PIN_DESC(SD_CMD, MMC0_CMD, DSP_TDI, RXD, TDI, GPIO, U1RXD),
	PIN_DESC(SD_DAT0, MMC0_DAT0, DSP_TDO, PTL_DAT0, TDO, GPIO, PM_DEBUG0),
	PIN_DESC(SD_DAT1, MMC0_DAT1, DSP_TRSTB, PTL_DAT1, TRSTB, GPIO, PM_DEBUG1),
	PIN_DESC(SD_DAT2, MMC0_DAT2, DSP_TMSC, PTL_DAT2, SWD_TMSC, GPIO, PM_DEBUG2),
	PIN_DESC(SD_DAT3, MMC0_DAT3, DSP_TCKC, PTL_DAT3, SWD_TCKC, GPIO, PM_DEBUG3),
	PIN_DESC(SIM1_CLK, SIM1_CLK, RESERVED, RESERVED, RESERVED, GPIO, RESERVED),
	PIN_DESC(SIM1_DAT, SIM1_DAT, RESERVED, RESERVED, RESERVED, GPIO, RESERVED),
	PIN_DESC(SIM1_DET, SIM1_DET, RESERVED, RESERVED, RESERVED, GPIO, RESERVED),
	PIN_DESC(SIM1_RST, SIM1_RST, RESERVED, RESERVED, RESERVED, GPIO, RESERVED),
	PIN_DESC(SIM2_CLK, SIM2_CLK, GPEN10, PWM1, DMIC0CLK, GPIO, RESERVED),
	PIN_DESC(SIM2_DAT, SIM2_DAT, CLK32EXT, PWM3, DMIC0DQ, GPIO, RESERVED),
	PIN_DESC(SIM2_DET, SIM2_DET, GPEN11, DCLK_REQ1, ACWAKE, GPIO, RESERVED),
	PIN_DESC(SIM2_RST, SIM2_RST, GPEN12, PWM2,  RESERVED, GPIO, RESERVED),
	PIN_DESC(SPI_CLK, SSP0_CLK, RESERVED, GPEN14, RESERVED, GPIO, RESERVED),
	PIN_DESC(SPI_FSS, SSP0_SYN, RESERVED, GPEN13, RESERVED, GPIO, RESERVED),
	PIN_DESC(SPI_RX, SSP0_DI, RESERVED, RESERVED, RESERVED, GPIO, RF),
	PIN_DESC(SPI_TX, SSP0_DO, RESERVED, GPEN15, RESERVED, GPIO, RESERVED),
	PIN_DESC(SWD_TCKC, SWD_TCKC, RESERVED, RESERVED, RESERVED, RESERVED, RESERVED),
	PIN_DESC(SWD_TMSC, SWD_TMSC, RESERVED, RESERVED, RESERVED, RESERVED, RESERVED),
	PIN_DESC(TRACE_CLK, TRACE, PTI_CLK, DSP_TRACE, BATREMO, GPIO, CLK_MON),
	PIN_DESC(TRACE_DATA00, TRACE, PTI_DAT0, DSP_TRACE, PWM0, GPIO, PC1),
	PIN_DESC(TRACE_DATA01, TRACE, PTI_DAT1, DSP_TRACE, PWM1, GPIO, PC2),
	PIN_DESC(TRACE_DATA02, TRACE, PTI_DAT2, DSP_TRACE, PWM2, GPIO, PC3),
	PIN_DESC(TRACE_DATA03, TRACE, PTI_DAT3, DSP_TRACE, PWM3, GPIO, RESERVED),
	PIN_DESC(UARTA_CTS_N, UARTA_CTS_N, RESERVED, RESERVED, SRI_E, GPIO, RESERVED),
	PIN_DESC(UARTA_RTS_N, UARTA_RTS_N, RESERVED, RESERVED, SRI_D, GPIO, RESERVED),
	PIN_DESC(UARTA_RX, UARTA_RX, RESERVED, RESERVED, RESERVED, GPIO, RESERVED),
	PIN_DESC(UARTA_TX, UARTA_TX, RESERVED, RESERVED, RESERVED, GPIO, RESERVED),
};

struct chip_pin_desc g_chip_pin_desc = {
	.desc_tbl	=	pin_desc_tbl,
};

/* unlock access lock */
static void __init unlock_padctl (void __iomem *base)
{
#define PASSWORD 0xA5A501
	writel(PASSWORD, base + PADCTRLREG_WR_ACCESS_OFFSET);
	writel(0x0, base + PADCTRLREG_ACCESS_LOCK0_OFFSET);

	writel(PASSWORD, base + PADCTRLREG_WR_ACCESS_OFFSET);
	writel(0x0, base + PADCTRLREG_ACCESS_LOCK1_OFFSET);

	writel(PASSWORD, base + PADCTRLREG_WR_ACCESS_OFFSET);
	writel(0x0, base + PADCTRLREG_ACCESS_LOCK2_OFFSET);

	writel(PASSWORD, base + PADCTRLREG_WR_ACCESS_OFFSET);
	writel(0x0, base + PADCTRLREG_ACCESS_LOCK3_OFFSET);

	writel(PASSWORD, base + PADCTRLREG_WR_ACCESS_OFFSET);
	writel(0x0, base + PADCTRLREG_ACCESS_LOCK4_OFFSET);
}

int __init pinmux_chip_init (void)
{
	g_chip_pin_desc.base = ioremap(PAD_CTRL_BASE_ADDR, SZ_2K);
	BUG_ON (!g_chip_pin_desc.base);

	unlock_padctl(g_chip_pin_desc.base);
	return 0;
}
