/************************************************************************************************/
/*                                                                                              */
/*  Copyright 2011  Broadcom Corporation                                                        */
/*                                                                                              */
/*     Unless you and Broadcom execute a separate written software license agreement governing  */
/*     use of this software, this software is licensed to you under the terms of the GNU        */
/*     General Public License version 2 (the GPL), available at                                 */
/*                                                                                              */
/*          http://www.broadcom.com/licenses/GPLv2.php                                          */
/*                                                                                              */
/*     with the following added to such license:                                                */
/*                                                                                              */
/*     As a special exception, the copyright holders of this software give you permission to    */
/*     link this software with independent modules, and to copy and distribute the resulting    */
/*     executable under terms of your choice, provided that you also meet, for each linked      */
/*     independent module, the terms and conditions of the license of that module.              */
/*     An independent module is a module which is not derived from this software.  The special  */
/*     exception does not apply to any modifications of the software.                           */
/*                                                                                              */
/*     Notwithstanding the above, under no circumstances may you combine this software in any   */
/*     way with any other Broadcom software provided under a license other than the GPL,        */
/*     without Broadcom's express prior written consent.                                        */
/*                                                                                              */
/*     Date     : Generated on 4/25/2011 11:6:8                                             */
/*     RDB file : /projects/BIGISLAND/revA0                                                                   */
/************************************************************************************************/

#ifndef __BRCM_RDB_CFP_CONFIGURATION_REGISTER_H__
#define __BRCM_RDB_CFP_CONFIGURATION_REGISTER_H__

#define CFP_CONFIGURATION_REGISTER_CFP_CONTROL_REGISTER_OFFSET            0x00000000
#define CFP_CONFIGURATION_REGISTER_CFP_CONTROL_REGISTER_TYPE              UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_CONTROL_REGISTER_RESERVED_MASK     0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_CONTROL_REGISTER_CFP_EN_MAP_SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_CONTROL_REGISTER_CFP_EN_MAP_MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A0_REGISTER_OFFSET           0x00000080
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A0_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A0_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A0_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A0_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A1_REGISTER_OFFSET           0x00000088
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A1_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A1_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A1_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A1_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A2_REGISTER_OFFSET           0x00000090
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A2_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A2_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A2_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A2_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A3_REGISTER_OFFSET           0x00000098
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A3_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A3_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A3_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A3_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A4_REGISTER_OFFSET           0x000000A0
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A4_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A4_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A4_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A4_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A5_REGISTER_OFFSET           0x000000A8
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A5_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A5_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A5_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A5_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A6_REGISTER_OFFSET           0x000000B0
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A6_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A6_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A6_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A6_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A7_REGISTER_OFFSET           0x000000B9
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A7_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A7_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A7_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A7_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A8_REGISTER_OFFSET           0x000000C0
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A8_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A8_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A8_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_A8_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A0_REGISTER_OFFSET           0x00000100
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A0_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A0_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A0_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A0_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A1_REGISTER_OFFSET           0x00000108
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A1_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A1_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A1_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A1_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A2_REGISTER_OFFSET           0x00000110
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A2_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A2_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A2_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A2_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A3_REGISTER_OFFSET           0x00000118
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A3_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A3_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A3_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A3_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A4_REGISTER_OFFSET           0x00000120
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A4_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A4_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A4_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A4_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A5_REGISTER_OFFSET           0x00000128
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A5_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A5_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A5_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A5_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A6_REGISTER_OFFSET           0x00000130
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A6_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A6_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A6_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A6_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A7_REGISTER_OFFSET           0x00000138
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A7_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A7_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A7_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A7_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A8_REGISTER_OFFSET           0x00000140
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A8_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A8_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A8_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_A8_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A0_REGISTER_OFFSET           0x00000180
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A0_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A0_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A0_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A0_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A1_REGISTER_OFFSET           0x00000188
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A1_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A1_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A1_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A1_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A2_REGISTER_OFFSET           0x00000190
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A2_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A2_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A2_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A2_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A3_REGISTER_OFFSET           0x00000198
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A3_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A3_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A3_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A3_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A4_REGISTER_OFFSET           0x000001A0
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A4_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A4_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A4_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A4_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A5_REGISTER_OFFSET           0x000001A8
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A5_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A5_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A5_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A5_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A6_REGISTER_OFFSET           0x000001B0
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A6_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A6_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A6_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A6_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A7_REGISTER_OFFSET           0x000001B8
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A7_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A7_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A7_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A7_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A8_REGISTER_OFFSET           0x000001C0
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A8_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A8_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A8_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_A8_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B0_REGISTER_OFFSET           0x00000200
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B0_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B0_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B0_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B0_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B1_REGISTER_OFFSET           0x00000208
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B1_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B1_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B1_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B1_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B2_REGISTER_OFFSET           0x00000210
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B2_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B2_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B2_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B2_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B3_REGISTER_OFFSET           0x00000218
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B3_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B3_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B3_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B3_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B4_REGISTER_OFFSET           0x00000220
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B4_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B4_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B4_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B4_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B5_REGISTER_OFFSET           0x00000228
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B5_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B5_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B5_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B5_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B6_REGISTER_OFFSET           0x00000230
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B6_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B6_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B6_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B6_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B7_REGISTER_OFFSET           0x00000238
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B7_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B7_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B7_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B7_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B8_REGISTER_OFFSET           0x00000240
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B8_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B8_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B8_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_B8_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B0_REGISTER_OFFSET           0x00000280
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B0_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B0_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B0_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B0_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B1_REGISTER_OFFSET           0x00000288
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B1_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B1_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B1_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B1_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B2_REGISTER_OFFSET           0x00000290
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B2_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B2_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B2_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B2_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B3_REGISTER_OFFSET           0x00000298
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B3_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B3_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B3_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B3_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B4_REGISTER_OFFSET           0x000002A0
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B4_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B4_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B4_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B4_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B5_REGISTER_OFFSET           0x000002A8
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B5_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B5_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B5_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B5_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B6_REGISTER_OFFSET           0x000002B0
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B6_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B6_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B6_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B6_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B7_REGISTER_OFFSET           0x000002B8
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B7_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B7_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B7_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B7_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B8_REGISTER_OFFSET           0x000002C0
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B8_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B8_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B8_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_B8_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B0_REGISTER_OFFSET           0x00000300
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B0_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B0_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B0_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B0_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B1_REGISTER_OFFSET           0x00000308
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B1_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B1_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B1_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B1_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B2_REGISTER_OFFSET           0x00000310
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B2_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B2_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B2_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B2_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B3_REGISTER_OFFSET           0x00000318
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B3_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B3_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B3_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B3_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B4_REGISTER_OFFSET           0x00000320
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B4_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B4_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B4_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B4_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B5_REGISTER_OFFSET           0x00000328
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B5_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B5_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B5_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B5_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B6_REGISTER_OFFSET           0x00000330
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B6_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B6_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B6_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B6_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B7_REGISTER_OFFSET           0x00000338
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B7_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B7_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B7_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B7_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B8_REGISTER_OFFSET           0x00000340
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B8_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B8_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B8_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_B8_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C0_REGISTER_OFFSET           0x00000380
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C0_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C0_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C0_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C0_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C1_REGISTER_OFFSET           0x00000388
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C1_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C1_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C1_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C1_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C2_REGISTER_OFFSET           0x00000390
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C2_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C2_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C2_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C2_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C3_REGISTER_OFFSET           0x00000398
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C3_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C3_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C3_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C3_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C4_REGISTER_OFFSET           0x000003A0
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C4_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C4_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C4_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C4_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C5_REGISTER_OFFSET           0x000003A8
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C5_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C5_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C5_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C5_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C6_REGISTER_OFFSET           0x000003B0
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C6_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C6_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C6_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C6_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C7_REGISTER_OFFSET           0x000003B8
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C7_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C7_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C7_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C7_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C8_REGISTER_OFFSET           0x000003C0
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C8_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C8_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C8_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_C8_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C0_REGISTER_OFFSET           0x00000400
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C0_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C0_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C0_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C0_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C1_REGISTER_OFFSET           0x00000408
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C1_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C1_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C1_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C1_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C2_REGISTER_OFFSET           0x00000410
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C2_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C2_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C2_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C2_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C3_REGISTER_OFFSET           0x00000418
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C3_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C3_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C3_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C3_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C4_REGISTER_OFFSET           0x00000420
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C4_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C4_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C4_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C4_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C5_REGISTER_OFFSET           0x00000428
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C5_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C5_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C5_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C5_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C6_REGISTER_OFFSET           0x00000430
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C6_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C6_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C6_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C6_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C7_REGISTER_OFFSET           0x00000438
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C7_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C7_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C7_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C7_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C8_REGISTER_OFFSET           0x00000440
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C8_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C8_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C8_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_1_C8_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C0_REGISTER_OFFSET           0x00000480
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C0_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C0_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C0_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C0_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C1_REGISTER_OFFSET           0x00000488
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C1_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C1_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C1_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C1_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C2_REGISTER_OFFSET           0x00000490
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C2_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C2_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C2_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C2_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C3_REGISTER_OFFSET           0x00000498
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C3_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C3_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C3_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C3_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C4_REGISTER_OFFSET           0x000004A0
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C4_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C4_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C4_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C4_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C5_REGISTER_OFFSET           0x000004A8
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C5_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C5_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C5_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C5_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C6_REGISTER_OFFSET           0x000004B0
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C6_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C6_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C6_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C6_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C7_REGISTER_OFFSET           0x000004B8
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C7_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C7_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C7_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C7_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C8_REGISTER_OFFSET           0x000004C0
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C8_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C8_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C8_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_2_C8_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D0_REGISTER_OFFSET           0x00000500
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D0_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D0_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D0_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D0_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D1_REGISTER_OFFSET           0x00000508
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D1_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D1_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D1_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D1_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D2_REGISTER_OFFSET           0x00000510
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D2_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D2_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D2_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D2_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D3_REGISTER_OFFSET           0x00000518
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D3_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D3_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D3_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D3_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D4_REGISTER_OFFSET           0x00000520
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D4_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D4_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D4_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D4_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D5_REGISTER_OFFSET           0x00000528
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D5_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D5_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D5_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D5_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D6_REGISTER_OFFSET           0x00000530
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D6_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D6_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D6_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D6_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D7_REGISTER_OFFSET           0x00000538
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D7_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D7_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D7_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D7_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D8_REGISTER_OFFSET           0x00000540
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D8_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D8_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D8_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D8_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D9_REGISTER_OFFSET           0x00000548
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D9_REGISTER_TYPE             UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D9_REGISTER_RESERVED_MASK    0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D9_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D9_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D10_REGISTER_OFFSET          0x00000550
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D10_REGISTER_TYPE            UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D10_REGISTER_RESERVED_MASK   0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D10_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D10_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D11_REGISTER_OFFSET          0x00000558
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D11_REGISTER_TYPE            UInt16
#define CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D11_REGISTER_RESERVED_MASK   0x0000FE00
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D11_REGISTER_CFG_UDF_N_X_N__SHIFT 0
#define    CFP_CONFIGURATION_REGISTER_CFP_UDF_0_D11_REGISTER_CFG_UDF_N_X_N__MASK 0x000001FF

#endif /* __BRCM_RDB_CFP_CONFIGURATION_REGISTER_H__ */


