obj-$(CONFIG_MAP_SDMA) += chal_dmux.o chal_dma.o
obj-$(CONFIG_IPC) += chal_ipc.o chal_icd.o
obj-$(CONFIG_MAP_SSASW) += chal_caph_switch.o chal_caph_srcmixer.o
obj-$(CONFIG_MAP_AADMA) += chal_caph_dma.o chal_caph_cfifo.o chal_caph_intc.o
