obj-$(CONFIG_MAP_SDMA) += chal_dmux.o chal_dma.o
obj-$(CONFIG_IPC) += chal_ipc.o chal_icd.o
obj-$(CONFIG_MAP_SSASW) += chal_caph_switch.o chal_caph_srcmixer.o
obj-$(CONFIG_MAP_AADMA) += chal_caph_dma.o chal_caph_cfifo.o chal_caph_intc.o
obj-$(CONFIG_MAP_ISLAND_AUDIOH_CHAL) +=   chal_audio.o chal_vibra.o chal_hs.o \
                                          chal_ihf.o chal_vout.o chal_nvin.o  \
                                          chal_vin.o chal_sidetone.o chal_analogmic.o \
                                          chal_analogtest.o \

obj-$(CONFIG_MAP_ISLAND_PCM_CHAL) += chal_sspi.o
obj-$(CONFIG_MAP_LITTLE_ISLAND_MEMC_QOS) += chal_memc.o chal_memc_ddr3.o chal_mqos.o
obj-$(CONFIG_MAP_ISLAND_NAND_CHAL) += chal_nand.o chal_nand_dma_linux.o
obj-$(CONFIG_RTC_DRV_ISLAND) += chal_rtc.o
obj-$(CONFIG_KEYBOARD_KONA) += chal_keypad.o



