MODULE_NAME = sec_touchscreen

obj-m := $(MODULE_NAME).o

$(MODULE_NAME)-objs := sec_ts.o
$(MODULE_NAME)-objs += sec_ts_fn.o
$(MODULE_NAME)-objs += sec_ts_fw.o
$(MODULE_NAME)-objs += sec_ts_only_vendor.o
$(MODULE_NAME)-objs += sec_cmd.o
