sec_touchscreen-objs := sec_ts.o
sec_touchscreen-objs += sec_ts_fn.o
sec_touchscreen-objs += sec_ts_fw.o
sec_touchscreen-objs += sec_ts_only_vendor.o
sec_touchscreen-objs += sec_cmd.o

obj-$(CONFIG_TOUCHSCREEN_SAMSUNG_INCELL) := sec_touchscreen.o
