/*****************************************************************************
* Copyright 2013 Broadcom Corporation.  All rights reserved.
*
* Unless you and Broadcom execute a separate written software license
* agreement governing use of this software, this software is licensed to you
* under the terms of the GNU General Public License version 2, available at
* http://www.broadcom.com/licenses/GPLv2.php (the "GPL").
*
*****************************************************************************/

#ifndef _CABAC_REG_H_
#define _CABAC_REG_H_

/* TODO: only really need to map 2 smaller memory
 * regions in order to access all relevant registers */
#define CABAC_HW_SIZE						(6148*1024)

#define CABAC_REGCABAC2BINSIMGCTXLAST_OFFSET			0x00000bbc

#define CABAC_REGCABAC2BINSRDCONTEXTBASEADDR_OFFSET		0x00000bd0

#define CABAC_REGCABAC2BINSWRCONTEXTBASEADDR_OFFSET		0x00000bd4

#define CABAC_REGCABAC2BINSUPSTRIPEBASEADDR_OFFSET		0x00002700

#define CABAC_REGCABAC2BINSCOMMANDBUFFERADDR_OFFSET		0x00002710

#define CABAC_REGCABAC2BINSCOMMANDBUFFERLOGSIZE_OFFSET		0x00002718

#define CABAC_REGCABAC2BINSCOMMANDBUFFERCOUNT_OFFSET		0x00002714
/* write access */
#define CABAC_REGCABAC2BINSCOMMANDBUFFERCOUNT_CLEAR_SHIFT	1
#define CABAC_REGCABAC2BINSCOMMANDBUFFERCOUNT_CLEAR_MASK	0x00000002
#define CABAC_REGCABAC2BINSCOMMANDBUFFERCOUNT_INC_SHIFT		0
#define CABAC_REGCABAC2BINSCOMMANDBUFFERCOUNT_INC_MASK		0x00000001
/* read access */
#define CABAC_REGCABAC2BINSCOMMANDBUFFERCOUNT_COUNT_SHIFT	0
#define CABAC_REGCABAC2BINSCOMMANDBUFFERCOUNT_COUNT_MASK	0x000007ff

#define CABAC_REGCABAC2BINSCTL_OFFSET				0x0000272c
#define CABAC_REGCABAC2BINSCTL_BE_LE_MUX_CTRL_SHIFT		17
#define CABAC_REGCABAC2BINSCTL_BE_LE_MUX_CTRL_MASK		0x00020000
#define CABAC_REGCABAC2BINSCTL_BE_LE_CTRL_SHIFT			16
#define CABAC_REGCABAC2BINSCTL_BE_LE_CTRL_MASK			0x00010000
#define CABAC_REGCABAC2BINSCTL_INT_SHIFT			11
#define CABAC_REGCABAC2BINSCTL_INT_MASK				0x00000800
#define CABAC_REGCABAC2BINSCTL_BUSY_SHIFT			10
#define CABAC_REGCABAC2BINSCTL_BUSY_MASK			0x00000400
#define CABAC_REGCABAC2BINSCTL_WRNR_SHIFT			9
#define CABAC_REGCABAC2BINSCTL_WRNR_MASK			0x00000200
#define CABAC_REGCABAC2BINSCTL_RDNR_SHIFT			8
#define CABAC_REGCABAC2BINSCTL_RDNR_MASK			0x00000100
#define CABAC_REGCABAC2BINSCTL_WRMK_SHIFT			7
#define CABAC_REGCABAC2BINSCTL_WRMK_MASK			0x00000080
#define CABAC_REGCABAC2BINSCTL_RDMK_SHIFT			6
#define CABAC_REGCABAC2BINSCTL_RDMK_MASK			0x00000040
#define CABAC_REGCABAC2BINSCTL_SDQ_SHIFT			4
#define CABAC_REGCABAC2BINSCTL_SDQ_MASK				0x00000010
#define CABAC_REGCABAC2BINSCTL_SDWR_SHIFT			3
#define CABAC_REGCABAC2BINSCTL_SDWR_MASK			0x00000008
#define CABAC_REGCABAC2BINSCTL_SDACT_SHIFT			2
#define CABAC_REGCABAC2BINSCTL_SDACT_MASK			0x00000004
#define CABAC_REGCABAC2BINSCTL_SDREQ_SHIFT			1
#define CABAC_REGCABAC2BINSCTL_SDREQ_MASK			0x00000002
#define CABAC_REGCABAC2BINSCTL_RESET_SHIFT			0
#define CABAC_REGCABAC2BINSCTL_RESET_MASK			0x00000001

#endif

