#
# Makefile for the QCOM specific video device drivers
# based on V4L2.
#
obj-$(CONFIG_MSM_VIDC_V4L2) += vidc/
obj-y += broadcast/
obj-$(CONFIG_DVB_MPQ) += dvb/
obj-$(CONFIG_MSMB_CAMERA_NEWGEN) += camera_v2/
obj-$(CONFIG_MSMB_CAMERA_LEGACY) += camera_v2_legacy/
obj-y += sde/
