#
# Makefile for the Imagis touch driver
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_IST30XX_NEW)  += ist30xx_update.o ist30xx.o ist30xx_misc.o ist30xx_sys.o ist30xx_tracking.o ist30xx_sec.o
