obj-y += common/
obj-y += h264/
# obj-$(CONFIG_KONA_PI_MGR) += mm_dvfs.o
obj-$(CONFIG_BCM_MM_PWRCTRL) += pwrctrl/
obj-$(CONFIG_BCM_HVA) += hva/
obj-$(CONFIG_BCM_VCE) += vce/
obj-$(CONFIG_BCM_MCI) += mci/
obj-$(CONFIG_BCM_CABAC) += cabac/
