#
# Makefile for the BRCM eMMC RPMB driver
#

obj-$(CONFIG_BRCM_EMMC_RPMB_SUPPORT)		+= hmac_sha2.o sha2.o emmc_rpmb_rw.o
obj-$(CONFIG_BRCM_EMMC_RPMB_TEST)		+= hmac_sha2.o sha2.o test_emmc_rpmb_rw.o
obj-$(CONFIG_BRCM_EMMC_RPMB_KEYBOX)		+=  keybox_emmc_rpmb.o
