#/*******************************************************************************************
#Copyright 2010 Broadcom Corporation.  All rights reserved.
#
#Unless you and Broadcom execute a separate written software license agreement 
#governing use of this software, this software is licensed to you under the 
#terms of the GNU General Public License version 2, available at 
#http://www.gnu.org/copyleft/gpl.html (the "GPL"). 
#
#Notwithstanding the above, under no circumstances may you combine this software 
#in any way with any other Broadcom software provided under a license other than 
#the GPL, without Broadcom's express prior written consent.
#*******************************************************************************************/

#
## Makefile for audio CAPH driver

# -D USE_HAL_AUDIO_THREAD

ifdef CONFIG_ARCH_RHEA
include $(src)/Rhea_Makefile
endif

ifdef CONFIG_ARCH_ISLAND
include $(src)/Island_Makefile
endif

ifdef CONFIG_ARCH_SAMOA
include $(src)/Samoa_Makefile
endif
