#/*******************************************************************************************
#Copyright 2010 Broadcom Corporation.  All rights reserved.
#
#Unless you and Broadcom execute a separate written software license agreement 
#governing use of this software, this software is licensed to you under the 
#terms of the GNU General Public License version 2, available at 
#http://www.gnu.org/copyleft/gpl.html (the "GPL"). 
#
#Notwithstanding the above, under no circumstances may you combine this software 
#in any way with any other Broadcom software provided under a license other than 
#the GPL, without Broadcom's express prior written consent.
#*******************************************************************************************/

#
## Makefile for ALSA BRCM OMX
#
# -D USE_HAL_AUDIO_THREAD


EXTRA_CFLAGS += -DUNDER_LINUX
EXTRA_CFLAGS += -D _RHEA_  -D MSP -D FUSE_DUAL_PROCESSOR_ARCHITECTURE -D FUSE_APPS_PROCESSOR -D PMU_MAX8986 -D CHAL_NDEBUG_BUILD -D CHIP_REVISION=20 -D VPU_INCLUDED
#Audio Controller header files
EXTRA_CFLAGS += -I $(src)/common -I $(src)/audio/audio_controller -I $(src)/audio/audio_controller/public
EXTRA_CFLAGS += -I $(src)/audio/audio_vdriver/public/
EXTRA_CFLAGS += -I $(src)/audio/public/
EXTRA_CFLAGS += -I $(src)/audio/audio_datadriver/public/
#CSL header files
EXTRA_CFLAGS += -I $(src)/soc/csl/audio/public/
EXTRA_CFLAGS += -I $(src)/soc/csl/dsp/public/
EXTRA_CFLAGS += -I $(src)/soc/csl/bsp/public/
#CHAL header files
EXTRA_CFLAGS += -I $(src)/soc/chal/modules/audio/inc/
EXTRA_CFLAGS += -I $(src)/soc/chal/modules/audio/caph/
EXTRA_CFLAGS += -I $(src)/soc/chal/modules/bsp/inc/
#RDB header files
EXTRA_CFLAGS += -I $(src)/rdb/rhea/A0
#DSP header files
EXTRA_CFLAGS += -I $(src)/dsp/public/
EXTRA_CFLAGS += -I $(src)/dsp/rhea/A0/Include/
#SYSPARM Header files
#EXTRA_CFLAGS += -I $(src)/sysinterface/sysparms/
#RPC Header files
EXTRA_CFLAGS += -I ../modules/drivers/char/brcm/fuse_rpc/rpc_CIB/public/
EXTRA_CFLAGS += -I ../modules/drivers/char/brcm/fuse_rpc/rpc_CIB/arpc/inc/
EXTRA_CFLAGS += -I ../modules/drivers/char/brcm/fuse_rpc/rpc_CIB/srpc/inc/
EXTRA_CFLAGS += -I ../modules/drivers/char/brcm/fuse_rpc/rpc_CIB/xdr/inc/
#LOG Header files
EXTRA_CFLAGS += -I $(src)/soc/debug/public
#PMU Header files
#EXTRA_CFLAGS += -I $(src)/peripherals/pmu/public
#EXTRA_CFLAGS += -I $(src)/sysinterface/hal/pmu/public

#Platform header files
EXTRA_CFLAGS += -I ./arch/arm/plat-kona/include/
EXTRA_CFLAGS += -I ./arch/arm/plat-kona/include/plat/
EXTRA_CFLAGS += -I ./drivers/char/broadcom/
EXTRA_CFLAGS += -I ./arch/arm/mach-island/include/
EXTRA_CFLAGS += -I ./arch/arm/mach-island/include/mach/
#EXTRA_CFLAGS += -I ./arch/arm/mach-island/include/mach/rdb/
EXTRA_CFLAGS += -I ./arch/arm/plat-kona/include/plat/chal/
EXTRA_CFLAGS += -I ./arch/arm/plat-kona/include/plat/osabstract/

obj-$(CONFIG_BCM_ALSA_SOUND)		+= snd-brcm-omx.o
snd-brcm-omx-objs := brcm_alsa_dev.o 
snd-brcm-omx-objs += brcm_auddrv_test.o
snd-brcm-omx-objs += brcm_alsa_ctl.o
snd-brcm-omx-objs += brcm_alsa_pcm.o
#snd-brcm-omx-objs += brcm_alsa_ctl.o
#snd-brcm-omx-objs += brcm_audio_thread.o
#snd-brcm-omx-objs += audio_stubs.o
#snd-brcm-omx-objs += audio/audio_controller/src/audio_controller_caph.o
snd-brcm-omx-objs += audio/audio_controller/src/audio_controller_common.o
snd-brcm-omx-objs += audio/audio_controller/src/audio_gain_table.o
#snd-brcm-omx-objs += audio/audio_datadriver/src/audio_ddriver.o

#CHAL Source Files
snd-brcm-omx-objs += soc/chal/modules/audio/caph/src/chal_caph_switch.o
snd-brcm-omx-objs += soc/chal/modules/audio/caph/src/chal_caph_srcmixer.o
snd-brcm-omx-objs += soc/chal/modules/audio/caph/src/chal_caph_other.o
snd-brcm-omx-objs += soc/chal/modules/audio/caph/src/chal_caph_intc.o
snd-brcm-omx-objs += soc/chal/modules/audio/caph/src/chal_caph_dma.o
snd-brcm-omx-objs += soc/chal/modules/audio/caph/src/chal_caph_cfifo.o
snd-brcm-omx-objs += soc/chal/modules/audio/caph/src/chal_caph_audioh_vout.o
snd-brcm-omx-objs += soc/chal/modules/audio/caph/src/chal_caph_audioh_vin.o
snd-brcm-omx-objs += soc/chal/modules/audio/caph/src/chal_caph_audioh_vibra.o
snd-brcm-omx-objs += soc/chal/modules/audio/caph/src/chal_caph_audioh_sidetone.o
snd-brcm-omx-objs += soc/chal/modules/audio/caph/src/chal_caph_audioh_nvin.o
snd-brcm-omx-objs += soc/chal/modules/audio/caph/src/chal_caph_audioh_ihf.o
snd-brcm-omx-objs += soc/chal/modules/audio/caph/src/chal_caph_audioh_hs.o
snd-brcm-omx-objs += soc/chal/modules/audio/caph/src/chal_caph_audioh_eanc.o
snd-brcm-omx-objs += soc/chal/modules/audio/caph/src/chal_caph_audioh_audio.o
snd-brcm-omx-objs += soc/chal/modules/audio/caph/src/chal_caph_audioh_analogtest.o
snd-brcm-omx-objs += soc/chal/modules/audio/caph/src/chal_caph_audioh_analogmic.o
#snd-brcm-omx-objs += soc/chal/modules/audio/audvoc/src/chal_audiospeaker.o
#snd-brcm-omx-objs += soc/chal/modules/audio/audvoc/src/chal_audioaipath.o
#snd-brcm-omx-objs += soc/chal/modules/audio/audvoc/src/chal_audioaopath.o
#snd-brcm-omx-objs += soc/chal/modules/audio/audvoc/src/chal_audiopopath.o
#snd-brcm-omx-objs += soc/chal/modules/audio/audvoc/src/chal_audiovipath.o
#snd-brcm-omx-objs += soc/chal/modules/audio/audvoc/src/chal_audiovopath.o
#snd-brcm-omx-objs += soc/chal/modules/audio/audvoc/src/chal_audiopcmif.o
#snd-brcm-omx-objs += soc/chal/modules/audio/audvoc/src/chal_audiomixertap.o
#snd-brcm-omx-objs += soc/chal/modules/audio/audvoc/src/chal_audiomixer.o
#snd-brcm-omx-objs += soc/chal/modules/audio/audvoc/src/chal_audiomic.o

#CSL Source Files
snd-brcm-omx-objs += soc/csl/audio/src/drv_caph_hwctrl.o
snd-brcm-omx-objs += soc/csl/audio/src/drv_audio_common.o
snd-brcm-omx-objs += soc/csl/audio/src/csl_caph_switch.o
snd-brcm-omx-objs += soc/csl/audio/src/csl_caph_srcmixer.o
snd-brcm-omx-objs += soc/csl/audio/src/csl_caph_render.o
snd-brcm-omx-objs += soc/csl/audio/src/csl_caph_pcm_sspi.o
snd-brcm-omx-objs += soc/csl/audio/src/csl_caph_i2s_sspi.o
snd-brcm-omx-objs += soc/csl/audio/src/csl_caph_hwctrl.o
snd-brcm-omx-objs += soc/csl/audio/src/csl_caph_dma.o
snd-brcm-omx-objs += soc/csl/audio/src/csl_caph_config.o
snd-brcm-omx-objs += soc/csl/audio/src/csl_caph_cfifo.o
snd-brcm-omx-objs += soc/csl/audio/src/csl_caph_capture.o
snd-brcm-omx-objs += soc/csl/audio/src/csl_caph_audioh.o
#snd-brcm-omx-objs += soc/csl/audio/src/csl_aud_drv_hw.o
#snd-brcm-omx-objs += soc/csl/audio/src/csl_audvoc_render.o
#snd-brcm-omx-objs += soc/csl/audio/src/csl_audvoc_capture.o
#snd-brcm-omx-objs += soc/csl/audio/src/csl_aud_queue.o

#audio vdriver Source Files
snd-brcm-omx-objs += audio/audio_vdriver/src/audio_vdriver_caph.o
snd-brcm-omx-objs += audio/audio_vdriver/src/audio_vdriver_common.o
snd-brcm-omx-objs += audio/audio_vdriver/src/audio_rpc.o
#snd-brcm-omx-objs += audio/audio_vdriver/src/ripisr_audio.o
#snd-brcm-omx-objs += audio/audio_vdriver/src/dspif_voice_record.o
#snd-brcm-omx-objs += audio/audio_vdriver/src/audio_ipc_ap.o
#snd-brcm-omx-objs += audio/audio_vdriver/src/audio_vdriver_voice_play.o
#snd-brcm-omx-objs += audio/audio_vdriver/src/audio_vdriver_voice_record.o
#snd-brcm-omx-objs += audio/audio_vdriver/src/audio_vdriver_voicetap.o
#snd-brcm-omx-objs += audio/audio_vdriver/src/audio_vdriver_audlog.o
#
#dsp source files
#snd-brcm-omx-objs += dsp/rip/ripisr_ap.o
#snd-brcm-omx-objs += dsp/rip/ripcmdq.o
#snd-brcm-omx-objs += dsp/rip/vpripcmdq.o
#snd-brcm-omx-objs += dsp/rip/vsharedmem.o
#snd-brcm-omx-objs += soc/csl/dsp/src/sharedmem_ap.o


#ccflags-$(CONFIG_BCM_ALSA_SOUND)	+= -DDEBUG

#obj-$(CONFIG_BCM_ALSA_SOUND)		+= snd-brcm-omx.o
#snd-brcm-omx-objs := brcm_alsa_dev.o 
#snd-brcm-omx-objs += brcm_auddrv_test.o
