obj-$(CONFIG_BACKPORT_ATMEL)             += atmel.o
obj-$(CONFIG_BACKPORT_PCI_ATMEL)         += atmel_pci.o 
obj-$(CONFIG_BACKPORT_PCMCIA_ATMEL)      += atmel_cs.o

obj-$(CONFIG_BACKPORT_AT76C50X_USB)      += at76c50x-usb.o
