ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/common/
obj-$(CONFIG_MSM_CSID) += msm_ispif.o
