EXTRA_CFLAGS += -DUNDER_LINUX
EXTRA_CFLAGS += -DIPC_DEBUG
EXTRA_CFLAGS += -DFUSE_DUAL_PROCESSOR_ARCHITECTURE
EXTRA_CFLAGS += -DFUSE_APPS_PROCESSOR
EXTRA_CFLAGS += -D_RHEA_
EXTRA_CFLAGS += -DCONFIG_BRCM_FUSE_IPC_CIB
EXTRA_CFLAGS += -DBCM_INT_ID_RESERVED36="(36 + BCM_INT_ID_PPI_MAX)"

obj-y += ipc_buffer.o
obj-y += ipc_bufferpool.o
obj-y += ipc_powersaving.o
obj-y += ipc_queues.o
obj-y += ipc_sharedmemory.o
obj-y += ipc_smbuffers.o
obj-y += ipc_trace.o
obj-y += ipc_server.o
obj-y += ipc_server_ccb.o
obj-y += ipc_stubs.o
obj-y += lnx_support.o
obj-y += irq_apcp.o
