/*****************************************************************************
  *
  * Voltage tables for Hawaii platform
  *
  * Copyright 2010 Broadcom Corporation.  All rights reserved.
  *
  * Unless you and Broadcom execute a separate written software license
  * agreement governing use of this software, this software is licensed to you
  * under the terms of the GNU General Public License version 2, available at
  * http://www.broadcom.com/licenses/GPLv2.php (the "GPL").
  *
  * Notwithstanding the above, under no circumstances may you combine this
  * software in any way with any other Broadcom software provided under a
  * license other than the GPL, without Broadcom's express prior written
  * consent.
 *****************************************************************************/

#include <linux/module.h>
#include <mach/avs.h>
#include "pm_params.h"

#define ARRAY_LIST(...) {__VA_ARGS__}

#define MSR_RETN_ID				0x1

#define CSR_ECO_ID_1G_SS			0xB
#define CSR_NM_ID_1G_SS				0xB
#define CSR_TURBO_ID_1G_SS			0x14
#define CSR_SUPER_TURBO_ID_1G_SS		0x28

#define CSR_ECO_ID_1G_TS			0xB
#define CSR_NM_ID_1G_TS				0xB
#define CSR_TURBO_ID_1G_TS			0x12
#define CSR_SUPER_TURBO_ID_1G_TS		0x25

#define CSR_ECO_ID_1G_TT			0xB
#define CSR_NM_ID_1G_TT				0xB
#define CSR_TURBO_ID_1G_TT			0x11
#define CSR_SUPER_TURBO_ID_1G_TT		0x23

#define CSR_ECO_ID_1G_TF			0xB
#define CSR_NM_ID_1G_TF				0xB
#define CSR_TURBO_ID_1G_TF			0xE
#define CSR_SUPER_TURBO_ID_1G_TF		0x1F

#define CSR_ECO_ID_1G_FF			0xB
#define CSR_NM_ID_1G_FF				0xB
#define CSR_TURBO_ID_1G_FF			0xC
#define CSR_SUPER_TURBO_ID_1G_FF		0x1B

#define CSR_ECO_ID_1200M_SS			0xB
#define CSR_NM_ID_1200M_SS			0xD
#define CSR_TURBO_ID_1200M_SS			0x18
#define CSR_SUPER_TURBO_ID_1200M_SS		0x30

#define CSR_ECO_ID_1200M_TS			0xB
#define CSR_NM_ID_1200M_TS			0xC
#define CSR_TURBO_ID_1200M_TS			0x16
#define CSR_SUPER_TURBO_ID_1200M_TS		0x2D

#define CSR_ECO_ID_1200M_TT			0xB
#define CSR_NM_ID_1200M_TT			0xC
#define CSR_TURBO_ID_1200M_TT			0x15
#define CSR_SUPER_TURBO_ID_1200M_TT		0x2B

#define CSR_ECO_ID_1200M_TF			0xB
#define CSR_NM_ID_1200M_TF			0xB
#define CSR_TURBO_ID_1200M_TF			0x12
#define CSR_SUPER_TURBO_ID_1200M_TF		0x27

#define CSR_ECO_ID_1200M_FF			0xB
#define CSR_NM_ID_1200M_FF			0xB
#define CSR_TURBO_ID_1200M_FF			0x10
#define CSR_SUPER_TURBO_ID_1200M_FF		0x23

#define CSR_ECO_ID_1500M_SS			0xB
#define CSR_NM_ID_1500M_SS			0xB
#define CSR_TURBO_ID_1500M_SS			0x1d
#define CSR_SUPER_TURBO_ID_1500M_SS		0x34

#define CSR_ECO_ID_1500M_TS			0xB
#define CSR_NM_ID_1500M_TS			0x13
#define CSR_TURBO_ID_1500M_TS			0x1d
#define CSR_SUPER_TURBO_ID_1500M_TS		0x34

#define CSR_ECO_ID_1500M_TT			0xB
#define CSR_NM_ID_1500M_TT			0x13
#define CSR_TURBO_ID_1500M_TT			0x1d
#define CSR_SUPER_TURBO_ID_1500M_TT		0x34

#define CSR_ECO_ID_1500M_TF			0xB
#define CSR_NM_ID_1500M_TF			0x13
#define CSR_TURBO_ID_1500M_TF			0x1d
#define CSR_SUPER_TURBO_ID_1500M_TF		0x34

#define CSR_ECO_ID_1500M_FF			0xB
#define CSR_NM_ID_1500M_FF			0x13
#define CSR_TURBO_ID_1500M_FF			0x1d
#define CSR_SUPER_TURBO_ID_1500M_FF		0x34

#define MSR_ECO_ID_1G_SS			0xF
#define MSR_NM_ID_1G_SS				0x1A
#define MSR_TURBO_ID_1G_SS			0x28
#define MSR_SUPER_TURBO_ID_1G_SS		0x30

#define MSR_ECO_ID_1G_TS			0xF
#define MSR_NM_ID_1G_TS				0x18
#define MSR_TURBO_ID_1G_TS			0x25
#define MSR_SUPER_TURBO_ID_1G_TS		0x2D

#define MSR_ECO_ID_1G_TT			0xF
#define MSR_NM_ID_1G_TT				0x16
#define MSR_TURBO_ID_1G_TT			0x23
#define MSR_SUPER_TURBO_ID_1G_TT		0x2B

#define MSR_ECO_ID_1G_TF			0xF
#define MSR_NM_ID_1G_TF				0x14
#define MSR_TURBO_ID_1G_TF			0x1F
#define MSR_SUPER_TURBO_ID_1G_TF		0x27

#define MSR_ECO_ID_1G_FF			0xF
#define MSR_NM_ID_1G_FF				0x12
#define MSR_TURBO_ID_1G_FF			0x1B
#define MSR_SUPER_TURBO_ID_1G_FF		0x23

#define MSR_ECO_ID_1200M_SS			0xF
#define MSR_NM_ID_1200M_SS			0x1A
#define MSR_TURBO_ID_1200M_SS			0x28
#define MSR_SUPER_TURBO_ID_1200M_SS		0x30

#define MSR_ECO_ID_1200M_TS			0xF
#define MSR_NM_ID_1200M_TS			0x18
#define MSR_TURBO_ID_1200M_TS			0x25
#define MSR_SUPER_TURBO_ID_1200M_TS		0x2D

#define MSR_ECO_ID_1200M_TT			0xF
#define MSR_NM_ID_1200M_TT			0x16
#define MSR_TURBO_ID_1200M_TT			0x23
#define MSR_SUPER_TURBO_ID_1200M_TT		0x2B

#define MSR_ECO_ID_1200M_TF			0xF
#define MSR_NM_ID_1200M_TF			0x14
#define MSR_TURBO_ID_1200M_TF			0x1F
#define MSR_SUPER_TURBO_ID_1200M_TF		0x27

#define MSR_ECO_ID_1200M_FF			0xF
#define MSR_NM_ID_1200M_FF			0x12
#define MSR_TURBO_ID_1200M_FF			0x1B
#define MSR_SUPER_TURBO_ID_1200M_FF		0x23


#define MSR_ECO_ID_1500M_SS			0xF
#define MSR_NM_ID_1500M_SS			0x1A
#define MSR_TURBO_ID_1500M_SS			0x28
#define MSR_SUPER_TURBO_ID_1500M_SS		0x28

#define MSR_ECO_ID_1500M_TS			0xF
#define MSR_NM_ID_1500M_TS			0x18
#define MSR_TURBO_ID_1500M_TS			0x25
#define MSR_SUPER_TURBO_ID_1500M_TS		0x25

#define MSR_ECO_ID_1500M_TT			0xF
#define MSR_NM_ID_1500M_TT			0x16
#define MSR_TURBO_ID_1500M_TT			0x23
#define MSR_SUPER_TURBO_ID_1500M_TT		0x23

#define MSR_ECO_ID_1500M_TF			0xF
#define MSR_NM_ID_1500M_TF			0x14
#define MSR_TURBO_ID_1500M_TF			0x1F
#define MSR_SUPER_TURBO_ID_1500M_TF		0x1F

#define MSR_ECO_ID_1500M_FF			0xF
#define MSR_NM_ID_1500M_FF			0x12
#define MSR_TURBO_ID_1500M_FF			0x1B
#define MSR_SUPER_TURBO_ID_1500M_FF		0x1B

#define PMU_VLT_TBL_1G_SS ARRAY_LIST(\
		INIT_A9_VLT_TABLE(CSR_ECO_ID_1G_SS, CSR_NM_ID_1G_SS,\
			CSR_TURBO_ID_1G_SS, CSR_SUPER_TURBO_ID_1G_SS),\
		INIT_OTHER_VLT_TABLE(MSR_ECO_ID_1G_SS, MSR_NM_ID_1G_SS,\
			MSR_TURBO_ID_1G_SS, MSR_SUPER_TURBO_ID_1G_SS),\
		INIT_LPM_VLT_IDS(MSR_RETN_ID, MSR_RETN_ID, MSR_RETN_ID),\
		INIT_UNUSED_VLT_IDS(MSR_RETN_ID))

#define PMU_VLT_TBL_1G_TS ARRAY_LIST(\
		INIT_A9_VLT_TABLE(CSR_ECO_ID_1G_TS, CSR_NM_ID_1G_TS,\
			CSR_TURBO_ID_1G_TS, CSR_SUPER_TURBO_ID_1G_TS),\
		INIT_OTHER_VLT_TABLE(MSR_ECO_ID_1G_TS, MSR_NM_ID_1G_TS,\
			MSR_TURBO_ID_1G_TS, MSR_SUPER_TURBO_ID_1G_TS),\
		INIT_LPM_VLT_IDS(MSR_RETN_ID, MSR_RETN_ID, MSR_RETN_ID),\
		INIT_UNUSED_VLT_IDS(MSR_RETN_ID))

#define PMU_VLT_TBL_1G_TT ARRAY_LIST(\
		INIT_A9_VLT_TABLE(CSR_ECO_ID_1G_TT, CSR_NM_ID_1G_TT,\
			CSR_TURBO_ID_1G_TT, CSR_SUPER_TURBO_ID_1G_TT),\
		INIT_OTHER_VLT_TABLE(MSR_ECO_ID_1G_TT, MSR_NM_ID_1G_TT,\
			MSR_TURBO_ID_1G_TT, MSR_SUPER_TURBO_ID_1G_TT),\
		INIT_LPM_VLT_IDS(MSR_RETN_ID, MSR_RETN_ID, MSR_RETN_ID),\
		INIT_UNUSED_VLT_IDS(MSR_RETN_ID))

#define PMU_VLT_TBL_1G_TF ARRAY_LIST(\
		INIT_A9_VLT_TABLE(CSR_ECO_ID_1G_TF, CSR_NM_ID_1G_TF,\
			CSR_TURBO_ID_1G_TF, CSR_SUPER_TURBO_ID_1G_TF),\
		INIT_OTHER_VLT_TABLE(MSR_ECO_ID_1G_TF, MSR_NM_ID_1G_TF,\
			MSR_TURBO_ID_1G_TF, MSR_SUPER_TURBO_ID_1G_TF),\
		INIT_LPM_VLT_IDS(MSR_RETN_ID, MSR_RETN_ID, MSR_RETN_ID),\
		INIT_UNUSED_VLT_IDS(MSR_RETN_ID))

#define PMU_VLT_TBL_1G_FF ARRAY_LIST(\
		INIT_A9_VLT_TABLE(CSR_ECO_ID_1G_FF, CSR_NM_ID_1G_FF,\
			CSR_TURBO_ID_1G_FF, CSR_SUPER_TURBO_ID_1G_FF),\
		INIT_OTHER_VLT_TABLE(MSR_ECO_ID_1G_FF, MSR_NM_ID_1G_FF,\
			MSR_TURBO_ID_1G_FF, MSR_SUPER_TURBO_ID_1G_FF),\
		INIT_LPM_VLT_IDS(MSR_RETN_ID, MSR_RETN_ID, MSR_RETN_ID),\
		INIT_UNUSED_VLT_IDS(MSR_RETN_ID))

#define PMU_VLT_TBL_1200M_SS ARRAY_LIST(\
		INIT_A9_VLT_TABLE(CSR_ECO_ID_1200M_SS, CSR_NM_ID_1200M_SS,\
			CSR_TURBO_ID_1200M_SS, CSR_SUPER_TURBO_ID_1200M_SS),\
		INIT_OTHER_VLT_TABLE(MSR_ECO_ID_1200M_SS, MSR_NM_ID_1200M_SS,\
			MSR_TURBO_ID_1200M_SS, MSR_SUPER_TURBO_ID_1200M_SS),\
		INIT_LPM_VLT_IDS(MSR_RETN_ID, MSR_RETN_ID, MSR_RETN_ID),\
		INIT_UNUSED_VLT_IDS(MSR_RETN_ID))

#define PMU_VLT_TBL_1200M_TS ARRAY_LIST(\
		INIT_A9_VLT_TABLE(CSR_ECO_ID_1200M_TS, CSR_NM_ID_1200M_TS,\
			CSR_TURBO_ID_1200M_TS, CSR_SUPER_TURBO_ID_1200M_TS),\
		INIT_OTHER_VLT_TABLE(MSR_ECO_ID_1200M_TS, MSR_NM_ID_1200M_TS,\
			MSR_TURBO_ID_1200M_TS, MSR_SUPER_TURBO_ID_1200M_TS),\
		INIT_LPM_VLT_IDS(MSR_RETN_ID, MSR_RETN_ID, MSR_RETN_ID),\
		INIT_UNUSED_VLT_IDS(MSR_RETN_ID))

#define PMU_VLT_TBL_1200M_TT ARRAY_LIST(\
		INIT_A9_VLT_TABLE(CSR_ECO_ID_1200M_TT, CSR_NM_ID_1200M_TT,\
			CSR_TURBO_ID_1200M_TT, CSR_SUPER_TURBO_ID_1200M_TT),\
		INIT_OTHER_VLT_TABLE(MSR_ECO_ID_1200M_TT, MSR_NM_ID_1200M_TT,\
			MSR_TURBO_ID_1200M_TT, MSR_SUPER_TURBO_ID_1200M_TT),\
		INIT_LPM_VLT_IDS(MSR_RETN_ID, MSR_RETN_ID, MSR_RETN_ID),\
		INIT_UNUSED_VLT_IDS(MSR_RETN_ID))

#define PMU_VLT_TBL_1200M_TF ARRAY_LIST(\
		INIT_A9_VLT_TABLE(CSR_ECO_ID_1200M_TF, CSR_NM_ID_1200M_TF,\
			CSR_TURBO_ID_1200M_TF, CSR_SUPER_TURBO_ID_1200M_TF),\
		INIT_OTHER_VLT_TABLE(MSR_ECO_ID_1200M_TF, MSR_NM_ID_1200M_TF,\
			MSR_TURBO_ID_1200M_TF, MSR_SUPER_TURBO_ID_1200M_TF),\
		INIT_LPM_VLT_IDS(MSR_RETN_ID, MSR_RETN_ID, MSR_RETN_ID),\
		INIT_UNUSED_VLT_IDS(MSR_RETN_ID))

#define PMU_VLT_TBL_1200M_FF ARRAY_LIST(\
		INIT_A9_VLT_TABLE(CSR_ECO_ID_1200M_FF, CSR_NM_ID_1200M_FF,\
			CSR_TURBO_ID_1200M_FF, CSR_SUPER_TURBO_ID_1200M_FF),\
		INIT_OTHER_VLT_TABLE(MSR_ECO_ID_1200M_FF, MSR_NM_ID_1200M_FF,\
			MSR_TURBO_ID_1200M_FF, MSR_SUPER_TURBO_ID_1200M_FF),\
		INIT_LPM_VLT_IDS(MSR_RETN_ID, MSR_RETN_ID, MSR_RETN_ID),\
		INIT_UNUSED_VLT_IDS(MSR_RETN_ID))

#define PMU_VLT_TBL_1500M_SS ARRAY_LIST(\
		INIT_A9_VLT_TABLE(CSR_ECO_ID_1500M_SS, CSR_NM_ID_1500M_SS,\
			CSR_TURBO_ID_1500M_SS, CSR_SUPER_TURBO_ID_1500M_SS),\
		INIT_OTHER_VLT_TABLE(MSR_ECO_ID_1500M_SS, MSR_NM_ID_1500M_SS,\
			MSR_TURBO_ID_1500M_SS, MSR_SUPER_TURBO_ID_1500M_SS),\
		INIT_LPM_VLT_IDS(MSR_RETN_ID, MSR_RETN_ID, MSR_RETN_ID),\
		INIT_UNUSED_VLT_IDS(MSR_RETN_ID))

#define PMU_VLT_TBL_1500M_TS ARRAY_LIST(\
		INIT_A9_VLT_TABLE(CSR_ECO_ID_1500M_TS, CSR_NM_ID_1500M_TS,\
			CSR_TURBO_ID_1500M_TS, CSR_SUPER_TURBO_ID_1500M_TS),\
		INIT_OTHER_VLT_TABLE(MSR_ECO_ID_1500M_TS, MSR_NM_ID_1500M_TS,\
			MSR_TURBO_ID_1500M_TS, MSR_SUPER_TURBO_ID_1500M_TS),\
		INIT_LPM_VLT_IDS(MSR_RETN_ID, MSR_RETN_ID, MSR_RETN_ID),\
		INIT_UNUSED_VLT_IDS(MSR_RETN_ID))

#define PMU_VLT_TBL_1500M_TT ARRAY_LIST(\
		INIT_A9_VLT_TABLE(CSR_ECO_ID_1500M_TT, CSR_NM_ID_1500M_TT,\
			CSR_TURBO_ID_1500M_TT, CSR_SUPER_TURBO_ID_1500M_TT),\
		INIT_OTHER_VLT_TABLE(MSR_ECO_ID_1500M_TT, MSR_NM_ID_1500M_TT,\
			MSR_TURBO_ID_1500M_TT, MSR_SUPER_TURBO_ID_1500M_TT),\
		INIT_LPM_VLT_IDS(MSR_RETN_ID, MSR_RETN_ID, MSR_RETN_ID),\
		INIT_UNUSED_VLT_IDS(MSR_RETN_ID))

#define PMU_VLT_TBL_1500M_TF ARRAY_LIST(\
		INIT_A9_VLT_TABLE(CSR_ECO_ID_1500M_TF, CSR_NM_ID_1500M_TF,\
			CSR_TURBO_ID_1500M_TF, CSR_SUPER_TURBO_ID_1500M_TF),\
		INIT_OTHER_VLT_TABLE(MSR_ECO_ID_1500M_TF, MSR_NM_ID_1500M_TF,\
			MSR_TURBO_ID_1500M_TF, MSR_SUPER_TURBO_ID_1500M_TF),\
		INIT_LPM_VLT_IDS(MSR_RETN_ID, MSR_RETN_ID, MSR_RETN_ID),\
		INIT_UNUSED_VLT_IDS(MSR_RETN_ID))

#define PMU_VLT_TBL_1500M_FF ARRAY_LIST(\
		INIT_A9_VLT_TABLE(CSR_ECO_ID_1500M_FF, CSR_NM_ID_1500M_FF,\
			CSR_TURBO_ID_1500M_FF, CSR_SUPER_TURBO_ID_1500M_FF),\
		INIT_OTHER_VLT_TABLE(MSR_ECO_ID_1500M_FF, MSR_NM_ID_1500M_FF,\
			MSR_TURBO_ID_1500M_FF, MSR_SUPER_TURBO_ID_1500M_FF),\
		INIT_LPM_VLT_IDS(MSR_RETN_ID, MSR_RETN_ID, MSR_RETN_ID),\
		INIT_UNUSED_VLT_IDS(MSR_RETN_ID))

u8 pmu_vlt_table_1g[SILICON_TYPE_MAX][SR_VLT_LUT_SIZE] = {
	PMU_VLT_TBL_1G_SS, PMU_VLT_TBL_1G_TS, PMU_VLT_TBL_1G_TT,
	PMU_VLT_TBL_1G_TF, PMU_VLT_TBL_1G_FF,
};

u8 pmu_vlt_table_1200m[SILICON_TYPE_MAX][SR_VLT_LUT_SIZE] = {
	PMU_VLT_TBL_1200M_SS, PMU_VLT_TBL_1200M_TS, PMU_VLT_TBL_1200M_TT,
	PMU_VLT_TBL_1200M_TF, PMU_VLT_TBL_1200M_FF,
};

u8 pmu_vlt_table_1500m[SILICON_TYPE_MAX][SR_VLT_LUT_SIZE] = {
	PMU_VLT_TBL_1500M_SS, PMU_VLT_TBL_1500M_TS, PMU_VLT_TBL_1500M_TT,
	PMU_VLT_TBL_1500M_TF, PMU_VLT_TBL_1500M_FF,
};

const u8 *get_sr_vlt_table(u32 silicon_type, int freq_id, void *param)
{
	u8 *vlt_table = (u8 *) pmu_vlt_table_1g[0];
#ifdef CONFIG_KONA_AVS
	int i = 0;
	struct adj_param *adj_param = (struct adj_param *)param;
#endif
	pr_info("%s silicon_type = %d, freq_id = %d\n", __func__,
		silicon_type, freq_id);
#ifdef CONFIG_KONA_AVS
	if (silicon_type > SILICON_TYPE_MAX || freq_id > A9_FREQ_MAX)
		BUG();
	switch (freq_id) {
	case A9_FREQ_1000_MHZ:
			vlt_table = pmu_vlt_table_1g[silicon_type];
			break;
	case A9_FREQ_1200_MHZ:
			vlt_table = pmu_vlt_table_1200m[silicon_type];
			break;
	case A9_FREQ_1500_MHZ:
			vlt_table = pmu_vlt_table_1500m[silicon_type];
			break;
	default:
			BUG();
	}
	if (adj_param && (adj_param->flags & AVS_VDDVAR_A9_ADJ_EN)) {
		for (i = 8; i < 0x10; (i = i+2))
			vlt_table[i] += adj_param->
				vddvar_a9_adj_val[silicon_type]/10;
	}
#endif
	return vlt_table;
}
