--- drivers/bluetooth/Makefile
+++ drivers/bluetooth/Makefile
@@ -22,6 +22,7 @@
 obj-$(CONFIG_MSM_BT_POWER)	+= bluetooth-power.o
 obj-$(CONFIG_BT_MSM_SLEEP)	+= msm_bt_sleep.o
 msm_bt_sleep-objs		:= bluesleep.o
+obj-$(CONFIG_BT_BCM4339)	+= bcm4339.o
 
 btmrvl-y			:= btmrvl_main.o
 btmrvl-$(CONFIG_DEBUG_FS)	+= btmrvl_debugfs.o
