obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_ARCH_QCOM)		+= qcom/
obj-$(CONFIG_ARCH_QCOM)		+= qcom/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_QNS_SYSTEM)	+= qns_system.o
obj-$(CONFIG_CHARGER_LIS2XXX)	+= lis2xxx-charger.o
