
EXTRA_CFLAGS := -fno-inline -Wno-multichar -O2

obj-y += common/
obj-y += v3d/
obj-y += interlock/
obj-y += isp/
obj-$(CONFIG_HAWAII_MM_H264) += h264/
obj-$(CONFIG_HAWAII_MM_H264) += h264_ol/
obj-$(CONFIG_ARCH_JAVA) += isp2/
#obj-y += unicam/
