EXTRA_CFLAGS += -I"vc4-dev/src/interface/vceb/host/"
EXTRA_CFLAGS += -I"vc4-dev/src/interface/vceb/host/linux"
EXTRA_CFLAGS += -I"vc4-dev/src/interface/vceb/host/common"
EXTRA_CFLAGS += -I"vc4-dev/src/interface/vceb/common"

obj-$(CONFIG_FB_VCEB_USE_BOOTMEMHEAP) += vceb_fb_mem.o
