ifeq ($(CONFIG_OF),y)

# MSM8994
dtb-$(CONFIG_MACH_SONY_IVY)		+= msm8994-v2.0-kitakami_ivy_generic.dtb
dtb-$(CONFIG_MACH_SONY_IVY)		+= msm8994-v2.1-kitakami_ivy_generic.dtb
dtb-$(CONFIG_MACH_SONY_IVY_DSDS)	+= msm8994-v2.0-kitakami_ivy_dsds.dtb
dtb-$(CONFIG_MACH_SONY_IVY_DSDS)	+= msm8994-v2.1-kitakami_ivy_dsds.dtb
dtb-$(CONFIG_MACH_SONY_KARIN)		+= msm8994-v2.0-kitakami_karin_generic.dtb
dtb-$(CONFIG_MACH_SONY_KARIN)		+= msm8994-v2.1-kitakami_karin_generic.dtb
dtb-$(CONFIG_MACH_SONY_KARIN_WINDY)	+= apq8094-v2.0-kitakami_karin_windy.dtb
dtb-$(CONFIG_MACH_SONY_KARIN_WINDY)	+= apq8094-v2.1-kitakami_karin_windy.dtb
dtb-$(CONFIG_MACH_SONY_SUMIRE)		+= msm8994-v2.0-kitakami_sumire_generic.dtb
dtb-$(CONFIG_MACH_SONY_SUMIRE)		+= msm8994-v2.1-kitakami_sumire_generic.dtb
dtb-$(CONFIG_MACH_SONY_SUMIRE_DSDS)	+= msm8994-v2.0-kitakami_sumire_dsds.dtb
dtb-$(CONFIG_MACH_SONY_SUMIRE_DSDS)	+= msm8994-v2.1-kitakami_sumire_dsds.dtb
dtb-$(CONFIG_MACH_SONY_SUZURAN)		+= msm8994-v2.0-kitakami_suzuran_generic.dtb
dtb-$(CONFIG_MACH_SONY_SUZURAN)		+= msm8994-v2.1-kitakami_suzuran_generic.dtb

# MSM8939/MSM8916
dtb-$(CONFIG_MACH_SONY_TULIP)		+= msm8939-kanuti_tulip.dtb

# MSM8974
dtb-$(CONFIG_MACH_SONY_SIRIUS)		+= msm8974pro-ab-shinano_sirius.dtb
dtb-$(CONFIG_MACH_SONY_CASTOR)		+= msm8974pro-ab-shinano_castor.dtb
dtb-$(CONFIG_MACH_SONY_CASTOR)	 	+= apq8074pro-ab-shinano_castor_windy.dtb
dtb-$(CONFIG_MACH_SONY_LEO)		+= msm8974pro-ac-shinano_leo.dtb
dtb-$(CONFIG_MACH_SONY_ARIES)		+= msm8974pro-ac-shinano_aries.dtb
dtb-$(CONFIG_MACH_SONY_SCORPION)	+= msm8974pro-ac-shinano_scorpion.dtb
dtb-$(CONFIG_MACH_SONY_SCORPION)	+= apq8074pro-ac-shinano_scorpion_windy.dtb

dtb-$(CONFIG_MACH_SONY_HONAMI_ROW)	+= msm8974-v2.0-1-rhine_honami_row.dtb
dtb-$(CONFIG_MACH_SONY_HONAMI_ROW)	+= msm8974-v2.2-rhine_honami_row.dtb
dtb-$(CONFIG_MACH_SONY_TOGARI_ROW)	+= msm8974-v2.0-1-rhine_togari_row.dtb
dtb-$(CONFIG_MACH_SONY_TOGARI_ROW)	+= msm8974-v2.2-rhine_togari_row.dtb
dtb-$(CONFIG_MACH_SONY_AMAMI_ROW)	+= msm8974-v2.0-1-rhine_amami_row.dtb
dtb-$(CONFIG_MACH_SONY_AMAMI_ROW)	+= msm8974-v2.2-rhine_amami_row.dtb

# MSM8226
dtb-$(CONFIG_MACH_SONY_EAGLE)	+= msm8226-yukon_eagle-720p-mtp.dtb
dtb-$(CONFIG_MACH_SONY_EAGLE)	+= msm8926-yukon_eagle-720p-mtp.dtb
dtb-$(CONFIG_MACH_SONY_FLAMINGO)+= msm8926-yukon_flamingo-8926ss_ap.dtb
dtb-$(CONFIG_MACH_SONY_TIANCHI) += msm8926-yukon_tianchi.dtb
dtb-$(CONFIG_MACH_SONY_TIANCHI) += msm8226-yukon_tianchi_dsds.dtb
dtb-$(CONFIG_MACH_SONY_SEAGULL) += msm8926-yukon_seagull-720p-mtp.dtb

# Other
dtb-$(CONFIG_ARCH_MSM8909) += msm8909-sim.dtb \
	msm8909-rumi.dtb \
	msm8909-qrd-skua.dtb \
	msm8909-qrd-skuc.dtb \
	msm8909-qrd-skue.dtb \
	msm8909-cdp.dtb \
	msm8909-mtp.dtb \
	msm8909-mtp-smb1360.dtb \
	msm8909-1gb-qrd-skua.dtb \
	msm8909-1gb-cdp.dtb \
	msm8909-1gb-mtp.dtb
dtb-$(CONFIG_ARCH_MSM8610) += msm8610-rumi.dtb \
	msm8610-v1-cdp.dtb \
	msm8610-v2-cdp.dtb \
	msm8610-v1-mtp.dtb \
	msm8610-v2-mtp.dtb \
	msm8610-sim.dtb \
	msm8610-v1-qrd-skuaa.dtb \
	msm8610-v1-qrd-skuab.dtb \
	msm8610-v2-qrd-skuaa.dtb \
	msm8610-v2-qrd-skuab.dtb
dtb-$(CONFIG_ARCH_FSM9900) += fsm9900-rumi.dtb \
	fsm9900-sim.dtb \
	fsm9900-cdp.dtb \
	fsm9900-mtp-v1.0.dtb \
	fsm9900-mtp-v1.1.dtb
dtb-$(CONFIG_ARCH_FSM9010) += fsm9010-rumi.dtb
dtb-$(CONFIG_ARCH_MDM9630) += mdm9630-sim.dtb \
	mdm9630-v1-cdp.dtb \
	mdm9630-v1-mtp.dtb \
	mdm9630-v2-cdp.dtb \
	mdm9630-v2-mtp.dtb \
	mdm9630-v2-tsmc-cdp.dtb \
	mdm9630-v2-gf-cdp.dtb  \
	mdm9630-v2-tsmc-mtp.dtb \
	mdm9630-v2-gf-mtp.dtb
dtb-$(CONFIG_ARCH_MSMZIRC) += msmzirc-sim.dtb \
	msmzirc-rumi.dtb \
	msmzirc-emmc-cdp.dtb \
	msmzirc-nand-cdp.dtb \
	msmzirc-mtp.dtb
dtb-$(CONFIG_ARCH_MDMFERRUM) += mdmferrum-sim.dtb \
	mdmferrum-rumi.dtb \
	mdmferrum-cdp.dtb \
	mdmferrum-mtp.dtb
dtb-$(CONFIG_ARCH_APQ8084) += apq8084-v1.0-old-pwr-grid-liquid.dtb \
	apq8084-v1.1-old-pwr-grid-liquid.dtb \
	apq8084-v1.1-liquid.dtb \
	apq8084-v1.0-old-pwr-grid-smb1357-cdp.dtb \
	apq8084-v1.1-old-pwr-grid-smb1357-cdp.dtb \
	apq8084-v1.1-smb1357-cdp.dtb \
	apq8084-v1.0-old-pwr-grid-smb1357-mtp.dtb \
	apq8084-v1.1-old-pwr-grid-smb1357-mtp.dtb \
	apq8084-v1.1-smb1357-mtp.dtb \
	apq8084-v1.0-old-pwr-grid-smb1359-mdm9x35-alt-mtp.dtb \
	apq8084-v1.1-old-pwr-grid-smb1359-mdm9x35-alt-mtp.dtb \
	apq8084-v1.1-smb1359-mdm9x35-alt-mtp.dtb \
	apq8084-old-pwr-grid-smb349-cdp.dtb \
	apq8084-old-pwr-grid-smb349-mtp.dtb \
	apq8084-v1.0-old-pwr-grid-smb1357-mdm9x35-alt-rcm.dtb \
	apq8084-v1.1-old-pwr-grid-smb1357-mdm9x35-alt-rcm.dtb \
	apq8084-v1.1-smb1357-mdm9x35-alt-rcm.dtb \
	apq8084-v1.0-old-pwr-grid-smb1357-mdm9x35-mtp.dtb \
	apq8084-v1.1-old-pwr-grid-smb1357-mdm9x35-mtp.dtb \
	apq8084-v1.1-smb1357-mdm9x35-mtp.dtb \
	apq8084-v1.0-old-pwr-grid-smb1357-mdm9x35-cdp.dtb \
	apq8084-v1.1-old-pwr-grid-smb1357-mdm9x35-cdp.dtb \
	apq8084-v1.1-smb1357-mdm9x35-cdp.dtb \
	apq8084-v1.0-old-pwr-grid-mdm9x35-alt-cdp.dtb \
	apq8084-v1.1-old-pwr-grid-mdm9x35-alt-cdp.dtb \
	apq8084-v1.1-mdm9x35-alt-cdp.dtb \
	apq8084-v1.1-sbc.dtb

dtb-$(CONFIG_ARCH_MSM8992) += msm8992-sim.dtb \
	msm8992-rumi.dtb \
	msm8992-cdp.dtb \
	msm8992-mtp.dtb

DTB_NAMES := $(subst $\",,$(CONFIG_BUILD_ARM_APPENDED_DTB_IMAGE_NAMES))
ifneq ($(DTB_NAMES),)
DTB_LIST := $(addsuffix .dtb,$(DTB_NAMES))
else
DTB_LIST := $(dtb-y)
endif

targets += dtbs
targets += $(addprefix ../, $(DTB_LIST))
endif

$(obj)/../%.dtb: $(src)/%.dts FORCE
	$(call if_changed_dep,dtc)

dtbs: $(addprefix $(obj)/../,$(DTB_LIST))

clean-files := *.dtb
