#******************************************************************************
#*
#*    Copyright 2009  Broadcom Corporation
#*    All Rights Reserved
#*
#*    No portions of this material may be reproduced in any form without the
#*    written permission of:
#*
#*       Broadcom Corporation
#*       16215 Alton Parkway
#*       Irvine, California 92619-7013
#*
#*    All information contained in this document is Broadcom Corporation
#*    company private, proprietary, and trade secret.
#*
#******************************************************************************
EXTRA_CFLAGS += -Wno-strict-prototypes 
obj-$(CONFIG_BRCM_XSCRIPT_REGULATOR) += xscript_regulator.o 
