ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/sensor/cci
obj-$(CONFIG_MSMB_CAMERA)   += msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o
