EXTRA_CFLAGS  += -Wall -Wstrict-prototypes -Wno-trigraphs
EXTRA_CFLAGS  += -Werror
EXTRA_CFLAGS  += -Idrivers/videocore
EXTRA_CFLAGS  += -Idrivers/videocore/host_support/include

obj-$(CONFIG_VC_MEM) := vc-mem.o

vc-mem-objs := vc_mem.o

