#
# Makefile for the Novatek touchscreen drivers.
#

obj-$(CONFIG_TOUCHSCREEN_NT36672) := nt36xxx.o
obj-$(CONFIG_TOUCHSCREEN_NT36672) += nt36xxx_fw_update.o
obj-$(CONFIG_TOUCHSCREEN_NT36672) += nt36xxx_ext_proc.o
obj-$(CONFIG_TOUCHSCREEN_NT36672) += nt36xxx_mp_ctrlram.o

