# Haptic Core
obj-$(CONFIG_HAPTIC_CLASS)		+= haptic-class.o

# Drivers
obj-$(CONFIG_HAPTIC_SAMSUNG_PWM)	+= haptic-samsung-pwm.o
obj-$(CONFIG_BCM_HAPTICS)			+= bcm_haptics.o
obj-$(CONFIG_BCM_SS_VIBRA)              += bcm_ss_vibra.o
