obj-$(CONFIG_FB_BRCM_KONA) += lcd_clock.o

obj-$(CONFIG_LCD_S6E63M0X_SUPPORT) += s6e63m0x3_dsi.o smart_mtp_s6e63m0_dsi.o
obj-$(CONFIG_LCD_HX8369_SUPPORT) += hx8369_dsi.o
obj-$(CONFIG_LCD_HX8369_CS02_SUPPORT) += hx8369_dsi.o
obj-$(CONFIG_LCD_SC7798_CS02_SUPPORT) += sc7798_dsi.o
obj-$(CONFIG_LDI_MDNIE_SUPPORT) += mdnie.o mdnie_tuning.o
