EXTRA_CFLAGS += -D_RHEA_

obj-y			+= lcd_clock.o
obj-y			+= dispdrv_nt35582_wvga_smi.o
obj-y			+= dispdrv_bcm91008_alex_dsi.o
obj-y			+= dispdrv_R61581_hvga_smi.o
obj-y			+= dispdrv_s6d05a1_dsi.o
obj-y			+= dispdrv_lq043y1dx01_dsi.o
obj-y			+= dispdrv_common_dsi.o
obj-$(CONFIG_LCD_ILI9486_SUPPORT)	+= dispdrv_ili9486_dsi.o
obj-$(CONFIG_LCD_R61531_SUPPORT)	+= dispdrv_R61531_dsi.o
obj-$(CONFIG_LCD_ILI9341_SUPPORT)       += dispdrv_ili9341_smi.o
