/****************************************************************************
*																			
*     Copyright (c) 2007-2008 Broadcom Corporation								
*																			
*   Unless you and Broadcom execute a separate written software license		
*   agreement governing use of this software, this software is licensed to you	
*   under the terms of the GNU General Public License version 2, available	
*    at http://www.gnu.org/licenses/old-licenses/gpl-2.0.html (the "GPL").	
*																			
*   Notwithstanding the above, under no circumstances may you combine this	
*   software in any way with any other Broadcom software provided under a license 
*   other than the GPL, without Broadcom's express prior written consent.	
*																			
****************************************************************************/
/****************************************************************************
*																			
*     WARNING!!!! Generated File ( Do NOT Modify !!!! )					
*																			
****************************************************************************/
#include "capi2_gen_common.h"
#ifndef CAPI2_GEN_MSG_CP_H
#define CAPI2_GEN_MSG_CP_H



Result_t CP_CAPI2_MS_IsGSMRegistered(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_IsGPRSRegistered(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_GetGSMRegCause(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_GetGPRSRegCause(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_GetRegisteredLAC(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_GetPlmnMCC(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_GetPlmnMNC(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYS_ProcessPowerDownReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYS_ProcessNoRfReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYS_ProcessPowerUpReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYS_GetMSPowerOnCause(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_IsGprsAllowed(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_GetCurrentRAT(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_GetCurrentBand(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_SetStartBand(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt8 startBand);
Result_t CP_CAPI2_SIM_UpdateSMSCapExceededFlag(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, Boolean cap_exceeded);
Result_t CP_CAPI2_SYS_SelectBand(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, BandSelect_t bandSelect);
Result_t CP_CAPI2_MS_SetSupportedRATandBand(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, RATSelect_t RAT_cap, BandSelect_t band_cap);
Result_t CP_CAPI2_PLMN_GetCountryByMcc(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt16 mcc);
Result_t CP_CAPI2_MS_GetPLMNEntryByIndex(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt16 index, Boolean ucs2);
Result_t CP_CAPI2_MS_GetPLMNListSize(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_GetPLMNByCode(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, Boolean ucs2, UInt16 plmn_mcc, UInt16 plmn_mnc);
Result_t CP_CAPI2_MS_PlmnSelect(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, Boolean ucs2, PlmnSelectMode_t selectMode, PlmnSelectFormat_t format, char_ptr_t plmnValue);
Result_t CP_CAPI2_MS_AbortPlmnSelect(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_GetPlmnMode(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_SetPlmnMode(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, PlmnSelectMode_t mode);
Result_t CP_CAPI2_MS_GetPlmnFormat(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_SetPlmnFormat(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, PlmnSelectFormat_t format);
Result_t CP_CAPI2_MS_IsMatchedPLMN(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt16 net_mcc, UInt8 net_mnc, UInt16 mcc, UInt8 mnc);
Result_t CP_CAPI2_MS_SearchAvailablePLMN(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_AbortSearchPLMN(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_AutoSearchReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_GetPLMNNameByCode(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt16 mcc, UInt8 mnc, UInt16 lac, Boolean ucs2);
Result_t CP_CAPI2_SYS_IsResetCausedByAssert(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYS_GetSystemState(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYS_SetSystemState(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SystemState_t state);
Result_t CP_CAPI2_SYS_GetRxSignalInfo(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYS_GetGSMRegistrationStatus(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYS_GetGPRSRegistrationStatus(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYS_IsRegisteredGSMOrGPRS(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYS_GetGSMRegistrationCause(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_IsPlmnForbidden(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_IsRegisteredHomePLMN(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_SetPowerDownTimer(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt8 powerDownTimer);
Result_t CP_CAPI2_SIMLockIsLockOn(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SIMLockType_t lockType);
Result_t CP_CAPI2_SIMLockCheckAllLocks(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, uchar_ptr_t imsi, uchar_ptr_t gid1, uchar_ptr_t gid2);
Result_t CP_CAPI2_SIMLockUnlockSIM(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SIMLockType_t lockType, uchar_ptr_t key);
Result_t CP_CAPI2_SIMLockGetCurrentClosedLock(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIMLockChangePasswordPHSIM(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, uchar_ptr_t old_pwd, uchar_ptr_t new_pwd);
Result_t CP_CAPI2_SIMLockCheckPasswordPHSIM(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, uchar_ptr_t pwd);
Result_t CP_CAPI2_SIMLockGetSignature(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIMLockGetImeiSecboot(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_GetSmsParamRecNum(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_GetSmsMemExceededFlag(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_IsPINRequired(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_GetCardPhase(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_GetSIMType(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_GetPresentStatus(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_IsOperationRestricted(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_IsPINBlocked(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, CHV_t chv);
Result_t CP_CAPI2_SIM_IsPUKBlocked(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, CHV_t chv);
Result_t CP_CAPI2_SIM_IsInvalidSIM(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_DetectSim(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_GetRuimSuppFlag(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_SendVerifyChvReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, CHV_t chv_select, CHVString_t chv);
Result_t CP_CAPI2_SIM_SendChangeChvReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, CHV_t chv_select, CHVString_t old_chv, CHVString_t new_chv);
Result_t CP_CAPI2_SIM_SendSetChv1OnOffReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, CHVString_t chv, Boolean enable_flag);
Result_t CP_CAPI2_SIM_SendUnblockChvReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, CHV_t chv_select, PUKString_t puk, CHVString_t new_chv);
Result_t CP_CAPI2_SIM_SendSetOperStateReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SIMOperState_t oper_state, CHVString_t chv2);
Result_t CP_CAPI2_SIM_IsPbkAccessAllowed(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SIMPBK_ID_t id);
Result_t CP_CAPI2_SIM_SendPbkInfoReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SIMPBK_ID_t id);
Result_t CP_CAPI2_SIM_SendReadAcmMaxReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_SendWriteAcmMaxReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, CallMeterUnit_t acm_max);
Result_t CP_CAPI2_SIM_SendReadAcmReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_SendWriteAcmReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, CallMeterUnit_t acm);
Result_t CP_CAPI2_SIM_SendIncreaseAcmReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, CallMeterUnit_t acm);
Result_t CP_CAPI2_SIM_SendReadSvcProvNameReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_SendReadPuctReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_GetServiceStatus(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SIMService_t service);
Result_t CP_CAPI2_SIM_SendGenericAccessEndReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_GetPinStatus(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_IsPinOK(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_GetIMSI(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_GetGID1(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_GetGID2(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_GetHomePlmn(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_GetCurrLockedSimlockType(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_simmi_GetMasterFileId(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, APDUFileID_t file_id);
Result_t CP_CAPI2_SIM_SendOpenSocketReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_GetAtrData(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_SendRemainingPinAttemptReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_IsCachedDataReady(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_GetServiceCodeStatus(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SERVICE_CODE_STATUS_CPHS_t service_code);
Result_t CP_CAPI2_SIM_CheckCphsService(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, CPHS_SST_ENTRY_t sst_entry);
Result_t CP_CAPI2_SIM_GetCphsPhase(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_GetSmsSca(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt8 rec_no);
Result_t CP_CAPI2_SIM_GetIccid(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_IsALSEnabled(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_GetAlsDefaultLine(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_SetAlsDefaultLine(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt8 line);
Result_t CP_CAPI2_SIM_GetCallForwardUnconditionalFlag(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_GetApplicationType(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_USIM_GetUst(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_ADCMGR_Start(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt16 init_value);
Result_t CP_CAPI2_AT_ProcessCmd(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt8 channel, uchar_ptr_t cmdStr);
Result_t CP_CAPI2_MS_GetSystemRAT(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_GetSupportedRAT(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_GetSystemBand(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_GetSupportedBand(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYSPARM_GetMSClass(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_AUDIO_GetMicrophoneGainSetting(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_AUDIO_GetSpeakerVol(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_AUDIO_SetSpeakerVol(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt8 vol);
Result_t CP_CAPI2_AUDIO_SetMicrophoneGain(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt8 gain);
Result_t CP_CAPI2_SYSPARM_GetManufacturerName(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYSPARM_GetModelName(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYSPARM_GetSWVersion(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYSPARM_GetEGPRSMSClass(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_UTIL_ExtractImei(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_GetRegistrationInfo(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_SendNumOfPLMNEntryReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SIM_PLMN_FILE_t plmn_file);
Result_t CP_CAPI2_SIM_SendReadPLMNEntryReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SIM_PLMN_FILE_t plmn_file, UInt16 start_index, UInt16 end_index);
Result_t CP_CAPI2_SYS_SetRegisteredEventMask(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt16 *maskList, UInt8 maskLen);
Result_t CP_CAPI2_SYS_SetFilteredEventMask(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt16 *maskList, UInt8 maskLen, SysFilterEnable_t enableFlag);
Result_t CP_CAPI2_SYS_SetRssiThreshold(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt8 gsm_rxlev_thresold, UInt8 gsm_rxqual_thresold, UInt8 umts_rscp_thresold, UInt8 umts_ecio_thresold);
Result_t CP_CAPI2_SYS_GetBootLoaderVersion(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYS_GetDSFVersion(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYSPARM_GetChanMode(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYSPARM_GetClassmark(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYSPARM_GetIMEI(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYSPARM_GetSysparmIndPartFileVersion(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYSPARM_SetDARPCfg(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt8 darp_cfg);
Result_t CP_CAPI2_SYSPARM_SetEGPRSMSClass(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt16 egprs_class);
Result_t CP_CAPI2_SYSPARM_SetGPRSMSClass(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt16 gprs_class);
Result_t CP_CAPI2_SYS_SetMSPowerOnCause(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt8 reset_cause);
Result_t CP_CAPI2_TIMEZONE_DeleteNetworkName(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_TIMEZONE_GetTZUpdateMode(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_TIMEZONE_SetTZUpdateMode(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, TimeZoneUpdateMode_t mode);
Result_t CP_CAPI2_TIMEZONE_UpdateRTC(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, Boolean updateFlag);
Result_t CP_CAPI2_TestCmds(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt32 testId, UInt32 param1, UInt32 param2, uchar_ptr_t buffer);
Result_t CP_CAPI2_SATK_SendPlayToneRes(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SATK_ResultCode_t resultCode);
Result_t CP_CAPI2_SATK_SendSetupCallRes(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SATK_ResultCode_t resultCode);
Result_t CP_CAPI2_PBK_SetFdnCheck(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, Boolean fdn_chk_on);
Result_t CP_CAPI2_PBK_GetFdnCheck(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_PMU_BattADCReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_PMU_Battery_Register(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, HAL_EM_BATTMGR_Event_en_t event);
Result_t CP_CAPI2_SMS_SendMemAvailInd(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SMS_ConfigureMEStorage(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, Boolean flag);
Result_t CP_CAPI2_MS_SetElement(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, CAPI2_MS_Element_t *inElemData);
Result_t CP_CAPI2_MS_GetElement(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, MS_Element_t inElemType);
Result_t CP_CAPI2_USIM_IsApplicationSupported(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, USIM_APPLICATION_TYPE appli_type);
Result_t CP_CAPI2_USIM_IsAllowedAPN(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, char_ptr_t apn_name);
Result_t CP_CAPI2_USIM_GetNumOfAPN(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_USIM_GetAPNEntry(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt8 index);
Result_t CP_CAPI2_USIM_IsEstServActivated(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, USIM_EST_SERVICE_t est_serv);
Result_t CP_CAPI2_USIM_SendSetEstServReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, USIM_EST_SERVICE_t est_serv, Boolean serv_on);
Result_t CP_CAPI2_USIM_SendWriteAPNReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt8 index, char_ptr_t apn_name);
Result_t CP_CAPI2_USIM_SendDeleteAllAPNReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_USIM_GetRatModeSetting(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_GetGPRSRegState(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_GetGSMRegState(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_GetRegisteredCellInfo(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_GetStartBand(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_SetMEPowerClass(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt8 band, UInt8 pwrClass);
Result_t CP_CAPI2_USIM_GetServiceStatus(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SIMService_t service);
Result_t CP_CAPI2_SIM_IsAllowedAPN(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, char_ptr_t apn_name);
Result_t CP_CAPI2_SMS_GetSmsMaxCapacity(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SmsStorage_t storageType);
Result_t CP_CAPI2_SMS_RetrieveMaxCBChnlLength(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_IsBdnOperationRestricted(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_SendPreferredPlmnUpdateInd(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SIM_PLMN_FILE_t prefer_plmn_file);
Result_t CP_CAPI2_SIM_Deactive(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_SendSetBdnReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SIMBdnOperState_t oper_state, CHVString_t chv2);
Result_t CP_CAPI2_SIM_PowerOnOffCard(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, Boolean power_on, SIM_POWER_ON_MODE_t mode);
Result_t CP_CAPI2_SIM_GetRawAtr(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_Set_Protocol(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt8 protocol);
Result_t CP_CAPI2_SIM_Get_Protocol(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_TerminateXferApdu(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_SetPlmnSelectRat(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt8 manual_rat);
Result_t CP_CAPI2_MS_IsDeRegisterInProgress(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_IsRegisterInProgress(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SOCKET_SignalInd(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SocketSignalInd_t *sockSignalInd);
Result_t CP_CAPI2_DC_ReportCallStatusInd(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, DC_ReportCallStatus_t *status);
Result_t CP_CAPI2_PBK_SendUsimHdkReadReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_PBK_SendUsimHdkUpdateReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, HDKString_t hidden_key);
Result_t CP_CAPI2_PBK_SendUsimAasReadReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt16 index, PBK_Id_t pbk_id);
Result_t CP_CAPI2_PBK_SendUsimAasUpdateReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt16 index, PBK_Id_t pbk_id, ALPHA_CODING_t alpha_coding, UInt8 alpha_size, uchar_ptr_t alpha);
Result_t CP_CAPI2_PBK_SendUsimGasReadReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt16 index, PBK_Id_t pbk_id);
Result_t CP_CAPI2_PBK_SendUsimGasUpdateReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt16 index, PBK_Id_t pbk_id, ALPHA_CODING_t alpha_coding, UInt8 alpha_size, uchar_ptr_t alpha);
Result_t CP_CAPI2_PBK_SendUsimAasInfoReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, PBK_Id_t pbk_id);
Result_t CP_CAPI2_PBK_SendUsimGasInfoReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, PBK_Id_t pbk_id);
Result_t CP_CAPI2_LCS_ServiceControl(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, LcsServiceType_t inServiceType);
Result_t CP_CAPI2_LCS_PowerConfig(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, LcsPowerState_t inPowerSate);
Result_t CP_CAPI2_LCS_ServiceQuery(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_LCS_StopPosReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, LcsHandle_t inLcsHandle);
Result_t CP_CAPI2_LCS_GetPosition(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_LCS_ConfigSet(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt32 configId, UInt32 value);
Result_t CP_CAPI2_LCS_ConfigGet(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt32 configId);
Result_t CP_CAPI2_LCS_SuplVerificationRsp(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, LcsSuplSessionHdl_t inSessionHdl, Boolean inIsAllowed);
Result_t CP_CAPI2_LCS_SuplConnectRsp(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, LcsSuplSessionHdl_t inSessionHdl, LcsSuplConnectHdl_t inConnectHdl);
Result_t CP_CAPI2_LCS_SuplDisconnected(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, LcsSuplSessionHdl_t inSessionHdl, LcsSuplConnectHdl_t inConnectHdl);
Result_t CP_CAPI2_LCS_CmdData(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, CAPI2_LcsCmdData_t inCmdData);
Result_t CP_CAPI2_AUDIO_ASIC_SetAudioMode(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, AudioMode_t mode);
Result_t CP_CAPI2_SPEAKER_StartTone(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SpeakerTone_t tone, UInt8 duration);
Result_t CP_CAPI2_SPEAKER_StartGenericTone(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, Boolean superimpose, UInt16 tone_duration, UInt16 f1, UInt16 f2, UInt16 f3);
Result_t CP_CAPI2_SPEAKER_StopTone(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_AUDIO_Turn_EC_NS_OnOff(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, Boolean ec_on_off, Boolean ns_on_off);
Result_t CP_CAPI2_ECHO_SetDigitalTxGain(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, int16_t digital_gain_step);
Result_t CP_CAPI2_RIPCMDQ_Connect_Uplink(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, Boolean Uplink);
Result_t CP_CAPI2_RIPCMDQ_Connect_Downlink(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, Boolean Downlink);
Result_t CP_CAPI2_VOLUMECTRL_SetBasebandVolume(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt8 level, UInt8 chnl, UInt16 *audio_atten, UInt8 extid);
Result_t CP_CAPI2_DIAG_ApiMeasurmentReportReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, Boolean inPeriodicReport, UInt32 inTimeInterval);
Result_t CP_CAPI2_PMU_BattChargingNotification(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, HAL_EM_BATTMGR_Charger_t chargeType, HAL_EM_BATTMGR_Charger_InOut_t inOut, UInt8 status);
Result_t CP_CAPI2_PATCH_GetRevision(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_InitCallCfg(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_InitFaxConfig(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_InitVideoCallCfg(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_MS_InitCallCfgAmpF(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_PMU_BattFullInd(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_AUDIO_GetSettings(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt8 audioMode);
Result_t CP_CAPI2_SIMLOCK_SetStatus(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, SIMLOCK_STATE_t *simlock_state);
Result_t CP_CAPI2_SYSPARM_GetActualLowVoltReading(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYSPARM_GetActual4p2VoltReading(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_program_equalizer(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, Int32 equalizer);
Result_t CP_CAPI2_program_poly_equalizer(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, Int32 equalizer);
Result_t CP_CAPI2_program_FIR_IIR_filter(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt16 audio_mode);
Result_t CP_CAPI2_program_poly_FIR_IIR_filter(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt16 audio_mode);
Result_t CP_CAPI2_audio_control_generic(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt32 param1, UInt32 param2, UInt32 param3, UInt32 param4);
Result_t CP_CAPI2_audio_control_dsp(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt32 param1, UInt32 param2, UInt32 param3, UInt32 param4);
Result_t CP_CAPI2_DIAG_ApiCellLockReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, Boolean cell_lockEnable);
Result_t CP_CAPI2_DIAG_ApiCellLockStatus(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_LCS_RegisterRrlpDataHandler(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, LcsClientInfo_t inRrlpHandler);
Result_t CP_CAPI2_LCS_RegisterRrcDataHandler(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, LcsClientInfo_t inRrcHandler);
Result_t CP_CAPI2_CC_IsThereEmergencyCall(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYSPARM_GetBattLowThresh(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYSPARM_GetDefault4p2VoltReading(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_L1_bb_isLocked(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, Boolean watch);
Result_t CP_CAPI2_MS_ForcePsReleaseReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYS_ProcessNoRfOnlyChgReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYSPARM_GetGPIO_Value(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYS_EnableCellInfoMsg(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, Boolean inEnableCellInfoMsg);
Result_t CP_CAPI2_SYSPARM_SetHSDPAPHYCategory(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt32 inHsdpaPhyCat);
Result_t CP_CAPI2_SYSPARM_GetHSDPAPHYCategory(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SMS_StartMultiSmsTransferReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SMS_StopMultiSmsTransferReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SIM_SendWriteSmsReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt16 rec_no, UInt8 tp_pid, SIMSMSMesg_t *p_sms_mesg);
Result_t CP_CAPI2_BATTMGR_GetChargingStatus(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_BATTMGR_GetPercentageLevel(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_BATTMGR_IsBatteryPresent(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_BATTMGR_IsChargerPlugIn(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SYSPARM_GetBattTable(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_BATTMGR_GetLevel(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID);
Result_t CP_CAPI2_SMS_WriteSMSPduToSIMRecordReq(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, UInt8 length, UInt8 *inSmsPdu, SIMSMSMesgStatus_t smsState, UInt8 rec_no);
Result_t CP_CAPI2_ADCMGR_MultiChStart(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, CAPI2_ADC_ChannelReq_t *ch);
Result_t CP_CAPI2_InterTaskMsgToCP(CAPI2_ReqRep_t* rsp, UInt32 tid, UInt8 clientID, InterTaskMsg_t *inPtrMsg);
#endif
