ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
