/****************************************************************************
*									      
* Copyright 2010 --2011 Broadcom Corporation.
*
* Unless you and Broadcom execute a separate written software license
* agreement governing use of this software, this software is licensed to you
* under the terms of the GNU General Public License version 2, available at
* http://www.broadcom.com/licenses/GPLv2.php (the "GPL").
*
*****************************************************************************/

#ifndef __ISLAND_PWR_MNGR_H__
#define __ISLAND_PWR_MNGR_H__

#include <mach/rdb/brcm_rdb_pwrmgr.h>

#ifdef CONFIG_DEBUG_FS
#include <linux/stringify.h>
#include <mach/rdb/brcm_rdb_bmdm_pwrmgr.h>
#endif


#define PWRMGR_EVENT_NEGEDGE_CONDITION_ENABLE_MASK	PWRMGR_LCDTE_EVENT_LCDTE_NEGEDGE_CONDITION_ENABLE_MASK
#define PWRMGR_EVENT_POSEDGE_CONDITION_ENABLE_MASK	PWRMGR_LCDTE_EVENT_LCDTE_POSEDGE_CONDITION_ENABLE_MASK
#define PWRMGR_EVENT_CONDITION_ACTIVE_MASK		PWRMGR_LCDTE_EVENT_LCDTE_CONDITION_ACTIVE_MASK

#ifdef CONFIG_DEBUG_FS
extern const char* _island__event2str[];
#define PWRMGR_EVENT_ID_TO_STR(e) _island__event2str[e]

#endif

enum {
    LCDTE_EVENT = 0,
	SSP3SYN_EVENT,	
	SSP3DI_EVENT,   
	SSP3CK_EVENT,
    SSP2SYN_EVENT,	
    SSP2DI_EVENT,	
    SSP2CK_EVENT,	
    SSP1SYN_EVENT,
    SSP1DI_EVENT,
    SSP1CK_EVENT,
    SSP0SYN_EVENT,
    SSP0DI_EVENT,
    SSP0CK_EVENT,
    DIGCLKREQ_EVENT,
    ANA_SYS_REQ_EVENT,
    SYSCLKREQ_EVENT,
    UBRX_EVENT,		//0X10
    UBCTSN_EVENT,
    UB2RX_EVENT,
    UB2CTSN_EVENT,
	UB3RX_EVENT,
	UB3CTSN_EVENT,
	UB4RX_EVENT,
	UB4CTSN_EVENT,
    SIMDET_EVENT,
    SIM2DET_EVENT,
    MMC0D3_EVENT,
    MMC0D1_EVENT,
    MMC1D3_EVENT,
    MMC1D1_EVENT,
    SDDAT3_EVENT,
    SDDAT1_EVENT,	
    SLB1CLK_EVENT,   //0X20
    SLB1DAT_EVENT,
    SWCLKTCK_EVENT,
    SWDIOTMS_EVENT,
    KEY_R0_EVENT,	
    KEY_R1_EVENT,
    KEY_R2_EVENT,
    KEY_R3_EVENT,
    KEY_R4_EVENT,
    KEY_R5_EVENT,
    KEY_R6_EVENT,
    KEY_R7_EVENT,
    CAWAKE_EVENT,
    CAREADY_EVENT,
    CAFLAG_EVENT,
    BATRM_EVENT,	
    USBDP_EVENT,  //0X30
    USBDN_EVENT,
    RXD0_EVENT,
    GPIO29_A_EVENT,
    GPIO32_A_EVENT,
    GPIO33_A_EVENT,
    GPIO43_A_EVENT,
    GPIO44_A_EVENT,
    GPIO45_A_EVENT,
    GPIO46_A_EVENT,	
    GPIO47_A_EVENT,
    GPIO48_A_EVENT,
    GPIO71_A_EVENT,
    GPIO72_A_EVENT,
    GPIO73_A_EVENT,
    GPIO74_A_EVENT,
    GPIO95_A_EVENT, //0X40
    GPIO96_A_EVENT,
    GPIO99_A_EVENT,
    GPIO100_A_EVENT,	
    GPIO111_A_EVENT,
    GPIO49_A_EVENT,
    GPIO141_A_EVENT,
    GPIO142_A_EVENT,
    GPIO143_A_EVENT,
    GPIO144_A_EVENT,
    GPIO156_A_EVENT,
    SPARE1_A_EVENT,
    SPARE2_A_EVENT,
    SPARE3_A_EVENT,
    SPARE4_A_EVENT,
    SPARE5_A_EVENT,
    SPARE6_A_EVENT,  //0X50
    SPARE7_A_EVENT,
    SPARE8_A_EVENT,
    SPARE9_A_EVENT,
    SPARE10_A_EVENT,
    GPIO29_B_EVENT,	
    GPIO32_B_EVENT,
    GPIO33_B_EVENT,
    GPIO43_B_EVENT,  
    GPIO44_B_EVENT,
    GPIO45_B_EVENT,
    GPIO46_B_EVENT,
    GPIO47_B_EVENT,
    GPIO48_B_EVENT,
    GPIO71_B_EVENT,
    GPIO72_B_EVENT,	
    GPIO73_B_EVENT,  //0X60
    GPIO74_B_EVENT,
    GPIO95_B_EVENT,
    GPIO96_B_EVENT,
    GPIO99_B_EVENT,
    GPIO100_B_EVENT,
    GPIO111_B_EVENT,
    GPIO49_B_EVENT,
    GPIO141_B_EVENT,
    GPIO142_B_EVENT,
    GPIO143_B_EVENT,
    GPIO144_B_EVENT,
    GPIO156_B_EVENT,
    SPARE1_B_EVENT,
    SPARE2_B_EVENT,
    SPARE3_B_EVENT,
    SPARE4_B_EVENT,  //0X70
    SPARE5_B_EVENT,
    SPARE6_B_EVENT,  
    SPARE7_B_EVENT,
    SPARE8_B_EVENT,
    SPARE9_B_EVENT,
    SPARE10_B_EVENT,
    COMMON_TIMER_0_EVENT,
    COMMON_TIMER_1_EVENT,
    COMMON_TIMER_2_EVENT,
    COMMON_TIMER_3_EVENT,
    COMMON_TIMER_4_EVENT,
    MM_TIMER_EVENT,
    COMMON_INT_TO_AC_EVENT,
    COMMON_INT_TO_MM_EVENT,
    TZCFG_INT_TO_AC_EVENT,
    DMA_REQUEST_EVENT, //0X80
    MODEM1_EVENT,
    MODEM2_EVENT,
    MODEM_UART_EVENT,
    BRIDGE_TO_AC_EVENT,
    BRIDGE_TO_MODEM_EVENT,
    VREQ_NONZERO_PI_MODEM_EVENT,
    USBOTG_EVENT,
    GPIO_EXP_IRQ_EVENT,
    DBR_IRQ_EVENT,
    ACI_EVENT,
    SOFTWARE_0_EVENT,
    SOFTWARE_1_EVENT,
    SOFTWARE_2_EVENT,
    VPM_WAKEUP_EVENT,
    ESW_WAKEUP_EVENT,
    HDMI_WAKEUP_EVENT,  //0X90
    SDIO2_CDN_EVENT,
    SDIO3_CDN_EVENT,
    ULPI1_EVENT,
    ULPI2_EVENT,   //0X94    
    
    PWR_MGR_NUM_EVENTS,
};


int island_pwr_mgr_init(void);
#endif /*__ISLAND_PWR_MNGR_H__*/
