EXTRA_CFLAGS  += -Wall -Wstrict-prototypes -Wno-trigraphs
EXTRA_CFLAGS  += -Werror
EXTRA_CFLAGS  += -Idrivers/videocore/host_support/include

obj-$(CONFIG_VC_DNFO) := vc-dnfo.o

vc-dnfo-objs := vc_dnfo.o

