/*  Copyright 2001 - 2012 Broadcom Corporation.  All rights reserved.
*
*  Unless you and Broadcom execute a separate written software license
*  agreement governing use of this software, this software is licensed to you
*  under the terms of the GNU General Public License version 2, available at
*  http://www.gnu.org/licenses/old-license/gpl-2.0.html (the "GPL").
*
*  Notwithstanding the above, under no circumstances may you combine this
*  software in any way with any other Broadcom software provided under a
*  license other than the GPL, without Broadcom's express prior written
*  consent.
*
*****************************************************************************/

#ifndef __LINUX_MFD_BCMPMU59054_REG_H_
#define __LINUX_MFD_BCMPMU59054_REG_H_

#define PMU_REG_HOSTCTRL0	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0000)

#define PMU_REG_HOSTCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0001)
#define HOSTCTRL1_SW_SHDWN      0x04

#define PMU_REG_HOSTCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0002)

#define PMU_REG_HOSTCTRL3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0003)

#define PMU_REG_HOSTCTRL4	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0004)
#define HOSTCTRL4_BB_SHDWN_DEB_MASK	0x18
#define HOSTCTRL4_BB_SHDWN_DEB_SHIFT	0x3


#define PMU_REG_HOSTCTRL5	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0005)

#define PMU_REG_HOSTCTRL6	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0006)

#define PMU_REG_HOSTCTRL7	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0007)
#define HOSTCTRL7_SW_RESTART_DLY_MASK	0x0E
#define HOSTCTRL7_SW_RESTART_DLY_SHIFT	1

#define PMU_REG_PONKEYCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0008)
#define PONKEYCTRL1_RELEASE_DEB_MASK	(7 << PONKEYCTRL1_RELEASE_DEB_SHIFT)
#define PONKEYCTRL1_RELEASE_DEB_SHIFT	3

#define PONKEYCTRL1_PRESS_DEB_MASK	0x07
#define PONKEYCTRL1_PRESS_DEB_SHIFT	0

#define PMU_REG_PONKEYCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0009)
#define PONKEY_TX_ACTION_MASK	(3 << PONKEY_TX_ACTION_SHIFT)
#define PONKEY_TX_ACTION_SHIFT	6
#define PONKEY_TX_DLY_MASK	(7 << PONKEY_TX_DLY_SHIFT)
#define PONKEY_TX_DLY_SHIFT	3
#define PONKEY_TX_DEB_MASK	(7 << PONKEY_TX_DEB_SHIFT)
#define PONKEY_TX_DEB_SHIFT	0

#define PMU_REG_PONKEYCTRL3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x000A)

#define PMU_REG_PONKEYCTRL4	ENC_PMU_REG(FIFO_MODE, MAP0, 0x000B)
#define PONKEYCTRL4_KEY_PAD_LOCK_MODE_MASK	0x40
#define PONKEYCTRL4_KEY_PAD_LOCK_MODE_SHIFT	6

#define PONKEYCTRL4_KEY_PAD_LOCK_MASK		0x20
#define PONKEYCTRL4_KEY_PAD_LOCK_SHIFT		5

#define PONKEYCTRL4_POK_RESTART_EN_MASK		0x10
#define PONKEYCTRL4_POK_RESTART_EN_SHIFT	4

#define PONKEYCTRL4_POK_WAKUP_DEB_MASK		0x07
#define PONKEYCTRL4_POK_WAKUP_DEB_SHIFT		0


#define PMU_REG_PONKEYCTRL5	ENC_PMU_REG(FIFO_MODE, MAP0, 0x000C)

#define PMU_REG_PONKEYCTRL6	ENC_PMU_REG(FIFO_MODE, MAP0, 0x000D)
#define PONKEY_SMART_RST_EN_MASK	1
#define PONKEY_SMART_RST_PWR_EN_MASK	(1 << 1)
#define PONKEY_SMART_RST_STATUS_MASK	(1 << 2)
#define PONKEY_SMART_RST_DLY_MASK	(3 << PONKEY_SMART_RST_DLY_SHIFT)
#define PONKEY_SMART_RST_DLY_SHIFT		3

#define PMU_REG_PONKEYCTRL7	ENC_PMU_REG(FIFO_MODE, MAP0, 0x000E)

#define PMU_REG_PONKEYCTRL8	ENC_PMU_REG(FIFO_MODE, MAP0, 0x000F)

#define PMU_REG_I2CCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0010)
#define I2CCTRL1_FIFOEMPTY_MASK		0x01
#define I2CCTRL1_FIFOEMPTY_SHIFT	0
#define I2CCTRL1_FIFOFULL_MASK		0x02
#define I2CCTRL1_FIFOFULL_SHIFT		0x01

#define PMU_REG_I2CCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0011)
#define I2CCTRL2_RDBLOCKEN_MASK		0x04
#define I2CCTRL2_RDBLOCKEN_SHIFT	2

#define PMU_REG_I2CCTRL3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0012)

#define PMU_REG_I2CCTRL4	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0013)

#define PMU_REG_GPIOCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0014)

#define PMU_REG_GPIOCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0015)

#define PMU_REG_GPIOCTRL3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0016)

#define PMU_REG_GPIOCTRL4	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0017)

#define PMU_REG_WRLOCKKEY	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0018)
#define WRLOCKKEY_VAL           0x38

#define PMU_REG_WRPROEN		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0019)
#define WRPROEN_DIS_WR_PRO      0x1
#define WRPROEN_DIS_WR_PRO_MASK 0x1
#define WRPROEN_DIS_WR_PRO_SHIFT	0

#define WRPROEN_PMU_UNLOCK      0x2
#define WRPROEN_PMU_UNLOCK_MASK 0x2
#define WRPROEN_PMU_UNLOCK_SHIFT        1

#define PMU_REG_PLLPMCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0x001A)

#define PMU_REG_PLLCTRL		ENC_PMU_REG(FIFO_MODE, MAP0, 0x001B)
#define PLLCTRL_PLLEN           0x02
#define PLLCTRL_PLLEN_MASK      0x02
#define PLLCTRL_PLLEN_SHIFT     1

#define PLLCTRL_AUDIO_EN        0x20
#define PLLCTRL_AUDIO_EN_MASK   0x20
#define PLLCTRL_AUDIO_EN_SHIFT  5

#define PLLCTRL_ENCLK26M        0x04
#define PLLCTRL_ENCLK26M_MASK   0x04
#define PLLCTRL_ENCLK26M_SHIFT  2

#define PMU_REG_PLLCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x001C)

#define PMU_REG_PMUGID		ENC_PMU_REG(FIFO_MODE, MAP0, 0x001D)

#define PMU_REG_PMUID		ENC_PMU_REG(FIFO_MODE, MAP0, 0x001E)

#define PMU_REG_PMUREV		ENC_PMU_REG(FIFO_MODE, MAP0, 0x001F)

#define PMU_REG_INT1		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0020)

#define PMU_REG_INT2		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0021)

#define PMU_REG_INT3		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0022)

#define PMU_REG_INT4		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0023)

#define PMU_REG_INT5		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0024)

#define PMU_REG_INT6		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0025)

#define PMU_REG_INT7		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0026)

#define PMU_REG_INT8		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0027)

#define PMU_REG_INT9		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0028)

#define PMU_REG_INT10		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0029)

#define PMU_REG_INT11		ENC_PMU_REG(FIFO_MODE, MAP0, 0x002A)

#define PMU_REG_INT12		ENC_PMU_REG(FIFO_MODE, MAP0, 0x002B)

#define PMU_REG_INT13		ENC_PMU_REG(FIFO_MODE, MAP0, 0x002C)

#define PMU_REG_INT14		ENC_PMU_REG(FIFO_MODE, MAP0, 0x002D)

#define PMU_REG_INT15		ENC_PMU_REG(FIFO_MODE, MAP0, 0x002E)

#define PMU_REG_INT16		ENC_PMU_REG(FIFO_MODE, MAP0, 0x002F)

#define PMU_REG_INT1MSK		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0030)

#define PMU_REG_INT2MSK		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0031)

#define PMU_REG_INT3MSK		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0032)

#define PMU_REG_INT4MSK		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0033)

#define PMU_REG_INT5MSK		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0034)

#define PMU_REG_INT6MSK		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0035)

#define PMU_REG_INT7MSK		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0036)

#define PMU_REG_INT8MSK		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0037)

#define PMU_REG_INT9MSK		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0038)

#define PMU_REG_INT10MSK	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0039)

#define PMU_REG_INT11MSK	ENC_PMU_REG(FIFO_MODE, MAP0, 0x003A)

#define PMU_REG_INT12MSK	ENC_PMU_REG(FIFO_MODE, MAP0, 0x003B)

#define PMU_REG_INT13MSK	ENC_PMU_REG(FIFO_MODE, MAP0, 0x003C)

#define PMU_REG_INT14MSK	ENC_PMU_REG(FIFO_MODE, MAP0, 0x003D)

#define PMU_REG_INT15MSK	ENC_PMU_REG(FIFO_MODE, MAP0, 0x003E)

#define PMU_REG_INT16MSK	ENC_PMU_REG(FIFO_MODE, MAP0, 0x003F)

#define PMU_REG_MBCCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0040)
#define MBCCTRL1_TTR_2_0_MASK		0x7
#define MBCCTRL1_TTR_2_0_SHIFT		0x7
#define MBCCTRL1_TCH_2_0_MASK		0x38
#define MBCCTRL1_TCH_2_0_SHIFT		0x3
#define MBCCTRL1_USB_CHG_PORT_SEL_MASK	0xC0
#define MBCCTRL1_USB_CHG_PORT_SEL_SHIFT	0x6

#define PMU_REG_MBCCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0041)
#define MBCCTRL2_SW_EXP_SEL_4S_MASK	0x00
#define MBCCTRL2_SW_EXP_SEL_8S_MASK	0x01
#define MBCCTRL2_SW_EXP_SEL_16S_MASK	0x10
#define MBCCTRL2_SW_EXP_SEL_32S_MASK	0x11
#define MBCCTRL2_SW_TMR_EN_MASK		0x4
#define MBCCTRL2_SW_TMR_EN_SHIFT	2
#define MBCCTRL2_SW_TMR_CLR_MASK	0x8
#define MBCCTRL2_SW_TMR_CLR_SHIFT	3

#define PMU_REG_MBCCTRL3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0042)
#define MBCCTRL3_USB_HOSTEN_MASK	0x1
#define MBCCTRL3_USB_HOSTEN_SHIFT	0
#define MBCCTRL3_HW_MC_ST_EN_MASK	0x2
#define MBCCTRL3_HW_MC_ST_EN_SHIFT	1
#define MBCCTRL3_SWUP_MASK		0x04
#define MBCCTRL3_SWUP_SHIFT		2

#define PMU_REG_MBCCTRL4	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0043)

#define PMU_REG_MBCCTRL5	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0044)
#define MBCCTRL5_CHP_TYP_MASK	0x30
#define MBCCTRL5_CHP_TYP_SHIFT	4

#define USB_DET_LDO_EN_MASK	0x04
#define USB_DET_LDO_EN_SHIFT	2

#define MBCCTRL5_BC12_EN_MASK	0x1
#define MBCCTRL5_BC12_EN_SHIFT	0

#define PMU_REG_MBCCTRL6		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0045)
#define MBCCTRL6_VFLOATMAX_MASK		0x1F
#define MBCCTRL6_VFLOATMAX_SHIFT	0
#define MBCCTRL6_VFLOATMAX_LOCK_MASK	0x20
#define MBCCTRL6_VFLOATMAX_LOCK_SHIFT	0
#define MBCCTRL6_RESERVED_MASK		0xC0
#define MBCCTRL6_RESERVED_SHIFT		6

#define PMU_REG_MBCCTRL7	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0046)
#define MBCCTRL7_VFLOAT_MASK	0x1F
#define MBCCTRL7_VFLOAT_SHIFT	0

#define PMU_REG_MBCCTRL8	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0047)

#define PMU_REG_MBCCTRL9		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0048)
#define MBCCTRL9_EOC_DET_MODE_MASK	0x1
#define MBCCTRL9_EOC_DET_MODE_SHIFT	0
#define MBCCTRL9_SW_EOC_MASK		0x2
#define MBCCTRL9_SW_EOC_SHIFT		1
#define MBCCTRL9_HW_EOC_MASK		0x4
#define MBCCTRL9_HW_EOC_SHIFT		2
#define MBCCTRL9_FG_EOC_MASK		0x8
#define MBCCTRL9_FG_EOC_SHIFT		3
#define MBCCTRL9_HW_EOC_DEB_MASK	0x70
#define MBCCTRL9_HW_EOC_DEB_SHIFT	4
#define MBCCTRL9_HW_EOC_SRT_DEB_MASK	0x80
#define MBCCTRL9_HW_EOC_SRT_DEB_SHIFT	7


#define PMU_REG_MBCCTRL10	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0049)

#define PMU_REG_MBCCTRL11	ENC_PMU_REG(FIFO_MODE, MAP0, 0x004A)

#define PMU_REG_MBCCTRL12	ENC_PMU_REG(FIFO_MODE, MAP0, 0x004B)

#define PMU_REG_MBCCTRL13	ENC_PMU_REG(FIFO_MODE, MAP0, 0x004C)

#define PMU_REG_MBCCTRL14	ENC_PMU_REG(FIFO_MODE, MAP0, 0x004D)

#define PMU_REG_MBCCTRL15	ENC_PMU_REG(FIFO_MODE, MAP0, 0x004E)

#define PMU_REG_MBCCTRL16	ENC_PMU_REG(FIFO_MODE, MAP0, 0x004F)

#define PMU_REG_MBCCTRL17	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0050)

#define PMU_REG_MBCCTRL18	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0051)

#define PMU_REG_MBCCTRL19	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0052)

#define PMU_REG_MBCCTRL20	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0053)

#define PMU_REG_MBCCTRL21	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0054)

#define PMU_REG_MBCCTRL22	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0055)

#define PMU_REG_MBCCTRL23	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0056)

#define PMU_REG_MBCCTRL24	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0057)

#define PMU_REG_MBCCTRL25	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0058)

#define PMU_REG_MBCCTRL26	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0059)

#define PMU_REG_MBCCTRL27	ENC_PMU_REG(FIFO_MODE, MAP0, 0x005A)

#define PMU_REG_MBCCTRL28	ENC_PMU_REG(FIFO_MODE, MAP0, 0x005B)

#define PMU_REG_MBCCTRL29	ENC_PMU_REG(FIFO_MODE, MAP0, 0x005C)

#define PMU_REG_MBCCTRL30	ENC_PMU_REG(FIFO_MODE, MAP0, 0x005D)
#define MBCCTRL29_MBC_CC_BOOST_MASK	0xF
#define MBCCTRL29_MBC_CC_BOOST_SHIFT	0

#define PMU_REG_MBCCTRL31	ENC_PMU_REG(FIFO_MODE, MAP0, 0x005E)

#define PMU_REG_MBCCTRL32	ENC_PMU_REG(FIFO_MODE, MAP0, 0x005F)

#define PMU_REG_RFLDOPMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0060)

#define PMU_REG_RFLDOPMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0061)

#define PMU_REG_CAMLDO1PMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0062)

#define PMU_REG_CAMLDO1PMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0063)

#define PMU_REG_CAMLDO2PMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0064)

#define PMU_REG_CAMLDO2PMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0065)

#define PMU_REG_SIMLDO1PMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0066)

#define PMU_REG_SIMLDO1PMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0067)

#define PMU_REG_SIMLDO2PMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0068)

#define PMU_REG_SIMLDO2PMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0069)

#define PMU_REG_SDLDOPMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x006A)

#define PMU_REG_SDLDOPMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x006B)

#define PMU_REG_SDXLDOPMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x006C)

#define PMU_REG_SDXLDOPMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x006D)

#define PMU_REG_MMCLDO1PMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x006E)

#define PMU_REG_MMCLDO1PMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x006F)

#define PMU_REG_MMCLDO2PMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0070)

#define PMU_REG_MMCLDO2PMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0071)

#define PMU_REG_AUDLDOPMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0072)

#define PMU_REG_AUDLDOPMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0073)

#define PMU_REG_MICLDOPMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0074)

#define PMU_REG_MICLDOPMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0075)

#define PMU_REG_USBLDOPMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0076)

#define PMU_REG_USBLDOPMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0077)

#define PMU_REG_VIBLDOPMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0078)

#define PMU_REG_VIBLDOPMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0079)

#define PMU_REG_IOSR1PMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x007A)

#define PMU_REG_IOSR1PMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x007B)

#define PMU_REG_IOSR2PMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x007C)

#define PMU_REG_IOSR2PMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x007D)

#define PMU_REG_CSRPMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x007E)

#define PMU_REG_CSRPMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x007F)

#define PMU_REG_CSRPMCTRL3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0080)

#define PMU_REG_CSRPMCTRL4	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0081)

#define PMU_REG_SDSR1PMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0082)

#define PMU_REG_SDSR1PMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0083)

#define PMU_REG_SDSR1PMCTRL3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0084)

#define PMU_REG_SDSR1PMCTRL4	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0085)

#define PMU_REG_SDSR2PMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0086)

#define PMU_REG_SDSR2PMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0087)

#define PMU_REG_SDSR2PMCTRL3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0088)

#define PMU_REG_SDSR2PMCTRL4	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0089)

#define PMU_REG_MMSRPMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x008A)

#define PMU_REG_MMSRPMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x008B)

#define PMU_REG_MMSRPMCTRL3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x008C)

#define PMU_REG_MMSRPMCTRL4	ENC_PMU_REG(FIFO_MODE, MAP0, 0x008D)

#define PMU_REG_VSRPMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x008E)

#define PMU_REG_VSRPMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x008F)

#define PMU_REG_VSRPMCTRL3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0090)

#define PMU_REG_VSRPMCTRL4	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0091)

#define PMU_REG_SRGRP1		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0092)

#define PMU_REG_SRGRP2		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0093)

#define PMU_REG_SRGRP3		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0094)

#define PMU_REG_SRGRP4		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0095)

#define PMU_REG_RFLDOCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0096)

#define PMU_REG_CAMLDO1CTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0097)

#define PMU_REG_CAMLDO2CTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0098)

#define PMU_REG_SIMLDO1CTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0099)

#define PMU_REG_SIMLDO2CTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0x009A)

#define PMU_REG_SDLDOCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0x009B)

#define PMU_REG_SDXLDOCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0x009C)

#define PMU_REG_MMCLDO1CTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0x009D)

#define PMU_REG_MMCLDO2CTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0x009E)

#define PMU_REG_AUDLDOCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0x009F)

#define PMU_REG_MICLDOCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00A0)

#define PMU_REG_USBLDOCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00A1)

#define PMU_REG_VIBLDOCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00A2)

#define PMU_REG_PWR_GRP_DLY	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00A3)
#define PWR_GRP_LDO_OVERI_SHDWN_MASK 0x80
#define PWR_GRP_LDO_OVERI_SHDWN_SHIFT 7

#define PMU_REG_SRCTRL1		ENC_PMU_REG(FIFO_MODE, MAP0, 0x00A4)

#define PMU_REG_SRCTRL2		ENC_PMU_REG(FIFO_MODE, MAP0, 0x00A5)

#define PMU_REG_SRCTRL3		ENC_PMU_REG(FIFO_MODE, MAP0, 0x00A6)

#define PMU_REG_SRCTRL4		ENC_PMU_REG(FIFO_MODE, MAP0, 0x00A7)

#define PMU_REG_SRCTRL5		ENC_PMU_REG(FIFO_MODE, MAP0, 0x00A8)

#define PMU_REG_SRCTRL6		ENC_PMU_REG(FIFO_MODE, MAP0, 0x00A9)

#define PMU_REG_SRCTRL7		ENC_PMU_REG(FIFO_MODE, MAP0, 0x00AA)

#define PMU_REG_SRCTRL8		ENC_PMU_REG(FIFO_MODE, MAP0, 0x00AB)

#define PMU_REG_SRCTRL9		ENC_PMU_REG(FIFO_MODE, MAP0, 0x00AC)

#define PMU_REG_SRCTRL10	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00AD)

#define PMU_REG_SRCTRL11	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00AE)

#define PMU_REG_SRCTRL12	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00AF)

#define PMU_REG_SRCTRL13	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00B0)

#define PMU_REG_SRCTRL14	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00B1)

#define PMU_REG_SRCTRL15	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00B2)

#define PMU_REG_SRCTRL16	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00B3)

#define PMU_REG_SRCTRL17	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00B4)

#define PMU_REG_SRCTRL18	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00B5)

#define PMU_REG_SRCTRL19	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00B6)

#define PMU_REG_SRCTRL20	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00B7)

#define PMU_REG_SRCTRL21	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00B8)

#define PMU_REG_CSRVOTRIM	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00B9)

#define PMU_REG_IOSR1VOTRIM	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00BA)

#define PMU_REG_IOSR2VOTRIM	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00BB)

#define PMU_REG_SDSR1VOTRIM	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00BC)

#define PMU_REG_SDSR2VOTRIM	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00BD)

#define PMU_REG_MMSRVOTRIM      ENC_PMU_REG(FIFO_MODE, MAP0, 0x00BE)

#define PMU_REG_VSRVOTRIM       ENC_PMU_REG(FIFO_MODE, MAP0, 0x00BF)

#define PMU_REG_CSRVOUT1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00C0)

#define PMU_REG_CSRVOUT2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00C1)

#define PMU_REG_CSRVOUT3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00C2)

#define PMU_REG_IOSR1VOUT1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00C3)

#define PMU_REG_IOSR1VOUT2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00C4)

#define PMU_REG_IOSR1VOUT3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00C5)

#define PMU_REG_IOSR2VOUT1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00C6)

#define PMU_REG_IOSR2VOUT2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00C7)

#define PMU_REG_IOSR2VOUT3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00C8)

#define PMU_REG_MMSRVOUT1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00C9)

#define PMU_REG_MMSRVOUT2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00CA)

#define PMU_REG_MMSRVOUT3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00CB)

#define PMU_REG_SDSR1VOUT1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00CC)

#define PMU_REG_SDSR1VOUT2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00CD)

#define PMU_REG_SDSR1VOUT3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00CE)

#define PMU_REG_SDSR2VOUT1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00CF)
#define PMU_REG_SDSR2VOUT2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00D0)
#define PMU_REG_SDSR2VOUT3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00D1)

#define PMU_REG_VSRVOUT1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00D2)
#define PMU_REG_VSRVOUT2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00D3)
#define PMU_REG_VSRVOUT3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x00D4)


/* PAGE0 MAP1 */
#define PMU_REG_PWMLEDCTRL1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0000)

#define PMU_REG_PWMLEDCTRL2	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0001)

#define PMU_REG_PWMLEDCTRL3	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0002)

#define PMU_REG_PWMLEDCTRL4	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0003)

#define PMU_REG_PWMLEDCTRL5	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0004)

#define PMU_REG_PWMLEDCTRL6	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0005)

#define PMU_REG_PWMLEDCTRL7	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0006)

#define PMU_REG_PWMLEDCTRL8	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0007)

#define PMU_REG_PASRCTRL1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0008)

#define PMU_REG_PASRCTRL2	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0009)

#define PMU_REG_PASRCTRL3	ENC_PMU_REG(FIFO_MODE, MAP1, 0x000a)

#define PMU_REG_PASRCTRL4	ENC_PMU_REG(FIFO_MODE, MAP1, 0x000b)

#define PMU_REG_PASRCTRL5	ENC_PMU_REG(FIFO_MODE, MAP1, 0x000c)

#define PMU_REG_PASRCTRL6	ENC_PMU_REG(FIFO_MODE, MAP1, 0x000d)

#define PMU_REG_PASRCTRL7	ENC_PMU_REG(FIFO_MODE, MAP1, 0x000e)

#define PMU_REG_PASRCTRL8	ENC_PMU_REG(FIFO_MODE, MAP1, 0x000f)

/* PMU MIPI */
#define PMU_REG_LVLDO1PMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0016)
#define PMU_REG_LVLDO1PMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0017)
#define PMU_REG_LVLDO2PMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0018)
#define PMU_REG_LVLDO2PMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0019)
#define PMU_REG_GPLDO1CTRL	ENC_PMU_REG(FIFO_MODE, MAP1, 0x001A)
#define PMU_REG_GPLDO2CTRL	ENC_PMU_REG(FIFO_MODE, MAP1, 0x001B)
#define PMU_REG_GPLDO3CTRL	ENC_PMU_REG(FIFO_MODE, MAP1, 0x001C)
#define PMU_REG_TCXLDOCTRL	ENC_PMU_REG(FIFO_MODE, MAP1, 0x001D)
#define PMU_REG_LVLDO1CTRL	ENC_PMU_REG(FIFO_MODE, MAP1, 0x001E)
#define PMU_REG_LVLDO2CTRL	ENC_PMU_REG(FIFO_MODE, MAP1, 0x001F)

#define PMU_REG_ADCCTRL1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0020)
#define PMU_REG_ADCCTRL2	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0021)
/* VMBAT*/
#define PMU_REG_ADCCTRL3	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0022)
#define PMU_REG_ADCCTRL4	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0023)
/* VBBAT */
#define PMU_REG_ADCCTRL5	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0024)
#define PMU_REG_ADCCTRL6	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0025)
/* Reserved */
#define PMU_REG_ADCCTRL7	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0026)
#define PMU_REG_ADCCTRL8	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0027)
/* VBUS */
#define PMU_REG_ADCCTRL9	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0028)
#define PMU_REG_ADCCTRL10	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0029)
/* IDIN */
#define PMU_REG_ADCCTRL11	ENC_PMU_REG(FIFO_MODE, MAP1, 0x002A)
#define PMU_REG_ADCCTRL12	ENC_PMU_REG(FIFO_MODE, MAP1, 0x002B)
/* NTC */
#define PMU_REG_ADCCTRL13	ENC_PMU_REG(FIFO_MODE, MAP1, 0x002C)
#define PMU_REG_ADCCTRL14	ENC_PMU_REG(FIFO_MODE, MAP1, 0x002D)
/* BSI */
#define PMU_REG_ADCCTRL15	ENC_PMU_REG(FIFO_MODE, MAP1, 0x002E)
#define PMU_REG_ADCCTRL16	ENC_PMU_REG(FIFO_MODE, MAP1, 0x002F)
/* BOM */
#define PMU_REG_ADCCTRL17	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0030)
#define PMU_REG_ADCCTRL18	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0031)
/* 32KTEMP */
#define PMU_REG_ADCCTRL19	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0032)
#define PMU_REG_ADCCTRL20	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0033)
/* PATEMP */
#define PMU_REG_ADCCTRL21	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0034)
#define PMU_REG_ADCCTRL22	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0035)
/* ALS */
#define PMU_REG_ADCCTRL23	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0036)
#define PMU_REG_ADCCTRL24	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0037)
/* DIE TEMP */
#define PMU_REG_ADCCTRL25	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0038)
#define PMU_REG_ADCCTRL26	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0039)
/* RTM */
#define PMU_REG_ADCCTRL27	ENC_PMU_REG(FIFO_MODE, MAP1, 0x003A)
#define PMU_REG_ADCCTRL28	ENC_PMU_REG(FIFO_MODE, MAP1, 0x003B)

#define PMU_REG_ADCCTRL29	ENC_PMU_REG(FIFO_MODE, MAP1, 0x003C)
#define PMU_REG_ADCCTRL30	ENC_PMU_REG(FIFO_MODE, MAP1, 0x003D)

#define ADC_READ_LEN		2
#define ADC_READ_INVALID	0x04
#define ADC_MSB_DATA		0x3
#define ADC_MSB_SHIFT		8

#define ADC_RTM_CHANN_SHIFT		4
#define ADC_RTM_CONV_ENABLE		0
#define ADC_RTM_CONV_DISABLE		1
#define ADC_RTM_CONVERSION_SHIFT	3
#define ADC_RTM_START			1
#define ADC_RTM_START_SHIFT		2
#define ADC_RTM_MAX_RST_CNT_1	0
#define ADC_RTM_MAX_RST_CNT_3	1
#define ADC_RTM_MAX_RST_CNT_5	2
#define ADC_RTM_MAX_RST_CNT_7	3
#define ADC_RTM_SLEEP			5
#define ADC_RTM_DATA_READY		1
#define ADC_RTM_MAX_POLL		5

#define ADC_RTM_START_DELAY_MASK	0x1F
#define ADC_RTM_START_DELAY_SHIFT	0
#define ADC_RTM_START_DELAY_MAX		0x1F
#define ADC_RTM_START_DELAY_MIN		0

#define PMU_REG_OTGCTRL1        ENC_PMU_REG(FIFO_MODE, MAP1, 0x0040)

#define OTGCTRL1_EN_VBUS_PULSE_MASK     0x01
#define OTGCTRL1_EN_VBUS_PULSE_SHIFT    0

#define OTGCTRL1_EN_PD_SRP_MASK         0x02
#define OTGCTRL1_EN_PD_SRP_SHIFT        1

#define OTGCTRL1_OFFVBUSB_MASK          0x04
#define OTGCTRL1_OFFVBUSB_SHIFT         2

#define OTGCTRL1_ID_DET_EN_MASK         0x08
#define OTGCTRL1_ID_DET_EN_SHIFT        3

#define OTGCTRL1_EN_SESS_VALID_MASK     0x10
#define OTGCTRL1_EN_SESS_VALID_SHIFT    4

#define OTGCTRL1_EN_VBUS_RBUS_MASK      0x20
#define OTGCTRL1_EN_VBUS_RBUS_SHIFT     5

#define OTGCTRL1_OTG_SHUTDOWNB_MASK     0x40
#define OTGCTRL1_OTG_SHUTDOWNB_SHIFT    6

#define OTGCTRL1_EN_SRP_COMPS_MASK      0x80
#define OTGCTRL1_EN_SRP_COMPS_SHIFT     7

#define PMU_REG_OTGCTRL2	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0041)
#define OTGCTRL2_VBUS_ADP_COMP_DB_MASK	0x03
#define OTGCTRL2_VBUS_ADP_COMP_DB_SHIFT	0

#define OTGCTRL2_VBUS_ADP_RBUS_SEL_MASK	0x04
#define OTGCTRL2_VBUS_ADP_RBUS_SEL_SHIFT	2

#define OTGCTRL2_ADP_PRB_CYCLE_TIME_MASK	0x08
#define OTGCTRL2_ADP_PRB_CYCLE_TIME_SHIFT	3

#define OTGCTRL2_ADP_SNS_MASK   0x10
#define OTGCTRL2_ADP_SNS_SHIFT  4

#define PMU_REG_OTGCTRL3	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0042)

#define PMU_REG_OTGCTRL4	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0043)

#define PMU_REG_OTGCTRL5	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0044)

#define PMU_REG_OTGCTRL6	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0045)

#define PMU_REG_OTGCTRL7	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0046)

#define PMU_REG_OTGCTRL8	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0047)

#define PMU_REG_OTGCTRL9	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0048)

#define PMU_REG_OTGCTRL10	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0049)

#define PMU_REG_OTGCTRL11	ENC_PMU_REG(FIFO_MODE, MAP1, 0x004A)
#define OTGCTRL11_ADP_PRB_MASK  0x01
#define OTGCTRL11_ADP_PRB_SHIFT 0

#define OTGCTRL11_ADP_PRB_MODE_MASK     0x06
#define OTGCTRL11_ADP_PRB_MODE_SHIFT    1

#define PMU_REG_OTGCTRL12	ENC_PMU_REG(FIFO_MODE, MAP1, 0x004B)
#define OTGCTRL12_EN_ADP_PRB_COMPS_MASK         0x01
#define OTGCTRL12_EN_ADP_PRB_COMPS_SHIFT        0

#define OTGCTRL12_EN_ADP_SNS_COMP_MASK  0x02
#define OTGCTRL12_EN_ADP_SNS_COMP_SHIFT 1

#define OTGCTRL12_ADP_SHUTDOWNB_MASK    0x08
#define OTGCTRL12_ADP_SHUTDOWNB_SHIFT   3

#define OTGCTRL12_ADP_COMP_METHOD_MASK  0x60
#define OTGCTRL12_ADP_COMP_METHOD_SHIFT 5

#define OTGCTRL12_ADP_THR_CTRL_MASK     0x80
#define OTGCTRL12_ADP_THR_CTRL_SHIFT    7

#define OTG_BOOSTCTRL1		ENC_PMU_REG(FIFO_MODE, MAP1, 0x4c)

#define OTG_BOOSTCTRL2		ENC_PMU_REG(FIFO_MODE, MAP1, 0x4d)

#define OTG_BOOSTCTRL3		ENC_PMU_REG(FIFO_MODE, MAP1, 0x4e)
#define PMU_REG_OTG_BOOSTCTRL3		ENC_PMU_REG(FIFO_MODE, MAP1, 0x4e)
#define ACLD_ENABLE_MASK		0x10
#define ACLD_ENABLE_SHIFT		4

#define OTG_BOOSTCTRL4		ENC_PMU_REG(FIFO_MODE, MAP1, 0x4f)

#define PMU_REG_OTG_STS1        ENC_PMU_REG(FIFO_MODE, MAP1, 0x0050)
#define OTG_STS1_ADP_ATTACH_DET_MASK    0x08
#define OTG_STS1_ADP_ATTACH_DET_SHIFT   3

#define OTG_STS1_ADP_SNS_DET_MASK       0x10
#define OTG_STS1_ADP_SNS_DET_SHIFT      4

#define PMU_REG_OTG_STS2        ENC_PMU_REG(FIFO_MODE, MAP1, 0x0051)

#define PMU_REG_OTG_STS3        ENC_PMU_REG(FIFO_MODE, MAP1, 0x0052)

#define PMU_REG_OTG_STS4        ENC_PMU_REG(FIFO_MODE, MAP1, 0x0053)

#define PMU_REG_OTG_STS5        ENC_PMU_REG(FIFO_MODE, MAP1, 0x0054)

#define PMU_REG_OTG_STS6        ENC_PMU_REG(FIFO_MODE, MAP1, 0x0055)

#define PMU_REG_OTGCTRL13	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0056)

#define PMU_REG_GPLDO1PMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0057)

#define PMU_REG_GPLDO1PMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0058)

#define PMU_REG_GPLDO2PMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0059)

#define PMU_REG_GPLDO2PMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP1, 0x005A)

#define PMU_REG_GPLDO3PMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x005B)

#define PMU_REG_GPLDO3PMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP1, 0x005C)

#define PMU_REG_TCXLDOPMCTRL1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x005D)

#define PMU_REG_TCXLDOPMCTRL2	ENC_PMU_REG(FIFO_MODE, MAP1, 0x005E)

#define PMU_REG_IHFTOP          ENC_PMU_REG(FIFO_MODE, MAP1, 0x60)
#define IHFTOP_IHF_IDDQ                 0x1
#define IHFTOP_IHF_IDDQ_MASK            0x1
#define IHFTOP_IHF_IDDQ_SHIFT           0


#define PMU_REG_IHFCLK          ENC_PMU_REG(FIFO_MODE, MAP1, 0x61)
#define IHFCLK_IHFBIASEN                0x04
#define IHFCLK_IHFBIASEN_MASK           0x04
#define IHFCLK_IHFBIASEN_SHIFT          2
#define IHFCLK_PUP                      0x08
#define IHFCLK_PUP_MASK                 0x08
#define IHFCLK_PUP_SHIFT                3

#define PMU_REG_IHFLDO          ENC_PMU_REG(FIFO_MODE, MAP1, 0x62)
#define IHFLDO_PUP                      0x1
#define IHFLDO_PUP_MASK                 0x1
#define IHFLDO_PUP_SHIFT                0

#define PMU_REG_IHFPOP          ENC_PMU_REG(FIFO_MODE, MAP1, 0x63)
#define IHFPOP_TIMECTL_MASK     0x03
#define IHFPOP_TIMECTL_SHIFT    0

#define IHFPOP_PUP              0x08
#define IHFPOP_PUP_MASK         0x08
#define IHFPOP_PUP_SHIFT        4

#define IHFPOP_EN               0x04
#define IHFPOP_EN_MASK          0x04
#define IHFPOP_EN_SHIFT         2

#define IHFPOP_BYPASS           0x20
#define IHFPOP_BYPASS_MASK      0x20
#define IHFPOP_BYPASS_SHIFT     4

#define IHFAUTO_SEQ             0x40
#define IHFAUTO_SEQ_MASK        0x40
#define IHFAUTO_SEQ_SHIFT       6

#define PMU_REG_IHFRCCAL        ENC_PMU_REG(FIFO_MODE, MAP1, 0x64)
#define IHFRCCAL_PUP            0x01
#define IHFRCCAL_PUP_MASK       0x01
#define IHFRCCAL_PUP_SHIFT      1

#define PMU_REG_IHFPSR1         ENC_PMU_REG(FIFO_MODE, MAP1, 0x65)
#define IHFPSR1_PSRCAL_PUP      0x01
#define IHFPSR1_PSRCAL_PUP_MASK 0x01
#define IHFPSR1_PSRCAL_PUP_SHIFT        0

#define PMU_REG_IHFFF           ENC_PMU_REG(FIFO_MODE, MAP1, 0x68)
#define IHFFF_PUP               0x01
#define IHFFF_PUP_MASK          0x01
#define IHFFF_PUP_SHIFT         0

#define PMU_REG_IHFALC1         ENC_PMU_REG(FIFO_MODE, MAP1, 0x69)
#define IHFALC1_IHFALC_BYP      0x04
#define IHFALC1_IHFALC_BYP_MASK 0x04
#define IHFALC1_IHFALC_BYP_SHIFT        2

#define IHFALC1_BYP             0x04
#define IHFALC1_BYP_MASK        0x04
#define IHFALC1_BYP_SHIFT       2

#define IHF_ALC_PUP_MASK	0x1
#define IHF_ALC_PUP_SHIFT	0

#define IHF_ALC_HISPEED         0x2

#define IHF_ALC_VBAT_REF_MASK	0x8
#define IHF_ALC_VBAT_REF_SHIFT	3

#define PMU_REG_IHFALC2	ENC_PMU_REG(FIFO_MODE, MAP1, 0x6A)

#define IHFALC2_THLD_MASK	0xF0
#define IHFALC2_THLD_SHIFT	4

#define	IHFALC2_RAMP_UP_CTRL_MASK	0xC
#define	IHFALC2_RAMP_UP_CTRL_SHIFT	2

#define	IHFALC2_RAMP_DOWN_CTRL_MASK	0x3
#define	IHFALC2_RAMP_DOWN_CTRL_SHIFT	0

#define PMU_REG_IHFRAMP         ENC_PMU_REG(FIFO_MODE, MAP1, 0x6C)
#define IHFRAMP_PUP             0x1
#define IHFRAMP_PUP_MASK        0x1
#define IHFRAMP_PUP_SHIFT       0

#define IHFRAMP_IHFCAL_SEL      0x10
#define IHFRAMP_IHFCAL_SEL_MASK 0x10
#define IHFRAMP_IHFCAL_SEL_SHIFT        4

#define IHFRAMP_DRVCLAMP_DIS    0x08
#define IHFRAMP_DRVCLAMP_DIS_MASK       0x08
#define IHFRAMP_DRVCLAMP_DIS_SHIFT      3

#define PMU_REG_HIGH_GAIN_MODE  ENC_PMU_REG(FIFO_MODE, MAP1, 0x6D)
#define IHFPGA1_6DBGAIN_SHIFT           0x08
#define IHFPGA1_6DBGAIN_SHIFT_MASK      0x08
#define IHFPGA1_6DBGAIN_SHIFT_SHIFT     3

#define PMU_REG_IHFPGA2_GAIN    ENC_PMU_REG(FIFO_MODE, MAP1, 0x6E)
#define IHFPGA2_MUTE            0
#define IHFPGA2_GAIN_SHIFT      0
#define IHFPGA2_GAIN_MASK       0x3F
#define IHFPGA2_MUX_MODE_MASK   0xC0
#define IHFPGA2_MUX_MODE_SHIFT  6
#define IHFPGA2_MUX_MODE_PADS_ONLY      0x00
#define IHFPGA2_MUX_MODE_PADS_MUX       0x01
#define IHFPGA2_MUX_MODE_DIS_PADS_MUX   0x10
#define IHFPGA2_MUX_MODE_MUX_ONLY       0x11

#define PMU_REG_IHFLF           ENC_PMU_REG(FIFO_MODE, MAP1, 0x6F)
#define IHFLF_PUP               1
#define IHFLF_PUP_MASK          0x1
#define IHFLF_PUP_SHIFT         0


#define PMU_REG_IHFCMPPD        ENC_PMU_REG(FIFO_MODE, MAP1, 0x70)
#define IHFCMPPD_PUP            1
#define IHFCMPPD_PUP_MASK       0x1
#define IHFCMPPD_PUP_SHIFT      0

#define PMU_REG_IHFPWRDRV       ENC_PMU_REG(FIFO_MODE, MAP1, 0x71)
#define IHFPWRDRV_PUP           1
#define IHFPWRDRV_PUP_MASK      0x1
#define IHFPWRDRV_PUP_SHIFT     0

#define PMU_REG_IHFFB           ENC_PMU_REG(FIFO_MODE, MAP1, 0x72)
#define IHFFB_PUP               1
#define IHFFB_PUP_MASK          0x1
#define IHFFB_PUP_SHIFT         0

#define PMU_REG_IHF_NGTHRESH    ENC_PMU_REG(FIFO_MODE, MAP1, 0x7A)
#define IHF_NGTHRESH_THLD_MASK  0x07
#define IHF_NGTHRESH_THLD_SHIFT 0

#define PMU_REG_IHF_NGMISC      ENC_PMU_REG(FIFO_MODE, MAP1, 0x7B)
#define NGMISC_IHFNG_PUP_EN_IHFNG       0x08
#define NGMISC_IHFNG_PUP_MASK   0x08
#define NGMISC_IHFNG_PUP_SHIFT  3

#define PMU_REG_IHF_HS_TST      ENC_PMU_REG(FIFO_MODE, MAP1, 0x7C)
#define HS_SC_EDISABLE      0x02
#define HS_SC_EDISABLE_MASK 0x02
#define HS_SC_EDISABLE_SHIFT        1

#define IHF_SC_EDISABLE         0x04
#define IHF_SC_EDISABLE_MASK    0x04
#define IHF_SC_EDISABLE_SHIFT   2

#define PMU_REG_HSCP1           ENC_PMU_REG(FIFO_MODE, MAP1, 0x80)

#define PMU_REG_HSCP2           ENC_PMU_REG(FIFO_MODE, MAP1, 0x81)

#define PMU_REG_HSCP3           ENC_PMU_REG(FIFO_MODE, MAP1, 0x82)

#define PMU_REG_HSDRV           ENC_PMU_REG(FIFO_MODE, MAP1, 0x83)
#define HSDRV_DISSC             0x10
#define HSDRV_DISSC_MASK        0x10
#define HSDRV_DISSC_SHIFT       4

#define PMU_REG_HSPGA1          ENC_PMU_REG(FIFO_MODE, MAP1, 0x86)

#define PMU_REG_HSPGA2          ENC_PMU_REG(FIFO_MODE, MAP1, 0x87)

#define PMU_REG_HSPGA3          ENC_PMU_REG(FIFO_MODE, MAP1, 0x88)
#define HSPGA3_RAMUP_DIS	0x80
#define HSPGA3_RAMUP_DIS_MASK	0x80
#define HSPGA3_RAMUP_DIS_SHIFT	7

#define PMU_REG_HSPUP1          ENC_PMU_REG(FIFO_MODE, MAP1, 0x8A)
#define HSPUP1_IDDQ_PWRDN       0x10
#define HSPUP1_IDDQ_PWRDN_MASK  0x10
#define HSPUP1_IDDQ_PWRDN_SHIFT 4

#define HSPUP1_CP_CG_SEL        0x04
#define HSPUP1_CP_CG_SEL_MASK   0x04
#define HSPUP1_CP_CG_SEL_SHIFT  2

#define PMU_REG_HSPUP2          ENC_PMU_REG(FIFO_MODE, MAP1, 0x8B)
#define HSPUP2_HS_PWRUP         0x40
#define HSPUP2_HS_PWRUP_MASK    0x40
#define HSPUP2_HS_PWRUP_SHIFT   6

#define PMU_REG_FGCTRL1		ENC_PMU_REG(FIFO_MODE, MAP1, 0x00A0)
#define FGCTRL1_FGHOSTEN_MASK		0x1
#define FGCTRL1_FGHOSTEN_SHIFT		0
#define FGCTRL1_FGCHP_MASK		0x2
#define FGCTRL1_FGCHP_SHIFT		1
#define FGCTRL1_FGOVLP_MASK		0x4
#define FGCTRL1_FGOVLP_SHIFT		2
#define FGCTRL1_FGCHPDIV_MASK		0x38
#define FGCTRL1_FGCHPDIV_SHIFT		3
#define FGCTRL1_FGSYNCMODE_MASK		0x40
#define FGCTRL1_FGSYNCMODE_SHIFT	6
#define FGCTRL1_FGMODON_MASK		0x80
#define FGCTRL1_FGMODON_SHIFT		7

#define PMU_REG_FGCTRL2		ENC_PMU_REG(FIFO_MODE, MAP1, 0x00A1)
#define FGCTRL2_FGTRIM_MASK		0x1
#define FGCTRL2_FGTRIM_SHIFT		0
#define FGCTRL2_FGCAL_MASK		0x2
#define FGCTRL2_FGCAL_SHIFT		1
#define FGCTRL2_LONGCAL_MASK		0x4
#define FGCTRL2_LONGCAL_SHIFT		2
#define FGCTRL2_FG1PTCAL_MASK		0x8
#define FGCTRL2_FG1PTCAL_SHIFT		3
#define FGCTRL2_FGRESET_MASK		0x10
#define FGCTRL2_FGRESET_SHIFT		4
#define FGCTRL2_FGFRZREAD_MASK		0x20
#define FGCTRL2_FGFRZREAD_SHIFT		5
#define FGCTRL2_FGFRZSMPL_MASK		0x40
#define FGCTRL2_FGRFZSMPL_SHIFT		6
#define FGCTRL2_FGFORCECAL_MASK		0x80
#define FGCTRL2_FGFORCECAL_SHIFT	7

#define PMU_REG_FGOPMODCTRL	ENC_PMU_REG(FIFO_MODE, MAP1, 0xA2)
#define FGOPMODCTRL_OPMODCTRL0_MASK	0x1
#define FGOPMODCTRL_OPMODCTRL0_SHIFT	0
#define FGOPMODCTRL_OPMODCTRL1_MASK	0x2
#define FGOPMODCTRL_OPMODCTRL1_SHIFT	1
#define FGOPMODCTRL_OPMODCTRL2_MASK	0x4
#define FGOPMODCTRL_OPMODCTRL2_SHIFT	2
#define FGOPMODCTRL_OPMODCTRL3_MASK	0x8
#define FGOPMODCTRL_OPMODCTRL3_SHIFT	3
#define FGOPMODCTRL_FGSYNCMODE_MASK	0x10
#define FGOPMODCTRL_FGSYNCMODE_SHIFT	4
#define FGOPMODCTRL_FGMODEON_MASK	0x20
#define FGOPMODCTRL_FGMODEON_SHIFT	5
#define FGOPMODCTRL_RESERVED_MASK	0xC0
#define FGOPMODCTRL_RESERVED_SHIFT	6

#define PMU_REG_FGOCICCTRL	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00A3)
#define FGOCICCTRL_FGCOMBRATE_MASK	0x3
#define FGOCICCTRL_FGCOMBRATE_SHIFT	0
#define FGOCICCTRL_FGSYNC_PLLOFF_MASK   0x4
#define FGOCICCTRL_FGSYNC_PLLOFF_SHIFT  2

#define PMU_REG_FGOFFSET_TRIM		ENC_PMU_REG(FIFO_MODE, MAP1, 0xA4)
#define FGOFFSET_TRIM_7_0_MASK		0xFF
#define FGOFFSET_TRIM_7_0_SHIFT		0

#define PMU_REG_FGGAIN_TRIM		ENC_PMU_REG(FIFO_MODE, MAP1, 0xA5)
#define FGGAIN_TRIM_7_0_MASK		0xFF
#define FGGAIN_TRIM_7_0_SHIFT		0

#define PMU_REG_FGACCM1			ENC_PMU_REG(FIFO_MODE, MAP1, 0xA6)
#define FGACCM1_FGACCM_25_24_MASK	0x3
#define FGACCM1_FGACCM_25_24_SHIFT	0
#define FGACCM1_RESERVED_MASK		0x7C
#define FGACCM1_RESERVED_SHIFT		2
#define FGACCM1_FGRDVALID_MASK		0x80
#define FGACCM1_FGRDVALID_SHIFT		7

#define PMU_REG_FGACCM2			ENC_PMU_REG(FIFO_MODE, MAP1, 0xA7)
#define FGACCM2_FGACCM_23_16_MASK	0xFF
#define FGACCM2_FGACCM_23_16_SHIFT	0

#define PMU_REG_FGACCM3			ENC_PMU_REG(FIFO_MODE, MAP1, 0xA8)
#define FGACCM3_FGACCM_15_8_MASK	0xFF
#define FGACCM3_FGACCM_15_8_SHIFT	0

#define PMU_REG_FGACC4			ENC_PMU_REG(FIFO_MODE, MAP1, 0xA9)
#define FGACCM4_FGACCM_7_0_MASK		0xFF
#define FGACCM4_FGACCM_7_0_SHIFT	0

#define PMU_REG_FGCNT1			ENC_PMU_REG(FIFO_MODE, MAP1, 0xAA)
#define FGCNT1_FGCNT_11_8_MASK		0xF
#define FGCNT1_FGCNT_11_8_SHIFT		0
#define FGCNT1_RESERVED_MASK		0xF
#define FGCNT1_RESERVED_SHIFT		4

#define PMU_REG_FGCNT2			ENC_PMU_REG(FIFO_MODE, MAP1, 0xAB)
#define FGCNT2_FGCNT_7_0_MASK		0xFF
#define FGCNT2_FGCNT_7_0_SHIFT		0

#define PMU_REG_FGSLEEPCNT1		ENC_PMU_REG(FIFO_MODE, MAP1, 0xAC)
#define FGSLEEPCNT1_FGSLEEPCNT_15_8_MASK	0xFF
#define FGSLEEPCNT1_FGSLEEPCNT_15_8_SHIFT	0

#define PMU_REG_FGSLEEPCNT2		ENC_PMU_REG(FIFO_MODE, MAP1, 0xAD)
#define FGSLEEPCNT2_FGSLEEPCNT_7_0_MASK		0xFF
#define FGSLEEPCNT2_FGSLEEPCNT_7_0_SHIFT	0

#define PMU_REG_FGSMPL1			ENC_PMU_REG(FIFO_MODE, MAP1, 0xAE)
#define FGSMPL1_FGSMPL_15_8_MASK	0xFF
#define FGSMPL1_FGSMPL_15_8_SHIFT	0

#define PMU_REG_FGSMPL2			ENC_PMU_REG(FIFO_MODE, MAP1, 0xAF)
#define FGSMPL2_FGSMPL_7_0_MASK		0xFF
#define FGSMPL2_FGSMPL_7_0_SHIFT	0

#define PMU_REG_FGSMPL3			ENC_PMU_REG(FIFO_MODE, MAP1, 0xB0)
#define FGSMPL3_FGSMPL_CAL_15_8_MASK	0xFF
#define FGSMPL3_FGSMPL_CAL_15_8_SHIFT	0

#define PMU_REG_FGSMPL4			ENC_PMU_REG(FIFO_MODE, MAP1, 0xB1)
#define FGSMPL4_FGSMPL_CAL_7_0_MASK	0xFF
#define FGSMPL4_FGSMPL_CAL_7_0_SHIFT	0

#define PMU_REG_FGSMPL5			ENC_PMU_REG(FIFO_MODE, MAP1, 0xB2)
#define FGSMPL5_FGSMPLB_15_8_MASK	0xFF
#define FGSMPL5_FGSMPLB_15_8_SHIFT	0

#define PMU_REG_FGSMPL6			ENC_PMU_REG(FIFO_MODE, MAP1, 0xB3)
#define FGSMPL6_FGSMPLB_7_0_MASK	0xFF
#define FGSMPL6_FGSMPLB_7_0SHIFT	0

#define PMU_REG_FGOFFSET1		ENC_PMU_REG(FIFO_MODE, MAP1, 0xB4)
#define FGOFFSET1_FGOFFSET_15_8_MASK	0xFF
#define FGOFFSET1_FGOFFSET_15_8_SHIFT	0

#define PMU_REG_FGOFFSET2		ENC_PMU_REG(FIFO_MODE, MAP1, 0xB5)
#define FGOFFSET2_FGOFFSET_7_0_MASK	0xFF
#define FGOFFSET2_FGOFFSET_7_0_SHIFT	0

#define PMU_REG_FGBATCAL1		ENC_PMU_REG(FIFO_MODE, MAP1, 0xB6)
#define FGBATCAL1_FGVMBAT_9_8_MASK	0x3
#define FGBATCAL1_FGVMBAT_9_8_SHIFT	0

#define PMU_REG_FGBATCAL2		ENC_PMU_REG(FIFO_MODE, MAP1, 0xB7)
#define FGBATCAL2_FGVMBAT_7_0_MASK	0xFF
#define FGBATCAL2_FGVMBAT_7_0_SHIFT	0

#define PMU_REG_FGGNRL1			ENC_PMU_REG(FIFO_MODE, MAP1, 0xB8)
#define FGGNRL1_7_0_MASK		0xFF
#define FGGNRL1_7_0_SHIFT		0

#define PMU_REG_FGGNRL2			ENC_PMU_REG(FIFO_MODE, MAP1, 0xB9)
#define FGGNRL2_7_0_MASK		0xFF
#define FGGNRL2_7_0_SHIFT		00

#define PMU_REG_FGGNRL3			ENC_PMU_REG(FIFO_MODE, MAP1, 0xBA)
#define FGGNRL3_7_0_MASK		0xFF
#define FGGNRL3_7_0_SHIFT		0

#define PMU_REG_FGTRIMGN1_1		ENC_PMU_REG(FIFO_MODE, MAP1, 0xBB)
#define FGTRIMGN1_1_FGPOINT1_13_8_MASK		0x3F
#define FGTRIMGN1_1_FGPOINT1_13_8_SHIFT		0

#define PMU_REG_FGTRIMGN1_2		ENC_PMU_REG(FIFO_MODE, MAP1, 0xBC)
#define FGTRIMGN1_2_FGPOINT1_7_0_MASK		0xFF
#define FGTRIMGN1_2_FGPOINT1_7_0_SHIFT		0

#define PMU_REG_FGTRIMGN2_1		ENC_PMU_REG(FIFO_MODE, MAP1, 0xBD)
#define FGTRIMGN2_1_FGPOINT2_13_8_MASK		0x3F
#define FGTRIMGN2_1_FGPOINT2_13_8_SHIFT		0

#define PMU_REG_FGTRIMGN2_2		ENC_PMU_REG(FIFO_MODE, MAP1, 0xBE)
#define FGTRIMGN2_1_FGPOINT2_7_0_MASK		0xFF
#define FGTRIMGN2_1_FGPOINT2_7_0_SHIFT		0

#define PMU_REG_FG_EOC_TH	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00BF)
#define FG_EOC_TH_7_0_MASK	0xFF
#define FG_EOC_TH_7_0_SHIFT	0

#define PMU_REG_CMPCTRL1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00C8)

#define PMU_REG_CMPCTRL2	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00C9)

#define PMU_REG_CMPCTRL3	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00CA)

#define PMU_REG_CMPCTRL4	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00CB)

#define PMU_REG_CMPCTRL5	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00CC)
#define NTCHT_RISE_7_0_MASK	0xFF
#define NTCHT_RISE_7_0_SHIFT	0

#define PMU_REG_CMPCTRL6	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00CD)
#define NTCHT_FALL_7_0_MASK	0xFF
#define NTCHT_FALL_7_0_SHIFT	0

#define PMU_REG_CMPCTRL7	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00CE)
#define NTCCT_RISE_7_0_MASK	0xFF
#define NTCCT_RISE_7_0_SHIFT	0

#define PMU_REG_CMPCTRL8	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00CF)
#define NTCCT_FALL_7_0_MASK	0xFF
#define NTCCT_FALL_7_0_SHIFT	0

#define PMU_REG_CMPCTRL9	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00D0)
#define NTCCT_FALL_9_8_MASK	0x3
#define NTCCT_FALL_9_8_SHIFT	0
#define NTCCT_RISE_9_8_MASK	0xC
#define NTCCT_RISE_9_8_SHIFT	2
#define NTCHT_FALL_9_8_MASK	0x30
#define NTCHT_FALL_9_8_SHIFT	4
#define NTCHT_RISE_9_8_MASK	0xC0
#define NTCHT_RISE_9_8_SHIFT	6

#define PMU_REG_CMPCTRL10	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00D1)

#define PMU_REG_CMPCTRL11	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00D2)

#define PMU_REG_CMPCTRL12	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00D3)

#define PMU_REG_CMPCTRL13	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00D4)

#define PMU_REG_CMPCTRL14	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00D5)

#define PMU_REG_CMPCTRL15	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00D6)

#define PMU_REG_CMPCTRL16	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00D7)

#define PMU_REG_CMPCTRL17	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00D8)

#define PMU_REG_CMPCTRL18	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00D9)

#define PMU_REG_CMPCTRL19	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00DA)

#define PMU_REG_CMPCTRL20	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00DB)

#define PMU_REG_CMPCTRL21	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00DC)


#define PMU_REG_RTCSC		ENC_PMU_REG(FIFO_MODE, MAP1, 0x00E0)

#define PMU_REG_RTCMN		ENC_PMU_REG(FIFO_MODE, MAP1, 0x00E1)

#define PMU_REG_RTCHR		ENC_PMU_REG(FIFO_MODE, MAP1, 0x00E2)

#define PMU_REG_RTCWD		ENC_PMU_REG(FIFO_MODE, MAP1, 0x00E3)

#define PMU_REG_RTCDT		ENC_PMU_REG(FIFO_MODE, MAP1, 0x00E4)

#define PMU_REG_RTCMT_WD	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00E5)

#define PMU_REG_RTCYR		ENC_PMU_REG(FIFO_MODE, MAP1, 0x00E6)

#define PMU_REG_RTCSC_A1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00E7)

#define PMU_REG_RTCMN_A1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00E8)

#define PMU_REG_RTCHR_A1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00E9)

#define PMU_REG_RTCWD_A1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00EA)

#define PMU_REG_RTCDT_A1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00EB)

#define PMU_REG_RTCMT_A1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00EC)

#define PMU_REG_RTCYR_A1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00ED)

#define PMU_REG_RTC_EXTRA	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00EE)

#define PMU_REG_PWMLEDCTRL1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x0000)

#define PMU_REG_RTC_C2C1_XOTRIM	ENC_PMU_REG(FIFO_MODE, MAP1, 0x00EF)

#define PMU_REG_ENV1		ENC_PMU_REG(FIFO_MODE, MAP0, 0x00E9)
#define ENV1_P_MBWV_MASK        0x01
#define ENV1_P_MBWV_DELTA       0x02
#define ENV1_P_ERC              0x04
#define ENV1_P_MBMC             0x08
#define ENV1_P_MBOV             0x10
#define ENV1_P_MBUV             0x20
#define ENV1_P_BATIDWV          0x40
#define ENV1_P_BBLOWB           0x80

#define PMU_REG_ENV2		ENC_PMU_REG(FIFO_MODE, MAP0, 0x00EA)
#define ENV2_P_UBPD_ENV         0x01
#define ENV2_USBPD_USBDET	0x02
#define ENV2_P_UBPD_INT         0x04
#define ENV2_P_UBPD_INT_SHIFT	2
#define ENV2_P_UBPD_CHG         0x08
#define ENV2_P_UBPD_CHG_SHIFT   3
#define ENV2_USB_PORT_DISABLED	0x10
#define ENV2_USB_PORT_DISABLED_SHIFT	4
#define ENV2_P_UBMBC            0x20
#define ENV2_P_USBOV            0x40
#define ENV2_USB_VALID		0x80
#define ENV2_USB_VALID_SHIFT	7

#define PMU_REG_ENV3		ENC_PMU_REG(FIFO_MODE, MAP0, 0x00EB)
#define ENV3_TRUE_TF            0x01
#define	ENV3_P_MBC_CV		0x02
#define ENV3_CV_TRIP		0x04
#define ENV3_CV_TMR_EXP		0x08
#define ENV3_CV_TMR_EXP_SHIFT	3
#define ENV3_FG_EOC		0x10
#define ENV3_HW_EOC		0x20
#define ENV3_MB_EOC		0x40
#define ENV3_MBMC_ACTIVE	0x80

#define PMU_REG_ENV4		ENC_PMU_REG(FIFO_MODE, MAP0, 0x00EC)
#define ENV4_VBUS_STATUS_MASK   0x01
#define ENV4_VBUS_STATUS_SHIFT  0

#define ENV4_SESS_STATUS_MASK   0x02
#define ENV4_SESS_STATUS_SHIFT  1

#define ENV4_ID_CODE_MASK       0x38
#define ENV4_ID_CODE_SHIFT      3

#define PMU_REG_ENV5		ENC_PMU_REG(FIFO_MODE, MAP0, 0x00ED)
#define ENV5_P_MBPD             0x01
#define ENV5_P_MBTEMPLOW        0x02
#define ENV5_P_MBTEMPHIGH       0x04
#define ENV5_P_PONKEYB          0x08
#define ENV5_P_AUXON            0x10
#define ENV5_P_CHIP_TOOHOT      0x20
#define ENV5_P_MBPD_LONG        0x80

#define PMU_REG_ENV6		ENC_PMU_REG(FIFO_MODE, MAP0, 0x00EE)
#define ENV6_MBCERROR		0x01
#define ENV6_OFF_VBUSB		0x02
#define ENV6_OTG_SHUTDOENB	0x04
#define ENV6_ADP_SHUTDOWNB	0x08
#define ENV6_TCH_EXP		0x10
#define ENV6_SW_TMR_EXP		0x20
#define ENV6_HW_TTR_EXP		0x40
#define ENV6_HW_TCH_EXP		0x80
#define ENV6_HW_TCH_EXP_SHIFT	7

#define PMU_REG_ENV7		ENC_PMU_REG(FIFO_MODE, MAP0, 0x00EF)
#define ENV7_STAT1_ENV		0x01
#define ENV7_STAT2_ENV		0x02
#define ENV7_P_LOWBAT		0x04
#define ENV7_CANT_WAKEUP_BY_CHG	0x08
#define ENV7_DIS_CHG_XTAL_FAIL	0x10
#define ENV7_SHDWN_ENV_XTAL	0x20
#define ENV7_SW_RST_SHDWN	0x40
#define ENV7_BB_SHSWN		0x80
#define OTG_VBUS_STAT_MASK	0x3
#define OTG_VBUS_STAT_SHIFT	0

#define PMU_REG_ENV8		ENC_PMU_REG(FIFO_MODE, MAP0, 0x00F0)
#define ENV8_UBPD_WAKE		0x01
#define	ENV8_GBAT_PLUGIN	0x02
#define ENV8_RTC_ALARM		0x04
#define ENV8_AUXON_WAKE		0x08
#define ENV8_POK_WAKE		0x10
#define ENV8_POK_RESTART_WAKE	0x20
#define	ENV8_SMPL_WAKE		0x40
#define ENV8_SW_RESTART_WAKE	0x80

#define PMU_REG_ENV9		ENC_PMU_REG(FIFO_MODE, MAP0, 0x00F1)
#define ENV9_P_MBUV		0x01
#define ENV9_P_THSD		0x02
#define	ENV9_MBWV_SHDWN		0x04
#define	ENV9_SYS_WDT_EXP	0x08
#define ENV9_SW_SHDWN_CMD	0x10
#define ENV9_POK_PRESS_SHDWN	0x20
#define ENV9_RESTART_SHDWN	0x40
#define ENV9_SR_OVERI_SHDWN	0x80


#define PMU_REG_MAX		0x100


#endif /*__LINUX_MFD_BCMPMU59054_REG_H_*/
