/*  Copyright 2001 - 2012 Broadcom Corporation.  All rights reserved.
*
*  Unless you and Broadcom execute a separate written software license
*  agreement governing use of this software, this software is licensed to you
*  under the terms of the GNU General Public License version 2, available at
*  http://www.gnu.org/licenses/old-license/gpl-2.0.html (the "GPL").
*
*  Notwithstanding the above, under no circumstances may you combine this
*  software in any way with any other Broadcom software provided under a
*  license other than the GPL, without Broadcom's express prior written
*  consent.
*
*****************************************************************************/

/*ENC_PMU_REG(_8BIT_FLAGS_##_8BIT_MAP_ADD##_REG_ADD) */

#define FLAG_SHIFT		24
#define AMAP_SHIFT		16
#define FLAG_MASK		0xFF000000
#define AMAP_MASK		0xFF0000
#define ADD_MASK		0xFFFF
#define MAP0			0
#define	MAP1			1
#define FIFO_MODE		1
#define DIRECT_MODE		0

#define ENC_PMU_REG(f, m, a)	(((f) << FLAG_SHIFT) | \
				(((m) << AMAP_SHIFT) & AMAP_MASK) | \
				((a) & ADD_MASK))

#define DEC_MAP_ADD(x)		(((x) & AMAP_MASK) >> AMAP_SHIFT)
#define DEC_REG_FLAG(x)		(((x) & FLAG_MASK) >> FLAG_SHIFT)
#define DEC_REG_ADD(x)		((x) & ADD_MASK)

#define DEC_PMU_REG(a, f, m, r) \
				f = u8(a >> FLAG_SHIFT);\
				m = u8(a >> AMAP_SHIFT);\
				r = u16(a);

#define PMU_REG_I2CCTRL		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0000)
#define I2CCTRL_RDBLKEN_MASK	0x40
#define I2CCTRL_WRBLKEN_MASK	0x20
#define I2CCTRL_FIFOFULL	0x02
#define I2CCTRL_RDBLOCK		0x01

#define	PMU_REG_HOSTCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0001)
#define HOSTCTRL1_SW_SHDWN	0x04

#define	PMU_REG_HOSTCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0002)
#define	PMU_REG_HOSTCTRL3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0003)
#define	PMU_REG_HOSTCTRL4	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0004)

#define	PMU_REG_HOSTCTRL5	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0005)
#define HOSTCTRL5_POK_RSTPIN_ONLY	0x40
#define HOSTCTRL5_POK_RSTPIN_ONLY_MASK	0x40
#define HOSTCTRL5_POK_RSTPIN_ONLY_SHIFT 6

#define	PMU_REG_SMPLCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0006)

#define	PMU_REG_WRLOCKKEY	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0007)
#define WRLOCKKEY_VAL           0x38

#define	PMU_REG_WRPROEN		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0008)
#define WRPROEN_DIS_WR_PRO	0x1
#define WRPROEN_DIS_WR_PRO_MASK	0x1
#define WRPROEN_DIS_WR_PRO_SHIFT	0

#define WRPROEN_PMU_UNLOCK	0x2
#define WRPROEN_PMU_UNLOCK_MASK	0x2
#define WRPROEN_PMU_UNLOCK_SHIFT	1

#define	PMU_REG_PMUGID		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0009)
#define	PMU_REG_PLLPMCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0x000A)

#define	PMU_REG_PLLCTRL		ENC_PMU_REG(FIFO_MODE, MAP0, 0x000B)
#define PLLCTRL_PLLEN		0x02
#define PLLCTRL_PLLEN_MASK	0x02
#define PLLCTRL_PLLEN_SHIFT	1

#define PLLCTRL_AUDIO_EN	0x20
#define PLLCTRL_AUDIO_EN_MASK	0x20
#define PLLCTRL_AUDIO_EN_SHIFT	5

#define PLLCTRL_ENCLK26M	0x04
#define PLLCTRL_ENCLK26M_MASK	0x04
#define PLLCTRL_ENCLK26M_SHIFT	2

#define	PMU_REG_PONKEYCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x000C)
#define PONKEY_KEY_PAD_LOCK             0x80
#define PONKEY_KEY_PAD_LOCK_MASK        0x80
#define PONKEY_KEY_PAD_LOCK_SHIFT       0x7
#define PONKEY_RESTART_EN_MASK          0x40
#define PONKEY_RESTART_EN_SHIFT         0x6
#define PONKEY_F_DEB_MASK               0x07
#define PONKEY_F_DEB_SHIFT              0x0
#define PONKEY_R_DEB_MASK               0x38
#define PONKEY_R_DEB_SHIFT              0x3

#define	PMU_REG_PONKEYCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x000D)
#define PONKEYOFF_HOLD_DEB_MASK         0x07
#define PONKEYOFF_HOLD_DEB_SHIFT        0x0
#define PONKEY_SHUTDOWN_DLY_MASK        0x78
#define PONKEY_SHUTDOWN_DLY_SHIFT       0x3

#define	PMU_REG_PONKEYCTRL3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x000E)
#define PONKEY_RESTART_DEB_MASK         0x78
#define PONKEY_RESTART_DEB_SHIFT        0x3
#define PONKEY_RESTART_DLY_MASK         0x07
#define PONKEY_RESTART_DLY_SHIFT        0x0

#define	PMU_REG_AUXCTRL		ENC_PMU_REG(FIFO_MODE, MAP0, 0x000F)
#define AUXCTRL_KEYPAD_LOCK_MODE        0x10
#define AUXCTRL_KEYPAD_LOCK_MASK        0x10
#define AUXCTRL_KEYPAD_LOCK_SHIFT       0x4

#define PONKEY_ONHOLD_DEB_MASK          0xE0
#define PONKEY_ONHOLD_DEB_SHIFT         0x5

#define	PMU_REG_CMPCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0010)

#define	PMU_REG_CMPCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0011)

#define	PMU_REG_CMPCTRL3	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0012)

#define	PMU_REG_CMPCTRL4	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0013)

#define	PMU_REG_CMPCTRL5	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0014)

#define	PMU_REG_CMPCTRL6	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0015)

#define	PMU_REG_CMPCTRL7	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0016)

#define	PMU_REG_CMPCTRL8	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0017)

#define	PMU_REG_CMPCTRL9	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0018)

#define	PMU_REG_CMPCTRL10	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0019)

#define	PMU_REG_CMPCTRL11	ENC_PMU_REG(FIFO_MODE, MAP0, 0x001A)

#define	PMU_REG_CMPCTRL12	ENC_PMU_REG(FIFO_MODE, MAP0, 0x001B)

#define	PMU_REG_CMPCTRL13	ENC_PMU_REG(FIFO_MODE, MAP0, 0x001C)

#define	PMU_REG_CMPCTRL14	ENC_PMU_REG(FIFO_MODE, MAP0, 0x001D)

#define	PMU_REG_CMPCTRL15	ENC_PMU_REG(FIFO_MODE, MAP0, 0x001E)

#define	PMU_REG_CMPCTRL16	ENC_PMU_REG(FIFO_MODE, MAP0, 0x001F)

#define PMU_REG_RTCSC		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0020)

#define PMU_REG_RTCMN		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0021)

#define PMU_REG_RTCHR		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0022)

#define PMU_REG_RTCDT		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0023)

#define PMU_REG_RTCMT_WD	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0024)

#define PMU_REG_RTCYR		ENC_PMU_REG(FIFO_MODE, MAP0, 0x0025)

#define PMU_REG_RTCSC_A1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0026)

#define PMU_REG_RTCMN_A1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0027)

#define PMU_REG_RTCHR_A1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0028)

#define PMU_REG_RTCWD_A1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0029)

#define PMU_REG_RTCDT_A1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x002A)

#define PMU_REG_RTCMT_A1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x002B)

#define PMU_REG_RTCYR_A1	ENC_PMU_REG(FIFO_MODE, MAP0, 0X002C)

#define PMU_REG_RTC_CORE	ENC_PMU_REG(FIFO_MODE, MAP0, 0X002D)

#define PMU_REG_RTC_C2C1_XOTRIM	ENC_PMU_REG(FIFO_MODE, MAP0, 0X002E)

#define PMU_REG_BBCCTRL		ENC_PMU_REG(FIFO_MODE, MAP0, 0X002F)

#define PMU_REG_INT1		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0030)

#define PMU_REG_INT2		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0031)

#define PMU_REG_INT3		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0032)

#define PMU_REG_INT4		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0033)

#define PMU_REG_INT5		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0034)

#define PMU_REG_INT6		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0035)

#define PMU_REG_INT7		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0036)

#define PMU_REG_INT8		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0037)

#define PMU_REG_INT1MSK		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0040)

#define PMU_REG_INT2MSK		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0041)

#define PMU_REG_INT3MSK		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0042)

#define PMU_REG_INT4MSK		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0043)

#define PMU_REG_INT5MSK		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0044)

#define PMU_REG_INT6MSK		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0045)

#define PMU_REG_INT7MSK		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0046)

#define PMU_REG_INT8MSK		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0047)

#define PMU_REG_MBCCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0050)

#define PMU_REG_MBCCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0051)

#define PMU_REG_MBCCTRL3	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0052)

#define PMU_REG_MBCCTRL4	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0053)

#define PMU_REG_MBCCTRL5	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0054)

#define PMU_REG_MBCCTRL6	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0055)

#define PMU_REG_MBCCTRL7	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0056)

#define PMU_REG_MBCCTRL8	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0057)

#define PMU_REG_MBCCTRL9	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0058)

#define PMU_REG_MBCCTRL10	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0059)

#define PMU_REG_MBCCTRL11	ENC_PMU_REG(FIFO_MODE, MAP0, 0X005A)

#define PMU_REG_MBCCTRL12	ENC_PMU_REG(FIFO_MODE, MAP0, 0X005B)

#define PMU_REG_MBCCTRL13	ENC_PMU_REG(FIFO_MODE, MAP0, 0X005C)

#define PMU_REG_MBCCTRL14	ENC_PMU_REG(FIFO_MODE, MAP0, 0X005D)

#define PMU_REG_MBCCTRL15	ENC_PMU_REG(FIFO_MODE, MAP0, 0X005E)

#define PMU_REG_MBCCTRL16	ENC_PMU_REG(FIFO_MODE, MAP0, 0X005F)

#define PMU_REG_BCCTRL1		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0060)

#define PMU_REG_BCCTRL2		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0061)
#define BCCTRL2_SW_RST          0x1
#define BCCTRL2_SW_RST_MASK     0x1
#define BCCTRL2_SW_RST_SHIFT    0

#define BCCTRL2_BC_DET_EN       0x2
#define BCCTRL2_BC_DET_EN_MASK  0x2
#define BCCTRL2_BC_DET_EN_SHIFT 1

#define BCCTRL2_SW_OVWR_EN	0x4
#define BCCTRL2_SW_OVWR_EN_MASK		0x4
#define BCCTRL2_SW_OVWR_EN_SHIFT        2

#define BCCTRL2_SW_OVWR_KEY_SHIFT	4
#define BCCTRL2_SW_OVWR_KEY_MASK         0xF0

#define PMU_REG_BCCTRL3		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0062)
#define PMU_REG_BCCTRL4		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0063)
#define PMU_REG_BCCTRL5		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0064)
#define PMU_REG_BCCTRL6		ENC_PMU_REG(FIFO_MODE, MAP0, 0X0065)
#define PMU_REG_BCSTATUS1	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0066)
#define PMU_REG_BCSTATUS2	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0067)

#define PMU_REG_BCSTATUS3	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0068)
#define	BCSTATUS3_BC_STATUS_MASK       0xFF
#define	BCSTATUS3_BC_STATUS_SHIFT	0

#define PMU_REG_BCSTATUS4	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0069)

#define PMU_REG_BCSTATUS5	ENC_PMU_REG(FIFO_MODE, MAP0, 0X006A)
#define BCSTATUS5_CHGTYPE_MASK	0x0F
#define BCSTATUS5_CHGTYPE_SHIFT	0

#define BCSTATUS5_BC_DONE_MASK	0x10
#define BCSTATUS5_BC_DONE_SHIFT	4

#define BCSTATUS5_HW_FSM_IDEL	0x20
#define BCSTATUS5_HW_FSM_IDEL_MASK	0x20
#define BCSTATUS5_HW_FSM_IDEL_SHIFT	5

#define BCSTATUS5_BC_BIAS_EN	0x40
#define BCSTATUS5_BC_BIAS_EN_MASK	0x40
#define BCSTATUS5_BC_BIAS_EN_SHIFT	6

#define PMU_REG_BCDBG1		ENC_PMU_REG(FIFO_MODE, MAP0, 0X006B)

#define PMU_REG_BCDBG2		ENC_PMU_REG(FIFO_MODE, MAP0, 0X006C)

#define PMU_REG_BCDBG3		ENC_PMU_REG(FIFO_MODE, MAP0, 0X006D)

#define PMU_REG_BCDBG4		ENC_PMU_REG(FIFO_MODE, MAP0, 0X006E)

#define PMU_REG_BCDBG5		ENC_PMU_REG(FIFO_MODE, MAP0, 0X006F)

#define PMU_REG_UASCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0070)
#define UASCTRL1_UAS_DET_MODE_MASK      0x3
#define UASCTRL1_UAS_DET_MODE_SHIFT	0

#define UASCTRL1_UAS_DET_MODE_SW        0x00
#define UASCTRL1_UAS_DET_MODE_MAN       0x01
#define UASCTRL1_UAS_DET_MODE_HW        0x10

#define UASCTRL1_UAS_SW_GRP_MASK        0x1C
#define UASCTRL1_UAS_SW_GRP_SHIFT	2

#define PMU_REG_UASCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0071)

#define PMU_REG_UASCTRL3	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0072)

#define PMU_REG_UASCTRL4	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0073)

#define PMU_REG_UASCTRL5	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0074)

#define PMU_REG_UASCTRL6	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0075)

#define PMU_REG_UASCTRL7	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0076)

#define PMU_REG_ADCCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0080)

#define PMU_REG_ADCCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0081)

#define PMU_REG_ADCCTRL3	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0082)

#define PMU_REG_ADCCTRL4	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0083)

#define PMU_REG_ADCCTRL5	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0084)

#define PMU_REG_ADCCTRL6	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0085)

#define PMU_REG_ADCCTRL7	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0086)

#define PMU_REG_ADCCTRL8	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0087)

#define PMU_REG_ADCCTRL9	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0088)

#define PMU_REG_ADCCTRL10	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0089)

#define PMU_REG_ADCCTRL11	ENC_PMU_REG(FIFO_MODE, MAP0, 0X008A)

#define PMU_REG_ADCCTRL12	ENC_PMU_REG(FIFO_MODE, MAP0, 0X008B)

#define PMU_REG_ADCCTRL13	ENC_PMU_REG(FIFO_MODE, MAP0, 0X008C)

#define PMU_REG_ADCCTRL14	ENC_PMU_REG(FIFO_MODE, MAP0, 0X008D)

#define PMU_REG_ADCCTRL15	ENC_PMU_REG(FIFO_MODE, MAP0, 0X008E)

#define PMU_REG_ADCCTRL16	ENC_PMU_REG(FIFO_MODE, MAP0, 0X008F)

#define PMU_REG_ADCCTRL17	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0090)

#define PMU_REG_ADCCTRL18	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0091)

#define PMU_REG_ADCCTRL19	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0092)

#define PMU_REG_ADCCTRL20	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0093)

#define PMU_REG_ADCCTRL21	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0094)

#define PMU_REG_ADCCTRL22	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0095)

#define PMU_REG_ADCCTRL23	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0096)

#define PMU_REG_ADCCTRL24	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0097)

#define PMU_REG_ADCCTRL25	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0098)

#define PMU_REG_ADCCTRL26	ENC_PMU_REG(FIFO_MODE, MAP0, 0X0099)

#define PMU_REG_ADCCTRL27	ENC_PMU_REG(FIFO_MODE, MAP0, 0X009A)

#define PMU_REG_RFOPMODCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00A0)

#define PMU_REG_CAMOPMODCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00A1)

#define PMU_REG_HV1OPMODCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00A2)

#define PMU_REG_HV2OPMODCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00A3)

#define PMU_REG_HV3OPMODCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00A4)

#define PMU_REG_HV4OPMODCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00A5)

#define PMU_REG_HV5OPMODCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00A6)

#define PMU_REG_HV6OPMODCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00A7)

#define PMU_REG_HV7OPMODCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00A8)

#define PMU_REG_HV8OPMODCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00A9)

#define PMU_REG_HV9OPMODCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00AA)

#define PMU_REG_HV10OPMODCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00AB)

#define PMU_REG_SIMOPMODCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00AC)

#define PMU_REG_CSROPMODCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00AD)

#define PMU_REG_IOSROPMODCTRL   ENC_PMU_REG(FIFO_MODE, MAP0, 0X00AE)

#define PMU_REG_SDSROPMODCTRL   ENC_PMU_REG(FIFO_MODE, MAP0, 0X00AF)

#define PMU_REG_ASROPMODCTRL    ENC_PMU_REG(FIFO_MODE, MAP0, 0X00B0)

#define PMU_REG_RFLDOCTRL       ENC_PMU_REG(FIFO_MODE, MAP0, 0X00B1)

#define PMU_REG_CAMLDOCTRL      ENC_PMU_REG(FIFO_MODE, MAP0, 0X00B2)

#define PMU_REG_HVLDO1CTRL      ENC_PMU_REG(FIFO_MODE, MAP0, 0X00B3)

#define PMU_REG_HVLDO2CTRL      ENC_PMU_REG(FIFO_MODE, MAP0, 0X00B4)

#define PMU_REG_HVLDO3CTRL      ENC_PMU_REG(FIFO_MODE, MAP0, 0X00B5)

#define PMU_REG_HVLDO4CTRL      ENC_PMU_REG(FIFO_MODE, MAP0, 0X00B6)

#define PMU_REG_HVLDO5CTRL      ENC_PMU_REG(FIFO_MODE, MAP0, 0X00B7)

#define PMU_REG_HVLDO6CTRL      ENC_PMU_REG(FIFO_MODE, MAP0, 0X00B8)

#define PMU_REG_HVLDO7CTRL      ENC_PMU_REG(FIFO_MODE, MAP0, 0X00B9)

#define PMU_REG_HVLDO8CTRL      ENC_PMU_REG(FIFO_MODE, MAP0, 0X00BA)

#define PMU_REG_HVLDO9CTRL      ENC_PMU_REG(FIFO_MODE, MAP0, 0X00BB)

#define PMU_REG_HVLDO10CTRL     ENC_PMU_REG(FIFO_MODE, MAP0, 0X00BC)

#define PMU_REG_SIMLDOCTRL	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00BD)

#define PMU_REG_PWR_GRP_DLY     ENC_PMU_REG(FIFO_MODE, MAP0, 0X00BE)

#define PMU_REG_VIOPON_CTRL     ENC_PMU_REG(FIFO_MODE, MAP0, 0X00BF)

#define PMU_REG_CSRCTRL1        ENC_PMU_REG(FIFO_MODE, MAP0, 0X00C0)

#define PMU_REG_CSRCTRL2        ENC_PMU_REG(FIFO_MODE, MAP0, 0X00C1)

#define PMU_REG_CSRCTRL3        ENC_PMU_REG(FIFO_MODE, MAP0, 0X00C2)

#define PMU_REG_CSRCTRL4        ENC_PMU_REG(FIFO_MODE, MAP0, 0X00C3)

#define PMU_REG_CSRCTRL5        ENC_PMU_REG(FIFO_MODE, MAP0, 0X00C4)

#define PMU_REG_CSRCTRL6        ENC_PMU_REG(FIFO_MODE, MAP0, 0X00C5)

#define PMU_REG_CSRCTRL7        ENC_PMU_REG(FIFO_MODE, MAP0, 0X00C6)

#define PMU_REG_CSRCTRL8        ENC_PMU_REG(FIFO_MODE, MAP0, 0X00C7)

#define PMU_REG_IOSRCTRL1       ENC_PMU_REG(FIFO_MODE, MAP0, 0X00C8)

#define PMU_REG_IOSRCTRL2       ENC_PMU_REG(FIFO_MODE, MAP0, 0X00C9)

#define PMU_REG_IOSRCTRL3       ENC_PMU_REG(FIFO_MODE, MAP0, 0X00CA)

#define PMU_REG_IOSRCTRL4       ENC_PMU_REG(FIFO_MODE, MAP0, 0X00CB)

#define PMU_REG_IOSRCTRL5       ENC_PMU_REG(FIFO_MODE, MAP0, 0X00CC)

#define PMU_REG_IOSRCTRL6	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00CD)

#define PMU_REG_IOSRCTRL7       ENC_PMU_REG(FIFO_MODE, MAP0, 0X00CE)

#define PMU_REG_IOSRCTRL8       ENC_PMU_REG(FIFO_MODE, MAP0, 0X00CF)

#define PMU_REG_SDSRCTRL1       ENC_PMU_REG(FIFO_MODE, MAP0, 0X00D0)

#define PMU_REG_SDSRCTRL2       ENC_PMU_REG(FIFO_MODE, MAP0, 0X00D1)

#define PMU_REG_SDSRCTRL3       ENC_PMU_REG(FIFO_MODE, MAP0, 0X00D2)

#define PMU_REG_SDSRCTRL4       ENC_PMU_REG(FIFO_MODE, MAP0, 0X00D3)

#define PMU_REG_SDSRCTRL5       ENC_PMU_REG(FIFO_MODE, MAP0, 0X00D4)

#define PMU_REG_SDSRCTRL6	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00D5)

#define PMU_REG_SDSRCTRL7	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00D6)

#define PMU_REG_SDSRCTRL8	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00D7)

#define PMU_REG_ASRCTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00D8)

#define PMU_REG_ASRCTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00D9)

#define PMU_REG_ASRCTRL3	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00DA)

#define PMU_REG_ASRCTRL4	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00DB)

#define PMU_REG_ASRCTRL5	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00DC)

#define PMU_REG_ASRCTRL6	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00DD)

#define PMU_REG_ASRCTRL7	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00DE)

#define PMU_REG_ASRCTRL8	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00DF)

#define PMU_REG_ENV1		ENC_PMU_REG(FIFO_MODE, MAP0, 0X00E0)

#define PMU_REG_ENV2		ENC_PMU_REG(FIFO_MODE, MAP0, 0X00E1)

#define PMU_REG_ENV3		ENC_PMU_REG(FIFO_MODE, MAP0, 0X00E2)

#define PMU_REG_ENV4		ENC_PMU_REG(FIFO_MODE, MAP0, 0X00E3)

#define PMU_REG_ENV5		ENC_PMU_REG(FIFO_MODE, MAP0, 0X00E4)

#define PMU_REG_ENV6		ENC_PMU_REG(FIFO_MODE, MAP0, 0X00E5)

#define PMU_REG_ENV7		ENC_PMU_REG(FIFO_MODE, MAP0, 0X00E6)

#define PMU_REG_PDCMPSYN0	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00F0)

#define PMU_REG_PDCMPSYN1	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00F1)

#define PMU_REG_PDCMPSYN2	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00F2)

#define PMU_REG_PDCMPSYN3	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00F3)

#define PMU_REG_PDCMPSYN4	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00F4)

#define PMU_REG_PDCMPSYN5	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00F5)

#define PMU_REG_DIGTESTMUX1	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00F9)

#define PMU_REG_DIGTESTMUX2	ENC_PMU_REG(FIFO_MODE, MAP0, 0X00FA)

#define PMU_REG_ANADBG1		ENC_PMU_REG(FIFO_MODE, MAP0, 0X00FB)

#define PMU_REG_ANADBG2		ENC_PMU_REG(FIFO_MODE, MAP0, 0X00FC)

#define PMU_REG_ANADBG3		ENC_PMU_REG(FIFO_MODE, MAP0, 0X00FD)

#define PMU_REG_ANADBG4		ENC_PMU_REG(FIFO_MODE, MAP0, 0X00FE)

#define PMU_REG_PAGESEL		ENC_PMU_REG(FIFO_MODE, MAP0, 0X00FF)

#define PMU_REG_OTG_CTRL1	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0101)

#define PMU_REG_OTG_CTRL2	ENC_PMU_REG(FIFO_MODE, MAP0, 0x0102)

/* Map 1 reg */
#define PMU_REG_FGOPMODCTRL	ENC_PMU_REG(FIFO_MODE, MAP1, 0x42)

#define PMU_REG_IHFTOP		ENC_PMU_REG(FIFO_MODE, MAP1, 0x80)
#define IHFTOP_IHF_IDDQ			0x1
#define IHFTOP_IHF_IDDQ_MASK		0x1
#define IHFTOP_IHF_IDDQ_SHIFT		0

#define PMU_REG_IHFCLK		ENC_PMU_REG(FIFO_MODE, MAP1, 0x81)
#define IHFCLK_IHFBIASEN                0x04
#define IHFCLK_IHFBIASEN_MASK           0x04
#define IHFCLK_IHFBIASEN_SHIFT          2
#define IHFCLK_PUP                      0x08
#define IHFCLK_PUP_MASK                 0x08
#define IHFCLK_PUP_SHIFT                3

#define PMU_REG_IHFLDO		ENC_PMU_REG(FIFO_MODE, MAP1, 0x82)
#define IHFLDO_PUP                      0x1
#define IHFLDO_PUP_MASK                 0x1
#define IHFLDO_PUP_SHIFT                0

#define PMU_REG_IHFPOP		ENC_PMU_REG(FIFO_MODE, MAP1, 0x83)
#define IHFPOP_TIMECTL_MASK	0x03
#define IHFPOP_TIMECTL_SHIFT	0

#define IHFPOP_PUP		0x08
#define IHFPOP_PUP_MASK		0x08
#define IHFPOP_PUP_SHIFT	4

#define IHFPOP_EN		0x04
#define IHFPOP_EN_MASK		0x04
#define IHFPOP_EN_SHIFT		2

#define IHFPOP_BYPASS		0x20
#define IHFPOP_BYPASS_MASK	0x20
#define IHFPOP_BYPASS_SHIFT	4

#define IHFAUTO_SEQ		0x40
#define IHFAUTO_SEQ_MASK	0x40
#define IHFAUTO_SEQ_SHIFT	6

#define PMU_REG_IHFRCCAL	ENC_PMU_REG(FIFO_MODE, MAP1, 0x84)
#define IHFRCCAL_PUP		0x01
#define IHFRCCAL_PUP_MASK	0x01
#define IHFRCCAL_PUP_SHIFT	1

#define PMU_REG_IHFPSR1		ENC_PMU_REG(FIFO_MODE, MAP1, 0x85)
#define IHFPSR1_PSRCAL_PUP	0x01
#define IHFPSR1_PSRCAL_PUP_MASK	0x01
#define IHFPSR1_PSRCAL_PUP_SHIFT	0

#define PMU_REG_IHFFF		ENC_PMU_REG(FIFO_MODE, MAP1, 0x88)
#define IHFFF_PUP		0x01
#define IHFFF_PUP_MASK		0x01
#define IHFFF_PUP_SHIFT		0

#define PMU_REG_IHFALC1		ENC_PMU_REG(FIFO_MODE, MAP1, 0x89)
#define IHFALC1_IHFALC_BYP	0x04
#define IHFALC1_IHFALC_BYP_MASK	0x04
#define IHFALC1_IHFALC_BYP_SHIFT	2

#define IHFALC1_BYP		0x04
#define IHFALC1_BYP_MASK	0x04
#define IHFALC1_BYP_SHIFT	2

#define PMU_REG_IHFRAMP		ENC_PMU_REG(FIFO_MODE, MAP1, 0x8C)
#define IHFRAMP_PUP		0x1
#define IHFRAMP_PUP_MASK	0x1
#define IHFRAMP_PUP_SHIFT	0

#define IHFRAMP_IHFCAL_SEL	0x10
#define IHFRAMP_IHFCAL_SEL_MASK	0x10
#define IHFRAMP_IHFCAL_SEL_SHIFT	4

#define IHFRAMP_DRVCLAMP_DIS	0x08
#define IHFRAMP_DRVCLAMP_DIS_MASK	0x08
#define IHFRAMP_DRVCLAMP_DIS_SHIFT	3

#define PMU_REG_HIGH_GAIN_MODE	ENC_PMU_REG(FIFO_MODE, MAP1, 0x8D)
#define IHFPGA1_6DBGAIN_SHIFT           0x08
#define IHFPGA1_6DBGAIN_SHIFT_MASK      0x08
#define IHFPGA1_6DBGAIN_SHIFT_SHIFT     3

#define PMU_REG_IHFPGA2_GAIN	ENC_PMU_REG(FIFO_MODE, MAP1, 0x8E)
#define IHFPGA2_MUTE		0
#define IHFPGA2_GAIN_SHIFT	0
#define IHFPGA2_GAIN_MASK	0x3F
#define IHFPGA2_MUX_MODE_MASK	0xC0
#define IHFPGA2_MUX_MODE_SHIFT	6
#define IHFPGA2_MUX_MODE_PADS_ONLY	0x00
#define IHFPGA2_MUX_MODE_PADS_MUX       0x01
#define IHFPGA2_MUX_MODE_DIS_PADS_MUX   0x10
#define IHFPGA2_MUX_MODE_MUX_ONLY       0x11

#define PMU_REG_IHFLF		ENC_PMU_REG(FIFO_MODE, MAP1, 0x8F)
#define IHFLF_PUP		1
#define IHFLF_PUP_MASK		0x1
#define IHFLF_PUP_SHIFT		0

#define PMU_REG_IHFCMPPD	ENC_PMU_REG(FIFO_MODE, MAP1, 0x90)
#define IHFCMPPD_PUP		1
#define IHFCMPPD_PUP_MASK	0x1
#define IHFCMPPD_PUP_SHIFT	0

#define PMU_REG_IHFPWRDRV	ENC_PMU_REG(FIFO_MODE, MAP1, 0x91)
#define IHFPWRDRV_PUP		1
#define IHFPWRDRV_PUP_MASK	0x1
#define IHFPWRDRV_PUP_SHIFT	0

#define PMU_REG_IHFFB		ENC_PMU_REG(FIFO_MODE, MAP1, 0x92)
#define IHFFB_PUP		1
#define IHFFB_PUP_MASK		0x1
#define IHFFB_PUP_SHIFT		0

#define PMU_REG_SPKSTIN		ENC_PMU_REG(FIFO_MODE, MAP1, 0x93)
#define SPKSTIN_ST_CTRL_MASK	0x3
#define SPKSTIN_ST_CTRL_SHIFT	0

#define PMU_REG_IHF_NGTHRESH	ENC_PMU_REG(FIFO_MODE, MAP1, 0x9A)
#define IHF_NGTHRESH_THLD_MASK	0x07
#define IHF_NGTHRESH_THLD_SHIFT	0

#define PMU_REG_IHF_NGMISC	ENC_PMU_REG(FIFO_MODE, MAP1, 0x9B)
#define NGMISC_IHFNG_PUP_EN_IHFNG	0x08
#define NGMISC_IHFNG_PUP_MASK	0x08
#define NGMISC_IHFNG_PUP_SHIFT	3

#define PMU_REG_IHF_HS_TST	ENC_PMU_REG(FIFO_MODE, MAP1, 0x9C)
#define IHF_HS_SC_EDISABLE	0x02
#define IHF_HS_SC_EDISABLE_MASK	0x02
#define IHF_HS_SC_EDISABLE_SHIFT	1

#define IHF_SC_EDISABLE		0x04
#define IHF_SC_EDISABLE_MASK	0x04
#define IHF_SC_EDISABLE_SHIFT	2

#define PMU_REG_HSCP1		ENC_PMU_REG(FIFO_MODE, MAP1, 0xA0)
#define PMU_REG_HSCP2		ENC_PMU_REG(FIFO_MODE, MAP1, 0xA1)
#define PMU_REG_HSCP3		ENC_PMU_REG(FIFO_MODE, MAP1, 0xA2)

#define PMU_REG_HSDRV		ENC_PMU_REG(FIFO_MODE, MAP1, 0xA3)
#define HSDRV_DISSC		0x10
#define HSDRV_DISSC_MASK	0x10
#define HSDRV_DISSC_SHIFT	4

#define PMU_REG_HSLDO		ENC_PMU_REG(FIFO_MODE, MAP1, 0xA4)
#define PMU_REG_HSPGA1		ENC_PMU_REG(FIFO_MODE, MAP1, 0xA6)
#define PMU_REG_HSPGA2		ENC_PMU_REG(FIFO_MODE, MAP1, 0xA7)
#define PMU_REG_HSPGA3		ENC_PMU_REG(FIFO_MODE, MAP1, 0xA8)

#define PMU_REG_HSPUP1		ENC_PMU_REG(FIFO_MODE, MAP1, 0xAA)
#define HSPUP1_IDDQ_PWRDN	0x10
#define HSPUP1_IDDQ_PWRDN_MASK	0x10
#define HSPUP1_IDDQ_PWRDN_SHIFT	4

#define HSPUP1_CP_CG_SEL	0x04
#define HSPUP1_CP_CG_SEL_MASK	0x04
#define HSPUP1_CP_CG_SEL_SHIFT	2

#define PMU_REG_HSPUP2		ENC_PMU_REG(FIFO_MODE, MAP1, 0xAB)
#define HSPUP2_HS_PWRUP		0x40
#define HSPUP2_HS_PWRUP_MASK	0x40
#define HSPUP2_HS_PWRUP_SHIFT	6

#define PMU_REG_HSIST		ENC_PMU_REG(FIFO_MODE, MAP1, 0xAC)
#define HSIST_OC_DISOCMUX	0x10
#define HSIST_OC_DISOCMUX_MASK	0x10
#define HSIST_OC_DISOCMUX_SHIFT	4

#define PMU_REG_PMUID		ENC_PMU_REG(FIFO_MODE, MAP1, 0x0F7)
#define PMU_REG_PMUREV		ENC_PMU_REG(FIFO_MODE, MAP1, 0x0F8)

/*Not mapped for 39 */
#define PMU_REG_IHFSTO		ENC_PMU_REG(FIFO_MODE, MAP1, 0x1090)

#define PMU_REG_OTGCTRL1	ENC_PMU_REG(FIFO_MODE, MAP1, 0x1070)

/* PMU_REG_OTGCTRL1 */
#define OTGCTRL1_EN_VBUS_PULSE_MASK	0x01
#define OTGCTRL1_EN_VBUS_PULSE_SHIFT	0

#define OTGCTRL1_EN_PD_SRP_MASK		0x02
#define OTGCTRL1_EN_PD_SRP_SHIFT	1

#define OTGCTRL1_OFFVBUSB_MASK		0x04
#define OTGCTRL1_OFFVBUSB_SHIFT		2

#define OTGCTRL1_ID_DET_EN_MASK		0x08
#define OTGCTRL1_ID_DET_EN_SHIFT	3

#define OTGCTRL1_EN_SESS_VALID_MASK	0x10
#define OTGCTRL1_EN_SESS_VALID_SHIFT	4

#define OTGCTRL1_EN_VBUS_RBUS_MASK	0x20
#define OTGCTRL1_EN_VBUS_RBUS_SHIFT	5

#define OTGCTRL1_OTG_SHUTDOWNB_MASK	0x40
#define OTGCTRL1_OTG_SHUTDOWNB_SHIFT	6

#define OTGCTRL1_EN_SRP_COMPS_MASK	0x80
#define OTGCTRL1_EN_SRP_COMPS_SHIFT	7

#define OTGCTRL1_OTG_VBUS_BOOST_MASK	0x04
#define OTGCTRL1_OTG_VBUS_BOOST_SHIFT	2

#define OTGCTRL1_OTG_VBUS_OTG_ENABLE_MASK	0x40
#define OTGCTRL1_OTG_VBUS_OTG_ENABLE_SHIFT	6

#define PMU_REG_OTGCTRL2	ENC_PMU_REG(FIFO_MODE, MAP1, 0x1071)
#define OTGCTRL2_VBUS_ADP_COMP_DB_MASK	0x03
#define OTGCTRL2_VBUS_ADP_COMP_DB_SHIFT	0

#define OTGCTRL2_VBUS_ADP_RBUS_SEL_MASK	0x04
#define OTGCTRL2_VBUS_ADP_RBUS_SEL_SHIFT         2

#define OTGCTRL2_ADP_PRB_CYCLE_TIME_MASK	0x08
#define OTGCTRL2_ADP_PRB_CYCLE_TIME_SHIFT	3

#define OTGCTRL2_ADP_SNS_MASK	0x10
#define OTGCTRL2_ADP_SNS_SHIFT	4

/* 0x7B */
#define PMU_REG_OTGCTRL12	ENC_PMU_REG(FIFO_MODE, MAP1, 0x107B)
#define OTGCTRL12_EN_ADP_SNS_COMP_MASK	0x02
#define OTGCTRL12_EN_ADP_SNS_COMP_SHIFT	1

#define OTGCTRL12_ADP_THR_CTRL_MASK	0x80
#define OTGCTRL12_ADP_THR_CTRL_SHIFT	7

/* 0x8F */
#define PMU_REG_IHFSTIN_EXT	ENC_PMU_REG(FIFO_MODE, MAP1, 0x108F)
#define IHFSTIN_EXT_EN_SELF_TEST_MASK	0x03
#define IHFSTIN_EXT_EN_SELF_TEST_SHIFT	0

#define PMU_REG_MAX		0x0100
