ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_legacy/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o
