/*****************************************************************************
* Copyright 2004 - 2008 Broadcom Corporation.  All rights reserved.
*
* Unless you and Broadcom execute a separate written software license
* agreement governing use of this software, this software is licensed to you
* under the terms of the GNU General Public License version 2, available at
* http://www.broadcom.com/licenses/GPLv2.php (the "GPL").
*
* Notwithstanding the above, under no circumstances may you combine this
* software in any way with any other Broadcom software provided under a
* license other than the GPL, without Broadcom's express prior written
* consent.
*****************************************************************************/

/*
 *  GPIO pin group definitions
 */

/* ---- Include Files ----------------------------------------------------- */
#include <mach/gpiomux.h>
#include <mach/gpiomux_groups.h>
#include <mach/gpio_defs_hana.h>

/*
 * Following is a number of lists of gpio pins, which are collected
 * by logical function.
 */

static const gpiomux_pinconfig_t arm_i2c0List[] =
{
   {GPIOMUX_ENTRY(GPIO_56_VC_CAM1_SDA_BSC1_SDA, ALT02, TTL, NONE, 08mA, HIGH) },
   {GPIOMUX_ENTRY(GPIO_57_VC_CAM1_SCL_BSC1_SCL, ALT02, TTL, NONE, 08mA, HIGH) }
};

static const gpiomux_pinconfig_t arm_i2c1List[] =
{
   {GPIOMUX_ENTRY(GPIO_58_BSC2_SDA_VC_CAM2_SDA_VC_GPIO_9, ALT01, TTL, NONE, 08mA, HIGH) },
   {GPIOMUX_ENTRY(GPIO_59_BSC2_SCL_VC_CAM2_SCL_VC_GPIO_8, ALT01, TTL, NONE, 08mA, HIGH) }
};

static const gpiomux_pinconfig_t clk_outList[] =
{
   {GPIOMUX_ENTRY(GPIO_16_CLKOUT_1,    ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_17_CLKOUT_0,    ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_18_CLKREQ_IN_1, ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_19_CLKREQ_IN_0, ALT01, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t digital_micList[] =
{
   {GPIOMUX_ENTRY(GPIO_12_DIGMIC2_DQ,  ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_13_DIGMIC2_CLK, ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_14_DIGMIC1_DQ,  ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_15_DIGMIC1_CLK, ALT01, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t hdmi_i2cList[] =
{
   {GPIOMUX_ENTRY(GPIO_54_HDMI_SDA, ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_55_HDMI_SCL, ALT01, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t hsiList[] =
{
   {GPIOMUX_ENTRY(GPIO_69_SSP2_FS_2_VC_PWM_0_CAWAKE_WCDMA_DEBUG_7,       ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_70_SSP2_TXD_1_IrTx_CAREADY_WCDMA_DEBUG_6,         ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_71_SSP2_RXD_1_IrRx_CAFLAG_WCDMA_DEBUG_5,          ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_72_SSP2_FS_1_IrRtsSd_CADATA_WCDMA_DEBUG_4,        ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_73_SSP2_TXD_0_UARTB4_UCTSN_ACWAKE_WCDMA_DEBUG_3,  ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_74_SSP2_RXD_0_UARTB4_URTSN_ACREADY_WCDMA_DEBUG_2, ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_75_SSP2_CLK_UARTB4_UTXD_ACFLAG_WCDMA_DEBUG_1,     ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_76_SSP2_FS_0_UARTB4_URXD_ACDATA_WCDMA_DEBUG_0,    ALT03, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t keypad_7x4List[] =
{
   {GPIOMUX_ENTRY(GPIO_158_NORFLSH_AD08_SSP2_FS_3_KP_ROW_OP_6_VC_TRSTB,       ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_159_NORFLSH_AD09_VC_GPIO_4_KP_ROW_OP_5_VC_TDO,         ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_160_NORFLSH_AD10_CWS_SYS_REQ3_KP_ROW_OP_4,             ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_161_NORFLSH_AD11_CWS_SYS_REQ2_KP_ROW_OP_3,             ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_162_NORFLSH_AD12_CLKREQ_IN_3_KP_ROW_OP_2_IRD_OSC_10,   ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_163_NORFLSH_AD13_CLKREQ_IN_2_KP_ROW_OP_1_IRD_OSC_9,    ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_164_NORFLSH_AD14_SWDIOTMS_KP_ROW_OP_0_IRD_OSC_8,       ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_166_NORFLSH_ADLAT_EN_VC_GPIO_3_KP_COL_IP_1_IRD_OSC_6,  ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_167_NORFLSH_AADLAT_EN_VC_GPIO_2_KP_COL_IP_2_IRD_OSC_5, ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_172_NORFLSH_ADDR20_SSP2_TXD_0_KP_COL_IP_3_IRD_OSC_0,   ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_173_NORFLSH_ADDR21_SSP2_RXD_0_KP_COL_IP_4_VC_TDI,      ALT03, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t keypad_7x8List[] =
{
   {GPIOMUX_ENTRY(GPIO_154_NORFLSH_AD04_VC_PWM_0_KP_COL_IP_0,                 ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_157_NORFLSH_AD07_SSP2_FS_1_KP_COL_IP_7,                ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_158_NORFLSH_AD08_SSP2_FS_3_KP_ROW_OP_6_VC_TRSTB,       ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_159_NORFLSH_AD09_VC_GPIO_4_KP_ROW_OP_5_VC_TDO,         ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_160_NORFLSH_AD10_CWS_SYS_REQ3_KP_ROW_OP_4,             ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_161_NORFLSH_AD11_CWS_SYS_REQ2_KP_ROW_OP_3,             ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_162_NORFLSH_AD12_CLKREQ_IN_3_KP_ROW_OP_2_IRD_OSC_10,   ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_163_NORFLSH_AD13_CLKREQ_IN_2_KP_ROW_OP_1_IRD_OSC_9,    ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_164_NORFLSH_AD14_SWDIOTMS_KP_ROW_OP_0_IRD_OSC_8,       ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_166_NORFLSH_ADLAT_EN_VC_GPIO_3_KP_COL_IP_1_IRD_OSC_6,  ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_167_NORFLSH_AADLAT_EN_VC_GPIO_2_KP_COL_IP_2_IRD_OSC_5, ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_172_NORFLSH_ADDR20_SSP2_TXD_0_KP_COL_IP_3_IRD_OSC_0,   ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_173_NORFLSH_ADDR21_SSP2_RXD_0_KP_COL_IP_4_VC_TDI,      ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_174_NORFLSH_ADDR22_SSP2_CLK_KP_COL_IP_5_VC_TCK,        ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_175_NORFLSH_ADDR23_SSP2_FS_0_KP_COL_IP_6_VC_TMS,       ALT03, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t lcd_teList[] =
{
   {GPIOMUX_ENTRY(GPIO_97_UARTB4_URXD_VC_TE1_VC_URXD, ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_98_UARTB4_UTXD_VC_TE0_VC_UTXD, ALT02, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t mphiList[] =
{
   {GPIOMUX_ENTRY(GPIO_184_RXDATA3G0_MPHI_HAT0,          ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_185_RTXEN2G_TXDATA3G2_MPHI_HAT1,  ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_186_RTXDATA2G_TXDATA3G1_MPHI_HA0, ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_187_TXDATA3G0_MPHI_HRD_N,         ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_188_GPEN03_MPHI_HWR_N,            ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_189_SRI_D_MPHI_RUN,               ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_190_SRI_E_MPHI_DATA0,             ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_191_SRI_C_MPHI_DATA01,            ALT02, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t nandList[] =
{
   {GPIOMUX_ENTRY(GPIO_99_NAND_AD0_SDIO3_DATA_0_SSP1_RXD_DEBUG_BUS15,                   ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_100_NAND_AD1_SDIO3_CLK_SSP1_CLK_DEBUG_BUS14,                     ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_101_NAND_AD2_SDIO3_DATA_3_SSP1_FS_WCDMA_UART_TXD_DEBUG_BUS13,    ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_102_NAND_AD3_SDIO3_CMD_SSP1_TXD_WCDMA_UART_RXD_DEBUG_BUS12,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_103_NAND_AD4_SDIO3_DATA_1_UARTB_URXD_WCDMA_DEBUG_7_DEBUG_BUS11,  ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_104_NAND_AD5_SDIO3_DATA_2_UARTB_UCTSN_WCDMA_DEBUG_6_DEBUG_BUS10, ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_105_NAND_AD6_SDIO3_DATA_4_UARTB_URTSN_WCDMA_DEBUG_5_DEBUG_BUS09, ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_106_NAND_AD7_SDIO3_DATA_5_UARTB_UTXD_WCDMA_DEBUG_4_DEBUG_BUS08,  ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_107_NAND_WEN_SDIO3_DATA_6_VC_TMS_WCDMA_DEBUG_3_DEBUG_BUS07,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_108_NAND_OEN_SDIO3_DATA_7_VC_TDO_WCDMA_DEBUG_2_DEBUG_BUS06,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_109_NAND_ALE_SDIO4_DATA_4_VC_TDI_WCDMA_DEBUG_1_DEBUG_BUS05,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_110_NAND_CLE_SDIO4_DATA_5_VC_TCK_WCDMA_DEBUG_0_DEBUG_BUS04,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_111_NAND_RDY1_SDIO4_CMD_VC_TRSTB_WCDMA_SYNC_DEBUG_BUS03,         ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_112_NAND_RDY0_SDIO4_DATA_0_WCDMA_CLK3_DEBUG_BUS02,               ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_113_NAND_CEN1_SDIO4_DATA_1_WCDMA_CLK2_DEBUG_BUS01,               ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_114_NAND_CEN0_SDIO4_DATA_2_OSC2_OUT_WCDMA_CLK1_DEBUG_BUS00,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_115_NAND_WP_SDIO4_DATA_3_OSC1_OUT,                               ALT01, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t norList[] =
{
   {GPIOMUX_ENTRY(GPIO_148_NORFLSH_CLK_N_SDIO4_DATA_6_SDIO1_DATA_2,           ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_149_NORFLSH_RDY_SDIO4_DATA_7_SDIO1_DATA_1,             ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_150_NORFLSH_AD00_SSP3_TXD_SDIO1_CMD,                   ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_151_NORFLSH_AD01_SSP3_RXD_SDIO1_DATA_0,                ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_152_NORFLSH_AD02_SSP3_CLK_SDIO1_CLK,                   ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_153_NORFLSH_AD03_SSP3_FS_SDIO1_DATA_3,                 ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_154_NORFLSH_AD04_VC_PWM_0_KP_COL_IP_0,                 ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_155_NORFLSH_AD05_SSP2_TXD_1_SDIO1_DATA_1,              ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_156_NORFLSH_AD06_SSP2_RXD_1_SDIO1_DATA_2,              ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_157_NORFLSH_AD07_SSP2_FS_1_KP_COL_IP_7,                ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_158_NORFLSH_AD08_SSP2_FS_3_KP_ROW_OP_6_VC_TRSTB,       ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_159_NORFLSH_AD09_VC_GPIO_4_KP_ROW_OP_5_VC_TDO,         ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_160_NORFLSH_AD10_CWS_SYS_REQ3_KP_ROW_OP_4,             ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_161_NORFLSH_AD11_CWS_SYS_REQ2_KP_ROW_OP_3,             ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_162_NORFLSH_AD12_CLKREQ_IN_3_KP_ROW_OP_2_IRD_OSC_10,   ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_163_NORFLSH_AD13_CLKREQ_IN_2_KP_ROW_OP_1_IRD_OSC_9,    ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_164_NORFLSH_AD14_SWDIOTMS_KP_ROW_OP_0_IRD_OSC_8,       ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_165_NORFLSH_AD_5_SWDCLKTCK_UARTB3_UTXD_IRD_OSC_7,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_166_NORFLSH_ADLAT_EN_VC_GPIO_3_KP_COL_IP_1_IRD_OSC_6,  ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_167_NORFLSH_AADLAT_EN_VC_GPIO_2_KP_COL_IP_2_IRD_OSC_5, ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_168_NORFLSH_ADDR16_PWM_O_5_IRD_OSC_4,                  ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_169_NORFLSH_ADDR17_PWM_O_2_IRD_OSC_3,                  ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_170_NORFLSH_ADDR18_PWM_O_1_IRD_OSC_2,                  ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_171_NORFLSH_ADDR19_VC_GPIO_1_PWM_O_0_IRD_OSC_1,        ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_172_NORFLSH_ADDR20_SSP2_TXD_0_KP_COL_IP_3_IRD_OSC_0,   ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_173_NORFLSH_ADDR21_SSP2_RXD_0_KP_COL_IP_4_VC_TDI,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_174_NORFLSH_ADDR22_SSP2_CLK_KP_COL_IP_5_VC_TCK,        ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_175_NORFLSH_ADDR23_SSP2_FS_0_KP_COL_IP_6_VC_TMS,       ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_176_NORFLSH_OE_N_CLKOUT_3,                             ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_177_NORFLSH_CE0_N_CWS_SYS_REQ1_CLKOUT_2,               ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_178_NORFLSH_CE1_N_VC_GPIO_0_UARTB3_URXD,               ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_179_NORFLSH_WE_N,                                      ALT01, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t pm_debugList[] =
{
   {GPIOMUX_ENTRY(GPIO_86_SDIO2_WP_VC_TDO_SDIO3_CMD_VC_SPI_MOSI_PM_DEBUG3,           ALT06, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_87_SDIO2_DATA_4_VC_TDI_SDIO3_DATA_0_VC_SPI_MISO_PM_DEBUG2,    ALT06, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_88_SDIO2_DATA_5_VC_TRSTB_SDIO3_DATA_1_VC_SPI_CE0_N_PM_DEBUG1, ALT06, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_89_SDIO2_DATA_6_VC_TMS_SDIO3_DATA_2_VC_SPI_CE1_N_PM_DEBUG0,   ALT06, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t pmu_i2cList[] =
{
   {GPIOMUX_ENTRY(GPIO_60_PMU_SDA, ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_61_PMU_SCL, ALT01, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t pwm_muxaList[] =
{
   {GPIOMUX_ENTRY(GPIO_145_SIM_DATA_PWM_O_2_VC_GPIO_7, ALT02, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t pwm_muxcList[] =
{
   {GPIOMUX_ENTRY(GPIO_171_NORFLSH_ADDR19_VC_GPIO_1_PWM_O_0_IRD_OSC_1, ALT03, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t sdio1List[] =
{
   {GPIOMUX_ENTRY(GPIO_148_NORFLSH_CLK_N_SDIO4_DATA_6_SDIO1_DATA_2, ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_149_NORFLSH_RDY_SDIO4_DATA_7_SDIO1_DATA_1,   ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_150_NORFLSH_AD00_SSP3_TXD_SDIO1_CMD,         ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_151_NORFLSH_AD01_SSP3_RXD_SDIO1_DATA_0,      ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_152_NORFLSH_AD02_SSP3_CLK_SDIO1_CLK,         ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_153_NORFLSH_AD03_SSP3_FS_SDIO1_DATA_3,       ALT03, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t sdio2List[] =
{
   {GPIOMUX_ENTRY(GPIO_87_SDIO2_DATA_4_VC_TDI_SDIO3_DATA_0_VC_SPI_MISO_PM_DEBUG2,       ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_88_SDIO2_DATA_5_VC_TRSTB_SDIO3_DATA_1_VC_SPI_CE0_N_PM_DEBUG1,    ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_89_SDIO2_DATA_6_VC_TMS_SDIO3_DATA_2_VC_SPI_CE1_N_PM_DEBUG0,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_90_SDIO2_DATA_7_VC_TESTDEBUG_CLK_SDIO3_DATA_3_AFCPDM,            ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_91_SDIO2_CLK_PTI_CLK,                                            ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_92_SDIO2_CMD_UARTB2_URXD,                                        ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_93_SDIO2_DATA_0_PTI_DAT0,                                        ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_94_SDIO2_DATA_1_PTI_DAT1,                                        ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_95_SDIO2_DATA_2_SWDIOTMS_PTI_DAT2,                               ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_96_SDIO2_DATA_3_SWDCLKTCK_PTI_DAT3,                              ALT01, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t sdio3List[] =
{
   {GPIOMUX_ENTRY(GPIO_99_NAND_AD0_SDIO3_DATA_0_SSP1_RXD_DEBUG_BUS15,                   ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_100_NAND_AD1_SDIO3_CLK_SSP1_CLK_DEBUG_BUS14,                     ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_101_NAND_AD2_SDIO3_DATA_3_SSP1_FS_WCDMA_UART_TXD_DEBUG_BUS13,    ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_102_NAND_AD3_SDIO3_CMD_SSP1_TXD_WCDMA_UART_RXD_DEBUG_BUS12,      ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_103_NAND_AD4_SDIO3_DATA_1_UARTB_URXD_WCDMA_DEBUG_7_DEBUG_BUS11,  ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_104_NAND_AD5_SDIO3_DATA_2_UARTB_UCTSN_WCDMA_DEBUG_6_DEBUG_BUS10, ALT02, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t ssp0List[] =
{
   {GPIOMUX_ENTRY(GPIO_81_SSP0_TXD_KP_ROW_OP_7_UARTB2_UCTSN_RFGPO_0, ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_82_SSP0_RXD_KP_ROW_OP_6_UARTB2_URTSN_RFGPO_1, ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_83_SSP0_CLK_KP_ROW_OP_5_UARTB2_UTXD_RFGPO_2,  ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_84_SSP0_FS_KP_ROW_OP_4_UARTB2_URXD_RFGPO_3,   ALT01, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t ssp2List[] =
{
   {GPIOMUX_ENTRY(GPIO_73_SSP2_TXD_0_UARTB4_UCTSN_ACWAKE_WCDMA_DEBUG_3,  ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_74_SSP2_RXD_0_UARTB4_URTSN_ACREADY_WCDMA_DEBUG_2, ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_75_SSP2_CLK_UARTB4_UTXD_ACFLAG_WCDMA_DEBUG_1,     ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_76_SSP2_FS_0_UARTB4_URXD_ACDATA_WCDMA_DEBUG_0,    ALT01, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t ssp3_muxaList[] =
{
   {GPIOMUX_ENTRY(GPIO_64_SSP3_EXTCLK_VC_TESTDEBUG_CLK_VC_SPI_SCLK, ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_65_SSP3_TXD_VC_I2S_SDO_VC_SPI_MOSI,          ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_66_SSP3_RXD_VC_I2S_SDI_VC_SPI_MISO,          ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_67_SSP3_CLK_VC_I2S_SCK_VC_SPI_CE0_N,         ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_68_SSP3_FS_VC_I2S_WSIO_VC_SPI_CE1_N,         ALT01, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t ssp3_muxbList[] =
{
   {GPIOMUX_ENTRY(GPIO_64_SSP3_EXTCLK_VC_TESTDEBUG_CLK_VC_SPI_SCLK, ALT01, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t ssp3_muxcList[] =
{
   {GPIOMUX_ENTRY(GPIO_65_SSP3_TXD_VC_I2S_SDO_VC_SPI_MOSI,  ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_66_SSP3_RXD_VC_I2S_SDI_VC_SPI_MISO,  ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_67_SSP3_CLK_VC_I2S_SCK_VC_SPI_CE0_N, ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_68_SSP3_FS_VC_I2S_WSIO_VC_SPI_CE1_N, ALT01, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t uartbList[] =
{
   {GPIOMUX_ENTRY(GPIO_52_UARTB_UTXD_VC_TCK_SSP1_CLK, ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_53_UARTB_URXD_VC_TMS_SSP1_FS,  ALT01, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t uartb2_muxaList[] =
{
   {GPIOMUX_ENTRY(GPIO_48_UARTB2_UTXD_RTCK_PWM_O_4_AFCPDM, ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_49_UARTB2_URXD_VC_TRSTB_PWM_O_3,    ALT01, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t uartb2_muxbList[] =
{
   {GPIOMUX_ENTRY(GPIO_128_ULPI0_STP_CAWAKE_UARTB2_UTXD_AP_SCLK_I,        ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_129_ULPI0_NXT_CAREADY_UARTB2_URXD_AP_LRCK_I,       ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_130_ULPI0_DIR_CAFLAG_UARTB2_UCTSN_AP_IHF_DATA_I,   ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_131_ULPI0_DATA7_CADATA_UARTB2_URTSN_AP_DAC_DATA_I, ALT03, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t uartb3_muxaList[] =
{
   {GPIOMUX_ENTRY(GPIO_77_SSP1_TXD_KP_ROW_OP_3_UARTB3_UCTSN_WCDMA_SYNC, ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_78_SSP1_RXD_KP_ROW_OP_2_UARTB3_URTSN_WCDMA_CLK3, ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_79_SSP1_CLK_KP_ROW_OP_1_UARTB3_UTXD_WCDMA_CLK2,  ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_80_SSP1_FS_KP_ROW_OP_0_UARTB3_URXD_WCDMA_CLK1,   ALT03, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t uartb3_muxbList[] =
{
   {GPIOMUX_ENTRY(GPIO_132_ULPI0_DATA6_ACWAKE_UARTB3_UTXD_AP_ADC_DATA_O, ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_133_ULPI0_DATA5_ACREADY_UARTB3_URXD_DAC_SCL_EN,   ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_134_ULPI0_DATA4_ACFLAG_UARTB3_UCTSN_IHF_AP_EN,    ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_135_ULPI0_DATA3_ACDATA_UARTB3_URTSN_VIBRA_AP_EN,  ALT03, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t uartb4_muxaList[] =
{
   {GPIOMUX_ENTRY(GPIO_73_SSP2_TXD_0_UARTB4_UCTSN_ACWAKE_WCDMA_DEBUG_3,  ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_74_SSP2_RXD_0_UARTB4_URTSN_ACREADY_WCDMA_DEBUG_2, ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_75_SSP2_CLK_UARTB4_UTXD_ACFLAG_WCDMA_DEBUG_1,     ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_76_SSP2_FS_0_UARTB4_URXD_ACDATA_WCDMA_DEBUG_0,    ALT02, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t uartb4_muxbList[] =
{
   {GPIOMUX_ENTRY(GPIO_136_ULPI0_DATA2_SSP0_TXD_UARTB4_UTXD_HS_AP_EN,         ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_137_ULPI0_DATA1_SSP0_RXD_UARTB4_URXD_EP_AP_EN,         ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_138_ULPI0_DATA0_SSP0_FS_UARTB4_UCTSN_ADC_AP_EN,        ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_139_ULPI0_CLOCK_SSP0_CLK_UARTB4_URTSN_AP_REF_2P4M_CLK, ALT03, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t usb_ulpi0List[] =
{
   {GPIOMUX_ENTRY(GPIO_128_ULPI0_STP_CAWAKE_UARTB2_UTXD_AP_SCLK_I,            ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_129_ULPI0_NXT_CAREADY_UARTB2_URXD_AP_LRCK_I,           ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_130_ULPI0_DIR_CAFLAG_UARTB2_UCTSN_AP_IHF_DATA_I,       ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_131_ULPI0_DATA7_CADATA_UARTB2_URTSN_AP_DAC_DATA_I,     ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_132_ULPI0_DATA6_ACWAKE_UARTB3_UTXD_AP_ADC_DATA_O,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_133_ULPI0_DATA5_ACREADY_UARTB3_URXD_DAC_SCL_EN,        ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_134_ULPI0_DATA4_ACFLAG_UARTB3_UCTSN_IHF_AP_EN,         ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_135_ULPI0_DATA3_ACDATA_UARTB3_URTSN_VIBRA_AP_EN,       ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_136_ULPI0_DATA2_SSP0_TXD_UARTB4_UTXD_HS_AP_EN,         ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_137_ULPI0_DATA1_SSP0_RXD_UARTB4_URXD_EP_AP_EN,         ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_138_ULPI0_DATA0_SSP0_FS_UARTB4_UCTSN_ADC_AP_EN,        ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_139_ULPI0_CLOCK_SSP0_CLK_UARTB4_URTSN_AP_REF_2P4M_CLK, ALT01, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t usb_ulpi1List[] =
{
   {GPIOMUX_ENTRY(GPIO_116_ULPI1_STP_SDIO4_CLK_VC_TE1_IRD_OSC_10,         ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_117_ULPI1_NXT_BSC1_SDA_GP_VC_TE2_IRD_OSC_9,        ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_118_ULPI1_DIR_BSC1_SCL_GP_NORFLSH_WP_IRD_OSC_8,    ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_119_ULPI1_DATA7_SSP2_FS_2_PWM_O_2_IRD_OSC_7,       ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_120_ULPI1_DATA6_SSP2_FS_3_IRD_OSC_6,               ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_121_ULPI1_DATA5_SSP2_TXD_1_IRD_OSC_5,              ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_122_ULPI1_DATA4_SSP2_TXD_0_SDIO3_CMD_IRD_OSC_4,    ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_123_ULPI1_DATA3_SSP2_RXD_0_SDIO3_DATA_0_IRD_OSC_3, ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_124_ULPI1_DATA2_SSP2_RXD_1_SDIO3_DATA_1_IRD_OSC_2, ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_125_ULPI1_DATA1_SSP2_FS_1_SDIO3_DATA_2_IRD_OSC_1,  ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_126_ULPI1_DATA0_SSP2_FS_0_SDIO3_DATA_3_AP_RSTN,    ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_127_ULPI1_CLOCK_SSP2_CLK_SDIO3_CLK_IRD_OSC_0,      ALT01, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t vc_dpi_rgbList[] =
{
   {GPIOMUX_ENTRY(GPIO_20_LCD_PCLK_SWDIOTMS_SDIO1_CLK_VC_PWM_1,         ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_21_LCD_OE_SWDCLKTCK_SDIO1_CMD_CLCD_A_5,          ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_22_LCD_VSYNC_DW_WIRE_1_SDIO1_DATA_0_CLCD_A_4,    ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_23_LCD_HSYNC_PWM_O_2_SDIO1_DATA_1_CLCD_A_3,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_24_LCD_B0_MPHI_DATA_0_KP_COL_IP_5_CLCD_A_2,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_25_LCD_B1_MPHI_DATA_1_KP_COL_IP_4_CLCD_A_1,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_26_LCD_B2_MPHI_DATA_2_SDIO1_DATA_2_CLCD_D_0,     ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_27_LCD_B3_MPHI_DATA_3_SDIO1_DATA_3_CLCD_D_1,     ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_28_LCD_B4_MPHI_DATA_4_WCDMA_UART_TXD_CLCD_D_2,   ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_29_LCD_B5_MPHI_DATA_5_PWM_O_5_CLCD_D_3,          ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_30_LCD_B6_MPHI_DATA_6_KP_COL_IP_7_CLCD_D_4,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_31_LCD_B7_MPHI_DATA_7_KP_COL_IP_6_CLCD_D_5,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_32_LCD_G0_MPHI_DATA_8_KP_COL_IP_3_CLCD_A_0,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_33_LCD_G1_MPHI_DATA_9_KP_COL_IP_2_CLCD_WEN,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_34_LCD_G2_MPHI_DATA_10_PWM_O_2_CLCD_D_6,         ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_35_LCD_G3_MPHI_DATA_11_PWM_O_1_CLCD_D_7,         ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_36_LCD_G4_MPHI_DATA_12_SSP2_TXD_1_CLCD_D_8,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_37_LCD_G5_MPHI_DATA_13_SSP2_RXD_1_CLCD_D_9,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_38_LCD_G6_MPHI_DATA_14_WCDMA_UART_RXD_CLCD_D_10, ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_39_LCD_G7_MPHI_DATA_15_SSP2_FS_1_CLCD_D_11,      ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_40_LCD_R0_MPHI_HAT1_KP_COL_IP_1_CLCD_OEN,        ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_41_LCD_R1_MPHI_HAT0_KP_COL_IP_0_VC_PWM_0,        ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_42_LCD_R2_MPHI_HA0_PWM_O_0_CLCD_D_12,            ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_43_LCD_R3_MPHI_HRD_N_SSP2_TXD_0_CLCD_D_13,       ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_44_LCD_R4_MPHI_HWR_N_SSP2_RXD_0_CLCD_D_14,       ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_45_LCD_R5_MPHI_HCE0_N_SSP2_CLK_CLCD_D_15,        ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_46_LCD_R6_MPHI_HCE1_N_SSP2_FS_2_CLCD_D_16,       ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_47_LCD_R7_MPHI_RUN_SSP2_FS_0_CLCD_D_17,          ALT01, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t vc_gpclkList[] =
{
   {GPIOMUX_ENTRY(GPIO_2_SDIO3_CD_N_VC_GPCLK_1, ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_3_SDIO3_WP_VC_GPCLK_0,   ALT02, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t vc_i2c1List[] =
{
   {GPIOMUX_ENTRY(GPIO_56_VC_CAM1_SDA_BSC1_SDA, ALT01, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_57_VC_CAM1_SCL_BSC1_SCL, ALT01, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t vc_i2sList[] =
{
   {GPIOMUX_ENTRY(GPIO_65_SSP3_TXD_VC_I2S_SDO_VC_SPI_MOSI,  ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_66_SSP3_RXD_VC_I2S_SDI_VC_SPI_MISO,  ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_67_SSP3_CLK_VC_I2S_SCK_VC_SPI_CE0_N, ALT02, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_68_SSP3_FS_VC_I2S_WSIO_VC_SPI_CE1_N, ALT02, TTL, NONE, 08mA, HIGH)}
};

static const gpiomux_pinconfig_t vc_jtagList[] =
{
   {GPIOMUX_ENTRY(GPIO_107_NAND_WEN_SDIO3_DATA_6_VC_TMS_WCDMA_DEBUG_3_DEBUG_BUS07, ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_108_NAND_OEN_SDIO3_DATA_7_VC_TDO_WCDMA_DEBUG_2_DEBUG_BUS06, ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_109_NAND_ALE_SDIO4_DATA_4_VC_TDI_WCDMA_DEBUG_1_DEBUG_BUS05, ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_110_NAND_CLE_SDIO4_DATA_5_VC_TCK_WCDMA_DEBUG_0_DEBUG_BUS04, ALT03, TTL, NONE, 08mA, HIGH)},
   {GPIOMUX_ENTRY(GPIO_111_NAND_RDY1_SDIO4_CMD_VC_TRSTB_WCDMA_SYNC_DEBUG_BUS03,    ALT03, TTL, NONE, 08mA, HIGH)}
};

/*
 * A table of logical groupings of gpio pins. Each group has an associate group enum, and chipreg
 * pin function, and a number of pins, followed by the pin numbers in a list. This table is used
 * by the gpiomux_requestGroup() and gpiomux_freeGroup() functions to check for conflicts
 * and to make chipreg assignments.
 */

const gpiomux_group_t gpiomux_GroupList_BCMHANA_FPGA[] =
{
   { gpiomux_group_i2c,           ARRAY_LEN(arm_i2c0List),        arm_i2c0List,    0 },
   { gpiomux_group_i2c,           ARRAY_LEN(arm_i2c1List),        arm_i2c1List,    1 },
   { gpiomux_group_i2c,           ARRAY_LEN(hdmi_i2cList),        hdmi_i2cList,    2 },
   { gpiomux_group_i2c,           ARRAY_LEN(pmu_i2cList),         pmu_i2cList,     3 },
   { gpiomux_group_i2c,           ARRAY_LEN(vc_i2c1List),         vc_i2c1List,     4 },
   { gpiomux_group_clk_out,       ARRAY_LEN(clk_outList),         clk_outList,     0 },
   { gpiomux_group_digital_mic,   ARRAY_LEN(digital_micList),     digital_micList, 0 },
   { gpiomux_group_hsi,           ARRAY_LEN(hsiList),             hsiList,         0 },
   { gpiomux_group_keypad,        ARRAY_LEN(keypad_7x4List),      keypad_7x4List,  0 },
   { gpiomux_group_keypad,        ARRAY_LEN(keypad_7x8List),      keypad_7x8List,  1 },
   { gpiomux_group_lcd_te,        ARRAY_LEN(lcd_teList),          lcd_teList,      0 },
   { gpiomux_group_mphi,          ARRAY_LEN(mphiList),            mphiList,        0 },
   { gpiomux_group_nand,          ARRAY_LEN(nandList),            nandList,        0 },
   { gpiomux_group_nor,           ARRAY_LEN(norList),             norList,         0 },
   { gpiomux_group_pm_debug,      ARRAY_LEN(pm_debugList),        pm_debugList,    0 },
   { gpiomux_group_pwm,           ARRAY_LEN(pwm_muxaList),        pwm_muxaList,    0 },
   { gpiomux_group_pwm,           ARRAY_LEN(pwm_muxcList),        pwm_muxcList,    1 },
   { gpiomux_group_sdio,          ARRAY_LEN(sdio1List),           sdio1List,       0 },
   { gpiomux_group_sdio,          ARRAY_LEN(sdio2List),           sdio2List,       1 },
   { gpiomux_group_sdio,          ARRAY_LEN(sdio3List),           sdio3List,       2 },
   { gpiomux_group_ssp,           ARRAY_LEN(ssp0List),            ssp0List,        0 },
   { gpiomux_group_ssp,           ARRAY_LEN(ssp2List),            ssp2List,        1 },
   { gpiomux_group_ssp,           ARRAY_LEN(ssp3_muxaList),       ssp3_muxaList,   2 },
   { gpiomux_group_ssp,           ARRAY_LEN(ssp3_muxbList),       ssp3_muxbList,   3 },
   { gpiomux_group_ssp,           ARRAY_LEN(ssp3_muxcList),       ssp3_muxcList,   4 },
   { gpiomux_group_uart,          ARRAY_LEN(uartbList),           uartbList,       0 },
   { gpiomux_group_uart,          ARRAY_LEN(uartb2_muxaList),     uartb2_muxaList, 1 },
   { gpiomux_group_uart,          ARRAY_LEN(uartb2_muxbList),     uartb2_muxbList, 2 },
   { gpiomux_group_uart,          ARRAY_LEN(uartb3_muxaList),     uartb3_muxaList, 3 },
   { gpiomux_group_uart,          ARRAY_LEN(uartb3_muxbList),     uartb3_muxbList, 4 },
   { gpiomux_group_uart,          ARRAY_LEN(uartb4_muxaList),     uartb4_muxaList, 5 },
   { gpiomux_group_uart,          ARRAY_LEN(uartb4_muxbList),     uartb4_muxbList, 6 },
   { gpiomux_group_usb_ulpi,      ARRAY_LEN(usb_ulpi0List),       usb_ulpi0List,   0 },
   { gpiomux_group_usb_ulpi,      ARRAY_LEN(usb_ulpi1List),       usb_ulpi1List,   1 },
   { gpiomux_group_vc_dpi_rgb,    ARRAY_LEN(vc_dpi_rgbList),      vc_dpi_rgbList,  0 },
   { gpiomux_group_vc_gpclk,      ARRAY_LEN(vc_gpclkList),        vc_gpclkList,    0 },
   { gpiomux_group_vc_i2s,        ARRAY_LEN(vc_i2sList),          vc_i2sList,      0 },
   { gpiomux_group_vc_jtag,       ARRAY_LEN(vc_jtagList),         vc_jtagList,     0 },
};

const unsigned int gpiomux_GroupListEntries_BCMHANA_FPGA = ARRAY_LEN(gpiomux_GroupList_BCMHANA_FPGA);

