obj-$(CONFIG_VC_VCOS)	+= ../interface/vcos/linuxkernel/
obj-$(CONFIG_VC_MEM)	+= vc_mem/
obj-$(CONFIG_VC_VCEB)	+= ../interface/vceb/host/linux/
obj-$(CONFIG_VC_VCHIQ)	+= ../interface/vchiq_arm/

obj-$(CONFIG_VC_HNFO)	+= vc_hnfo/
obj-$(CONFIG_VC_DNFO)	+= vc_dnfo/
obj-$(CONFIG_VC_OMX)	+= vc_omx/
obj-$(CONFIG_VC_FB)	+= vc_fb/
obj-$(CONFIG_VC_OVL)	+= vc_ovl/
obj-$(CONFIG_VC_SM)	+= vc_sm/

header-y += include/
