/****************************************************************************
*
*     Copyright (c) 2007-2008 Broadcom Corporation
*
*   Unless you and Broadcom execute a separate written software license 
*   agreement governing use of this software, this software is licensed to you 
*   under the terms of the GNU General Public License version 2, available 
*    at http://www.gnu.org/licenses/old-licenses/gpl-2.0.html (the "GPL"). 
*
*   Notwithstanding the above, under no circumstances may you combine this 
*   software in any way with any other Broadcom software provided under a license 
*   other than the GPL, without Broadcom's express prior written consent.
*
****************************************************************************/
/**
*
*   @file   capi2_reqrep.c
*
*   @brief  This file define the request/respose structure for 
*	serialize/deserialize.
*
****************************************************************************/
#include "capi2_reqrep.h"
#include "capi2_taskmsgs.h"
#include "capi2_phonectrl_api.h"
#include "capi2_phonectrl_msg.h"
#include "capi2_gen_cp_api.h"

#ifndef RPC_INCLUDED
#include "capi2_ipc.h"

Result_t CAPI2_GenCommsMsgHnd(CAPI2_ReqRep_t* reqRep, CAPI2_ReqRep_t* rsp);
void CAPI2_LogBinaryData(MsgType_t msgId, UInt8* stream , UInt32 len);
UInt32 CAPI2_GetMaxPktSize(PACKET_InterfaceType_t interfaceType, UInt32 size);

XDR_ENUM_DECLARE(MsgType_t)
XDR_ENUM_DECLARE(CAPI2_MsgType_t)
XDR_ENUM_DECLARE(CAPI2_Direction_t)
struct xdr_discrim* xdr_fast_lookup(enum_t dscm);
bool_t xdr_CAPI2_ReqRep_t(XDR *xdrs, CAPI2_ReqRep_t* reqRep);
bool_t xdr_build_lookup(void);

#ifdef XDR_DETAIL_LOG_ENABLED
#define MAX_LOG_BUFFER_SIZE 4000 //~4.5K
static char log_buf[MAX_LOG_BUFFER_SIZE+100];
#endif
#endif

#define DEFINE_XDR_UNION_MAPPING
#define _T(a) a

#ifdef FUSE_COMMS_PROCESSOR
#define REMOTE_AP_NOT_RESPONDING 0
#else
#define REMOTE_CP_NOT_RESPONDING 0
#endif

#ifndef RPC_INCLUDED
extern Capi2ProcessorType_t gCapi2Type;
 
bool_t
xdr_default_proc(XDR *xdrs, void *unp)
{
	if (xdrs || unp) { }  //fixes compiler warnings
	return(TRUE);
}
#endif

/* TODO: Hookup the serialzation/deserialization function with the message Id */
/* TODO: DONOT Forget to increment the TABLE_SIZE */
//#define TABLE_SIZE	(sizeof(CAPI2_ReqRep_dscrm) / sizeof(xdr_discrim))

#ifndef RPC_INCLUDED
#define _D(a) (int)a 
#define REQRSP_MSG_EXT(unsize,capi2_proc,ptr_proc,maxMsgSize)	unsize, (capi2_proc_t)capi2_proc, (xdrproc_t)ptr_proc, maxMsgSize
#else
#define _D(a) a
#define REQRSP_MSG_EXT(unsize,capi2_proc,ptr_proc,maxMsgSize)	unsize, maxMsgSize
#endif

#ifndef RPC_INCLUDED
static const struct xdr_discrim CAPI2_ReqRep_dscrm[] = {
#else
static const RPC_XdrInfo_t CAPI2_ReqRep_dscrm[] = {
#endif
	
	/* Add phonebook message serialize/deserialize routine map */
#ifndef RPC_INCLUDED
	{ _D(MSG_CAPI2_ACK_RSP),_T("MSG_CAPI2_ACK_RSP"), (xdrproc_t)xdr_CAPI2_Ack_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
#endif
	{ _D(MSG_PBK_GETALPHA_REQ),_T("MSG_PBK_GETALPHA_REQ"), (xdrproc_t)xdr_CAPI2_PBK_GetAlpha_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PBK_GETALPHA_RSP),_T("MSG_PBK_GETALPHA_RSP"), (xdrproc_t)xdr_PBK_API_Name_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PBK_ISEMERGENCYCALLNUMBER_REQ),_T("MSG_PBK_ISEMERGENCYCALLNUMBER_REQ"), (xdrproc_t)xdr_CAPI2_PBK_IsEmergencyNumber_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PBK_ISEMERGENCYCALLNUMBER_RSP),_T("MSG_PBK_ISEMERGENCYCALLNUMBER_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PBK_ISPARTIALEMERGENCYCALLNUMBER_REQ),_T("MSG_PBK_ISPARTIALEMERGENCYCALLNUMBER_REQ"), (xdrproc_t)xdr_CAPI2_PBK_IsPartialEmergencyNumber_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PBK_ISPARTIALEMERGENCYCALLNUMBER_RSP),_T("MSG_PBK_ISPARTIALEMERGENCYCALLNUMBER_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PBK_SENDINFOREQ_REQ),_T("MSG_PBK_SENDINFOREQ_REQ"), (xdrproc_t)XDR_ENUM_DEF(PBK_Id_t), REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_GET_PBK_INFO_RSP),_T("MSG_GET_PBK_INFO_RSP"), (xdrproc_t)xdr_CAPI2_PBK_Info_t, REQRSP_MSG_EXT(0,NULL,NULL,35000) },
	{ _D(MSG_SENDFINDALPHAMATCHMULTIPLEREQ_REQ),_T("MSG_SENDFINDALPHAMATCHMULTIPLEREQ_REQ"), (xdrproc_t)xdr_CAPI2_PBK_SendFindAlphaMatchMultipleReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PBK_ENTRY_DATA_RSP),_T("MSG_PBK_ENTRY_DATA_RSP"), (xdrproc_t)xdr_CAPI2_PBK_PBK_ENTRY_DATA_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,3000) },
	{ _D(MSG_SENDFINDALPHAMATCHONEREQ_REQ),_T("MSG_SENDFINDALPHAMATCHONEREQ_REQ"), (xdrproc_t)xdr_CAPI2_PBK_SendFindAlphaMatchOneReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	/* MSG_PBK_ENTRY_DATA_RSP */
	/* MSG_PBK_ISREADY_REQ */
	{ _D(MSG_PBK_ISREADY_REQ),_T("MSG_PBK_ISREADY_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PBK_ISREADY_RSP),_T("MSG_PBK_ISREADY_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SENDREADENTRYREQ_REQ),_T("MSG_SENDREADENTRYREQ_REQ"), (xdrproc_t)xdr_CAPI2_PBK_SendReadEntryReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	/* MSG_PBK_ENTRY_DATA_RSP */
	{ _D(MSG_PBK_SENDWRITEENTRYREQ_REQ),_T("MSG_PBK_SENDWRITEENTRYREQ_REQ"), (xdrproc_t)xdr_CAPI2_PBK_SendWriteEntryReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PBK_SENDUPDATEENTRYREQ_REQ),_T("MSG_PBK_SENDUPDATEENTRYREQ_REQ"), (xdrproc_t)xdr_CAPI2_PBK_SendUpdateEntryReq_t, REQRSP_MSG_EXT(0,NULL,NULL,25000) },
	{ _D(MSG_WRT_PBK_ENTRY_RSP),_T("MSG_WRT_PBK_ENTRY_RSP"), (xdrproc_t)xdr_CAPI2_PBK_WRITE_ENTRY_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PBK_SENDISNUMDIALLABLEREQ),_T("MSG_PBK_SENDISNUMDIALLABLEREQ"), (xdrproc_t)xdr_CAPI2_PBK_SendIsNumDiallableReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CHK_PBK_DIALLED_NUM_RSP),_T("MSG_CHK_PBK_DIALLED_NUM_RSP"), (xdrproc_t)xdr_CAPI2_PBK_CHK_NUM_DIALLABLE_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PBK_ISNUMDIALLABLE_REQ),_T("MSG_PBK_ISNUMDIALLABLE_REQ"), (xdrproc_t)xdr_CAPI2_PBK_IsNumDiallable_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PBK_ISNUMDIALABLE_RSP),_T("MSG_PBK_ISNUMDIALABLE_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PBK_ISUSSDDIALLABLE_REQ),_T("MSG_PBK_ISUSSDDIALLABLE_REQ"), (xdrproc_t)xdr_CAPI2_PBK_IsUssdDiallable_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PBK_ISUSSDDIALLABLE_RSP),_T("MSG_PBK_ISUSSDDIALLABLE_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_WRT_PBK_ENTRY_IND),_T("MSG_WRT_PBK_ENTRY_IND"), (xdrproc_t)xdr_CAPI2_PBK_WRITE_ENTRY_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PBK_READY_IND),_T("MSG_PBK_READY_IND"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	/* Add SMS message serialize/deserialize routine map */
	{ _D(MSG_SMS_SENDSMSSRVCENTERNUMBERUPDATE_REQ),_T("MSG_SMS_SENDSMSSRVCENTERNUMBERUPDATE_REQ"), (xdrproc_t)xdr_CAPI2_SMS_SendSMSSrvCenterNumberUpdateReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	/* MSG_SMS_SENDSMSSRVCENTERNUMBERUPDATEREQ_RSP */
	{ _D(MSG_SMS_SENDSMSSRVCENTERNUMBERUPDATEREQ_RSP),_T("MSG_SMS_SENDSMSSRVCENTERNUMBERUPDATEREQ_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETSMSSRVCENTERNUMBER_REQ),_T("MSG_SMS_GETSMSSRVCENTERNUMBER_REQ"), (xdrproc_t)xdr_CAPI2_SMS_GetSMSrvCenterNumber_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETSMSSRVCENTERNUMBER_RSP),_T("MSG_SMS_GETSMSSRVCENTERNUMBER_RSP"), (xdrproc_t)xdr_CAPI2_SMS_GetSMSrvCenterNumberRsp_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETSIMSMSCAPACITYEXCEEDEDFLAG_REQ),_T("MSG_SMS_GETSIMSMSCAPACITYEXCEEDEDFLAG_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETSIMSMSCAPACITYEXCEEDEDFLAG_RSP),_T("MSG_SMS_GETSIMSMSCAPACITYEXCEEDEDFLAG_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_ISSMSSERVICEAVAIL_REQ),_T("MSG_SMS_ISSMSSERVICEAVAIL_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_ISSMSSERVICEAVAIL_RSP),_T("MSG_SMS_ISSMSSERVICEAVAIL_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETSMSSTOREDSTATE_REQ),_T("MSG_SMS_GETSMSSTOREDSTATE_REQ"), (xdrproc_t)xdr_CAPI2_SMS_GetSmsStoredState_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETSMSSTOREDSTATE_RSP),_T("MSG_SMS_GETSMSSTOREDSTATE_RSP"), (xdrproc_t)XDR_ENUM_DEF(SIMSMSMesgStatus_t), REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_WRITESMSPDU_REQ),_T("MSG_SMS_WRITESMSPDU_REQ"), (xdrproc_t)xdr_CAPI2_SMS_WriteSMSPduReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_WRITE_RSP_IND),_T("MSG_SMS_WRITE_RSP_IND"), (xdrproc_t)xdr_CAPI2_SmsIncMsgStoredResult_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_WRITESMSREQ_REQ),_T("MSG_SMS_WRITESMSREQ_REQ"), (xdrproc_t)xdr_CAPI2_SMS_WriteSMSReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SENDSMSREQ_REQ),_T("MSG_SMS_SENDSMSREQ_REQ"), (xdrproc_t)xdr_CAPI2_SMS_SendSMSReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SUBMIT_RSP),_T("MSG_SMS_SUBMIT_RSP"), (xdrproc_t)xdr_CAPI2_SmsSubmitRspMsg_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SENDSMSPDUREQ_REQ),_T("MSG_SMS_SENDSMSPDUREQ_REQ"), (xdrproc_t)xdr_CAPI2_SMS_SendSMSPduReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SENDSTOREDSMSREQ_REQ),_T("MSG_SMS_SENDSTOREDSMSREQ_REQ"), (xdrproc_t)xdr_CAPI2_SMS_SendStoredSmsReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_WRITESMSPDUTOSIM_REQ),_T("MSG_SMS_WRITESMSPDUTOSIM_REQ"), (xdrproc_t)xdr_CAPI2_SMS_WriteSMSPduToSIMReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETLASTTPMR_REQ),_T("MSG_SMS_GETLASTTPMR_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETLASTTPMR_RSP),_T("MSG_SMS_GETLASTTPMR_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETSMSTXPARAMS_REQ),_T("MSG_SMS_GETSMSTXPARAMS_REQ"), (xdrproc_t)xdr_CAPI2_SMS_GetSmsTxParams_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETSMSTXPARAMS_RSP),_T("MSG_SMS_GETSMSTXPARAMS_RSP"), (xdrproc_t)xdr_SmsTxParam_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETTXPARAMINTEXTMODE_REQ),_T("MSG_SMS_GETTXPARAMINTEXTMODE_REQ"), (xdrproc_t)xdr_CAPI2_SMS_GetTxParamInTextMode_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETTXPARAMINTEXTMODE_RSP),_T("MSG_SMS_GETTXPARAMINTEXTMODE_RSP"), (xdrproc_t)xdr_SmsTxTextModeParms_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSTXPARAMPROCID_REQ),_T("MSG_SMS_SETSMSTXPARAMPROCID_REQ"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSTXPARAMPROCID_RSP),_T("MSG_SMS_SETSMSTXPARAMPROCID_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSTXPARAMCODINGTYPE_REQ),_T("MSG_SMS_SETSMSTXPARAMCODINGTYPE_REQ"), (xdrproc_t)xdr_CAPI2_SMS_SetSmsTxParamCodingType_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSTXPARAMCODINGTYPE_RSP),_T("MSG_SMS_SETSMSTXPARAMCODINGTYPE_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSTXPARAMVALIDPERIOD_REQ),_T("MSG_SMS_SETSMSTXPARAMVALIDPERIOD_REQ"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSTXPARAMVALIDPERIOD_RSP),_T("MSG_SMS_SETSMSTXPARAMVALIDPERIOD_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSTXPARAMCOMPRESSION_REQ),_T("MSG_SMS_SETSMSTXPARAMCOMPRESSION_REQ"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSTXPARAMCOMPRESSION_RSP),_T("MSG_SMS_SETSMSTXPARAMCOMPRESSION_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSTXPARAMREPLYPATH_REQ),_T("MSG_SMS_SETSMSTXPARAMREPLYPATH_REQ"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSTXPARAMREPLYPATH_RSP),_T("MSG_SMS_SETSMSTXPARAMREPLYPATH_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSTXPARAMUSERDATAHDRIND_REQ),_T("MSG_SMS_SETSMSTXPARAMUSERDATAHDRIND_REQ"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSTXPARAMUSERDATAHDRIND_RSP),_T("MSG_SMS_SETSMSTXPARAMUSERDATAHDRIND_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSTXPARAMSTATUSRPTREQFLAG_REQ),_T("MSG_SMS_SETSMSTXPARAMSTATUSRPTREQFLAG_REQ"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSTXPARAMSTATUSRPTREQFLAG_RSP),_T("MSG_SMS_SETSMSTXPARAMSTATUSRPTREQFLAG_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSTXPARAMREJDUPL_REQ),_T("MSG_SMS_SETSMSTXPARAMREJDUPL_REQ"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSTXPARAMREJDUPL_RSP),_T("MSG_SMS_SETSMSTXPARAMREJDUPL_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_DELETESMSMSGBYINDEX_REQ),_T("MSG_SMS_DELETESMSMSGBYINDEX_REQ"), (xdrproc_t)xdr_CAPI2_SMS_DeleteSmsMsgByIndexReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SIM_SMS_STATUS_UPD_RSP),_T("MSG_SIM_SMS_STATUS_UPD_RSP"), (xdrproc_t)xdr_CAPI2_SmsMsgDeleteResult_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_READSMSMSG_REQ),_T("MSG_SMS_READSMSMSG_REQ"), (xdrproc_t)xdr_CAPI2_SMS_ReadSmsMsgReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMSCB_READ_RSP),_T("MSG_SMSCB_READ_RSP"), (xdrproc_t)xdr_CAPI2_SIM_SMS_DATA_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SIM_SMS_DATA_RSP),_T("MSG_SIM_SMS_DATA_RSP"), (xdrproc_t)xdr_CAPI2_SmsSimMsg_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_LISTSMSMSG_REQ),_T("MSG_SMS_LISTSMSMSG_REQ"), (xdrproc_t)xdr_CAPI2_SMS_ListSmsMsgReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETNEWMSGDISPLAYPREF_REQ),_T("MSG_SMS_SETNEWMSGDISPLAYPREF_REQ"), (xdrproc_t)xdr_CAPI2_SMS_SetNewMsgDisplayPref_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETNEWMSGDISPLAYPREF_RSP),_T("MSG_SMS_SETNEWMSGDISPLAYPREF_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETNEWMSGDISPLAYPREF_REQ),_T("MSG_SMS_GETNEWMSGDISPLAYPREF_REQ"), (xdrproc_t)XDR_ENUM_DEF(NewMsgDisplayPref_t), REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETNEWMSGDISPLAYPREF_RSP),_T("MSG_SMS_GETNEWMSGDISPLAYPREF_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSPREFSTORAGE_REQ),_T("MSG_SMS_SETSMSPREFSTORAGE_REQ"), (xdrproc_t)XDR_ENUM_DEF(SmsStorage_t), REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSPREFSTORAGE_RSP),_T("MSG_SMS_SETSMSPREFSTORAGE_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETSMSPREFSTORAGE_REQ),_T("MSG_SMS_GETSMSPREFSTORAGE_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETSMSPREFSTORAGE_RSP),_T("MSG_SMS_GETSMSPREFSTORAGE_RSP"), (xdrproc_t)XDR_ENUM_DEF(SmsStorage_t), REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETSMSSTORAGESTATUS_REQ),_T("MSG_SMS_GETSMSSTORAGESTATUS_REQ"), (xdrproc_t)XDR_ENUM_DEF(SmsStorage_t), REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETSMSSTORAGESTATUS_RSP),_T("MSG_SMS_GETSMSSTORAGESTATUS_RSP"), (xdrproc_t)xdr_CAPI2_SMS_GetSMSStorageStatus_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SAVESMSSERVICEPROFILE_REQ),_T("MSG_SMS_SAVESMSSERVICEPROFILE_REQ"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SAVESMSSERVICEPROFILE_RSP),_T("MSG_SMS_SAVESMSSERVICEPROFILE_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_RESTORESMSSERVICEPROFILE_REQ),_T("MSG_SMS_RESTORESMSSERVICEPROFILE_REQ"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_RESTORESMSSERVICEPROFILE_RSP),_T("MSG_SMS_RESTORESMSSERVICEPROFILE_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETCELLBROADCASTMSGTYPE_REQ),_T("MSG_SMS_SETCELLBROADCASTMSGTYPE_REQ"), (xdrproc_t)xdr_CAPI2_SMS_SetCellBroadcastMsgTypeReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_CB_START_STOP_RSP),_T("MSG_SMS_CB_START_STOP_RSP"), (xdrproc_t)xdr_CAPI2_SmsCBMsgRspType_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_CBALLOWALLCHNLREQ_REQ),_T("MSG_SMS_CBALLOWALLCHNLREQ_REQ"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_CBALLOWALLCHNLREQ_RSP),_T("MSG_SMS_CBALLOWALLCHNLREQ_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_ADDCELLBROADCASTCHNLREQ_REQ),_T("MSG_SMS_ADDCELLBROADCASTCHNLREQ_REQ"), (xdrproc_t)xdr_xdr_string_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_ADDCELLBROADCASTCHNLREQ_RSP),_T("MSG_SMS_ADDCELLBROADCASTCHNLREQ_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_REMOVECELLBROADCASTCHNLREQ_REQ),_T("MSG_SMS_REMOVECELLBROADCASTCHNLREQ_REQ"), (xdrproc_t)xdr_xdr_string_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_REMOVECELLBROADCASTCHNLREQ_RSP),_T("MSG_SMS_REMOVECELLBROADCASTCHNLREQ_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_REMOVEALLCBCHNLFROMSEARCHLIST_REQ),_T("MSG_SMS_REMOVEALLCBCHNLFROMSEARCHLIST_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_REMOVEALLCBCHNLFROMSEARCHLIST_RSP),_T("MSG_SMS_REMOVEALLCBCHNLFROMSEARCHLIST_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETCBMI_REQ),_T("MSG_SMS_GETCBMI_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETCBMI_RSP),_T("MSG_SMS_GETCBMI_RSP"), (xdrproc_t)xdr_SMS_CB_MSG_IDS_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETCBLANGUAGE_REQ),_T("MSG_SMS_GETCBLANGUAGE_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETCBLANGUAGE_RSP),_T("MSG_SMS_GETCBLANGUAGE_RSP"), (xdrproc_t)xdr_T_MN_CB_LANGUAGES, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_ADDCELLBROADCASTLANGREQ_REQ),_T("MSG_SMS_ADDCELLBROADCASTLANGREQ_REQ"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_ADDCELLBROADCASTLANGREQ_RSP),_T("MSG_SMS_ADDCELLBROADCASTLANGREQ_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_REMOVECELLBROADCASTLANGREQ_REQ),_T("MSG_SMS_REMOVECELLBROADCASTLANGREQ_REQ"), (xdrproc_t)xdr_xdr_string_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_REMOVECELLBROADCASTLANGREQ_RSP),_T("MSG_SMS_REMOVECELLBROADCASTLANGREQ_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_STARTRECEIVINGCELLBROADCAST_REQ),_T("MSG_SMS_STARTRECEIVINGCELLBROADCAST_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_STOPRECEIVINGCELLBROADCAST_REQ),_T("MSG_SMS_STOPRECEIVINGCELLBROADCAST_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETCBIGNOREDUPLFLAG_REQ),_T("MSG_SMS_SETCBIGNOREDUPLFLAG_REQ"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETCBIGNOREDUPLFLAG_RSP),_T("MSG_SMS_SETCBIGNOREDUPLFLAG_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETCBIGNOREDUPLFLAG_REQ),_T("MSG_SMS_GETCBIGNOREDUPLFLAG_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETCBIGNOREDUPLFLAG_RSP),_T("MSG_SMS_GETCBIGNOREDUPLFLAG_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETVMINDONOFF_REQ),_T("MSG_SMS_SETVMINDONOFF_REQ"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETVMINDONOFF_RSP),_T("MSG_SMS_SETVMINDONOFF_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_ISVMINDENABLED_REQ),_T("MSG_SMS_ISVMINDENABLED_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_ISVMINDENABLED_RSP),_T("MSG_SMS_ISVMINDENABLED_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETVMWAITINGSTATUS_REQ),_T("MSG_SMS_GETVMWAITINGSTATUS_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETVMWAITINGSTATUS_RSP),_T("MSG_SMS_GETVMWAITINGSTATUS_RSP"), (xdrproc_t)xdr_SmsVoicemailInd_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETNUMOFVMSCNUMBER_REQ),_T("MSG_SMS_GETNUMOFVMSCNUMBER_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETNUMOFVMSCNUMBER_RSP),_T("MSG_SMS_GETNUMOFVMSCNUMBER_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETVMSCNUMBER_REQ),_T("MSG_SMS_GETVMSCNUMBER_REQ"), (xdrproc_t)XDR_ENUM_DEF(SIM_MWI_TYPE_t), REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETVMSCNUMBER_RSP),_T("MSG_SMS_GETVMSCNUMBER_RSP"), (xdrproc_t)xdr_SmsAddress_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_UPDATEVMSCNUMBERREQ_REQ),_T("MSG_SMS_UPDATEVMSCNUMBERREQ_REQ"), (xdrproc_t)xdr_CAPI2_SMS_UpdateVmscNumberReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_UPDATEVMSCNUMBERREQ_RSP),_T("MSG_SMS_UPDATEVMSCNUMBERREQ_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETSMSBEARERPREFERENCE_REQ),_T("MSG_SMS_GETSMSBEARERPREFERENCE_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETSMSBEARERPREFERENCE_RSP),_T("MSG_SMS_GETSMSBEARERPREFERENCE_RSP"), (xdrproc_t)XDR_ENUM_DEF(SMS_BEARER_PREFERENCE_t), REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSBEARERPREFERENCE_REQ),_T("MSG_SMS_SETSMSBEARERPREFERENCE_REQ"), (xdrproc_t)XDR_ENUM_DEF(SMS_BEARER_PREFERENCE_t), REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSBEARERPREFERENCE_RSP),_T("MSG_SMS_SETSMSBEARERPREFERENCE_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSREADSTATUSCHANGEMODE_REQ),_T("MSG_SMS_SETSMSREADSTATUSCHANGEMODE_REQ"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSREADSTATUSCHANGEMODE_RSP),_T("MSG_SMS_SETSMSREADSTATUSCHANGEMODE_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETSMSREADSTATUSCHANGEMODE_REQ),_T("MSG_SMS_GETSMSREADSTATUSCHANGEMODE_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETSMSREADSTATUSCHANGEMODE_RSP),_T("MSG_SMS_GETSMSREADSTATUSCHANGEMODE_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_CHANGESTATUSREQ_REQ),_T("MSG_SMS_CHANGESTATUSREQ_REQ"), (xdrproc_t)xdr_CAPI2_SMS_ChangeSmsStatusReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_CHANGESTATUSREQ_RSP),_T("MSG_SMS_CHANGESTATUSREQ_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SENDMESTOREDSTATUSIND_REQ),_T("MSG_SMS_SENDMESTOREDSTATUSIND_REQ"), (xdrproc_t)xdr_CAPI2_SMS_SendMEStoredStatusInd_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SENDMESTOREDSTATUSIND_RSP),_T("MSG_SMS_SENDMESTOREDSTATUSIND_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SENDMERETRIEVESMSDATAIND_REQ),_T("MSG_SMS_SENDMERETRIEVESMSDATAIND_REQ"), (xdrproc_t)xdr_CAPI2_SMS_SendMERetrieveSmsDataInd_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SENDMERETRIEVESMSDATAIND_RSP),_T("MSG_SMS_SENDMERETRIEVESMSDATAIND_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SENDMEREMOVEDSTATUSIND_REQ),_T("MSG_SMS_SENDMEREMOVEDSTATUSIND_REQ"), (xdrproc_t)xdr_CAPI2_SMS_SendMERemovedStatusInd_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SENDMEREMOVEDSTATUSIND_RSP),_T("MSG_SMS_SENDMEREMOVEDSTATUSIND_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSSTOREDSTATE_REQ),_T("MSG_SMS_SETSMSSTOREDSTATE_REQ"), (xdrproc_t)xdr_CAPI2_SMS_SetSmsStoredState_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETSMSSTOREDSTATE_RSP),_T("MSG_SMS_SETSMSSTOREDSTATE_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETTRANSACTIONFROMCLIENTID_REQ),_T("MSG_SMS_GETTRANSACTIONFROMCLIENTID_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETTRANSACTIONFROMCLIENTID_RSP),_T("MSG_SMS_GETTRANSACTIONFROMCLIENTID_RSP"), (xdrproc_t)xdr_CAPI2_SMS_GetTransactionFromClientID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_READY_IND),_T("MSG_SMS_READY_IND"), (xdrproc_t)xdr_CAPI2_smsModuleReady_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMSPP_DELIVER_IND),_T("MSG_SMSPP_DELIVER_IND"), (xdrproc_t)xdr_CAPI2_SmsSimMsg_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMSPP_OTA_IND),_T("MSG_SMSPP_OTA_IND"), (xdrproc_t)xdr_CAPI2_SmsSimMsg_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMSPP_REGULAR_PUSH_IND),_T("MSG_SMSPP_REGULAR_PUSH_IND"), (xdrproc_t)xdr_CAPI2_SmsSimMsg_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMSPP_SECURE_PUSH_IND),_T("MSG_SMSPP_SECURE_PUSH_IND"), (xdrproc_t)xdr_CAPI2_SmsSimMsg_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMSCB_DATA_IND),_T("MSG_SMSCB_DATA_IND"), (xdrproc_t)xdr_CAPI2_SmsStoredSmsCb_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_HOMEZONE_STATUS_IND),_T("MSG_HOMEZONE_STATUS_IND"), (xdrproc_t)xdr_CAPI2_HomezoneIndData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMSPP_STORED_IND),_T("MSG_SMSPP_STORED_IND"), (xdrproc_t)xdr_CAPI2_SmsIncMsgStoredResult_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMSCB_STORED_IND),_T("MSG_SMSCB_STORED_IND"), (xdrproc_t)xdr_CAPI2_SmsIncMsgStoredResult_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMSSR_REPORT_IND),_T("MSG_SMSSR_REPORT_IND"), (xdrproc_t)xdr_CAPI2_SmsSimMsg_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMSSR_STORED_IND),_T("MSG_SMSSR_STORED_IND"), (xdrproc_t)xdr_CAPI2_SmsIncMsgStoredResult_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_VM_WAITING_IND),_T("MSG_VM_WAITING_IND"), (xdrproc_t)xdr_CAPI2_SmsVoicemailInd_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_VMSC_UPDATE_RSP),_T("MSG_VMSC_UPDATE_RSP"), (xdrproc_t)xdr_CAPI2_SIM_SubmitBinaryEFileUpdateReq_Rsp_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_ISCACHEDDATAREADY_REQ),_T("MSG_SMS_ISCACHEDDATAREADY_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_ISCACHEDDATAREADY_RSP),_T("MSG_SMS_ISCACHEDDATAREADY_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETENHANCEDVMINFOIEI_REQ),_T("MSG_SMS_GETENHANCEDVMINFOIEI_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_GETENHANCEDVMINFOIEI_RSP),_T("MSG_SMS_GETENHANCEDVMINFOIEI_RSP"), (xdrproc_t)xdr_CAPI2_SmsEnhancedVMInd_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_340ADDRTOTE_REQ),_T("MSG_SMS_340ADDRTOTE_REQ"), (xdrproc_t)xdr_CAPI2_SMS_340AddrToTe_Req_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_340ADDRTOTE_RSP),_T("MSG_SMS_340ADDRTOTE_RSP"), (xdrproc_t)xdr_CAPI2_SMS_340AddrToTe_Rsp_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETALLNEWMSGDISPLAYPREF_REQ),_T("MSG_SMS_SETALLNEWMSGDISPLAYPREF_REQ"), (xdrproc_t)xdr_CAPI2_SMS_SetAllNewMsgDisplayPref_Req_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SETALLNEWMSGDISPLAYPREF_RSP),_T("MSG_SMS_SETALLNEWMSGDISPLAYPREF_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_ACKTONETWORK_REQ),_T("MSG_SMS_ACKTONETWORK_REQ"), (xdrproc_t)xdr_CAPI2_SMS_SendAckToNetwork_Req_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_ACKTONETWORK_RSP),_T("MSG_SMS_ACKTONETWORK_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SMSRESPONSE_REQ),_T("MSG_SMS_SMSRESPONSE_REQ"), (xdrproc_t)xdr_CAPI2_MNSMS_SMResponse_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SMS_SMSRESPONSE_RSP),_T("MSG_SMS_SMSRESPONSE_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },


	/* Add STK message serialize/deserialize routine map */
	{ _D(MSG_SATK_GETCACHEDROOTMENUPTR_REQ),_T("MSG_SATK_GETCACHEDROOTMENUPTR_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_GETCACHEDROOTMENUPTR_RSP),_T("MSG_SATK_GETCACHEDROOTMENUPTR_RSP"), (xdrproc_t)xdr_CAPI2_SetupMenu_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_SENDUSERACTIVITYEVENT_REQ),_T("MSG_SATK_SENDUSERACTIVITYEVENT_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_SENDUSERACTIVITYEVENT_RSP),_T("MSG_SATK_SENDUSERACTIVITYEVENT_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_SENDIDLESCREENAVAIEVENT_REQ),_T("MSG_SATK_SENDIDLESCREENAVAIEVENT_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_SENDIDLESCREENAVAIEVENT_RSP),_T("MSG_SATK_SENDIDLESCREENAVAIEVENT_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_SENDLANGSELECTEVENT_REQ),_T("MSG_SATK_SENDLANGSELECTEVENT_REQ"), (xdrproc_t)xdr_u_int16_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_SENDLANGSELECTEVENT_RSP),_T("MSG_SATK_SENDLANGSELECTEVENT_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_SENDBROWSERTERMEVENT_REQ),_T("MSG_SATK_SENDBROWSERTERMEVENT_REQ"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_SENDBROWSERTERMEVENT_RSP),_T("MSG_SATK_SENDBROWSERTERMEVENT_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_CMDRESP_REQ),_T("MSG_SATK_CMDRESP_REQ"), (xdrproc_t)xdr_CAPI2_SATKCmdResp_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_CMDRESP_RSP),_T("MSG_SATK_CMDRESP_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_DATASERVCMDRESP_REQ),_T("MSG_SATK_DATASERVCMDRESP_REQ"), (xdrproc_t)xdr_CAPI2_StkCmdRespond_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_DATASERVCMDRESP_RSP),_T("MSG_SATK_DATASERVCMDRESP_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_EVENT_DISPLAY_TEXT),_T("MSG_SATK_EVENT_DISPLAY_TEXT"), (xdrproc_t)xdr_CAPI2_SATK_EventData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },    
	{ _D(MSG_SATK_EVENT_GET_INKEY),_T("MSG_SATK_EVENT_GET_INKEY"), (xdrproc_t)xdr_CAPI2_SATK_EventData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_EVENT_GET_INPUT),_T("MSG_SATK_EVENT_GET_INPUT"), (xdrproc_t)xdr_CAPI2_SATK_EventData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_EVENT_PLAY_TONE),_T("MSG_SATK_EVENT_PLAY_TONE"), (xdrproc_t)xdr_CAPI2_SATK_EventData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_EVENT_SELECT_ITEM),_T("MSG_SATK_EVENT_SELECT_ITEM"), (xdrproc_t)xdr_CAPI2_SATK_EventData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_EVENT_SEND_SS),_T("MSG_SATK_EVENT_SEND_SS"), (xdrproc_t)xdr_CAPI2_SATK_EventData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_EVENT_SEND_USSD),_T("MSG_SATK_EVENT_SEND_USSD"), (xdrproc_t)xdr_CAPI2_SATK_EventData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_EVENT_SETUP_CALL),_T("MSG_SATK_EVENT_SETUP_CALL"), (xdrproc_t)xdr_CAPI2_SATK_EventData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_EVENT_SETUP_MENU),_T("MSG_SATK_EVENT_SETUP_MENU"), (xdrproc_t)xdr_CAPI2_SATK_EventData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_EVENT_REFRESH),_T("MSG_SATK_EVENT_REFRESH"), (xdrproc_t)xdr_CAPI2_SATK_EventData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SIM_FATAL_ERROR_IND),_T("MSG_SIM_FATAL_ERROR_IND"), (xdrproc_t)xdr_CAPI2_SIM_FatalErrorInd_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
    { _D(MSG_STK_CC_SETUPFAIL_IND),_T("MSG_STK_CC_SETUPFAIL_IND"), (xdrproc_t)xdr_CAPI2_SATK_CallSetupFail_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
    { _D(MSG_STK_CC_DISPLAY_IND),_T("MSG_STK_CC_DISPLAY_IND"), (xdrproc_t)xdr_CAPI2_SATK_CallControlDisplay_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_EVENT_SEND_SHORT_MSG),_T("MSG_SATK_EVENT_SEND_SHORT_MSG"), (xdrproc_t)xdr_CAPI2_SATK_EventData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_EVENT_SEND_DTMF),_T("MSG_SATK_EVENT_SEND_DTMF"), (xdrproc_t)xdr_CAPI2_SATK_EventData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_EVENT_LAUNCH_BROWSER),_T("MSG_SATK_EVENT_LAUNCH_BROWSER"), (xdrproc_t)xdr_CAPI2_SATK_EventData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_EVENT_IDLEMODE_TEXT),_T("MSG_SATK_EVENT_IDLEMODE_TEXT"), (xdrproc_t)xdr_CAPI2_SATK_EventData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_EVENT_DATA_SERVICE_REQ),_T("MSG_SATK_EVENT_DATA_SERVICE_REQ"), (xdrproc_t)xdr_CAPI2_SATK_EventData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_EVENT_ACTIVATE),_T("MSG_SATK_EVENT_ACTIVATE"), (xdrproc_t)xdr_CAPI2_SATK_EventData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_SETTERMPROFILE_REQ),_T("MSG_SATK_SETTERMPROFILE_REQ"), (xdrproc_t)xdr_CAPI2_TermProfile_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_SETTERMPROFILE_RSP),_T("MSG_SATK_SETTERMPROFILE_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_GETTERMPROFILE_REQ),_T("MSG_SATK_GETTERMPROFILE_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_GETTERMPROFILE_RSP),_T("MSG_SATK_GETTERMPROFILE_RSP"), (xdrproc_t)xdr_CAPI2_TermProfile_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_STK_LANG_NOTIFICATION_IND),_T("MSG_STK_LANG_NOTIFICATION_IND"), (xdrproc_t)xdr_CAPI2_StkLangNotification_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
    { _D(MSG_SIM_CACHED_DATA_READY_IND),_T("MSG_SIM_CACHED_DATA_READY_IND"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SIM_MMI_SETUP_EVENT_IND),_T("MSG_SIM_MMI_SETUP_EVENT_IND"), (xdrproc_t)xdr_u_int16_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_STK_RUN_AT_IND),_T("MSG_STK_RUN_AT_IND"), (xdrproc_t)xdr_CAPI2_SATK_EventData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
    { _D(MSG_STK_RUN_AT_REQ),_T("MSG_STK_RUN_AT_REQ"), (xdrproc_t)xdr_CAPI2_StkRunAtReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
    { _D(MSG_STK_SEND_IPAT_REQ),_T("MSG_STK_SEND_IPAT_REQ"), (xdrproc_t)xdr_CAPI2_StkRunIpAtReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
    { _D(MSG_SATK_SEND_CC_SETUP_REQ),_T("MSG_SATK_SEND_CC_SETUP_REQ"), (xdrproc_t)xdr_CAPI2_SATK_SendCcSetupReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_STK_CALL_CONTROL_SETUP_RSP),_T("MSG_STK_CALL_CONTROL_SETUP_RSP"), (xdrproc_t)xdr_CAPI2_StkCallControlSetupRsp_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
    { _D(MSG_SATK_SEND_CC_SS_REQ),_T("MSG_SATK_SEND_CC_SS_REQ"), (xdrproc_t)xdr_CAPI2_SATK_SendCcSsReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_STK_CALL_CONTROL_SS_RSP),_T("MSG_STK_CALL_CONTROL_SS_RSP"), (xdrproc_t)xdr_CAPI2_StkCallControlSsRsp_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
    { _D(MSG_SATK_SEND_CC_USSD_REQ),_T("MSG_SATK_SEND_CC_USSD_REQ"), (xdrproc_t)xdr_CAPI2_SATK_SendCcUssdReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_STK_CALL_CONTROL_USSD_RSP),_T("MSG_STK_CALL_CONTROL_USSD_RSP"), (xdrproc_t)xdr_CAPI2_StkCallControlUssdRsp_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
    { _D(MSG_SATK_SEND_CC_SMS_REQ),_T("MSG_SATK_SEND_CC_SMS_REQ"), (xdrproc_t)xdr_CAPI2_SATK_SendCcSmsReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_STK_CALL_CONTROL_SMS_RSP),_T("MSG_STK_CALL_CONTROL_SMS_RSP"), (xdrproc_t)xdr_CAPI2_StkCallControlSmsRsp_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
   
	{ _D(MSG_SATK_EVENT_STK_SESSION_END),_T("MSG_SATK_EVENT_STK_SESSION_END"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SATK_EVENT_PROV_LOCAL_LANG),_T("MSG_SATK_EVENT_PROV_LOCAL_LANG"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
    { _D(MSG_STK_MENU_SELECTION_RES),_T("MSG_STK_MENU_SELECTION_RES"), (xdrproc_t)xdr_CAPI2_StkMenuSelectionRes_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },

	/* Add Call Control  message serialize/deserialize routine map */

	{ _D(MSG_CC_MAKEVOICECALL_REQ),_T("MSG_CC_MAKEVOICECALL_REQ"), (xdrproc_t)xdr_CAPI2_CC_MakeVoiceCall_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_MAKEDATACALL_REQ),_T("MSG_CC_MAKEDATACALL_REQ"), (xdrproc_t)xdr_xdr_string_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_MAKEFAXCALL_REQ),_T("MSG_CC_MAKEFAXCALL_REQ"), (xdrproc_t)xdr_xdr_string_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_MAKEVIDEOCALL_REQ),_T("MSG_CC_MAKEVIDEOCALL_REQ"), (xdrproc_t)xdr_xdr_string_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ENDCALL_REQ),_T("MSG_CC_ENDCALL_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ENDALLCALLS_REQ),_T("MSG_CC_ENDALLCALLS_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ENDMPTYCALLS_REQ),_T("MSG_CC_ENDMPTYCALLS_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ENDHELDCALL_REQ),_T("MSG_CC_ENDHELDCALL_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ACCEPTVOICECALL_REQ),_T("MSG_CC_ACCEPTVOICECALL_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ACCEPTDATACALL_REQ),_T("MSG_CC_ACCEPTDATACALL_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ACCEPTWAITINGCALL_REQ),_T("MSG_CC_ACCEPTWAITINGCALL_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ACCEPTVIDEOCALL_REQ),_T("MSG_CC_ACCEPTVIDEOCALL_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_HOLDCURRENTCALL_REQ),_T("MSG_CC_HOLDCURRENTCALL_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_HOLDCALL_REQ),_T("MSG_CC_HOLDCALL_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_RETRIEVENEXTHELDCALL_REQ),_T("MSG_CC_RETRIEVENEXTHELDCALL_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_RETRIEVECALL_REQ),_T("MSG_CC_RETRIEVECALL_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_SWAPCALL_REQ),_T("MSG_CC_SWAPCALL_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_SPLITCALL_REQ),_T("MSG_CC_SPLITCALL_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_JOINCALL_REQ),_T("MSG_CC_JOINCALL_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_TRANSFERCALL_REQ),_T("MSG_CC_TRANSFERCALL_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
//	{ _D(MSG_CC_SENDDTMF_REQ),_T("MSG_CC_SENDDTMF_REQ"), (xdrproc_t)xdr_CAPI2_CC_SendDTMF_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
//	{ _D(MSG_CC_SENDDTMF_RSP),_T("MSG_CC_SENDDTMF_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
//	{ _D(MSG_CC_STOPDTMF_REQ),_T("MSG_CC_STOPDTMF_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
//	{ _D(MSG_CC_STOPDTMF_RSP),_T("MSG_CC_STOPDTMF_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_MUTECALL_REQ),_T("MSG_CC_MUTECALL_REQ"), (xdrproc_t)xdr_CAPI2_CC_MuteCall_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_MUTECALL_RSP),_T("MSG_CC_MUTECALL_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCURRENTCALLINDEX_REQ),_T("MSG_CC_GETCURRENTCALLINDEX_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCURRENTCALLINDEX_RSP),_T("MSG_CC_GETCURRENTCALLINDEX_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETNEXTACTIVECALLINDEX_REQ),_T("MSG_CC_GETNEXTACTIVECALLINDEX_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETNEXTACTIVECALLINDEX_RSP),_T("MSG_CC_GETNEXTACTIVECALLINDEX_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETNEXTHELDCALLINDEX_REQ),_T("MSG_CC_GETNEXTHELDCALLINDEX_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETNEXTHELDCALLINDEX_RSP),_T("MSG_CC_GETNEXTHELDCALLINDEX_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETNEXTWAITCALLINDEX_REQ),_T("MSG_CC_GETNEXTWAITCALLINDEX_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETNEXTWAITCALLINDEX_RSP),_T("MSG_CC_GETNEXTWAITCALLINDEX_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETMPTYCALLINDEX_REQ),_T("MSG_CC_GETMPTYCALLINDEX_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETMPTYCALLINDEX_RSP),_T("MSG_CC_GETMPTYCALLINDEX_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCALLSTATE_REQ),_T("MSG_CC_GETCALLSTATE_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCALLSTATE_RSP),_T("MSG_CC_GETCALLSTATE_RSP"), (xdrproc_t)XDR_ENUM_DEF(CCallState_t), REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCALLTYPE_REQ),_T("MSG_CC_GETCALLTYPE_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCALLTYPE_RSP),_T("MSG_CC_GETCALLTYPE_RSP"), (xdrproc_t)XDR_ENUM_DEF(CCallType_t), REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETLASTCALLEXITCAUSE_REQ),_T("MSG_CC_GETLASTCALLEXITCAUSE_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETLASTCALLEXITCAUSE_RSP),_T("MSG_CC_GETLASTCALLEXITCAUSE_RSP"), (xdrproc_t)XDR_ENUM_DEF(Cause_t), REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCNAPNAME_REQ),_T("MSG_CC_GETCNAPNAME_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCNAPNAME_RSP),_T("MSG_CC_GETCNAPNAME_RSP"), (xdrproc_t) xdr_CNAP_NAME_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCALLNUMBER_REQ),_T("MSG_CC_GETCALLNUMBER_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCALLNUMBER_RSP),_T("MSG_CC_GETCALLNUMBER_RSP"), (xdrproc_t) xdr_PHONE_NUMBER_STR_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCALLINGINFO_REQ),_T("MSG_CC_GETCALLINGINFO_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCALLINGINFO_RSP),_T("MSG_CC_GETCALLINGINFO_RSP"), (xdrproc_t) xdr_CallingInfo_t, REQRSP_MSG_EXT(0,NULL,NULL,0) }, 
	{ _D(MSG_CC_GETALLCALLSTATES_REQ),_T("MSG_CC_GETALLCALLSTATES_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETALLCALLSTATES_RSP),_T("MSG_CC_GETALLCALLSTATES_RSP"), (xdrproc_t) xdr_ALL_CALL_STATE_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETALLCALLINDEX_REQ),_T("MSG_CC_GETALLCALLINDEX_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETALLCALLINDEX_RSP),_T("MSG_CC_GETALLCALLINDEX_RSP"), (xdrproc_t) xdr_ALL_CALL_INDEX_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETALLHELDCALLINDEX_REQ),_T("MSG_CC_GETALLHELDCALLINDEX_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETALLHELDCALLINDEX_RSP),_T("MSG_CC_GETALLHELDCALLINDEX_RSP"), (xdrproc_t) xdr_ALL_CALL_INDEX_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETALLACTIVECALLINDEX_REQ),_T("MSG_CC_GETALLACTIVECALLINDEX_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETALLACTIVECALLINDEX_RSP),_T("MSG_CC_GETALLACTIVECALLINDEX_RSP"), (xdrproc_t) xdr_ALL_CALL_INDEX_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETALLMPTYCALLINDEX_REQ),_T("MSG_CC_GETALLMPTYCALLINDEX_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETALLMPTYCALLINDEX_RSP),_T("MSG_CC_GETALLMPTYCALLINDEX_RSP"), (xdrproc_t) xdr_ALL_CALL_INDEX_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETNUMOFMPTYCALLS_REQ),_T("MSG_CC_GETNUMOFMPTYCALLS_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETNUMOFMPTYCALLS_RSP),_T("MSG_CC_GETNUMOFMPTYCALLS_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETNUMOFACTIVECALLS_REQ),_T("MSG_CC_GETNUMOFACTIVECALLS_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETNUMOFACTIVECALLS_RSP),_T("MSG_CC_GETNUMOFACTIVECALLS_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETNUMOFHELDCALLS_REQ),_T("MSG_CC_GETNUMOFHELDCALLS_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETNUMOFHELDCALLS_RSP),_T("MSG_CC_GETNUMOFHELDCALLS_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ISTHEREWAITINGCALL_REQ),_T("MSG_CC_ISTHEREWAITINGCALL_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ISTHEREWAITINGCALL_RSP),_T("MSG_CC_ISTHEREWAITINGCALL_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ISTHEREALERTINGCALL_REQ),_T("MSG_CC_ISTHEREALERTINGCALL_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ISTHEREALERTINGCALL_RSP),_T("MSG_CC_ISTHEREALERTINGCALL_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCONNECTEDLINEID_REQ),_T("MSG_CC_GETCONNECTEDLINEID_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCONNECTEDLINEID_RSP),_T("MSG_CC_GETCONNECTEDLINEID_RSP"), (xdrproc_t) xdr_PHONE_NUMBER_STR_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ISMULTIPARTYCALL_REQ),_T("MSG_CC_ISMULTIPARTYCALL_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ISCURRENTSTATEMPTY_REQ),_T("MSG_CC_ISCURRENTSTATEMPTY_REQ"),(xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ISMULTIPARTYCALL_RSP),_T("MSG_CC_ISMULTIPARTYCALL_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ISCURRENTSTATEMPTY_RSP),_T("MSG_CC_ISCURRENTSTATEMPTY_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
//	{ _D(MSG_CC_ISVALIDDTMF_REQ),_T("MSG_CC_ISVALIDDTMF_REQ"), (xdrproc_t)xdr_CAPI2_CC_IsValidDTMF_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
//	{ _D(MSG_CC_ISVALIDDTMF_RSP),_T("MSG_CC_ISVALIDDTMF_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ISTHEREVOICECALL_REQ),_T("MSG_CC_ISTHEREVOICECALL_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ISTHEREVOICECALL_RSP),_T("MSG_CC_ISTHEREVOICECALL_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ISCONNECTEDLINEIDPRESENTALLOWED_REQ),_T("MSG_CC_ISCONNECTEDLINEIDPRESENTALLOWED_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ISCONNECTEDLINEIDPRESENTALLOWED_RSP),_T("MSG_CC_ISCONNECTEDLINEIDPRESENTALLOWED_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCURRENTCALLDURATIONINMILLISECONDS_REQ),_T("MSG_CC_GETCURRENTCALLDURATIONINMILLISECONDS_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCURRENTCALLDURATIONINMILLISECONDS_RSP),_T("MSG_CC_GETCURRENTCALLDURATIONINMILLISECONDS_RSP"), (xdrproc_t)xdr_u_int32_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETLASTCALLCCM_REQ),_T("MSG_CC_GETLASTCALLCCM_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETLASTCALLCCM_RSP),_T("MSG_CC_GETLASTCALLCCM_RSP"), (xdrproc_t)xdr_u_int32_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETLASTCALLDURATION_REQ),_T("MSG_CC_GETLASTCALLDURATION_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETLASTCALLDURATION_RSP),_T("MSG_CC_GETLASTCALLDURATION_RSP"), (xdrproc_t)xdr_u_int32_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETLASTDATACALLRXBYTES_REQ),_T("MSG_CC_GETLASTDATACALLRXBYTES_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETLASTDATACALLRXBYTES_RSP),_T("MSG_CC_GETLASTDATACALLRXBYTES_RSP"), (xdrproc_t)xdr_u_int32_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETLASTDATACALLTXBYTES_REQ),_T("MSG_CC_GETLASTDATACALLTXBYTES_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETLASTDATACALLTXBYTES_RSP),_T("MSG_CC_GETLASTDATACALLTXBYTES_RSP"), (xdrproc_t)xdr_u_int32_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETDATACALLINDEX_REQ),_T("MSG_CC_GETDATACALLINDEX_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETDATACALLINDEX_RSP),_T("MSG_CC_GETDATACALLINDEX_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCALLCLIENTID_REQ),_T("MSG_CC_GETCALLCLIENTID_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCALLCLIENTID_RSP),_T("MSG_CC_GETCALLCLIENTID_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETTYPEADD_REQ),_T("MSG_CC_GETTYPEADD_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETTYPEADD_RSP),_T("MSG_CC_GETTYPEADD_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_SETVOICECALLAUTOREJECT_REQ),_T("MSG_CC_SETVOICECALLAUTOREJECT_REQ"), (xdrproc_t)xdr_CAPI2_CC_SetVoiceCallAutoReject_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_SETVOICECALLAUTOREJECT_RSP),_T("MSG_CC_SETVOICECALLAUTOREJECT_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ISVOICECALLAUTOREJECT_REQ),_T("MSG_CC_ISVOICECALLAUTOREJECT_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ISVOICECALLAUTOREJECT_RSP),_T("MSG_CC_ISVOICECALLAUTOREJECT_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },  
	{ _D(MSG_CC_SETTTYCALL_REQ),_T("MSG_CC_SETTTYCALL_REQ"), (xdrproc_t)xdr_CAPI2_CC_SetTTYCall_t, REQRSP_MSG_EXT(0,NULL,NULL,0) }, 
	{ _D(MSG_CC_SETTTYCALL_RSP),_T("MSG_CC_SETTTYCALL_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ISTTYENABLE_REQ),_T("MSG_CC_ISTTYENABLE_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ISTTYENABLE_RSP),_T("MSG_CC_ISTTYENABLE_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ISSIMORIGINEDCALL_REQ),_T("MSG_CC_ISSIMORIGINEDCALL_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_ISSIMORIGINEDCALL_RSP),_T("MSG_CC_ISSIMORIGINEDCALL_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_SETVIDEOCALLPARAM_REQ),_T("MSG_CC_SETVIDEOCALLPARAM_REQ"), (xdrproc_t)xdr_CAPI2_CC_SetVideoCallParam_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_SETVIDEOCALLPARAM_RSP),_T("MSG_CC_SETVIDEOCALLPARAM_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETVIDEOCALLPARAM_REQ),_T("MSG_CC_GETVIDEOCALLPARAM_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETVIDEOCALLPARAM_RSP),_T("MSG_CC_GETVIDEOCALLPARAM_RSP"), (xdrproc_t) xdr_VideoCallParam_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCALLCFG_REQ),_T("MSG_CC_GETCALLCFG_REQ"), (xdrproc_t)xdr_CAPI2_CC_GetCallCfg_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCALLCFG_RSP),_T("MSG_CC_GETCALLCFG_RSP"), (xdrproc_t) xdr_CAPI2_CallConfig_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_SETCALLCFG_REQ),_T("MSG_CC_SETCALLCFG_REQ"), (xdrproc_t)xdr_CAPI2_CC_SetCallCfg_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_SETCALLCFG_RSP),_T("MSG_CC_SETCALLCFG_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_RESETCALLCFG_REQ),_T("MSG_CC_RESETCALLCFG_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_RESETCALLCFG_RSP),_T("MSG_CC_RESETCALLCFG_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCALLINDEXINTHISSTATE_REQ), _T("MSG_CC_GETCALLINDEXINTHISSTATE_REQ"), (xdrproc_t)xdr_CAPI2_CC_GetCallIndexInThisState_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCALLINDEXINTHISSTATE_RSP), _T("MSG_CC_GETCALLINDEXINTHISSTATE_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCCM_REQ), _T("MSG_CC_GETCCM_REQ"), (xdrproc_t)xdr_CAPI2_CC_CallIndex_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCCM_RSP), _T("MSG_CC_GETCCM_RSP"), (xdrproc_t) xdr_CallMeterUnit_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCALLPRESENT_REQ), _T("MSG_CC_GETCALLPRESENT_REQ"), (xdrproc_t)xdr_CAPI2_CC_GetCallPresent_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CC_GETCALLPRESENT_RSP), _T("MSG_CC_GETCALLPRESENT_RSP"), (xdrproc_t)XDR_ENUM_DEF(PresentationInd_t), REQRSP_MSG_EXT(0,NULL,NULL,0) },

	{ _D(MSG_CCAPI_SENDDTMF_REQ),_T("MSG_CCAPI_SENDDTMF_REQ"), (xdrproc_t)xdr_CAPI2_CcApi_SendDtmf_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CCAPI_SENDDTMF_RSP),_T("MSG_CCAPI_SENDDTMF_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CCAPI_STOPDTMF_REQ),_T("MSG_CCAPI_STOPDTMF_REQ"), (xdrproc_t)xdr_CAPI2_CcApi_StopDtmf_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CCAPI_STOPDTMF_RSP),_T("MSG_CCAPI_STOPDTMF_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CCAPI_ABORTDTMF_REQ),_T("MSG_CCAPI_ABORTDTMF_REQ"), (xdrproc_t)xdr_CAPI2_CcApi_AbortDtmf_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CCAPI_ABORTDTMF_RSP),_T("MSG_CCAPI_ABORTDTMF_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CCAPI_SETDTMFTIMER_REQ),_T("MSG_CCAPI_SETDTMFTIMER_REQ"), (xdrproc_t)xdr_CAPI2_CcApi_SetDtmfTimer_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CCAPI_SETDTMFTIMER_RSP),_T("MSG_CCAPI_SETDTMFTIMER_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CCAPI_RESETDTMFTIMER_REQ),_T("MSG_CCAPI_RESETDTMFTIMER_REQ"), (xdrproc_t)xdr_CAPI2_CcApi_ResetDtmfTimer_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CCAPI_RESETDTMFTIMER_RSP),_T("MSG_CCAPI_RESETDTMFTIMER_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CCAPI_GETDTMFTIMER_REQ),_T("MSG_CCAPI_GETDTMFTIMER_REQ"), (xdrproc_t)xdr_CAPI2_CcApi_GetDtmfTimer_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CCAPI_GETDTMFTIMER_RSP),_T("MSG_CCAPI_GETDTMFTIMER_RSP"), (xdrproc_t)xdr_u_int32_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },  

	{ _D(MSG_VOICECALL_CONNECTED_IND),_T("MSG_VOICECALL_CONNECTED_IND"), (xdrproc_t) xdr_CAPI2_VOICECALL_CONNECTED_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_VOICECALL_PRECONNECT_IND),_T("MSG_VOICECALL_PRECONNECT_IND"), (xdrproc_t) xdr_CAPI2_VOICECALL_PRECONNECT_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_CALL_NOTIFICATION),_T("MSG_SS_CALL_NOTIFICATION"), (xdrproc_t) xdr_CAPI2_SS_CALL_NOTIFICATION_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_NOTIFY_CLOSED_USER_GROUP),_T("MSG_SS_NOTIFY_CLOSED_USER_GROUP"), (xdrproc_t) xdr_CAPI2_SS_CALL_NOTIFICATION_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_NOTIFY_EXTENDED_CALL_TRANSFER),_T("MSG_SS_NOTIFY_EXTENDED_CALL_TRANSFER"), (xdrproc_t) xdr_CAPI2_SS_CALL_NOTIFICATION_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_NOTIFY_CALLING_NAME_PRESENT),_T("MSG_SS_NOTIFY_CALLING_NAME_PRESENT"), (xdrproc_t) xdr_CAPI2_SS_CALL_NOTIFICATION_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CALL_STATUS_IND),_T("MSG_CALL_STATUS_IND"), (xdrproc_t) xdr_CAPI2_CALL_STATUS_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_VOICECALL_ACTION_RSP),_T("MSG_VOICECALL_ACTION_RSP"), (xdrproc_t) xdr_CAPI2_VOICECALL_ACTION_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_VOICECALL_RELEASE_IND),_T("MSG_VOICECALL_RELEASE_IND"), (xdrproc_t) xdr_CAPI2_VOICECALL_RELEASE_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_VOICECALL_RELEASE_CNF),_T("MSG_VOICECALL_RELEASE_CNF"), (xdrproc_t) xdr_CAPI2_VOICECALL_RELEASE_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_INCOMING_CALL_IND),_T("MSG_INCOMING_CALL_IND"), (xdrproc_t) xdr_CAPI2_INCOMING_CALL_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_VOICECALL_WAITING_IND),_T("MSG_VOICECALL_WAITING_IND"), (xdrproc_t) xdr_CAPI2_VOICECALL_WAITING_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CALL_AOCSTATUS_IND),_T("MSG_CALL_AOCSTATUS_IND"), (xdrproc_t) xdr_CAPI2_CALL_AOCSTATUS_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CALL_CCM_IND),_T("MSG_CALL_CCM_IND"), (xdrproc_t) xdr_CAPI2_CALL_CCM_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_CALL_CONNECTEDLINEID_IND),_T("MSG_CALL_CONNECTEDLINEID_IND"), (xdrproc_t) xdr_CAPI2_CALL_CONNECTEDLINEID_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_DATACALL_STATUS_IND),_T("MSG_DATACALL_STATUS_IND"), (xdrproc_t) xdr_CAPI2_DATACALL_STATUS_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_DATACALL_RELEASE_IND),_T("MSG_DATACALL_RELEASE_IND"), (xdrproc_t) xdr_CAPI2_DATACALL_RELEASE_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_DATACALL_RELEASE_CNF),_T("MSG_DATACALL_RELEASE_CNF"), (xdrproc_t) xdr_CAPI2_DATACALL_RELEASE_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_DATACALL_ECDC_IND),_T("MSG_DATACALL_ECDC_IND"), (xdrproc_t) xdr_CAPI2_DATACALL_ECDC_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_DATACALL_CONNECTED_IND),_T("MSG_DATACALL_CONNECTED_IND"), (xdrproc_t) xdr_CAPI2_DATACALL_CONNECTED_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) }, 
	{ _D(MSG_API_CLIENT_CMD_IND),_T("MSG_API_CLIENT_CMD_IND"), (xdrproc_t) xdr_CAPI2_API_CLIENT_CMD_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) }, 
	{ _D(MSG_DTMF_STATUS_IND),_T("MSG_DTMF_STATUS_IND"), (xdrproc_t) xdr_CAPI2_DTMF_STATUS_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) }, 
    { _D(MSG_USER_INFORMATION),_T("MSG_USER_INFORMATION"), (xdrproc_t) xdr_CAPI2_USER_INFORMATION_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },

	/* Add SS  message serialize/deserialize routine map */

	{ _D(MSG_SS_SENDCALLFORWARDREQ_REQ),_T("MSG_SS_SENDCALLFORWARDREQ_REQ"), (xdrproc_t)xdr_CAPI2_SS_SendCallForwardReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_QUERYCALLFORWARDSTATUS_REQ),_T("MSG_SS_QUERYCALLFORWARDSTATUS_REQ"), (xdrproc_t)xdr_CAPI2_SS_QueryCallForwardStatus_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_SENDCALLBARRINGREQ_REQ),_T("MSG_SS_SENDCALLBARRINGREQ_REQ"), (xdrproc_t)xdr_CAPI2_SS_SendCallBarringReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_QUERYCALLBARRINGSTATUS_REQ),_T("MSG_SS_QUERYCALLBARRINGSTATUS_REQ"), (xdrproc_t)xdr_CAPI2_SS_QueryCallBarringStatus_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_SENDCALLBARRINGPWDCHANGEREQ_REQ),_T("MSG_SS_SENDCALLBARRINGPWDCHANGEREQ_REQ"), (xdrproc_t)xdr_CAPI2_SS_SendCallBarringPWDChangeReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_SENDCALLWAITINGREQ_REQ),_T("MSG_SS_SENDCALLWAITINGREQ_REQ"), (xdrproc_t)xdr_CAPI2_SS_SendCallWaitingReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_QUERYCALLWAITINGSTATUS_REQ),_T("MSG_SS_QUERYCALLWAITINGSTATUS_REQ"), (xdrproc_t)xdr_CAPI2_SS_QueryCallWaitingStatus_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_QUERYCALLINGLINEIDSTATUS_REQ), _T("MSG_SS_QUERYCALLINGLINEIDSTATUS_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_QUERYCONNECTEDLINEIDSTATUS_REQ), _T("MSG_SS_QUERYCONNECTEDLINEIDSTATUS_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_QUERYCALLINGLINERESTRICTIONSTATUS_REQ), _T("MSG_SS_QUERYCALLINGLINERESTRICTIONSTATUS_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_QUERYCONNECTEDLINERESTRICTIONSTATUS_REQ), _T("MSG_SS_QUERYCONNECTEDLINERESTRICTIONSTATUS_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_QUERYCALLINGNAMEPRESENTSTATUS_REQ), _T("MSG_SS_QUERYCALLINGNAMEPRESENTSTATUS_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_SETCALLINGLINEIDSTATUS_REQ), _T("MSG_SS_SETCALLINGLINEIDSTATUS_REQ"), (xdrproc_t)xdr_CAPI2_SS_SetCallingLineIDStatus_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_SETCALLINGLINERESTRICTIONSTATUS_REQ), _T("MSG_SS_SETCALLINGLINERESTRICTIONSTATUS_REQ"), (xdrproc_t)xdr_CAPI2_SS_SetCallingLineRestrictionStatus_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_SETCONNECTEDLINEIDSTATUS_REQ), _T("MSG_SS_SETCONNECTEDLINEIDSTATUS_REQ"), (xdrproc_t)xdr_CAPI2_SS_SetConnectedLineIDStatus_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_SETCONNECTEDLINERESTRICTIONSTATUS_REQ), _T("MSG_SS_SETCONNECTEDLINERESTRICTIONSTATUS_REQ"), (xdrproc_t)xdr_CAPI2_SS_SetConnectedLineRestrictionStatus_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_SENDUSSDCONNECTREQ_REQ),_T("MSG_SS_SENDUSSDCONNECTREQ_REQ"), (xdrproc_t)xdr_CAPI2_SS_SendUSSDConnectReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_ENDUSSDCONNECTREQ_REQ),_T("MSG_SS_ENDUSSDCONNECTREQ_REQ"), (xdrproc_t)xdr_CAPI2_SS_EndUSSDConnectReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_SENDUSSDDATA_REQ),_T("MSG_SS_SENDUSSDDATA_REQ"), (xdrproc_t)xdr_CAPI2_SS_SendUSSDData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) }, 

	{ _D(MSG_SS_CALL_FORWARD_RSP),_T("MSG_SS_CALL_FORWARD_RSP"), (xdrproc_t) xdr_CAPI2_SS_CALL_FORWARD_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_CALL_FORWARD_STATUS_RSP),_T("MSG_SS_CALL_FORWARD_STATUS_RSP"), (xdrproc_t) xdr_CAPI2_SS_CALL_FORWARD_STATUS_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_CALL_BARRING_RSP),_T("MSG_SS_CALL_BARRING_RSP"), (xdrproc_t) xdr_CAPI2_SS_CALL_BARRING_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_CALL_BARRING_STATUS_RSP),_T("MSG_SS_CALL_BARRING_STATUS_RSP"), (xdrproc_t) xdr_CAPI2_SS_CALL_BARRING_STATUS_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_CALL_BARRING_PWD_CHANGE_RSP),_T("MSG_SS_CALL_BARRING_PWD_CHANGE_RSP"), (xdrproc_t) xdr_CAPI2_SS_CALL_BARRING_PWD_CHANGE_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_CALL_WAITING_RSP),_T("MSG_SS_CALL_WAITING_RSP"), (xdrproc_t) xdr_CAPI2_SS_CALL_WAITING_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_CALL_WAITING_STATUS_RSP),_T("MSG_SS_CALL_WAITING_STATUS_RSP"), (xdrproc_t) xdr_CAPI2_SS_CALL_WAITING_STATUS_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_CALLING_LINE_ID_STATUS_RSP),_T("MSG_SS_CALLING_LINE_ID_STATUS_RSP"), (xdrproc_t) xdr_CAPI2_SS_CALLING_LINE_ID_STATUS_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_CONNECTED_LINE_STATUS_RSP),_T("MSG_SS_CONNECTED_LINE_STATUS_RSP"), (xdrproc_t) xdr_CAPI2_SS_CONNECTED_LINE_STATUS_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_CALLING_LINE_RESTRICTION_STATUS_RSP),_T("MSG_SS_CALLING_LINE_RESTRICTION_STATUS_RSP"), (xdrproc_t) xdr_CAPI2_SS_CALLING_LINE_RESTRICTION_STATUS_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_CONNECTED_LINE_RESTRICTION_STATUS_RSP),_T("MSG_SS_CONNECTED_LINE_RESTRICTION_STATUS_RSP"), (xdrproc_t) xdr_CAPI2_SS_CONNECTED_LINE_RESTRICTION_STATUS_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_CALLING_NAME_PRESENT_STATUS_RSP),_T("MSG_SS_CALLING_NAME_PRESENT_STATUS_RSP"), (xdrproc_t) xdr_CAPI2_SS_CALLING_NAME_PRESENT_STATUS_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_INTERNAL_PARAM_SET_IND),  _T("MSG_SS_INTERNAL_PARAM_SET_IND"), (xdrproc_t) xdr_CAPI2_SS_INTERNAL_PARAM_SET_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_CALL_REQ_FAIL),_T("MSG_SS_CALL_REQ_FAIL"), (xdrproc_t) xdr_CAPI2_SS_CALL_REQ_FAIL_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },  
	{ _D(MSG_USSD_DATA_RSP),_T("MSG_USSD_DATA_RSP"), (xdrproc_t) xdr_CAPI2_USSD_DATA_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_USSD_DATA_IND),_T("MSG_USSD_DATA_IND"), (xdrproc_t) xdr_CAPI2_USSD_DATA_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_USSD_SESSION_END_IND),_T("MSG_USSD_SESSION_END_IND"), (xdrproc_t) xdr_CAPI2_USSD_SESSION_END_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },  
	{ _D(MSG_USSD_CALLINDEX_IND),_T("MSG_USSD_CALLINDEX_IND"), (xdrproc_t) xdr_CAPI2_USSD_CALLINDEX_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },  
	{ _D(MSG_SS_RESETSSALSFLAG_REQ), _T("MSG_SS_RESETSSALSFLAG_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_RESETSSALSFLAG_RSP), _T("MSG_SS_RESETSSALSFLAG_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SS_ENDUSSDCONNECTREQ_RSP), _T("MSG_SS_ENDUSSDCONNECTREQ_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_LOCAL_ELEM_NOTIFY_IND),  _T("MSG_MS_LOCAL_ELEM_NOTIFY_IND"), (xdrproc_t) xdr_CAPI2_MS_LOCAL_ELEM_NOTIFY_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },

	{ _D(MSG_SSAPI_DIALSTRSRVREQ_REQ), _T("MSG_SsApi_DIALSTRSRVREQ_REQ"), (xdrproc_t)xdr_CAPI2_SsApi_DialStrSrvReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SSAPI_DIALSTRSRVREQ_RSP), _T("MSG_SsApi_DIALSTRSRVREQ_RSP"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },

	{ _D(MSG_SSAPI_SSSRVREQ_REQ), _T("MSG_SSAPI_SSSRVREQ_REQ"), (xdrproc_t)xdr_CAPI2_SsApi_SsSrvReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SSAPI_SSSRVREQ_RSP), _T("MSG_SSAPI_SSSRVREQ_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SSAPI_USSDSRVREQ_REQ), _T("MSG_SSAPI_USSDSRVREQ_REQ"), (xdrproc_t)xdr_CAPI2_SsApi_UssdSrvReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SSAPI_USSDSRVREQ_RSP), _T("MSG_SSAPI_USSDSRVREQ_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SSAPI_USSDDATAREQ_REQ), _T("MSG_SSAPI_USSDDATAREQ_REQ"), (xdrproc_t)xdr_CAPI2_SsApi_UssdDataReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SSAPI_USSDDATAREQ_RSP), _T("MSG_SSAPI_USSDDATAREQ_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SSAPI_SSRELEASEREQ_REQ), _T("MSG_SSAPI_SSRELEASEREQ_REQ"), (xdrproc_t)xdr_CAPI2_SsApi_SsReleaseReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SSAPI_SSRELEASEREQ_RSP), _T("MSG_SSAPI_SSRELEASEREQ_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SSAPI_DATAREQ_REQ), _T("MSG_SSAPI_DATAREQ_REQ"), (xdrproc_t)xdr_CAPI2_SsApi_DataReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_SSAPI_DATAREQ_RSP), _T("MSG_SSAPI_DATAREQ_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },

	{ _D(MSG_ISIM_ISISIMSUPPORTED_REQ), _T("MSG_ISIM_ISISIMSUPPORTED_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_ISIM_ISISIMSUPPORTED_RSP), _T("MSG_ISIM_ISISIMSUPPORTED_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_ISIM_ISISIMACTIVATED_REQ), _T("MSG_ISIM_ISISIMACTIVATED_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_ISIM_ISISIMACTIVATED_RSP), _T("MSG_ISIM_ISISIMACTIVATED_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_ISIM_ACTIVATEISIMAPPLI_REQ), _T("MSG_ISIM_ACTIVATEISIMAPPLI_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_ISIM_SENDAUTHENAKAREQ_REQ), _T("MSG_ISIM_SENDAUTHENAKAREQ_REQ"), (xdrproc_t)xdr_CAPI2_ISIM_SendAuthenAkaReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_ISIM_SENDAUTHENHTTPREQ_REQ), _T("MSG_ISIM_SENDAUTHENHTTPREQ_REQ"), (xdrproc_t)xdr_CAPI2_ISIM_SendAuthenHttpReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_ISIM_SENDAUTHENGBABOOTREQ_REQ), _T("MSG_ISIM_SENDAUTHENGBABOOTREQ_REQ"), (xdrproc_t)xdr_CAPI2_ISIM_SendAuthenGbaBootReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_ISIM_SENDAUTHENGBANAFREQ_REQ), _T("MSG_ISIM_SENDAUTHENGBANAFREQ_REQ"), (xdrproc_t)xdr_CAPI2_ISIM_SendAuthenGbaNafReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },

	{ _D(MSG_ISIM_ACTIVATE_RSP), _T("MSG_ISIM_ACTIVATE_RSP"), (xdrproc_t) xdr_CAPI2_ISIM_ACTIVATE_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_ISIM_AUTHEN_AKA_RSP), _T("MSG_ISIM_AUTHEN_AKA_RSP"), (xdrproc_t) xdr_CAPI2_ISIM_AUTHEN_AKA_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_ISIM_AUTHEN_HTTP_RSP), _T("MSG_ISIM_AUTHEN_HTTP_RSP"), (xdrproc_t) xdr_CAPI2_ISIM_AUTHEN_HTTP_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_ISIM_AUTHEN_GBA_BOOT_RSP), _T("MSG_ISIM_AUTHEN_GBA_BOOT_RSP"), (xdrproc_t) xdr_CAPI2_ISIM_AUTHEN_GBA_BOOT_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_ISIM_AUTHEN_GBA_NAF_RSP), _T("MSG_ISIM_AUTHEN_GBA_NAF_RSP"), (xdrproc_t) xdr_CAPI2_ISIM_AUTHEN_GBA_NAF_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },

	{ _D(MSG_PDP_GETPDPCONTEXT_REQ), _T("MSG_PDP_GETPDPCONTEXT_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETPDPCONTEXT_RSP), _T("MSG_PDP_GETPDPCONTEXT_RSP"), (xdrproc_t) xdr_PDPContext_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETPDPCONTEXT_REQ), _T("MSG_PDP_SETPDPCONTEXT_REQ"), (xdrproc_t)xdr_CAPI2_PDP_SetPDPContext_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETPDPCONTEXT_RSP), _T("MSG_PDP_SETPDPCONTEXT_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_DELETEPDPCONTEXT_REQ), _T("MSG_PDP_DELETEPDPCONTEXT_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_DELETEPDPCONTEXT_RSP), _T("MSG_PDP_DELETEPDPCONTEXT_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETSECPDPCONTEXT_REQ), _T("MSG_PDP_SETSECPDPCONTEXT_REQ"), (xdrproc_t)xdr_CAPI2_PDP_SetSecPDPContext_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETSECPDPCONTEXT_RSP), _T("MSG_PDP_SETSECPDPCONTEXT_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETGPRSQOS_REQ), _T("MSG_PDP_GETGPRSQOS_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETGPRSQOS_RSP), _T("MSG_PDP_GETGPRSQOS_RSP"), (xdrproc_t) xdr_PCHQosProfile_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETGPRSQOS_REQ), _T("MSG_PDP_SETGPRSQOS_REQ"), (xdrproc_t)xdr_CAPI2_PDP_SetGPRSQoS_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETGPRSQOS_RSP), _T("MSG_PDP_SETGPRSQOS_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_DELETEGPRSQOS_REQ), _T("MSG_PDP_DELETEGPRSQOS_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_DELETEGPRSQOS_RSP), _T("MSG_PDP_DELETEGPRSQOS_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETGPRSMINQOS_REQ), _T("MSG_PDP_GETGPRSMINQOS_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETGPRSMINQOS_RSP), _T("MSG_PDP_GETGPRSMINQOS_RSP"), (xdrproc_t) xdr_PDP_GPRSMinQoS_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETGPRSMINQOS_REQ), _T("MSG_PDP_SETGPRSMINQOS_REQ"), (xdrproc_t)xdr_CAPI2_PDP_SetGPRSMinQoS_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETGPRSMINQOS_RSP), _T("MSG_PDP_SETGPRSMINQOS_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_DELETEGPRSMINQOS_REQ), _T("MSG_PDP_DELETEGPRSMINQOS_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_DELETEGPRSMINQOS_RSP), _T("MSG_PDP_DELETEGPRSMINQOS_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_ISSECONDARYPDPDEFINED_REQ), _T("MSG_PDP_ISSECONDARYPDPDEFINED_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_ISSECONDARYPDPDEFINED_RSP), _T("MSG_PDP_ISSECONDARYPDPDEFINED_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SENDPDPACTIVATEREQ_REQ), _T("MSG_PDP_SENDPDPACTIVATEREQ_REQ"), (xdrproc_t)xdr_CAPI2_PDP_SendPDPActivateReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SENDPDPDEACTIVATEREQ_REQ), _T("MSG_PDP_SENDPDPDEACTIVATEREQ_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SENDPDPACTIVATESECREQ_REQ), _T("MSG_PDP_SENDPDPACTIVATESECREQ_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETGPRSACTIVATESTATUS_REQ), _T("MSG_PDP_GETGPRSACTIVATESTATUS_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETGPRSACTIVATESTATUS_RSP), _T("MSG_PDP_GETGPRSACTIVATESTATUS_RSP"), (xdrproc_t) xdr_PDP_GetGPRSActivateStatus_Rsp_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETMSCLASS_REQ), _T("MSG_PDP_SETMSCLASS_REQ"), (xdrproc_t)xdr_CAPI2_PDP_SetMSClass_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETMSCLASS_RSP), _T("MSG_PDP_SETMSCLASS_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETMSCLASS_REQ), _T("MSG_PDP_GETMSCLASS_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETMSCLASS_RSP), _T("MSG_PDP_GETMSCLASS_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },



	{ _D(MSG_MS_SENDCOMBINEDATTACHREQ_REQ), _T("MSG_MS_SENDCOMBINEDATTACHREQ_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_SENDCOMBINEDATTACHREQ_RSP), _T("MSG_MS_SENDCOMBINEDATTACHREQ_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_SENDDETACHREQ_REQ), _T("MSG_MS_SENDDETACHREQ_REQ"), (xdrproc_t)xdr_CAPI2_MS_SendDetachReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_SENDDETACHREQ_RSP), _T("MSG_MS_SENDDETACHREQ_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_GETGPRSATTACHSTATUS_REQ), _T("MSG_MS_GETGPRSATTACHSTATUS_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_GETGPRSATTACHSTATUS_RSP), _T("MSG_MS_GETGPRSATTACHSTATUS_RSP"), (xdrproc_t)XDR_ENUM_DEF(AttachState_t), REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_SETATTACHMODE_REQ), _T("MSG_MS_SETATTACHMODE_REQ"), (xdrproc_t)xdr_CAPI2_MS_SetAttachMode_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_SETATTACHMODE_RSP), _T("MSG_MS_SETATTACHMODE_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_GETATTACHMODE_REQ), _T("MSG_MS_GETATTACHMODE_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_GETATTACHMODE_RSP), _T("MSG_MS_GETATTACHMODE_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETUMTSTFT_REQ), _T("MSG_PDP_GETUMTSTFT_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETUMTSTFT_RSP), _T("MSG_PDP_GETUMTSTFT_RSP"), (xdrproc_t) xdr_PCHTrafficFlowTemplate_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETUMTSTFT_REQ), _T("MSG_PDP_SETUMTSTFT_REQ"), (xdrproc_t)xdr_CAPI2_PDP_SetUMTSTft_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETUMTSTFT_RSP), _T("MSG_PDP_SETUMTSTFT_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_DELETEUMTSTFT_REQ), _T("MSG_PDP_DELETEUMTSTFT_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_DELETEUMTSTFT_RSP), _T("MSG_PDP_DELETEUMTSTFT_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_ACTIVATESNDCPCONNECTION_REQ), _T("MSG_PDP_ACTIVATESNDCPCONNECTION_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_DEACTIVATESNDCPCONNECTION_REQ), _T("MSG_PDP_DEACTIVATESNDCPCONNECTION_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_DEACTIVATE_SNDCP_RSP), _T("MSG_PDP_DEACTIVATE_SNDCP_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETPDPDEFAULTCONTEXT_REQ), _T("MSG_PDP_GETPDPDEFAULTCONTEXT_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETPDPDEFAULTCONTEXT_RSP), _T("MSG_PDP_GETPDPDEFAULTCONTEXT_RSP"), (xdrproc_t) xdr_PDPDefaultContext_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETPCHCONTEXT_REQ), _T("MSG_PDP_GETPCHCONTEXT_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETPCHCONTEXT_RSP), _T("MSG_PDP_GETPCHCONTEXT_RSP"), (xdrproc_t) xdr_PDP_GetPCHContext_Rsp_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETPCHCONTEXTSTATE_REQ), _T("MSG_PDP_GETPCHCONTEXTSTATE_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETPCHCONTEXTSTATE_RSP), _T("MSG_PDP_GETPCHCONTEXTSTATE_RSP"), (xdrproc_t)XDR_ENUM_DEF(PCHContextState_t), REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_ISGPRSCALLACTIVE_REQ), _T("MSG_MS_ISGPRSCALLACTIVE_REQ"), (xdrproc_t)xdr_CAPI2_MS_IsGprsCallActive_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_ISGPRSCALLACTIVE_RSP), _T("MSG_MS_ISGPRSCALLACTIVE_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_SETCHANGPRSCALLACTIVE_REQ), _T("MSG_MS_SETCHANGPRSCALLACTIVE_REQ"), (xdrproc_t)xdr_CAPI2_MS_SetChanGprsCallActive_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_SETCHANGPRSCALLACTIVE_RSP), _T("MSG_MS_SETCHANGPRSCALLACTIVE_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_SETCIDFORGPRSACTIVECHAN_REQ), _T("MSG_MS_SETCIDFORGPRSACTIVECHAN_REQ"), (xdrproc_t)xdr_CAPI2_MS_SetCidForGprsActiveChan_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_SETCIDFORGPRSACTIVECHAN_RSP), _T("MSG_MS_SETCIDFORGPRSACTIVECHAN_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_GETGPRSACTIVECHANFROMCID_REQ), _T("MSG_MS_GETGPRSACTIVECHANFROMCID_REQ"), (xdrproc_t)xdr_CAPI2_MS_GetGprsActiveChanFromCid_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_GETGPRSACTIVECHANFROMCID_RSP), _T("MSG_MS_GETGPRSACTIVECHANFROMCID_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_GETCIDFROMGPRSACTIVECHAN_REQ), _T("MSG_MS_GETCIDFROMGPRSACTIVECHAN_REQ"), (xdrproc_t)xdr_CAPI2_MS_GetCidFromGprsActiveChan_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MS_GETCIDFROMGPRSACTIVECHAN_RSP), _T("MSG_MS_GETCIDFROMGPRSACTIVECHAN_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETPPPMODEMCID_REQ), _T("MSG_PDP_GETPPPMODEMCID_REQ"), (xdrproc_t)xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETPPPMODEMCID_RSP), _T("MSG_PDP_GETPPPMODEMCID_RSP"), (xdrproc_t)xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETPDPADDRESS_REQ), _T("MSG_PDP_GETPDPADDRESS_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETPDPADDRESS_RSP), _T("MSG_PDP_GETPDPADDRESS_RSP"), (xdrproc_t) xdr_PCHPDPAddress_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETR99UMTSMINQOS_REQ), _T("MSG_PDP_GETR99UMTSMINQOS_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETR99UMTSMINQOS_RSP), _T("MSG_PDP_GETR99UMTSMINQOS_RSP"), (xdrproc_t) xdr_PCHR99QosProfile_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETR99UMTSQOS_REQ), _T("MSG_PDP_GETR99UMTSQOS_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETR99UMTSQOS_RSP), _T("MSG_PDP_GETR99UMTSQOS_RSP"), (xdrproc_t) xdr_PCHR99QosProfile_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SENDTBFDATA_REQ), _T("MSG_PDP_SENDTBFDATA_REQ"), (xdrproc_t)xdr_CAPI2_PDP_SendTBFData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SENDTBFDATA_RSP), _T("MSG_PDP_SENDTBFDATA_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETR99UMTSMINQOS_REQ), _T("MSG_PDP_SETR99UMTSMINQOS_REQ"), (xdrproc_t)xdr_CAPI2_PDP_SetR99UMTSMinQoS_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETR99UMTSMINQOS_RSP), _T("MSG_PDP_SETR99UMTSMINQOS_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETR99UMTSQOS_REQ), _T("MSG_PDP_SETR99UMTSQOS_REQ"), (xdrproc_t)xdr_CAPI2_PDP_SetR99UMTSQoS_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETR99UMTSQOS_RSP), _T("MSG_PDP_SETR99UMTSQOS_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_TFTADDFILTER_REQ), _T("MSG_PDP_TFTADDFILTER_REQ"), (xdrproc_t)xdr_CAPI2_PDP_TftAddFilter_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_TFTADDFILTER_RSP), _T("MSG_PDP_TFTADDFILTER_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETPCHCONTEXTSTATE_REQ), _T("MSG_PDP_SETPCHCONTEXTSTATE_REQ"), (xdrproc_t)xdr_CAPI2_PDP_SetPCHContextState_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETPCHCONTEXTSTATE_RSP), _T("MSG_PDP_SETPCHCONTEXTSTATE_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETDEFAULTPDPCONTEXT_REQ), _T("MSG_PDP_SETDEFAULTPDPCONTEXT_REQ"), (xdrproc_t)xdr_CAPI2_PDP_SetDefaultPDPContext_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SETDEFAULTPDPCONTEXT_RSP), _T("MSG_PDP_SETDEFAULTPDPCONTEXT_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_READDECODEDPROTCONFIG_REQ), _T("MSG_READDECODEDPROTCONFIG_REQ"), (xdrproc_t) xdr_u_char, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_READDECODEDPROTCONFIG_RSP), _T("MSG_READDECODEDPROTCONFIG_RSP"), (xdrproc_t) xdr_PCHDecodedProtConfig_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_BUILDPROTCONFIGOPTIONS_REQ), _T("MSG_BUILDPROTCONFIGOPTIONS_REQ"), (xdrproc_t) xdr_CAPI2_BuildProtocolConfigOption_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_BUILDPROTCONFIGOPTIONS2_REQ), _T("MSG_BUILDPROTCONFIGOPTIONS2_REQ"), (xdrproc_t) xdr_CAPI2_BuildProtocolConfigOption2_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_BUILDPROTCONFIGOPTIONS_RSP), _T("MSG_BUILDPROTCONFIGOPTIONS_RSP"), (xdrproc_t) xdr_PCHProtConfig_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_BUILDPROTCONFIGOPTIONS2_RSP), _T("MSG_BUILDPROTCONFIGOPTIONS2_RSP"), (xdrproc_t) xdr_PCHProtConfig_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETNEGOTIATEDPARMS_REQ), _T("MSG_PDP_GETNEGOTIATEDPARMS_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETNEGOTIATEDPARMS_RSP), _T("MSG_PDP_GETNEGOTIATEDPARMS_RSP"), (xdrproc_t) xdr_PCHNegotiatedParms_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },

	{ _D(MSG_PDP_ACTIVATION_RSP),  _T("MSG_PDP_ACTIVATION_RSP"), (xdrproc_t) xdr_CAPI2_PDP_ACTIVATION_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_DEACTIVATION_RSP),  _T("MSG_PDP_DEACTIVATION_RSP"), (xdrproc_t) xdr_CAPI2_PDP_DEACTIVATION_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_SEC_ACTIVATION_RSP),  _T("MSG_PDP_SEC_ACTIVATION_RSP"), (xdrproc_t) xdr_CAPI2_PDP_SEC_ACTIVATION_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_ACTIVATE_SNDCP_RSP),  _T("MSG_PDP_ACTIVATE_SNDCP_RSP"), (xdrproc_t) xdr_CAPI2_PDP_ACTIVATE_SNDCP_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_GPRS_ACTIVATE_IND),  _T("MSG_GPRS_ACTIVATE_IND"), (xdrproc_t) xdr_CAPI2_GPRS_ACTIVATE_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_GPRS_DEACTIVATE_IND),  _T("MSG_GPRS_DEACTIVATE_IND"), (xdrproc_t) xdr_CAPI2_GPRS_DEACTIVATE_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_DEACTIVATION_IND),  _T("MSG_PDP_DEACTIVATION_IND"), (xdrproc_t) xdr_CAPI2_PDP_DEACTIVATION_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_PPP_SENDCLOSE_IND),  _T("MSG_PDP_PPP_SENDCLOSE_IND"), (xdrproc_t) xdr_CAPI2_PDP_DEACTIVATION_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_GPRS_MODIFY_IND),  _T("MSG_GPRS_MODIFY_IND"), (xdrproc_t) xdr_CAPI2_GPRS_MODIFY_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_GPRS_REACT_IND),  _T("MSG_GPRS_REACT_IND"), (xdrproc_t) xdr_CAPI2_GPRS_REACT_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_DATA_SUSPEND_IND),  _T("MSG_DATA_SUSPEND_IND"), (xdrproc_t) xdr_CAPI2_DATA_SUSPEND_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_DATA_RESUME_IND),  _T("MSG_DATA_RESUME_IND"),(xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0)  },
	{ _D(MSG_PDP_GETNEGQOS_REQ), _T("MSG_PDP_GETNEGQOS_REQ"), (xdrproc_t)xdr_CAPI2_PDP_ContextID_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_PDP_GETNEGQOS_RSP), _T("MSG_PDP_GETNEGQOS_RSP"), (xdrproc_t) xdr_PCHR99QosProfile_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },	
	{ _D(MSG_PDP_SENDPDPMODIFYREQ_REQ), _T("MSG_PDP_SENDPDPMODIFYREQ_REQ"), (xdrproc_t)xdr_CAPI2_PDP_SendPDPModifyReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0)},
	{ _D(MSG_PDP_MODIFICATION_RSP),  _T("MSG_PDP_MODIFICATION_RSP"), (xdrproc_t) xdr_CAPI2_PDP_MODIFICATION_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0)},

	{ _D(MSG_LCS_CPMOLRREQ_REQ), _T("MSG_LCS_CPMOLRREQ_REQ"), (xdrproc_t)xdr_CAPI2_LCS_CpMoLrReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_LCS_CPMOLRABORT_REQ), _T("MSG_LCS_CPMOLRABORT_REQ"), (xdrproc_t)xdr_CAPI2_LCS_CpMoLrAbort_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_LCS_CPMOLRABORT_RSP), _T("MSG_LCS_CPMOLRABORT_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_LCS_CPMTLRVERIFICATIONRSP_REQ), _T("MSG_LCS_CPMTLRVERIFICATIONRSP_REQ"), (xdrproc_t)xdr_CAPI2_LCS_CpMtLrVerificationRsp_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_LCS_CPMTLRVERIFICATIONRSP_RSP), _T("MSG_LCS_CPMTLRVERIFICATIONRSP_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_LCS_CPMTLRRSP_REQ), _T("MSG_LCS_CPMTLRRSP_REQ"), (xdrproc_t)xdr_CAPI2_LCS_CpMtLrRsp_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_LCS_CPMTLRRSP_RSP), _T("MSG_LCS_CPMTLRRSP_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_LCS_CPLOCUPDATERSP_REQ), _T("MSG_LCS_CPLOCUPDATERSP_REQ"), (xdrproc_t)xdr_CAPI2_LCS_CpLocUpdateRsp_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_LCS_CPLOCUPDATERSP_RSP), _T("MSG_LCS_CPLOCUPDATERSP_RSP"), (xdrproc_t) xdr_default_proc, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_LCS_DECODEPOSESTIMATE_REQ), _T("MSG_LCS_DECODEPOSESTIMATE_REQ"), (xdrproc_t)xdr_CAPI2_LCS_DecodePosEstimate_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_LCS_DECODEPOSESTIMATE_RSP), _T("MSG_LCS_DECODEPOSESTIMATE_RSP"), (xdrproc_t) xdr_LcsPosEstimateInfo_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_LCS_ENCODEASSISTANCEREQ_REQ), _T("MSG_LCS_ENCODEASSISTANCEREQ_REQ"), (xdrproc_t)xdr_CAPI2_LCS_EncodeAssistanceReq_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_LCS_ENCODEASSISTANCEREQ_RSP), _T("MSG_LCS_ENCODEASSISTANCEREQ_RSP"), (xdrproc_t) xdr_LCS_GanssAssistData_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MNSS_CLIENT_LCS_SRV_RSP),  _T("MSG_MNSS_CLIENT_LCS_SRV_RSP"), (xdrproc_t) xdr_CAPI2_MNSS_CLIENT_LCS_SRV_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MNSS_CLIENT_LCS_SRV_IND),  _T("MSG_MNSS_CLIENT_LCS_SRV_IND"), (xdrproc_t) xdr_CAPI2_MNSS_CLIENT_LCS_SRV_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MNSS_CLIENT_LCS_SRV_REL),  _T("MSG_MNSS_CLIENT_LCS_SRV_REL"), (xdrproc_t) xdr_CAPI2_MNSS_CLIENT_LCS_SRV_REL_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MNSS_CLIENT_SS_SRV_RSP),  _T("MSG_MNSS_CLIENT_SS_SRV_RSP"), (xdrproc_t) xdr_CAPI2_MNSS_CLIENT_SS_SRV_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MNSS_CLIENT_SS_SRV_REL),  _T("MSG_MNSS_CLIENT_SS_SRV_REL"), (xdrproc_t) xdr_CAPI2_MNSS_CLIENT_SS_SRV_REL_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MNSS_CLIENT_SS_SRV_IND),  _T("MSG_MNSS_CLIENT_SS_SRV_IND"), (xdrproc_t) xdr_CAPI2_MNSS_CLIENT_SS_SRV_IND_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },
	{ _D(MSG_MNSS_SATK_SS_SRV_RSP),  _T("MSG_MNSS_SATK_SS_SRV_RSP"), (xdrproc_t) xdr_CAPI2_MNSS_SATK_SS_SRV_RSP_t, REQRSP_MSG_EXT(0,NULL,NULL,0) },


#include "capi2_gen_union_map.h"
	
	/* Add other modules message to serialize/deserialize routine map */
	{ __dontcare__, "",NULL_xdrproc_t, REQRSP_MSG_EXT(0,NULL,NULL,0) } };

#undef DEFINE_XDR_UNION_MAPPING

#ifndef RPC_INCLUDED

XDR_ENUM_FUNC(Result_t)
XDR_ENUM_FUNC(MsgType_t)
XDR_ENUM_FUNC(CAPI2_MsgType_t)
XDR_ENUM_FUNC(CAPI2_Direction_t)

static struct  xdr_discrim*** tableBase = NULL;
/*
 *	Lookup table indexed by MsgType and organized into two levels
 *	to optimize the memory usage.
	Lookup table entry for MsgType = MSG_PBK_GETALPHA_REQ = 0xf601
	tableBase(+0x00)-->NULL
		|
		|(+0x01)
		------->NULL
		|
		|		...
		|
		|(+0xf6)		   (+0x00)
		|------>tableBase2------->NULL
		|			|(+0x01)
		|			|------------>&CAPI2_ReqRep_dscrm[1]
		|			|
		|			|------------>...
		|			|(+0xff)
		|			|------------>NULL
		|
		|(0xff)
		|------>NULL
		

 */

bool_t xdr_build_lookup(void)
{
	bool_t bRetVal = TRUE;
	if(tableBase == NULL)
	{
		tableBase = (struct xdr_discrim***)capi2_malloc(256*sizeof(struct xdr_discrim**));
		if(tableBase)
		{
			int i;
			for(i=0; i < 256; i++)
				tableBase[i] = NULL;
			for(i=0; i < (int)(sizeof(CAPI2_ReqRep_dscrm)/sizeof(struct  xdr_discrim)); i++)
			{
				unsigned short id = (unsigned short)CAPI2_ReqRep_dscrm[i].value;
				unsigned short id1 = ( (unsigned short)(( id & (unsigned short)0xff00 ) >> 8));
				unsigned short id2 = id & ((unsigned short)0x00ff);
				struct xdr_discrim** tableBase2 = NULL;
				if(tableBase[id1] == NULL)
				{
					int j;
					tableBase[id1] = (struct xdr_discrim**)capi2_malloc(256*sizeof(struct xdr_discrim*));
					tableBase2 = tableBase[id1];
					for(j=0; j < 256; j++)
						tableBase2[j] = NULL;
				}
				if(tableBase[id1] == NULL)
				{
					bRetVal = FALSE;
				}
				else
				{
					tableBase2 = tableBase[id1];
					if(tableBase2[id2] != NULL &&
						(id != MSG_SIM_EFILE_DATA_RSP && id != MSG_SIM_EFILE_UPDATE_RSP && id != MSG_PLMNLIST_IND) )
						_DBG_(CAPI2_TRACE("xdr_build_lookup duplicate entry = 0x%x, 0x%x, 0x%x\r\n", id, id1, id2));
					tableBase2[id2] = (struct xdr_discrim*)&CAPI2_ReqRep_dscrm[i];
					//_DBG_(CAPI2_TRACE("xdr_build_lookup = 0x%x, 0x%x, 0x%x\r\n", id, id1, id2));
				}
			}
		}
		else
		{
			bRetVal = FALSE;
		}
	}
	return bRetVal;
}

struct xdr_discrim* xdr_fast_lookup(enum_t dscm)
{
	struct xdr_discrim* nodePtr = NULL;
	unsigned short id = (unsigned short)dscm;
	unsigned short id1 = ((unsigned short)( (id & (unsigned short)(((unsigned short)0xff00))) >> 8));
	unsigned short id2 = id & ((unsigned short)0x00ff);
	struct xdr_discrim** tableBase2 = NULL;
	
	/* Make sure the table is built up */
	if(xdr_build_lookup() == FALSE)
		return NULL;

	tableBase2 = tableBase[id1];
	/* maximum message type is 0xffff */
	if(dscm > ((enum_t)0xffff))
	{
		/* should assert here */
		_DBG_(CAPI2_TRACE("xdr_fast_lookup no CAP2 entry = 0x%x, 0x%x\r\n", id, dscm));
	}
	else if(tableBase2 == NULL)
	{
		/* message not handled in CAPI2 */
		_DBG_(CAPI2_TRACE("xdr_fast_lookup no CAP2 entry = 0x%x, 0x%x, 0x%x\r\n", id, id1, id2));
	}
	else if(tableBase2[id2] != NULL)
		nodePtr = tableBase2[id2];
	else
	{
		/* message not handled in CAPI2 */
		_DBG_(CAPI2_TRACE("xdr_fast_lookup no CAP2 entry = 0x%x, 0x%x, 0x%x\r\n", id, id1, id2));
		return NULL;
	}
	/* message type sanity check invariant */
	if(nodePtr && nodePtr->value != dscm)
	{
		/* should assert here */
		_DBG_(CAPI2_TRACE("xdr_fast_lookup ERROR!!! = 0x%x, 0x%x\r\n", id, dscm));
		return NULL;
	}
	return nodePtr;
}

int
CAPI2_IsValidReqRsp(MsgType_t msgId)
{
	return( (xdr_fast_lookup((enum_t)msgId) == NULL)?0:1);
}

bool_t 
xdr_xdr_string_t(XDR *xdrs, xdr_string_t* str)
{
	return xdr_bytes(xdrs, &str->str, &str->len, 1024);
}

bool_t
xdr_CAPI2_ReqRep_t(XDR *xdrs, CAPI2_ReqRep_t* reqRep)
{
	struct xdr_discrim *entry = NULL;
	enum_t dscm = reqRep->msgId;
	/* Build the lookup table */
		if( xdr_build_lookup()&&
			xdr_u_long(xdrs, &reqRep->tid) &&
			xdr_u_char(xdrs, &reqRep->clientID) &&
			XDR_ENUM(xdrs, &reqRep->msgId, MsgType_t) &&
			XDR_ENUM(xdrs, &reqRep->respId, MsgType_t) &&
			XDR_ENUM(xdrs, &reqRep->result, Result_t) &&
			XDR_ENUM(xdrs, &reqRep->msgType, CAPI2_MsgType_t) &&
			XDR_ENUM(xdrs, &reqRep->msgDirection, CAPI2_Direction_t)
			)
	{
		XDR_LOG_RESET(xdrs, "[CAPI2] { msgId=");

		if(xdr_union(xdrs, (enum_t *)&dscm, (caddr_t)(void *)&(reqRep->req_rep_u), 
							CAPI2_ReqRep_dscrm, NULL_xdrproc_t, &entry, xdr_fast_lookup))
		{
			if(entry != NULL)
			{
				reqRep->unsize = entry->unsize;

				if(xdrs->x_op == XDR_ENCODE || xdrs->x_op == XDR_DECODE)
				{
					if(BASIC_LOG_ENABLED)
					{
						char tempStr[20];
						if(reqRep->msgId == MSG_CAPI2_ACK_RSP)
							snprintf(tempStr,20,"pend=%d",reqRep->req_rep_u.CAPI2_Ack_Rsp.isCapiPending);
						else
							strncpy(tempStr,"",20);

							_DBG_(CAPI2_TRACE("%cCAPI2 %s%c msgid=%d str=%s tid %d cid %d result %d %s\r\n", 
								(gCapi2Type == CAPI2_APPS) ? '[' : '<',
								(xdrs->x_op == XDR_DECODE)?"DE":"EN",
								(gCapi2Type == CAPI2_APPS) ? ']' : '>',
								reqRep->msgId, 
								(entry->debugStr)?entry->debugStr:"<>", 
								reqRep->tid, reqRep->clientID, reqRep->result,
								tempStr));
					}
				}

#ifdef XDR_DETAIL_LOG_ENABLED
				if(DETAIL_LOG_ENABLED)
				{
					if(reqRep->msgId != MSG_CAPI2_ACK_RSP && (xdrs->x_op == XDR_ENCODE || xdrs->x_op == XDR_DECODE))
					{

						if((strlen(log_buf)+3) < MAX_LOG_BUFFER_SIZE)
							strncat(log_buf,"}\r\n",3);

						_DBG_(Capi2_DebugOutputString(log_buf));
					}
				}
#endif

			}
			return(TRUE);
		}
	}
	
	xassert(0, dscm);
	return(FALSE);
}

XDR_ENUM_FUNC(CAPI2_ACK_Result_t)

bool_t
xdr_CAPI2_Ack_t(XDR *xdrs, CAPI2_Ack_t* data)
{
	if( xdr_u_char(xdrs, &data->isCapiPending) &&
		XDR_ENUM(xdrs,  &data->ackResult, CAPI2_ACK_Result_t)
		)
		return(TRUE);
	else
		return(FALSE);
}

#ifndef  BYPASS_IPC 
extern IPC_BufferPool ipc_capi2_pool;
#endif

Result_t CAPI2_SerializeReqRsp(CAPI2_ReqRep_t* req_rsp, UInt32 tid, MsgType_t msgId, UInt8 clientID,  Result_t result, char** stream, UInt32* len)
{
	XDR xdrs;
	UInt32 maxPktSize =0;
	struct xdr_discrim* entry = xdr_fast_lookup((enum_t)msgId);


#ifndef  BYPASS_IPC 
	PACKET_BufHandle_t bufHandle;
	if(entry == NULL)
	{
		_DBG_(CAPI2_TRACE("CAPI2_SerializeReqRsp: failed!"));
		return RESULT_ERROR;
	}
	else
	{
		maxPktSize = CAPI2_GetMaxPktSize(INTERFACE_CAPI2, entry->maxMsgSize);
	}

	bufHandle = CAPI2_PACKET_AllocateBuffer (INTERFACE_CAPI2, (maxPktSize==0) ? MAX_MSG_STREAM_SIZE : maxPktSize, 0);
	if(!bufHandle)
	{
		_DBG_(CAPI2_TRACE("CAPI2_SerializeReqRsp buffer allocation fail!!! = 0x%x, 0x%x\r\n", msgId, tid));
		//If you see this assert then likely remote processor does not free the buffers.
		//- Likely cause is CAPI2 Task on remote processor is stuck waiting on a Queue.
		//- or Watchdog issue where CAPI2 Task does not get chance to run.
		//- or Remote processor is completely DEAD
		#ifdef FUSE_COMMS_PROCESSOR
			xassert(REMOTE_AP_NOT_RESPONDING, msgId);
		#else
			xassert(REMOTE_CP_NOT_RESPONDING, msgId);
		#endif
		return RESULT_ERROR;
	}

	*stream = CAPI2_PACKET_GetBufferData(bufHandle);
	if(*stream == 0)
		return RESULT_ERROR;
#endif	

	/* Initialize the common part of the request/response */
	req_rsp->tid = tid;
	req_rsp->clientID = clientID;
	req_rsp->msgId = msgId;
	req_rsp->result = result;

#ifdef  BYPASS_IPC 
    maxPktSize = (entry && entry->maxMsgSize !=0 ) ? entry->maxMsgSize : MAX_MSG_STREAM_SIZE;
	/* Serialize request/response */
	*stream = (char*)ALLOC_STREAM(maxPktSize);
#endif

	if(DETAIL_LOG_ENABLED)
		xdrmem_create(&xdrs, *stream, (maxPktSize==0) ? MAX_MSG_STREAM_SIZE : maxPktSize, log_buf, MAX_LOG_BUFFER_SIZE, XDR_ENCODE);
	else
		xdrmem_create(&xdrs, *stream, (maxPktSize==0) ? MAX_MSG_STREAM_SIZE : maxPktSize, NULL, 0, XDR_ENCODE);

	result = (xdr_CAPI2_ReqRep_t(&xdrs, req_rsp)) ? RESULT_OK : RESULT_ERROR;

	if(result != RESULT_OK)
		_DBG_(CAPI2_TRACE("CAPI2_SerializeReqRsp: failed tid=%d cid=%d msgId=%d", tid, clientID, msgId));

	*len = xdr_getpos(&xdrs);
	xdr_destroy(&xdrs);

#ifndef WIN32
	CAPI2_LogBinaryData(req_rsp->msgId, (UInt8*)*stream, *len);
#endif

#ifndef  BYPASS_IPC 
	CAPI2_PACKET_SetBufferLength(bufHandle, *len);
	CAPI2_PACKET_SendData(0, INTERFACE_CAPI2, 0, bufHandle);
#endif
	return(result);
}

Result_t CAPI2_SerializeRsp(CAPI2_ReqRep_t* req_rsp, UInt32 tid, MsgType_t msgId, UInt8 clientID,  Result_t result, char** stream, UInt32* len)
{
	req_rsp->msgType = CAPI2_TYPE_RESPONSE;
	return CAPI2_SerializeReqRsp(req_rsp, tid, msgId, clientID, result, stream, len);
}


/* Deserialize the response stream passed by the IPC */
Result_t CAPI2_DeserializeReqRsp( char* stream, UInt32 stream_len, CAPI2_ReqRep_t** inReqRep, ResultDataBuffer_t**  inDataBuf)
{
	XDR *xdrs = NULL;
	CAPI2_ReqRep_t* reqRep = NULL;
	ResultDataBuffer_t* dataBuf;
	Result_t result = RESULT_OK;

	*inReqRep = NULL;
	*inDataBuf = NULL;

	dataBuf = (ResultDataBuffer_t*)capi2_malloc(sizeof(ResultDataBuffer_t));
	if(dataBuf)
	{
		xdrs = &dataBuf->xdrs;
		reqRep = &dataBuf->rsp;
		/* Deserialize the request/response */
		memset(reqRep, 0, sizeof(CAPI2_ReqRep_t));
		if(DETAIL_LOG_ENABLED)
			xdrmem_create( xdrs, stream, stream_len, log_buf, MAX_LOG_BUFFER_SIZE, XDR_DECODE );
		else
			xdrmem_create( xdrs, stream, stream_len, NULL, 0, XDR_DECODE );

		result = (xdr_CAPI2_ReqRep_t( xdrs, reqRep )) ? RESULT_OK : RESULT_ERROR; 
		
		if(result != RESULT_OK)
			_DBG_(CAPI2_TRACE("CAPI2_DeserializeReqRsp: failed dataBuf=%x stream=%x len=%d", (UInt32)dataBuf, (UInt32)stream, stream_len));

		*inReqRep = reqRep;
		*inDataBuf = dataBuf;
#ifndef WIN32
		CAPI2_LogBinaryData(reqRep->msgId, (UInt8*)stream, stream_len);
#endif
	}
	else
	{
		xassert(0,stream);
		result = RESULT_ERROR;
	}

	/* The AP side want to free up the deserialized buffer. */
	return(result);
}

bool_t xdr_uchar_ptr_t(XDR *xdrs, unsigned char** ptr)
{
	u_int len = (*ptr)?(strlen((char*)(*ptr))+1) : 0;
	return xdr_bytes(xdrs, (char**)ptr, &len, 512);
}

bool_t xdr_char_ptr_t(XDR *xdrs, char** ptr)
{
	u_int len = (*ptr)?(strlen(*ptr)+1) : 0;
	return xdr_bytes(xdrs, ptr, &len, 512);
}

void CAPI2_SYSFreeResultDataBuffer(ResultDataBufHandle_t dataBufHandle)
{
	ResultDataBuffer_t* dataBuf = (ResultDataBuffer_t*)dataBufHandle;
	if(dataBuf)
	{
		/* Free up the memory allocated during deserialization of the pointers */
		dataBuf->xdrs.x_op = XDR_FREE;
		xdr_CAPI2_ReqRep_t( &dataBuf->xdrs, &dataBuf->rsp );
		capi2_free(dataBuf);
	}
}


#ifdef  BYPASS_IPC 
Result_t CAPI2_DeserializeAndHandleReq( char* stream, UInt32 stream_len )
{
	CAPI2_ReqRep_t* reqRep;
	ResultDataBuffer_t*  dataBuf;

	CAPI2_DeserializeReqRsp(stream, stream_len, &reqRep, &dataBuf);

	if(reqRep)
	{
		CAPI2_HandleApRequestMsg(reqRep);
		CAPI2_SYSFreeResultDataBuffer(dataBuf);
	}


	return RESULT_OK;
}

Result_t CAPI2_DeserializeAndHandleRsp( char* stream, UInt32 stream_len )
{
	CAPI2_ReqRep_t* reqRep;
	ResultDataBuffer_t*  dataBuf;

	CAPI2_DeserializeReqRsp(stream, stream_len, &reqRep, &dataBuf);

	if(reqRep)
		CAPI2_DispatchMsg(reqRep, dataBuf);
	
	return RESULT_OK;
}
#endif

#ifdef XDR_DETAIL_LOG_ENABLED
bool_t	xdr_u_char_dbg(XDR* xdrs, u_char *p, u_char *s)
{
	XDR_LOG(xdrs,(char*)s)
	return xdr_u_char(xdrs, p);
}

bool_t	xdr_u_int16_dbg(XDR* xdrs, u_int16_t *p, u_char *s)
{
	XDR_LOG(xdrs,(char *)s)
	return xdr_u_int16_t(xdrs, p);
}

bool_t	xdr_u_long_dbg(XDR* xdrs, u_long *p, u_char *s)
{
	XDR_LOG(xdrs,(char *)s)
	return xdr_u_long(xdrs, p);
}


#define	MAX_LOG_STRING_LENGTH	78
void Capi2_DebugOutputString(char* pStr)
{
	char endChar;
	char* tempStr = pStr;
	int strLen = strlen(pStr);
	pStr += strLen;

	while(strLen > MAX_LOG_STRING_LENGTH)
	{
		endChar = tempStr[MAX_LOG_STRING_LENGTH];
		
		tempStr[MAX_LOG_STRING_LENGTH]='\0';
		CAPI2_TRACE_DETAIL(tempStr);
		tempStr[MAX_LOG_STRING_LENGTH]=endChar;
		
		tempStr += MAX_LOG_STRING_LENGTH;
		strLen = strlen(tempStr);
	}

	if(tempStr < pStr )
	{
		CAPI2_TRACE_DETAIL(tempStr);
	}
}
#endif

void CAPI2_SendAck(UInt32 tid, UInt8 clientID, CAPI2_ACK_Result_t ackResult, Boolean isCapiPending)
{
	CAPI2_ReqRep_t rsp;
	char* stream;
	UInt32 len;
	Result_t result = RESULT_OK;
	/* Create the request */
	/* Init the request */
	memset(&rsp, 0, sizeof(CAPI2_ReqRep_t));

	/* message specific */
	rsp.req_rep_u.CAPI2_Ack_Rsp.ackResult = ackResult;
	rsp.req_rep_u.CAPI2_Ack_Rsp.isCapiPending = isCapiPending;
	rsp.msgType = CAPI2_TYPE_ACK;

	/* serialize */
	CAPI2_SerializeReqRsp(&rsp, tid, MSG_CAPI2_ACK_RSP, clientID, result, &stream, &len);

	#ifdef BYPASS_IPC
		CAPI2_DeserializeAndHandleRsp(stream, len);
	#endif
}

#else

/**************************************** RPC ONLY ***********************************************************************/
RPC_XdrInfo_t* capi2GetXdrStruct(void)
{
	return (RPC_XdrInfo_t*)CAPI2_ReqRep_dscrm;
}

UInt32 capi2GetXdrStructSize(void)
{
	return (sizeof(CAPI2_ReqRep_dscrm)/sizeof(RPC_XdrInfo_t));
}

bool_t xdr_CAPI2_ReqRep_t(XDR *xdrs, CAPI2_ReqRep_t* req, xdrproc_t proc)
{
	if( xdr_u_char(xdrs, &req->clientID) &&
		XDR_ENUM(xdrs, &req->msgId, MsgType_t) &&
		XDR_ENUM(xdrs, &req->respId, MsgType_t) &&
		XDR_ENUM(xdrs, &req->result, Result_t)
		)
	{
			return proc(xdrs, &(req->req_rep_u));
	}
	
	return(FALSE);
}





Result_t CAPI2_SerializeReqRsp(CAPI2_ReqRep_t* req_rsp, UInt32 tid, MsgType_t msgId, UInt8 clientID,  Result_t result, char** stream, UInt32* len)
{
	RPC_Msg_t msg;
	
	msg.msgId = msgId;
	msg.tid = tid;
	msg.clientID = clientID;
	msg.dataBuf = (void*)req_rsp;
	msg.dataLen = 0;
	
	return RPC_SerializeReq(&msg);
}



Result_t CAPI2_SerializeRsp(CAPI2_ReqRep_t* req_rsp, UInt32 tid, MsgType_t msgId, UInt8 clientID,  Result_t result, char** stream, UInt32* len)
{
	RPC_Msg_t msg;
	
	msg.msgId = msgId;
	msg.tid = tid;
	msg.clientID = clientID;
	msg.dataBuf = (void*)req_rsp;
	msg.dataLen = 0;
	
	return RPC_SerializeRsp(&msg);
}

#endif
