obj-$(CONFIG_QCA_CLD_WLAN)	+= qcacld-3.0/

subdir-ccflags-y += $(call cc-option,-Wno-error=array-parameter)
subdir-ccflags-y += $(call cc-option,-Wno-error=maybe-uninitialized)
subdir-ccflags-y += $(call cc-option,-Wno-error=misleading-indentation)
