#/*******************************************************************************************
#Copyright 2010 Broadcom Corporation.  All rights reserved.                                */
#
#Unless you and Broadcom execute a separate written software license agreement
#governing use of this software, this software is licensed to you under the
#terms of the GNU General Public License version 2, available at
#http://www.gnu.org/copyleft/gpl.html (the "GPL").
#
#Notwithstanding the above, under no circumstances may you combine this software
#in any way with any other Broadcom software provided under a license other than
#the GPL, without Broadcom's express prior written consent.
#*******************************************************************************************/

# Makefile for the audio caph driver
# use $(srctree) for kernel top (see below) and
# use $(src) in a relative path which points to the directory

# DSP Source Files
obj-$(CONFIG_BCM_ALSA_SOUND) 	+= csl_apcmd.o
obj-$(CONFIG_BCM_ALSA_SOUND) 	+= csl_dsp.o
obj-$(CONFIG_BCM_ALSA_SOUND) 	+= csl_arm2sp.o
obj-$(CONFIG_BCM_ALSA_SOUND) 	+= csl_bttap.o
obj-$(CONFIG_BCM_ALSA_SOUND) 	+= csl_vpu.o
obj-$(CONFIG_BCM_ALSA_SOUND) 	+= csl_log.o
obj-$(CONFIG_BCM_ALSA_SOUND) 	+= csl_voip.o
obj-$(CONFIG_BCM_ALSA_SOUND) 	+= csl_voif.o
obj-$(CONFIG_BCM_ALSA_SOUND) 	+= osdw_dsp_drv.o
obj-$(CONFIG_BCM_ALSA_SOUND) 	+= csl_dsp_caph_control_api.o
obj-$(CONFIG_BCM_ALSA_SOUND) 	+= csl_dsp_cneon_api.o
obj-$(CONFIG_BCM_ALSA_SOUND) 	+= csl_dsp_common_util.o
obj-$(CONFIG_BCM_ALSA_SOUND) 	+= csl_ptt.o
