/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *
 *
 *  Unless you and Broadcom execute a separate written software license
 * agreement governing use of this software, this software is licensed to you
 * under the terms of the GNU General Public License version 2 (the "GPL"),
 * available at http://www.broadcom.com/licenses/GPLv2.php, with the
 * following added to such license:
 *
 *
 *  As a special exception, the copyright holders of this software give you
 * permission to link this software with independent modules, and to copy
 * and distribute the resulting executable under terms of your choice,
 * provided that you also meet, for each linked independent module, the terms
 * and conditions of the license of that module.  An independent module is a
 * module which is not derived from this software.  The special exception
 * does not apply to any modifications of the software.
 *
 *
 *  Notwithstanding the above, under no circumstances may you combine this
 * software in any way with any other Broadcom software provided under a
 * license other than the GPL, without Broadcom's express prior written
 * consent.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Thu Mar 19 20:05:08 2009
 *                 MD5 Checksum         93c8a72ac3ac1b3437a19d5e411b5fa8
 *
 * Compiled with:  RDB Utility          1.0
 *                 RDB Parser           3.0
 *                 rdbfirmware_split.pl 3.0
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Spec Versions:  AUXADC               1.0
 *                 AUXMIC               1.0
 *                 BBRX                 1
 *                 CAMINTF              1.0
 *                 CIPHER               1.0
 *                 CLK                  1.0
 *                 CPC_HARQ             1
 *                 CRC                  1.0
 *                 CRYPTO               1.0
 *                 CSTF                 1.0
 *                 CSTPIU               1.0
 *                 DATAPACKER           1.0
 *                 DES                  1.0
 *                 DISPC                1.1
 *                 DMAC                 1.0
 *                 DPE                  1.0
 *                 DSI                  1.0
 *                 DSP_3WIRE_INTF       1.0
 *                 DSP_AUDIO            3.0
 *                 DSP_CIPHER           1.0
 *                 DSP_CPMR             1
 *                 DSP_DIGRF            1.0
 *                 DSP_EQUALIZER        1.0
 *                 DSP_EVENT_CTRL       1.0
 *                 DSP_INTC             1
 *                 DSP_RF_GPO           1.0
 *                 DSP_RX_CONTROL       1.0
 *                 DSP_SYS_TIMER        1.0
 *                 DSP_TL3R             1
 *                 DSP_TPIF             1
 *                 DSP_TX_CONTROL       1.0
 *                 ECT                  1.0
 *                 EMI                  1
 *                 FSUSBHOST            1.0
 *                 GEA                  1.1
 *                 GPIO                 1.0
 *                 GPIO16               1.0
 *                 GPTIMERS             2.3
 *                 HARQ                 1
 *                 HSDPA_Turbo_Decoder_Module1
 *                 HSOTG                1.0
 *                 HSOTG_CTRL           1.0
 *                 HTM                  1.0
 *                 HUCM                 1
 *                 I2S                  1.0
 *                 INTC                 1.0
 *                 KEYPAD               1.0
 *                 LCDC                 1.0
 *                 MHARB                1.0
 *                 MLARB                1.0
 *                 MP                   1.0
 *                 MPHI                 1.0
 *                 MSPRO                1.0
 *                 NVSRAM               1.1
 *                 OTP                  1.0
 *                 PKA                  1.0
 *                 PTIMER               1.0
 *                 PWM_TOP              1.0
 *                 RNG                  1.0
 *                 SCLKCAL              1.0
 *                 SDHOST_SS            3.4
 *                 SIMI                 1.0
 *                 SLPTIMER             1.0
 *                 SOFTRST              1.0
 *                 SPI                  1.0
 *                 SYSCFG               1.0
 *                 UARTA                1.0
 *                 UARTB                1.0
 *                 UARTC                1.0
 *                 VEC                  1.1
 *                 WCDMA_BOOT           2.0
 *                 WCDMA_GPIO           1
 *                 WTI                  1.0
 *                 afc_top              1
 *                 bb_tx_filters_and_2091_if1
 *                 combiner             1
 *                 cpp_cluster          1
 *                 decoderh264          1.1
 *                 deinterleaver        1
 *                 edch_fng_core_top    1
 *                 encoderh264          1.1
 *                 fng_core_top         1
 *                 hs_scch              1
 *                 i2c_mm_hs            1.0
 *                 layer_1_int_cont     1
 *                 layer_2_int_cont     1
 *                 master_timer         1
 *                 modem_cfg_and_core_clks1
 *                 modem_clocks_part_1  1
 *                 modem_clocks_part_2  1
 *                 mpdxx_apb            1
 *                 pdm_top              1
 *                 prism                1
 *                 psync_for_10ppm      1
 *                 rake_fng_top         1
 *                 rake_tiny_fng_top    1
 *                 rf_interface_block1_top1
 *                 rf_interface_block2_top1
 *                 rf_interface_block3_top1
 *                 rf_interface_block4_top1
 *                 rf_interface_block5_top1
 *                 rfic_mst             1
 *                 rfic_reg_file        1
 *                 rfic_scheduler       1
 *                 rxbitlevel           1
 *                 sc_xy_state_derive   1
 *                 ssync_apb            1
 *                 sttd_apb             1
 *                 tiny_fng_core_top    1
 *                 tx                   1
 *                 wcdma_gp_timers      1
 *                 wcdma_uart           1
 *
 * RDB Files:  /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/athena_chip.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/auxmic_det.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/i2c_mm_hs.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/sdhost_ss.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/GEA.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/lcdc_top.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/pka_top.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/rng.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/uarta.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/uart_defs.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/uartb.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/uart_defs.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/uartc.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/uart_defs.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/emi.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/softrst.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/ect_top.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/sim_top.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/dmac.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/dmac_defs.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/crc.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/crypto_top.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/des.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/mipi_dsi_top.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/athena_MatrixL_reg.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/athena_MatrixH_reg.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/mp.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/encoderh264.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/decoder_h264.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/athena_intrpt_cntrl.rd
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/gptimers.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/ptimer.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/slptimer.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/wtimer.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/mspro.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/sclkcal.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/gpio16.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/gpio_defs.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/gpio.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/gpio_defs.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/keypad.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/auxadc.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/secure_otp.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/athena_syscfg.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/da.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/athena_clk_pwr_mngr.rd
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/nv_sram_if.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/spi.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/datapacker.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/cipher.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/hucm.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/displayc.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/vec.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/cstf.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/cstpiu.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/hsotg.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/hsotg_ctrl.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/fsusbhost.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/htm.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/wcdma_boot.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/pwm_top.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/dpe.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/mphi.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/camintf_top.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/afc_top.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/bbrx.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/combiner.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/cpc_harq.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/cpp_cluster.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/deinterleaver.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/edch_fng_core_top.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/fng_core_top.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/harq.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/hs_scch.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/hsdpa_turbo_decoder_mo
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/layer_1_int_cont.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/layer_2_int_cont.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/master_timer.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/modem_cfg_and_core_clk
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/modem_clocks_part_1.rd
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/modem_clocks_part_2.rd
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/mpdxx_apb.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/pdm_top.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/prism.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/psync_for_10ppm.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/rake_fng_top.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/rake_tiny_fng_top.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/rf_interface_block1_to
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/rf_interface_block2_to
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/rf_interface_block3_to
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/rf_interface_block4_to
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/rf_interface_block5_to
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/rfic_mst.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/rfic_reg_file.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/rxbitlevel.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/sc_xy_state_derive.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/ssync_apb.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/sttd_apb.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/tiny_fng_core_top.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/tx.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/wcdma_gpio.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/wcdma_gp_timers.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/wcdma_uart.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/rfic_scheduler.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/bb_tx_filters_and_2091
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/dsp_cpmr.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/dsp_tl3r.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/dsp_intc.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/dsp_tpif.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/dsp_cipher.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/dsp_equalizer.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/dsp_evnt_ctrl.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/dsp_rf_gpo.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/dsp_3_wire_intf.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/dsp_sys_timer.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/dsp_2g_digrf.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/dsp_rx_control.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/dsp_tx_control.rdb
 *             /projects/athena_ext/revA0/users/CRDB/athena_revA0/design_database/athena_chip/rdb/dsp_audio.rdb
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef __ATHENA_AHB_TL3R_H__
#define __ATHENA_AHB_TL3R_H__

/****  AHB_TL3R  ****/
//#define AHB_TL3R_BASE_ADDR      0x30400000      /* AHB_TL3R core */

typedef volatile struct {
    UInt32  m_AHB_TL3R_TL3_SHM_CFG_R0;                            // 000
    UInt32  m_AHB_TL3R_TL3_SHM_CFG_R1;                            // 004
    UInt32  m_AHB_TL3R_TL3_SHM_CFG_R2;                            // 008
    UInt32  m_AHB_TL3R_TL3_SHM_CFG_R3;                            // 00C
    UInt32  m_AHB_TL3R_TL3_SHM_CFG_R4;                            // 010
    UInt32  m_AHB_TL3R_TL3_SHM_CFG_R5;                            // 014
    UInt32  m_AHB_TL3R_TL3_SHM_CFG_R6;                            // 018
    UInt32  m_AHB_TL3R_TL3_SHM_CFG_R7;                            // 01C
    UInt32  m_RESERVED_020[1];                                  // 020
    UInt32  m_AHB_TL3R_TL3_CFG_R;                                 // 024
    UInt32  m_RESERVED_028[1];                                  // 028
    UInt32  m_AHB_TL3R_TL3_A2D_ACCESS_EN_R;                       // 02C
    UInt32  m_RESERVED_030[2];                                  // 030-038
    UInt32  m_AHB_TL3R_TL3_TEST_R;                                // 038
    UInt32  m_AHB_TL3R_TL3_CTRL_REG;                              // 03C
} BCMRDB_AHB_TL3R_REGS;

/****  AHB_TL3R  ****/
#define AHB_TL3R_TL3_SHM_CFG_R0          (AHB_TL3R_BASE_ADDR + 0x0000)  /* ARM TL3 Shared Memory Configuration Regist */
  #define AHB_TL3R_TL3_SHM_CFG_R0_sm_base_addr_31to13       0xFFFFE000
                                                       /* RW Shared Memory Base Address[31:13]. (default=0x06000000), */
  #define AHB_TL3R_TL3_SHM_CFG_R0_reserved_12to7       0x1F80
                                                                       /* RO Reserved. If write, should write all 0., */
  #define AHB_TL3R_TL3_SHM_CFG_R0_rbuf_adaptive_en       0x0040
  /* RW Shared Memory Interface Pre-Fetch Read Buffer Adaptive Burst Enable., if rbuf_en and rbuf_adaptive_en are on  */
  #define AHB_TL3R_TL3_SHM_CFG_R0_wbuf_en            0x0020                                     /* RW Shared Memory I */
  #define AHB_TL3R_TL3_SHM_CFG_R0_page_size_3to0       0x001E
  /* RW Shared Memory Interface Address formation., This field is used to limit the address ranges for a segment., ,  */
  #define AHB_TL3R_TL3_SHM_CFG_R0_rbuf_en            0x0001                                     /* RW Shared Memory I */
#define AHB_TL3R_TL3_SHM_CFG_R1          (AHB_TL3R_BASE_ADDR + 0x0004)  /* ARM TL3 Shared Memory Configuration Regist */
  #define AHB_TL3R_TL3_SHM_CFG_R1_sm_base_addr_31to13       0xFFFFE000
                                                       /* RW Shared Memory Base Address[31:13]. (default=0x06000000), */
  #define AHB_TL3R_TL3_SHM_CFG_R1_reserved_12to7       0x1F80
                                                                       /* RO Reserved. If write, should write all 0., */
  #define AHB_TL3R_TL3_SHM_CFG_R1_rbuf_adaptive_en       0x0040
  /* RW Shared Memory Interface Pre-Fetch Read Buffer Adaptive Burst Enable., if rbuf_en and rbuf_adaptive_en are on  */
  #define AHB_TL3R_TL3_SHM_CFG_R1_wbuf_en            0x0020                                     /* RW Shared Memory I */
  #define AHB_TL3R_TL3_SHM_CFG_R1_page_size_3to0       0x001E
  /* RW Shared Memory Interface Address formation., This field is used to limit the address ranges for a segment., ,  */
  #define AHB_TL3R_TL3_SHM_CFG_R1_rbuf_en            0x0001                                     /* RW Shared Memory I */
#define AHB_TL3R_TL3_SHM_CFG_R2          (AHB_TL3R_BASE_ADDR + 0x0008)  /* ARM TL3 Shared Memory Configuration Regist */
  #define AHB_TL3R_TL3_SHM_CFG_R2_sm_base_addr_31to13       0xFFFFE000
                                                       /* RW Shared Memory Base Address[31:13]. (default=0x06000000), */
  #define AHB_TL3R_TL3_SHM_CFG_R2_reserved_12to7       0x1F80
                                                                       /* RO Reserved. If write, should write all 0., */
  #define AHB_TL3R_TL3_SHM_CFG_R2_rbuf_adaptive_en       0x0040
  /* RW Shared Memory Interface Pre-Fetch Read Buffer Adaptive Burst Enable., if rbuf_en and rbuf_adaptive_en are on  */
  #define AHB_TL3R_TL3_SHM_CFG_R2_wbuf_en            0x0020                                     /* RW Shared Memory I */
  #define AHB_TL3R_TL3_SHM_CFG_R2_page_size_3to0       0x001E
  /* RW Shared Memory Interface Address formation., This field is used to limit the address ranges for a segment., ,  */
  #define AHB_TL3R_TL3_SHM_CFG_R2_rbuf_en            0x0001                                     /* RW Shared Memory I */
#define AHB_TL3R_TL3_SHM_CFG_R3          (AHB_TL3R_BASE_ADDR + 0x000C)  /* ARM TL3 Shared Memory Configuration Regist */
  #define AHB_TL3R_TL3_SHM_CFG_R3_sm_base_addr_31to13       0xFFFFE000
                                                       /* RW Shared Memory Base Address[31:13]. (default=0x06000000), */
  #define AHB_TL3R_TL3_SHM_CFG_R3_reserved_12to7       0x1F80
                                                                       /* RO Reserved. If write, should write all 0., */
  #define AHB_TL3R_TL3_SHM_CFG_R3_rbuf_adaptive_en       0x0040
  /* RW Shared Memory Interface Pre-Fetch Read Buffer Adaptive Burst Enable., if rbuf_en and rbuf_adaptive_en are on  */
  #define AHB_TL3R_TL3_SHM_CFG_R3_wbuf_en            0x0020                                     /* RW Shared Memory I */
  #define AHB_TL3R_TL3_SHM_CFG_R3_page_size_3to0       0x001E
  /* RW Shared Memory Interface Address formation., This field is used to limit the address ranges for a segment., ,  */
  #define AHB_TL3R_TL3_SHM_CFG_R3_rbuf_en            0x0001                                     /* RW Shared Memory I */
#define AHB_TL3R_TL3_SHM_CFG_R4          (AHB_TL3R_BASE_ADDR + 0x0010)  /* ARM TL3 Shared Memory Configuration Regist */
  #define AHB_TL3R_TL3_SHM_CFG_R4_sm_base_addr_31to13       0xFFFFE000
                                                       /* RW Shared Memory Base Address[31:13]. (default=0x06000000), */
  #define AHB_TL3R_TL3_SHM_CFG_R4_reserved_12to7       0x1F80
                                                                       /* RO Reserved. If write, should write all 0., */
  #define AHB_TL3R_TL3_SHM_CFG_R4_rbuf_adaptive_en       0x0040
  /* RW Shared Memory Interface Pre-Fetch Read Buffer Adaptive Burst Enable., if rbuf_en and rbuf_adaptive_en are on  */
  #define AHB_TL3R_TL3_SHM_CFG_R4_wbuf_en            0x0020                                     /* RW Shared Memory I */
  #define AHB_TL3R_TL3_SHM_CFG_R4_page_size_3to0       0x001E
  /* RW Shared Memory Interface Address formation., This field is used to limit the address ranges for a segment., ,  */
  #define AHB_TL3R_TL3_SHM_CFG_R4_rbuf_en            0x0001                                     /* RW Shared Memory I */
#define AHB_TL3R_TL3_SHM_CFG_R5          (AHB_TL3R_BASE_ADDR + 0x0014)  /* ARM TL3 Shared Memory Configuration Regist */
  #define AHB_TL3R_TL3_SHM_CFG_R5_sm_base_addr_31to13       0xFFFFE000
                                                       /* RW Shared Memory Base Address[31:13]. (default=0x06000000), */
  #define AHB_TL3R_TL3_SHM_CFG_R5_reserved_12to7       0x1F80
                                                                       /* RO Reserved. If write, should write all 0., */
  #define AHB_TL3R_TL3_SHM_CFG_R5_rbuf_adaptive_en       0x0040
  /* RW Shared Memory Interface Pre-Fetch Read Buffer Adaptive Burst Enable., if rbuf_en and rbuf_adaptive_en are on  */
  #define AHB_TL3R_TL3_SHM_CFG_R5_wbuf_en            0x0020                                     /* RW Shared Memory I */
  #define AHB_TL3R_TL3_SHM_CFG_R5_page_size_3to0       0x001E
  /* RW Shared Memory Interface Address formation., This field is used to limit the address ranges for a segment., ,  */
  #define AHB_TL3R_TL3_SHM_CFG_R5_rbuf_en            0x0001                                     /* RW Shared Memory I */
#define AHB_TL3R_TL3_SHM_CFG_R6          (AHB_TL3R_BASE_ADDR + 0x0018)  /* ARM TL3 Shared Memory Configuration Regist */
  #define AHB_TL3R_TL3_SHM_CFG_R6_sm_base_addr_31to13       0xFFFFE000
                                                       /* RW Shared Memory Base Address[31:13]. (default=0x06000000), */
  #define AHB_TL3R_TL3_SHM_CFG_R6_reserved_12to7       0x1F80
                                                                       /* RO Reserved. If write, should write all 0., */
  #define AHB_TL3R_TL3_SHM_CFG_R6_rbuf_adaptive_en       0x0040
  /* RW Shared Memory Interface Pre-Fetch Read Buffer Adaptive Burst Enable., if rbuf_en and rbuf_adaptive_en are on  */
  #define AHB_TL3R_TL3_SHM_CFG_R6_wbuf_en            0x0020                                     /* RW Shared Memory I */
  #define AHB_TL3R_TL3_SHM_CFG_R6_page_size_3to0       0x001E
  /* RW Shared Memory Interface Address formation., This field is used to limit the address ranges for a segment., ,  */
  #define AHB_TL3R_TL3_SHM_CFG_R6_rbuf_en            0x0001                                     /* RW Shared Memory I */
#define AHB_TL3R_TL3_SHM_CFG_R7          (AHB_TL3R_BASE_ADDR + 0x001C)  /* ARM TL3 Shared Memory Configuration Regist */
  #define AHB_TL3R_TL3_SHM_CFG_R7_sm_base_addr_31to13       0xFFFFE000
                                                       /* RW Shared Memory Base Address[31:13]. (default=0x06000000), */
  #define AHB_TL3R_TL3_SHM_CFG_R7_reserved_12to7       0x1F80
                                                                       /* RO Reserved. If write, should write all 0., */
  #define AHB_TL3R_TL3_SHM_CFG_R7_rbuf_adaptive_en       0x0040
  /* RW Shared Memory Interface Pre-Fetch Read Buffer Adaptive Burst Enable., if rbuf_en and rbuf_adaptive_en are on  */
  #define AHB_TL3R_TL3_SHM_CFG_R7_wbuf_en            0x0020                                     /* RW Shared Memory I */
  #define AHB_TL3R_TL3_SHM_CFG_R7_page_size_3to0       0x001E
  /* RW Shared Memory Interface Address formation., This field is used to limit the address ranges for a segment., ,  */
  #define AHB_TL3R_TL3_SHM_CFG_R7_rbuf_en            0x0001                                     /* RW Shared Memory I */
#define AHB_TL3R_TL3_CFG_R               (AHB_TL3R_BASE_ADDR + 0x0024)  /* ARM TL3 Configuration Register             */
  #define AHB_TL3R_TL3_CFG_R_icache_ahb_base_addr_16to0       0xFFFF8000
                                                       /* RW iCache MSB of AHB Base Address at 16KW (32KB) boundary., */
  #define AHB_TL3R_TL3_CFG_R_reserved_14to4          0x7FF0                                /* RO Reserved. If write,  */
  #define AHB_TL3R_TL3_CFG_R_icache_page_range_3to0       0x000F
  /* RW iCache Number of Pages (from 1 to 15 pages), , 0h: error. 0 cache size is not allowed., 1-Ch: address transla */
#define AHB_TL3R_TL3_A2D_ACCESS_EN_R     (AHB_TL3R_BASE_ADDR + 0x002C)  /* ARM TL3 A2D Access Enable Register         */
  #define AHB_TL3R_TL3_A2D_ACCESS_EN_R_ACCE55_31to8       0xFFFFFF00
  /* RW ARM to DSP Space Access Enable, If set to 24’hACCE55, allows ARM to access certain DSP address spaces., If se */
  #define AHB_TL3R_TL3_A2D_ACCESS_EN_R_reserved_7to3       0x00F8
                                                                       /* RO Reserved. If write, should write all 0., */
  #define AHB_TL3R_TL3_A2D_ACCESS_EN_R_arm2dsp_peripheral_access_en       0x0004
  /* RW ARM to DSP Access Enable for Peripherals., 0: disable, 1: enable. If set, allows ARM to access DSP TL3 periph */
  #define AHB_TL3R_TL3_A2D_ACCESS_EN_R_arm2dsp_dmem_access_en       0x0002
  /* RW ARM to DSP Access Enable for Data Memory., 0: disable, 1: enable. If set, allows ARM to access DSP TL3 data m */
  #define AHB_TL3R_TL3_A2D_ACCESS_EN_R_arm2dsp_pmem_access_en       0x0001
  /* RW ARM to DSP Access Enable for Program Memory., 0: disable, 1: enable. If set, allows ARM to access DSP TL3 pro */
#define AHB_TL3R_TL3_TEST_R              (AHB_TL3R_BASE_ADDR + 0x0038)  /* ARM DSP Access Enable Register             */
  #define AHB_TL3R_TL3_TEST_R_dsp_test_reg_31to16       0xFFFF0000
                                                                     /* RO DSP TL3 Test Register. Value from DEXTR3., */
  #define AHB_TL3R_TL3_TEST_R_arm_test_reg_15to0       0xFFFF
                                                                    /* RW ARM TL3 Test Register. Only ARM can write., */
#define AHB_TL3R_TL3_CTRL_REG            (AHB_TL3R_BASE_ADDR + 0x003C)  /* ARM TL3 Control Register                   */
  #define AHB_TL3R_TL3_CTRL_REG_reserved_31to29       0xE0000000
                                                                       /* RO Reserved. If write, should write all 0., */
  #define AHB_TL3R_TL3_CTRL_REG_ahbs_herror_status       0x10000000
  /* RW AHB Slave Port Hresp Status, 0: no error., 1: error response occurred., This bit is readable and can only be  */
  #define AHB_TL3R_TL3_CTRL_REG_arm_invalidate_prebuf       0x08000000
  /* RW ARM Shared Memory Prefetch Buffer Invalidate, 0: Continue operation., 1: Invalidate shared memory prefetch bu */
  #define AHB_TL3R_TL3_CTRL_REG_dsp2apb_clk_2to1       0x04000000
  /* RW DSP to APB Clock Ratio 2 to 1, 0: clock ratio is 1:1, 1: clock ratio is 2:1, , Example clock selections in Mh */
  #define AHB_TL3R_TL3_CTRL_REG_azarb_wait_cycles_5to0       0x03F00000
                                        /* RW AZ ARB Mux ARM access wait cycle number (N), N=0,1,2,…,63 AMBA clocks., */
  #define AHB_TL3R_TL3_CTRL_REG_reserved_19to16       0x000F0000
                                                                       /* RO Reserved. If write, should write all 0., */
  #define AHB_TL3R_TL3_CTRL_REG_reserved_15to10       0xFC00
                                                                       /* RO Reserved. If write, should write all 0., */
  #define AHB_TL3R_TL3_CTRL_REG_tl3_core_reset       0x0200                                   /* RW Software core res */
  #define AHB_TL3R_TL3_CTRL_REG_tl3_orst_reset       0x0100                                   /* RW Software orst res */
  #define AHB_TL3R_TL3_CTRL_REG_tl3_core_wait        0x0080                                   /* RW TL3_core wait. (u */
  #define AHB_TL3R_TL3_CTRL_REG_reserved_6           0x0040                                   /* RO Reserved. If writ */
  #define AHB_TL3R_TL3_CTRL_REG_tl3_wakeup_dsp       0x0020                                   /* RW TL3 wakes up DSP  */
  #define AHB_TL3R_TL3_CTRL_REG_reserved_4to0        0x001F                                   /* RO Reserved. If writ */

#endif /* __ATHENA_AHB_TL3R_H__ */
