EXTRA_CFLAGS  += -Wall -Wstrict-prototypes -Wno-trigraphs
EXTRA_CFLAGS  += -Werror
EXTRA_CFLAGS  += -Idrivers/videocore/host_support/include

obj-$(CONFIG_VC_OMX) += vc-omx.o

vc-omx-objs := vc_omx.o

