ifeq ($(CONFIG_BUILD_ARM64_DT_OVERLAY), y)

# Use the current MSM_ARCH as the target config/ Makefile
# Since Kernel SI can support multiple ARCH's this allows only the current selected target ARCH
# to compile.
include $(CAMERA_DEVICETREE_ROOT)/config/$(MSM_ARCH).mk

else
$(error CONFIG_BUILD_ARM64_DT_OVERLAY is: $(CONFIG_BUILD_ARM64_DT_OVERLAY))

endif # ($(CONFIG_BUILD_ARM64_DT_OVERLAY), y)

always-y	:= $(dtbo-y) $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo