
EXTRA_CFLAGS := -fno-inline -Wno-multichar -O0

obj-n += tv_intf/
obj-n += gencmd/
obj-n += smi/
obj-n += camera/
obj-n += graphics/



##BUILD_ROOT = ../../../../
##VC_SRC_ROOT = $(BUILD_ROOT)/hardware/broadcom/videocore/src

##obj-$(CONFIG_BCM_VCHIQ_VC04) += $(VC_SRC_ROOT)/host_support/linux/added/drivers/misc/vc04_services/vcos/ 

##obj-$(CONFIG_BCM_VCHIQ_VC04) += $(VC_SRC_ROOT)/host_support/linux/added/drivers/misc/vc04_services/vchiq/

obj-$(CONFIG_BCM_VCHIQ_VC04) += vcos/
obj-$(CONFIG_BCM_VCHIQ_VC04) += vchiq/
