CONFIG_HALL_SENSOR_NOT_USE_SWITCH := y
CONFIG_HALL_SENSOR_NOT_USE_SETUP_TIMER := y
CONFIG_HALL_SENSOR_KZFREE_RENAMED := y

ccflags-y += -DCONFIG_HALL_SENSOR_NOT_USE_SWITCH=1
ccflags-y += -DCONFIG_HALL_SENSOR_NOT_USE_SETUP_TIMER=1
ccflags-y += -DCONFIG_HALL_SENSOR_KZFREE_RENAMED=1
