#
# Makefile for the Linux Wireless network device drivers for Realtek units
#

obj-$(CONFIG_BACKPORT_RTL8180)		+= rtl818x/
obj-$(CONFIG_BACKPORT_RTL8187)		+= rtl818x/
obj-$(CONFIG_BACKPORT_RTLWIFI)		+= rtlwifi/
obj-$(CONFIG_BACKPORT_RTL8XXXU)		+= rtl8xxxu/

