
#ifndef __JAVA_PI_MNGR_H__
#define __JAVA_PI_MNGR_H__

#define MM_CLK_SRC_312M  1

enum {
	PI_MGR_PI_ID_MM,
	PI_MGR_PI_ID_HUB_SWITCHABLE,
	PI_MGR_PI_ID_HUB_AON,
	PI_MGR_PI_ID_ARM_CORE,
	PI_MGR_PI_ID_ARM_SUB_SYSTEM,
	PI_MGR_PI_ID_MODEM,
	PI_MGR_PI_ID_MAX
};

enum {
	PI_STATE_ACTIVE,
	PI_STATE_RETENTION,
	PI_STATE_SHUTDOWN,
};

enum {
	ARM_CORE_STATE_ACTIVE,
	ARM_CORE_STATE_SUSPEND,
	ARM_CORE_STATE_RETENTION,
	ARM_CORE_STATE_DORMANT,
};

enum {
	PI_OPP_XTAL,
	PI_OPP_ECONOMY,
	PI_OPP_NORMAL,
	PI_OPP_TURBO,
	PI_OPP_SUPER_TURBO,
	PI_OPP_MAX
};

#define OPP_XTAL_STRING		"XTAL"
#define OPP_ECONOMY_STRING	"ECONOMY"
#define OPP_NORMAL_STRING	"NORMAL"
#define OPP_TURBO_STRING	"TURBO"
#define OPP_SUPER_TURBO_STRING	"SUPER_TURBO"

void java_pi_mgr_init(void);

#endif /*__JAVA_PI_MNGR_H__*/
