GCOV_PROFILE := y

obj-$(CONFIG_CPU_QUIET) += driver.o governor.o governors/
obj-$(CONFIG_CPU_QUIET_STATS) += sysfs.o attribute.o
obj-$(CONFIG_TEGRA_CPUQUIET) += cpuquiet-common.o cpuquiet-tegra.o
obj-$(CONFIG_X86_CPUQUIET) += cpuquiet-common.o cpuquiet-x86.o
