
EXTRA_CFLAGS := -fno-inline -Wno-multichar -O0

obj-y += v3d/
obj-y += vce/
obj-y += fuse_log/
obj-y += modem/
obj-y += isp/
obj-y += unicam/
obj-$(CONFIG_BCM_GPS)    	 += gps.o
obj-$(CONFIG_GPIO_USER_MODE_SUPPORT)	+= user-gpio.o
