obj-$(CONFIG_TOUCHSCREEN_LXS) += lxs_touchscreen.o
obj-$(CONFIG_TOUCHSCREEN_LXS_SW82907) += lxs_touchscreen_sw82907.o

lxs_touchscreen-objs := lxs_ts.o \
		lxs_ts_fn.o \
		lxs_ts_hal.o \
		lxs_ts_hal_fw.o \
		lxs_ts_hal_prd.o \
		lxs_ts_sysfs.o

lxs_touchscreen_sw82907-objs := touch_sw82907.o
