
#EXTRA_CFLAGS := -fno-inline -Wno-multichar -O0


#obj-y   += $(CONFIG_BRCM_VIDEOCORE_ROOT)/services/gpio/kernel/
#obj-y   += $(CONFIG_BRCM_VIDEOCORE_ROOT)/services/vc_ctl/kernel/

obj-y   += vcos/
obj-y 	+= vchiq/
#obj-y   += vmcs_fb/
#obj-y 	+= vmcs_sm/

#obj-y	+= ../../../vc4-dev/src/interface/vceb/host/linux/

