
# Kernel makefile for ALPS compass infrastructure
#
#
obj-$(CONFIG_SENSORS_HSCD_INPUT)	+= alps-input.o
obj-$(CONFIG_SENSORS_HSCDTD007A)	+= hscdtd007a_i2c.o
obj-$(CONFIG_SENSORS_HSCD_BMA222)	+= hscd_bma222e.o
obj-$(CONFIG_SENSORS_HSCD_KXTF9)	+= hscd_kxtf9.o
