MODULE_NAME = sec_touchscreen
TOUCH_DRIVER_SOD := $(srctree)/drivers/sony/sec_ts
obj-m := $(MODULE_NAME).o

$(MODULE_NAME)-objs := sec_ts.o
$(MODULE_NAME)-objs += sec_ts_fn.o
$(MODULE_NAME)-objs += sec_ts_fw.o
$(MODULE_NAME)-objs += sec_ts_only_vendor.o
$(MODULE_NAME)-objs += sec_cmd.o

ifneq ($(CONFIG_ARCH_LAHAINA), y)
  include $(TOUCH_DRIVER_SOD)/config/waipio.mk
endif
