/************************************************************************************************/
/*                                                                                              */
/*  Copyright 2010  Broadcom Corporation                                                        */
/*                                                                                              */
/*     Unless you and Broadcom execute a separate written software license agreement governing  */
/*     use of this software, this software is licensed to you under the terms of the GNU        */
/*     General Public License version 2 (the GPL), available at                                 */
/*                                                                                              */
/*          http://www.broadcom.com/licenses/GPLv2.php                                          */
/*                                                                                              */
/*     with the following added to such license:                                                */
/*                                                                                              */
/*     As a special exception, the copyright holders of this software give you permission to    */
/*     link this software with independent modules, and to copy and distribute the resulting    */
/*     executable under terms of your choice, provided that you also meet, for each linked      */
/*     independent module, the terms and conditions of the license of that module.              */
/*     An independent module is a module which is not derived from this software.  The special  */
/*     exception does not apply to any modifications of the software.                           */
/*                                                                                              */
/*     Notwithstanding the above, under no circumstances may you combine this software in any   */
/*     way with any other Broadcom software provided under a license other than the GPL,        */
/*     without Broadcom's express prior written consent.                                        */
/*                                                                                              */
/************************************************************************************************/
#include <linux/kernel.h>
#include <linux/init.h>

#include <mach/pinmux.h>
#include <mach/rdb/brcm_rdb_sysmap.h>
#include <mach/rdb/brcm_rdb_chipreg.h>

#define	PIN_DESC(ball, alt1, alt2, alt3, alt4, alt5, alt6)	 	\
	[PN_##ball] = {							\
		.name		=	PN_##ball,			\
		.reg_offset	=	CHIPREG_##ball##_OFFSET,	\
		.f_tbl		=	{				\
			PF_##alt1, PF_##alt2, PF_##alt3, 		\
			PF_##alt4, PF_##alt5, PF_##alt6, 		\
		},							\
	}

/*
 * Island chip-level pin description table
 */
static const struct pin_desc pin_desc_tbl[PN_MAX] = {
	/* GPIO 178 */ PIN_DESC(NORFLSH_CE1_N,     NORFLSH_CE1_N,     VC_GPIO_0,RESERVED,    GPIO, RESERVED, RESERVED),
	/* GPIO 175 */ PIN_DESC(NORFLSH_ADDR_23,   NORFLSH_ADDR_23,   RESERVED, KP_COL_IP_6, GPIO, RESERVED, RESERVED),
	/* GPIO 174 */ PIN_DESC(NORFLSH_ADDR_22,   NORFLSH_ADDR_22,   RESERVED, KP_COL_IP_5, GPIO, RESERVED, RESERVED),
	/* GPIO 173 */ PIN_DESC(NORFLSH_ADDR_21,   NORFLSH_ADDR_21,   RESERVED, KP_COL_IP_4, GPIO, RESERVED, RESERVED),
	/* GPIO 172 */ PIN_DESC(NORFLSH_ADDR_20,   NORFLSH_ADDR_20,   RESERVED, KP_COL_IP_3, GPIO, RESERVED, RESERVED),
	/* GPIO 171 */ PIN_DESC(NORFLSH_ADDR_19,   NORFLSH_ADDR_19,   VC_GPIO_1,PWM_O_0,     GPIO, RESERVED, RESERVED),
	/* GPIO 167 */ PIN_DESC(NORFLSH_AADLAT_EN, NORFLSH_AADLAT_EN, RESERVED, KP_COL_IP_2, GPIO, RESERVED, RESERVED),
	/* GPIO 166 */ PIN_DESC(NORFLSH_ADLAT_EN,  NORFLSH_ADLAT_EN,  RESERVED, KP_COL_IP_1, GPIO, RESERVED, RESERVED),
	/* GPIO 164 */ PIN_DESC(NORFLSH_AD_14,     NORFLSH_AD_14,     RESERVED, KP_ROW_OP_0, GPIO, RESERVED, RESERVED),
	/* GPIO 163 */ PIN_DESC(NORFLSH_AD_13,     NORFLSH_AD_13,     RESERVED, KP_ROW_OP_1, GPIO, RESERVED, RESERVED),
	/* GPIO 162 */ PIN_DESC(NORFLSH_AD_12,     NORFLSH_AD_12,     RESERVED, KP_ROW_OP_2, GPIO, RESERVED, RESERVED),
	/* GPIO 161 */ PIN_DESC(NORFLSH_AD_11,     NORFLSH_AD_11,     RESERVED, KP_ROW_OP_3, GPIO, RESERVED, RESERVED),
	/* GPIO 160 */ PIN_DESC(NORFLSH_AD_10,     NORFLSH_AD_10,     RESERVED, KP_ROW_OP_4, GPIO, RESERVED, RESERVED),
	/* GPIO 159 */ PIN_DESC(NORFLSH_AD_09,     NORFLSH_AD_09,     RESERVED, KP_ROW_OP_5, GPIO, RESERVED, RESERVED),
	/* GPIO 158 */ PIN_DESC(NORFLSH_AD_08,     NORFLSH_AD_08,     RESERVED, KP_ROW_OP_6, GPIO, RESERVED, RESERVED),
	/* GPIO 157 */ PIN_DESC(NORFLSH_AD_07,     NORFLSH_AD_07,     RESERVED, KP_COL_IP_7, GPIO, RESERVED, RESERVED),
	/* GPIO 154 */ PIN_DESC(NORFLSH_AD_04,     NORFLSH_AD_04,     RESERVED, KP_COL_IP_0, GPIO, RESERVED, RESERVED),
	/* GPIO 153 */ PIN_DESC(NORFLSH_AD_03,     NORFLSH_AD_03,     RESERVED, SDIO1_DATA_3, GPIO, RESERVED, RESERVED),
	/* GPIO 152 */ PIN_DESC(NORFLSH_AD_02,     NORFLSH_AD_02,     RESERVED, SDIO1_CLK, GPIO, RESERVED, RESERVED),
	/* GPIO 151 */ PIN_DESC(NORFLSH_AD_01,     NORFLSH_AD_01,     RESERVED, SDIO1_DATA_0, GPIO, RESERVED, RESERVED),
	/* GPIO 150 */ PIN_DESC(NORFLSH_AD_00,     NORFLSH_AD_00,     RESERVED, SDIO1_CMD, GPIO, RESERVED, RESERVED),
	/* GPIO 149 */ PIN_DESC(NORFLSH_RDY,       NORFLSH_RDY,       RESERVED, SDIO1_DATA_1, GPIO, RESERVED, RESERVED),
	/* GPIO 148 */ PIN_DESC(NORFLSH_CLK_N,     NORFLSH_CLK_N,     RESERVED, SDIO1_DATA_2, GPIO, RESERVED, RESERVED),

	/* GPIO 145 */ PIN_DESC(SIM_DATA,          SIM_DATA,          PWM_O_2,  VC_GPIO_7,   GPIO, RESERVED, RESERVED),

	/* GPIO 139 */ PIN_DESC(ULPI0_CLOCK,  ULPI0_CLOCK,  RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 138 */ PIN_DESC(ULPI0_DATA_0, ULPI0_DATA_0, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 137 */ PIN_DESC(ULPI0_DATA_1, ULPI0_DATA_1, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 136 */ PIN_DESC(ULPI0_DATA_2, ULPI0_DATA_2, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 135 */ PIN_DESC(ULPI0_DATA_3, ULPI0_DATA_3, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 134 */ PIN_DESC(ULPI0_DATA_4, ULPI0_DATA_4, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 133 */ PIN_DESC(ULPI0_DATA_5, ULPI0_DATA_5, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 132 */ PIN_DESC(ULPI0_DATA_6, ULPI0_DATA_6, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 131 */ PIN_DESC(ULPI0_DATA_7, ULPI0_DATA_7, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 130 */ PIN_DESC(ULPI0_DIR,    ULPI0_DIR,    RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 129 */ PIN_DESC(ULPI0_NXT,    ULPI0_NXT,    RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 128 */ PIN_DESC(ULPI0_STP,    ULPI0_STP,    RESERVED, RESERVED, GPIO, RESERVED, RESERVED),

	/* GPIO 127 */ PIN_DESC(ULPI1_CLOCK,  ULPI1_CLOCK,  RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 126 */ PIN_DESC(ULPI1_DATA_0, ULPI1_DATA_0, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 125 */ PIN_DESC(ULPI1_DATA_1, ULPI1_DATA_1, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 124 */ PIN_DESC(ULPI1_DATA_2, ULPI1_DATA_2, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 123 */ PIN_DESC(ULPI1_DATA_3, ULPI1_DATA_3, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 122 */ PIN_DESC(ULPI1_DATA_4, ULPI1_DATA_4, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 121 */ PIN_DESC(ULPI1_DATA_5, ULPI1_DATA_5, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 120 */ PIN_DESC(ULPI1_DATA_6, ULPI1_DATA_6, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 119 */ PIN_DESC(ULPI1_DATA_7, ULPI1_DATA_7, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 118 */ PIN_DESC(ULPI1_DIR,    ULPI1_DIR,    RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 117 */ PIN_DESC(ULPI1_NXT,    ULPI1_NXT,    RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 116 */ PIN_DESC(ULPI1_STP,    ULPI1_STP,    RESERVED, RESERVED, GPIO, RESERVED, RESERVED),

	/* GPIO 111 */ PIN_DESC(NAND_RDY_1, NAND_RDY_1, RESERVED, VC_TRSTB, GPIO, RESERVED, RESERVED),
	/* GPIO 110 */ PIN_DESC(NAND_CLE,   NAND_CLE,   RESERVED, VC_TCK,   GPIO, RESERVED, RESERVED),
	/* GPIO 109 */ PIN_DESC(NAND_ALE,   NAND_ALE,   RESERVED, VC_TDI,   GPIO, RESERVED, RESERVED),
	/* GPIO 108 */ PIN_DESC(NAND_OEN,   NAND_OEN,   RESERVED, VC_TDO,   GPIO, RESERVED, RESERVED),
	/* GPIO 107 */ PIN_DESC(NAND_WEN,   NAND_WEN,   RESERVED, VC_TMS,   GPIO, RESERVED, RESERVED),

	/* GPIO 104 */ PIN_DESC(NAND_AD_5, NAND_AD_5, SDIO3_DATA_2, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 103 */ PIN_DESC(NAND_AD_4, NAND_AD_4, SDIO3_DATA_1, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 102 */ PIN_DESC(NAND_AD_3, NAND_AD_3, SDIO3_CMD, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 101 */ PIN_DESC(NAND_AD_2, NAND_AD_2, SDIO3_DATA_3, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 100 */ PIN_DESC(NAND_AD_1, NAND_AD_1, SDIO3_CLK, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 99 */  PIN_DESC(NAND_AD_0, NAND_AD_0, SDIO3_DATA_0, RESERVED, GPIO, RESERVED, RESERVED),
	
	/* GPIO 96 */ PIN_DESC(SDIO2_DATA_3, SDIO2_DATA_3, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 95 */ PIN_DESC(SDIO2_DATA_2, SDIO2_DATA_2, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 94 */ PIN_DESC(SDIO2_DATA_1, SDIO2_DATA_1, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 93 */ PIN_DESC(SDIO2_DATA_0, SDIO2_DATA_0, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 92 */ PIN_DESC(SDIO2_CMD, SDIO2_CMD, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 91 */ PIN_DESC(SDIO2_CLK, SDIO2_CLK, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	
	/* GPIO 90 */ PIN_DESC(SDIO3_DATA_3, SDIO2_DATA_7, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 89 */ PIN_DESC(SDIO3_DATA_2, SDIO2_DATA_6, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 88 */ PIN_DESC(SDIO3_DATA_1, SDIO2_DATA_5, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 87 */ PIN_DESC(SDIO3_DATA_0, SDIO2_DATA_4, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 86 */ PIN_DESC(SDIO3_CMD, RESERVED, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 85 */ PIN_DESC(SDIO3_CLK, RESERVED, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),

	/* STM pin description */	
	PIN_DESC(TRACECLK, TRACECLK, PTI_CLK, RESERVED, MDN_DSP_TRACE_CLK, GPIO, RESERVED),
	PIN_DESC(TRACEDT07, TRACEDT07, UARTB2_URXD, RESERVED, MDN_DSP_TRACE_DAT7, GPIO, RESERVED),
	PIN_DESC(TRACEDT03, TRACEDT03, PTI_DAT3, RESERVED, MDN_DSP_TRACE_DAT3, GPIO, RESERVED),
	PIN_DESC(TRACEDT02, TRACEDT02, PTI_DAT2, RESERVED, MDN_DSP_TRACE_DAT2, GPIO, RESERVED),
	PIN_DESC(TRACEDT01, TRACEDT01, PTI_DAT1, RESERVED, MDN_DSP_TRACE_DAT1, GPIO, RESERVED),
	PIN_DESC(TRACEDT00, TRACEDT00, PTI_DAT0, RESERVED, MDN_DSP_TRACE_DAT0, GPIO, RESERVED),

	/* GPIO 61 */ PIN_DESC(PMU_SCL, PMU_SCL, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 60 */ PIN_DESC(PMU_SDA, PMU_SDA, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),

	/* GPIO 59 */ PIN_DESC(BSC2_SCL, BSC2_SCL, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 58 */ PIN_DESC(BSC2_SDA, BSC2_SDA, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),

	/* GPIO 57 */ PIN_DESC(VC_CAM1_SCL, VC_CAM1_SCL, BSC1_SCL, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 56 */ PIN_DESC(VC_CAM1_SDA, VC_CAM1_SDA, BSC1_SDA, RESERVED, GPIO, RESERVED, RESERVED),

	/* GPIO 55 */ PIN_DESC(HDMI_SCL, HDMI_SCL, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 54 */ PIN_DESC(HDMI_SDA, HDMI_SDA, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),

	/* GPIO 47 */ PIN_DESC(LCD_R_7, LCD_R_7, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 46 */ PIN_DESC(LCD_R_6, LCD_R_6, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 45 */ PIN_DESC(LCD_R_5, LCD_R_5, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 44 */ PIN_DESC(LCD_R_4, LCD_R_4, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 43 */ PIN_DESC(LCD_R_3, LCD_R_3, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 42 */ PIN_DESC(LCD_R_2, LCD_R_2, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 41 */ PIN_DESC(LCD_R_1, LCD_R_1, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 40 */ PIN_DESC(LCD_R_0, LCD_R_0, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),

	/* GPIO 39 */ PIN_DESC(LCD_G_7, LCD_G_7, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 38 */ PIN_DESC(LCD_G_6, LCD_G_6, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 37 */ PIN_DESC(LCD_G_5, LCD_G_5, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 36 */ PIN_DESC(LCD_G_4, LCD_G_4, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 35 */ PIN_DESC(LCD_G_3, LCD_G_3, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 34 */ PIN_DESC(LCD_G_2, LCD_G_2, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 33 */ PIN_DESC(LCD_G_1, LCD_G_1, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 32 */ PIN_DESC(LCD_G_0, LCD_G_0, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),

	/* GPIO 31 */ PIN_DESC(LCD_B_7, LCD_B_7, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 30 */ PIN_DESC(LCD_B_6, LCD_B_6, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 29 */ PIN_DESC(LCD_B_5, LCD_B_5, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 28 */ PIN_DESC(LCD_B_4, LCD_B_4, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 27 */ PIN_DESC(LCD_B_3, LCD_B_3, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 26 */ PIN_DESC(LCD_B_2, LCD_B_2, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 25 */ PIN_DESC(LCD_B_1, LCD_B_1, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 24 */ PIN_DESC(LCD_B_0, LCD_B_0, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),

	/* GPIO 23 */ PIN_DESC(LCD_HSYNC, LCD_HSYNC, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 22 */ PIN_DESC(LCD_VSYNC, LCD_VSYNC, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 21 */ PIN_DESC(LCD_OE,    LCD_OE,    RESERVED, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 20 */ PIN_DESC(LCD_PCLK,  LCD_PCLK,  RESERVED, RESERVED, GPIO, RESERVED, RESERVED),

	/* GPIO 10 */  PIN_DESC(PMU_INT, RESERVED, RESERVED, RESERVED, GPIO, RESERVED, RESERVED),

	/* GPIO 3 */  PIN_DESC(GPIO_3, RESERVED, VC_GPCLK_0, RESERVED, GPIO, RESERVED, RESERVED),
	/* GPIO 2 */  PIN_DESC(GPIO_2, RESERVED, VC_GPCLK_1, RESERVED, GPIO, RESERVED, RESERVED),
};

struct chip_pin_desc g_chip_pin_desc = {
	.desc_tbl	=	pin_desc_tbl,
};

int __init pinmux_chip_init (void)
{
	g_chip_pin_desc.base = ioremap(CHIPREGS_BASE_ADDR, SZ_4K);
	BUG_ON (!g_chip_pin_desc.base);

	return 0;
}
