/*****************************************************************************
* Copyright 2010 Broadcom Corporation.  All rights reserved.
*
* Unless you and Broadcom execute a separate written software license
* agreement governing use of this software, this software is licensed to you
* under the terms of the GNU General Public License version 2, available at
* http://www.broadcom.com/licenses/GPLv2.php (the "GPL").
*
* Notwithstanding the above, under no circumstances may you combine this
* software in any way with any other Broadcom software provided under a
* license other than the GPL, without Broadcom's express prior written
* consent.
*****************************************************************************/
#ifndef __ARM_ARCH_BCM2165X_CLOCK_MGR_H
#define __ARM_ARCH_BCM2165X_CLOCK_MGR_H

/*Defines used by Kona*/
#define	CLK_WR_ACCESS_PASSWORD	0x00A5A5



#define	FRAC_1M_REF_CLK_NAME_STR "frac_1m_clk"
#define	REF_96M_VARVDD_REF_CLK_NAME_STR "ref_96m_varvdd_clk"
#define	REF_96M_REF_CLK_NAME_STR "ref_48m_clk"
#define	VAR_96M_REF_CLK_NAME_STR "var_48m_clk"
#define	VAR_500M_VARVDD_REF_CLK_NAME_STR "var_500m_varvdd_clk"
#define	REF_312M_REF_CLK_NAME_STR "ref_312m_clk"
#define	REF_208M_REF_CLK_NAME_STR "ref_208m_clk"
#define	REF_156M_REF_CLK_NAME_STR "ref_156m_clk"
#define	REF_104M_REF_CLK_NAME_STR "ref_104m_clk"
#define	REF_52M_REF_CLK_NAME_STR "ref_52m_clk"
#define	REF_13M_REF_CLK_NAME_STR "ref_13m_clk"
#define	REF_26M_REF_CLK_NAME_STR "ref_26m_clk"
#define	VAR_312M_REF_CLK_NAME_STR "var_312m_clk"
#define	VAR_208M_REF_CLK_NAME_STR "var_208m_clk"
#define	VAR_156M_REF_CLK_NAME_STR "var_156m_clk"
#define	VAR_104M_REF_CLK_NAME_STR "var_104m_clk"
#define	VAR_52M_REF_CLK_NAME_STR "var_52m_clk"
#define	VAR_13M_REF_CLK_NAME_STR "var_13m_clk"
#define	DFT_19_5M_REF_CLK_NAME_STR "dft_19_5m_clk"
#define	REF_CX40_VARVDD_REF_CLK_NAME_STR "ref_cx40_varvdd_clk"
#define	REF_CX40_REF_CLK_NAME_STR "ref_cx40_clk"
#define	KHUB_CCU_CLK_NAME_STR "hub_ccu_clk"
#define	NOR_APB_BUS_CLK_NAME_STR "nor_apb_clk"
#define	AUDIOH_APB_BUS_CLK_NAME_STR "audioh_apb_clk"
#define	SSP3_APB_BUS_CLK_NAME_STR "ssp3_apb_clk"
#define	SSP4_APB_BUS_CLK_NAME_STR "ssp4_apb_clk"
#define	TMON_APB_BUS_CLK_NAME_STR "tmon_apb_clk"
#define	NOR_BUS_CLK_NAME_STR "nor_clk"
#define	AUDIOH_26M_PERI_CLK_NAME_STR "audioh_26m_clk"
#define	AUDIOH_2P4M_PERI_CLK_NAME_STR "audioh_2p4m_clk"
#define	AUDIOH_156M_PERI_CLK_NAME_STR "audioh_156m_clk"
#define	SSP3_AUDIO_PERI_CLK_NAME_STR "ssp3_audio_clk"
#define	SSP3_PERI_CLK_NAME_STR "ssp3_clk"
#define	SSP4_AUDIO_PERI_CLK_NAME_STR "ssp4_audio_clk"
#define	SSP4_PERI_CLK_NAME_STR "ssp4_clk"
#define	TMON_1M_PERI_CLK_NAME_STR "tmon_1m_clk"
#define	CAPH_SRCMIXER_PERI_CLK_NAME_STR "caph_srcmixer_clk"
#define	KHUBAON_CCU_CLK_NAME_STR "khubaon_ccu_clk"
#define	HUB_TIMER_APB_BUS_CLK_NAME_STR "hub_timer_apb_clk"
#define	ACI_APB_BUS_CLK_NAME_STR "aci_apb_clk"
#define	SIM_APB_BUS_CLK_NAME_STR "sim_apb_clk"
#define	SIM2_APB_BUS_CLK_NAME_STR "sim2_apb_clk"
#define	SIM_PERI_CLK_NAME_STR "sim_clk"
#define	SIM2_PERI_CLK_NAME_STR "sim2_clk"
#define	HUB_TIMER_PERI_CLK_NAME_STR "hub_timer_clk"
#define	KPM_CCU_CLK_NAME_STR "kpm_ccu_clk"
#define	USB_OTG_AHB_BUS_CLK_NAME_STR "usb_otg_clk"
#define	SDIO2_AHB_BUS_CLK_NAME_STR "sdio2_ahb_clk"
#define	SDIO3_AHB_BUS_CLK_NAME_STR "sdio3_ahb_clk"
#define	SDIO1_AHB_BUS_CLK_NAME_STR "sdio1_ahb_clk"
#define	SDIO2_PERI_CLK_NAME_STR "sdio2_clk"
#define	SDIO2_SLEEP_PERI_CLK_NAME_STR "sdio2_sleep_clk"
#define	SDIO3_PERI_CLK_NAME_STR "sdio3_clk"
#define	SDIO3_SLEEP_PERI_CLK_NAME_STR "sdio3_sleep_clk"
#define	SDIO1_PERI_CLK_NAME_STR "sdio1_clk"
#define	SDIO1_SLEEP_PERI_CLK_NAME_STR "sdio1_sleep_clk"
#define	KPS_CCU_CLK_NAME_STR "kps_ccu_clk"
#define	UARTB_APB_BUS_CLK_NAME_STR "uartb_apb_clk"
#define	UARTB2_APB_BUS_CLK_NAME_STR "uartb2_apb_clk"
#define	UARTB3_APB_BUS_CLK_NAME_STR "uartb3_apb_clk"
#define	DMAC_MUX_APB_BUS_CLK_NAME_STR "dmac_mux_apb_clk"
#define	BSC1_APB_BUS_CLK_NAME_STR "bsc1_apb_clk"
#define	BSC2_APB_BUS_CLK_NAME_STR "bsc2_apb_clk"
#define	PWM_APB_BUS_CLK_NAME_STR "pwm_apb_clk"
#define	SSP0_APB_BUS_CLK_NAME_STR "ssp0_apb_clk"
#define	UARTB_PERI_CLK_NAME_STR "uartb_clk"
#define	UARTB2_PERI_CLK_NAME_STR "uartb2_clk"
#define	UARTB3_PERI_CLK_NAME_STR "uartb3_clk"
#define	SSP0_AUDIO_PERI_CLK_NAME_STR "ssp0_audio_clk"
#define	BSC1_PERI_CLK_NAME_STR "bsc1_clk"
#define	BSC2_PERI_CLK_NAME_STR "bsc2_clk"
#define	PWM_PERI_CLK_NAME_STR "pwm_clk"
#define	SSP0_PERI_CLK_NAME_STR "ssp0_clk"
#define	MM_CCU_CLK_NAME_STR "mm_ccu_clk"
#define	mm_switch_axi_PERI_CLK_NAME_STR "mm_switch_axi_clk"
#define	CSI0_AXI_BUS_CLK_NAME_STR "csi0_axi_clk"
#define	CSI1_AXI_BUS_CLK_NAME_STR "csi1_axi_clk"
#define	ISP_AXI_BUS_CLK_NAME_STR "isp_axi_clk"
#define	SMI_AXI_BUS_CLK_NAME_STR "smi_axi_clk"
#define	VCE_AXI_BUS_CLK_NAME_STR "vce_axi_clk"
#define	DSI0_AXI_BUS_CLK_NAME_STR "dsi0_axi_clk"
#define	DSI1_AXI_BUS_CLK_NAME_STR "dsi1_axi_clk"
#define	MM_APB_BUS_CLK_NAME_STR "mm_apb_clk"
#define	SPI_APB_BUS_CLK_NAME_STR "spi_apb_clk"
#define	MM_DMA_AXI_BUS_CLK_NAME_STR "mm_dma_axi_clk"
#define	V3D_AXI_BUS_CLK_NAME_STR "v3d_axi_clk"
#define	CSI0_LP_PERI_CLK_NAME_STR "csi0_lp_clk"
#define	CSI1_LP_PERI_CLK_NAME_STR "csi1_lp_clk"
#define	SMI_PERI_CLK_NAME_STR "smi_clk"
#define	DSI0_ESC_PERI_CLK_NAME_STR "dsi0_esc_clk"
#define	DSI1_ESC_PERI_CLK_NAME_STR "dsi1_esc_clk"
#define	DSI_PLL_O_DSI_PLL_PERI_CLK_NAME_STR "dsi_pll_o_dsi_pll_clk"


/*
Clock ids
*/
enum
{
    	CLK_FRAC_1M_REF_CLK_ID,
	CLK_REF_96M_VARVDD_REF_CLK_ID,
	CLK_REF_96M_REF_CLK_ID,
	CLK_VAR_96M_REF_CLK_ID,
	CLK_VAR_500M_VARVDD_REF_CLK_ID,
	CLK_REF_312M_REF_CLK_ID,
	CLK_REF_208M_REF_CLK_ID,
	CLK_REF_156M_REF_CLK_ID,
	CLK_REF_104M_REF_CLK_ID,
	CLK_REF_52M_REF_CLK_ID,
	CLK_REF_13M_REF_CLK_ID,
	CLK_REF_26M_REF_CLK_ID,
	CLK_VAR_312M_REF_CLK_ID,
	CLK_VAR_208M_REF_CLK_ID,
	CLK_VAR_156M_REF_CLK_ID,
	CLK_VAR_104M_REF_CLK_ID,
	CLK_VAR_52M_REF_CLK_ID,
	CLK_VAR_13M_REF_CLK_ID,
	CLK_DFT_19_5M_REF_CLK_ID,
	CLK_REF_CX40_VARVDD_REF_CLK_ID,
	CLK_REF_CX40_REF_CLK_ID,
	CLK_KHUB_CCU_CLK_ID,
	CLK_NOR_APB_BUS_CLK_ID,
	CLK_AUDIOH_APB_BUS_CLK_ID,
	CLK_SSP3_APB_BUS_CLK_ID,
	CLK_SSP4_APB_BUS_CLK_ID,
	CLK_TMON_APB_BUS_CLK_ID,
	CLK_NOR_BUS_CLK_ID,
	CLK_AUDIOH_26M_PERI_CLK_ID,
	CLK_AUDIOH_2P4M_PERI_CLK_ID,
	CLK_AUDIOH_156M_PERI_CLK_ID,
	CLK_SSP3_AUDIO_PERI_CLK_ID,
	CLK_SSP3_PERI_CLK_ID,
	CLK_SSP4_AUDIO_PERI_CLK_ID,
	CLK_SSP4_PERI_CLK_ID,
	CLK_TMON_1M_PERI_CLK_ID,
	CLK_CAPH_SRCMIXER_PERI_CLK_ID,
	CLK_KHUBAON_CCU_CLK_ID,
	CLK_HUB_TIMER_APB_BUS_CLK_ID,
	CLK_ACI_APB_BUS_CLK_ID,
	CLK_SIM_APB_BUS_CLK_ID,
	CLK_SIM2_APB_BUS_CLK_ID,
	CLK_SIM_PERI_CLK_ID,
	CLK_SIM2_PERI_CLK_ID,
	CLK_HUB_TIMER_PERI_CLK_ID,
	CLK_KPM_CCU_CLK_ID,
	CLK_USB_OTG_AHB_BUS_CLK_ID,
	CLK_SDIO2_AHB_BUS_CLK_ID,
	CLK_SDIO3_AHB_BUS_CLK_ID,
	CLK_SDIO1_AHB_BUS_CLK_ID,
	CLK_SDIO2_PERI_CLK_ID,
	CLK_SDIO2_SLEEP_PERI_CLK_ID,
	CLK_SDIO3_PERI_CLK_ID,
	CLK_SDIO3_SLEEP_PERI_CLK_ID,
	CLK_SDIO1_PERI_CLK_ID,
	CLK_SDIO1_SLEEP_PERI_CLK_ID,
	CLK_KPS_CCU_CLK_ID,
	CLK_UARTB_APB_BUS_CLK_ID,
	CLK_UARTB2_APB_BUS_CLK_ID,
	CLK_UARTB3_APB_BUS_CLK_ID,
	CLK_DMAC_MUX_APB_BUS_CLK_ID,
	CLK_BSC1_APB_BUS_CLK_ID,
	CLK_BSC2_APB_BUS_CLK_ID,
	CLK_PWM_APB_BUS_CLK_ID,
	CLK_SSP0_APB_BUS_CLK_ID,
	CLK_UARTB_PERI_CLK_ID,
	CLK_UARTB2_PERI_CLK_ID,
	CLK_UARTB3_PERI_CLK_ID,
	CLK_SSP0_AUDIO_PERI_CLK_ID,
	CLK_BSC1_PERI_CLK_ID,
	CLK_BSC2_PERI_CLK_ID,
	CLK_PWM_PERI_CLK_ID,
	CLK_SSP0_PERI_CLK_ID,
	CLK_MM_CCU_CLK_ID,
	CLK_mm_switch_axi_PERI_CLK_ID,
	CLK_CSI0_AXI_BUS_CLK_ID,
	CLK_CSI1_AXI_BUS_CLK_ID,
	CLK_ISP_AXI_BUS_CLK_ID,
	CLK_SMI_AXI_BUS_CLK_ID,
	CLK_VCE_AXI_BUS_CLK_ID,
	CLK_DSI0_AXI_BUS_CLK_ID,
	CLK_DSI1_AXI_BUS_CLK_ID,
	CLK_MM_APB_BUS_CLK_ID,
	CLK_SPI_APB_BUS_CLK_ID,
	CLK_MM_DMA_AXI_BUS_CLK_ID,
	CLK_V3D_AXI_BUS_CLK_ID,
	CLK_CSI0_LP_PERI_CLK_ID,
	CLK_CSI1_LP_PERI_CLK_ID,
	CLK_SMI_PERI_CLK_ID,
	CLK_DSI0_ESC_PERI_CLK_ID,
	CLK_DSI1_ESC_PERI_CLK_ID,
	CLK_DSI_PLL_O_DSI_PLL_PERI_CLK_ID,

};



#define FRAC_1M_REF_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH|ENABLE_ON_INIT
#define REF_96M_VARVDD_REF_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define REF_96M_REF_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH|ENABLE_ON_INIT
#define VAR_96M_REF_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH|ENABLE_ON_INIT
#define VAR_500M_VARVDD_REF_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define REF_312M_REF_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH|ENABLE_ON_INIT
#define REF_208M_REF_CLK_FLAGS 			0
#define REF_156M_REF_CLK_FLAGS 			0
#define REF_104M_REF_CLK_FLAGS 			0
#define REF_52M_REF_CLK_FLAGS 			0
#define REF_13M_REF_CLK_FLAGS 			0
#define REF_26M_REF_CLK_FLAGS 			0
#define VAR_312M_REF_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH|ENABLE_ON_INIT
#define VAR_208M_REF_CLK_FLAGS 			0
#define VAR_156M_REF_CLK_FLAGS 			0
#define VAR_104M_REF_CLK_FLAGS 			0
#define VAR_52M_REF_CLK_FLAGS 			0
#define VAR_13M_REF_CLK_FLAGS 			0
#define DFT_19_5M_REF_CLK_FLAGS 			0
#define REF_CX40_VARVDD_REF_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define REF_CX40_REF_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define KHUB_CCU_CLK_FLAGS 			CCU_TARGET_AC
#define NOR_APB_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define AUDIOH_APB_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define SSP3_APB_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define SSP4_APB_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define TMON_APB_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define NOR_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define AUDIOH_26M_PERI_CLK_FLAGS 			HYST_ENABLE|HYST_HIGH
#define AUDIOH_2P4M_PERI_CLK_FLAGS 			HYST_ENABLE|HYST_HIGH|RATE_FIXED
#define AUDIOH_156M_PERI_CLK_FLAGS 			HYST_ENABLE|HYST_HIGH
#define SSP3_AUDIO_PERI_CLK_FLAGS 			HYST_ENABLE|HYST_HIGH
#define SSP3_PERI_CLK_FLAGS 			HYST_ENABLE|HYST_HIGH
#define SSP4_AUDIO_PERI_CLK_FLAGS 			HYST_ENABLE|HYST_HIGH
#define SSP4_PERI_CLK_FLAGS 			HYST_ENABLE|HYST_HIGH
#define TMON_1M_PERI_CLK_FLAGS 			HYST_ENABLE|HYST_HIGH
#define CAPH_SRCMIXER_PERI_CLK_FLAGS 			HYST_ENABLE|HYST_HIGH
#define KHUBAON_CCU_CLK_FLAGS 			CCU_TARGET_AC
#define HUB_TIMER_APB_BUS_CLK_FLAGS 	ENABLE_ON_INIT|	HYST_ENABLE | HYST_HIGH
#define ACI_APB_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define SIM_APB_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define SIM2_APB_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define SIM_PERI_CLK_FLAGS 			HYST_ENABLE|HYST_HIGH
#define SIM2_PERI_CLK_FLAGS 			HYST_ENABLE|HYST_HIGH
#define HUB_TIMER_PERI_CLK_FLAGS 		ENABLE_ON_INIT|HYST_ENABLE|HYST_HIGH
#define KPM_CCU_CLK_FLAGS 			CCU_TARGET_AC
#define USB_OTG_AHB_BUS_CLK_FLAGS 			0
#define SDIO2_AHB_BUS_CLK_FLAGS 			0
#define SDIO3_AHB_BUS_CLK_FLAGS 			0
#define SDIO1_AHB_BUS_CLK_FLAGS 			0
#define SDIO2_PERI_CLK_FLAGS 			0
#define SDIO2_SLEEP_PERI_CLK_FLAGS 			0
#define SDIO3_PERI_CLK_FLAGS 			0
#define SDIO3_SLEEP_PERI_CLK_FLAGS 			0
#define SDIO1_PERI_CLK_FLAGS 			0
#define SDIO1_SLEEP_PERI_CLK_FLAGS 			0
#define KPS_CCU_CLK_FLAGS 			CCU_TARGET_AC
#define UARTB_APB_BUS_CLK_FLAGS 			0
#define UARTB2_APB_BUS_CLK_FLAGS 			0
#define UARTB3_APB_BUS_CLK_FLAGS 			0
#define DMAC_MUX_APB_BUS_CLK_FLAGS 			0
#define BSC1_APB_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define BSC2_APB_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define PWM_APB_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define SSP0_APB_BUS_CLK_FLAGS 			0
#define UARTB_PERI_CLK_FLAGS 			0
#define UARTB2_PERI_CLK_FLAGS 			0
#define UARTB3_PERI_CLK_FLAGS 			0
#define SSP0_AUDIO_PERI_CLK_FLAGS 			HYST_ENABLE|HYST_HIGH
#define BSC1_PERI_CLK_FLAGS 			0
#define BSC2_PERI_CLK_FLAGS 			0
#define PWM_PERI_CLK_FLAGS 				RATE_FIXED
#define SSP0_PERI_CLK_FLAGS 			0
#define MM_CCU_CLK_FLAGS 			CCU_TARGET_AC
#define mm_switch_axi_PERI_CLK_FLAGS		HYST_ENABLE|HYST_HIGH
#define CSI0_AXI_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define CSI1_AXI_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define ISP_AXI_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define SMI_AXI_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define VCE_AXI_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define DSI0_AXI_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define DSI1_AXI_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define MM_APB_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define SPI_APB_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define MM_DMA_AXI_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define V3D_AXI_BUS_CLK_FLAGS 			HYST_ENABLE | HYST_HIGH
#define CSI0_LP_PERI_CLK_FLAGS 			HYST_ENABLE|HYST_HIGH
#define CSI1_LP_PERI_CLK_FLAGS 			HYST_ENABLE|HYST_HIGH
#define SMI_PERI_CLK_FLAGS 			HYST_ENABLE|HYST_HIGH
#define DSI0_ESC_PERI_CLK_FLAGS 			HYST_ENABLE|HYST_HIGH
#define DSI1_ESC_PERI_CLK_FLAGS 			HYST_ENABLE|HYST_HIGH
#define DSI_PLL_O_DSI_PLL_PERI_CLK_FLAGS 			HYST_ENABLE|HYST_HIGH

#endif /* __ARM_ARCH_BCM2165X_CLOCK_MGR_H  */
