/*****************************************************************************
* Copyright 2010 Broadcom Corporation.  All rights reserved.
*
* Unless you and Broadcom execute a separate written software license
* agreement governing use of this software, this software is licensed to you
* under the terms of the GNU General Public License version 2, available at
* http://www.broadcom.com/licenses/GPLv2.php (the "GPL").
*
* Notwithstanding the above, under no circumstances may you combine this
* software in any way with any other Broadcom software provided under a
* license other than the GPL, without Broadcom's express prior written
* consent.
*****************************************************************************/
#ifndef __ARM_ARCH_BCM2165X_CLOCK_H
#define __ARM_ARCH_BCM2165X_CLOCK_H

/* clock strings */
#define		BCM2165X_CLK_ARM_STR_ID				"arm_clk"
#define		BCM2165X_CLK_USBH_48M_STR_ID			"usbh_48m_clk"
#define		BCM2165X_CLK__STR_ID				"kpm_ccu_clk"
#define		BCM2165X_CLK__STR_ID				"kps_ccu_clk"
#define		BCM2165X_CLK__STR_ID				"mm_ccu_clk"
#define		BCM2165X_CLK__STR_ID				"khubaon_ccu_clk"
#define		BCM2165X_CLK__STR_ID				"khub_ccu_clk"
#define		BCM2165X_CLK__STR_ID				"sdio1_ahb_clk"
#define		BCM2165X_CLK__STR_ID				"sdio2_ahb_clk"
#define		BCM2165X_CLK__STR_ID				"sdio3_ahb_clk"
#define		BCM2165X_CLK__STR_ID				"sdio4_ahb_clk"
#define		BCM2165X_CLK__STR_ID				"sdio1_sleep_clk"
#define		BCM2165X_CLK__STR_ID				"sdio2_sleep_clk"
#define		BCM2165X_CLK__STR_ID				"sdio3_sleep_clk"
#define		BCM2165X_CLK__STR_ID				"sdio4_sleep_clk"
#define		BCM2165X_CLK__STR_ID				"bsc1_apb_clk"
#define		BCM2165X_CLK__STR_ID				"bsc2_apb_clk"
#define		BCM2165X_CLK__STR_ID				"hsm_ahb_clk"
#define		BCM2165X_CLK__STR_ID				"hsm_apb_clk"
#define		BCM2165X_CLK__STR_ID				"spum_open_apb_clk"
#define		BCM2165X_CLK__STR_ID				"spum_sec_apb_clk"
#define		BCM2165X_CLK__STR_ID				"apb1_clk"
#define		BCM2165X_CLK__STR_ID				"timers_apb_clk"
#define		BCM2165X_CLK__STR_ID				"ssp0_apb_clk"
#define		BCM2165X_CLK__STR_ID				"dmac_mux_apb_clk"
#define		BCM2165X_CLK__STR_ID				"uartb3_apb_clk"
#define		BCM2165X_CLK__STR_ID				"uartb2_apb_clk"
#define		BCM2165X_CLK__STR_ID				"uartb_apb_clk"
#define		BCM2165X_CLK__STR_ID				"pwm_apb_clk"
#define		BCM2165X_CLK__STR_ID				"spi_apb_clk"
#define		BCM2165X_CLK__STR_ID				"mm_apb_clk"
#define		BCM2165X_CLK__STR_ID				"csi0_axi_clk"
#define		BCM2165X_CLK__STR_ID				"csi1_axi_clk"
#define		BCM2165X_CLK__STR_ID				"dsi0_axi_clk"
#define		BCM2165X_CLK__STR_ID				"dsi1_axi_clk"
#define		BCM2165X_CLK__STR_ID				"v3d_axi_clk"
#define		BCM2165X_CLK__STR_ID				"vce_axi_clk"
#define		BCM2165X_CLK__STR_ID				"isp_axi_clk"
#define		BCM2165X_CLK__STR_ID				"mm_dma_axi_clk"
#define		BCM2165X_CLK__STR_ID				"smi_axi_clk"
#define		BCM2165X_CLK__STR_ID				"pwrmgr_axi_clk"
#define		BCM2165X_CLK__STR_ID				"gpiokp_apb_clk"
#define		BCM2165X_CLK__STR_ID				"hub_timer_apb_clk"
#define		BCM2165X_CLK__STR_ID				"pmu_bsc_apb_clk"
#define		BCM2165X_CLK__STR_ID				"chipreg_apb_clk"
#define		BCM2165X_CLK__STR_ID				"fmon_apb_clk"
#define		BCM2165X_CLK__STR_ID				"hub_tzcfg_apb_clk"
#define		BCM2165X_CLK__STR_ID				"sec_wd_apb_clk"
#define		BCM2165X_CLK__STR_ID				"sysemi_sec_apb_clk"
#define		BCM2165X_CLK__STR_ID				"sysemi_open_apb_clk"
#define		BCM2165X_CLK__STR_ID				"vcemi_sec_apb_clk"
#define		BCM2165X_CLK__STR_ID				"vcemi_open_apb_clk"
#define		BCM2165X_CLK__STR_ID				"aci_apb_clk"
#define		BCM2165X_CLK__STR_ID				"sim_apb_clk"
#define		BCM2165X_CLK__STR_ID				"spm_apb_clk"
#define		BCM2165X_CLK__STR_ID				"sim2_apb_clk"
#define		BCM2165X_CLK__STR_ID				"dap_clk"
#define		BCM2165X_CLK__STR_ID				"dap_switch_clk"
#define		BCM2165X_CLK__STR_ID				"brom_clk"
#define		BCM2165X_CLK__STR_ID				"nor_apb_clk"
#define		BCM2165X_CLK__STR_ID				"nor_clk"
#define		BCM2165X_CLK__STR_ID				"mdiomaster_clk"
#define		BCM2165X_CLK__STR_ID				"apb5_clk"
#define		BCM2165X_CLK__STR_ID				"cti_apb_clk"
#define		BCM2165X_CLK__STR_ID				"funnel_apb_clk"
#define		BCM2165X_CLK__STR_ID				"tpiu_apb_clk"
#define		BCM2165X_CLK__STR_ID				"vc_itm_apb_clk"
#define		BCM2165X_CLK__STR_ID				"sec_viol_trap_4_apb_clk"
#define		BCM2165X_CLK__STR_ID				"sec_viol_trap_5_apb_clk"
#define		BCM2165X_CLK__STR_ID				"sec_viol_trap_7_apb_clk"
#define		BCM2165X_CLK__STR_ID				"hsi_apb_clk"
#define		BCM2165X_CLK__STR_ID				"axi_trace_19_apb_clk"
#define		BCM2165X_CLK__STR_ID				"axi_trace_11_apb_clk"
#define		BCM2165X_CLK__STR_ID				"axi_trace_12_apb_clk"
#define		BCM2165X_CLK__STR_ID				"axi_trace_13_apb_clk"
#define		BCM2165X_CLK__STR_ID				"etb_apb_clk"
#define		BCM2165X_CLK__STR_ID				"final_funnel_apb_clk"
#define		BCM2165X_CLK__STR_ID				"apb10_clk"
#define		BCM2165X_CLK__STR_ID				"apb9_clk"
#define		BCM2165X_CLK__STR_ID				"atb_filter_apb_clk"
#define		BCM2165X_CLK__STR_ID				"bt_slim_ahb_apb_clk"
#define		BCM2165X_CLK__STR_ID				"etb2axi_apb_clk"
#define		BCM2165X_CLK__STR_ID				"ssp3_apb_clk"
#define		BCM2165X_CLK__STR_ID				"audioh_apb_clk"
#define		BCM2165X_CLK__STR_ID				"audioh_156m_clk"
#define		BCM2165X_CLK__STR_ID				"audioh_2p4m_clk"
#define		BCM2165X_CLK__STR_ID				"tmon_apb_clk"
#define		BCM2165X_CLK__STR_ID				"var_spm_apb_clk"
#define		BCM2165X_CLK__STR_ID				"ssp4_apb_clk"
#define		BCM2165X_CLK__STR_ID				"hub_clk"
#define		BCM2165X_CLK__STR_ID				"sdio1_clk"
#define		BCM2165X_CLK__STR_ID				"sdio2_clk"
#define		BCM2165X_CLK__STR_ID				"sdio3_clk"
#define		BCM2165X_CLK__STR_ID				"sdio4_clk"
#define		BCM2165X_CLK__STR_ID				"bsc1_clk"
#define		BCM2165X_CLK__STR_ID				"bsc2_clk"
#define		BCM2165X_CLK__STR_ID				"smi_clk"
#define		BCM2165X_CLK__STR_ID				"usb_otg_clk"
#define		BCM2165X_CLK__STR_ID				"pwm_clk"
#define		BCM2165X_CLK__STR_ID				"apb2_clk"
#define		BCM2165X_CLK__STR_ID				"ssp0_clk"
#define		BCM2165X_CLK__STR_ID				"uartb3_clk"
#define		BCM2165X_CLK__STR_ID				"uartb2_clk"
#define		BCM2165X_CLK__STR_ID				"uartb_clk"
#define		BCM2165X_CLK__STR_ID				"timers_clk"
#define		BCM2165X_CLK__STR_ID				"spum_open_clk"
#define		BCM2165X_CLK__STR_ID				"spum_sec_clk"
#define		BCM2165X_CLK__STR_ID				"hub_timer_clk"
#define		BCM2165X_CLK__STR_ID				"pmu_bsc_clk"
#define		BCM2165X_CLK__STR_ID				"sim_clk"
#define		BCM2165X_CLK__STR_ID				"sim2_clk"
#define		BCM2165X_CLK__STR_ID				"audioh_26m_clk"
#define		BCM2165X_CLK__STR_ID				"tmon_1m_clk"
#define		BCM2165X_CLK__STR_ID				"caph_srcmixer_clk"
#define		BCM2165X_CLK__STR_ID				"ssp3_clk"
#define		BCM2165X_CLK__STR_ID				"ssp4_clk"
#define		BCM2165X_CLK__STR_ID				"ssp3_audio_clk"
#define		BCM2165X_CLK__STR_ID				"ssp4_audio_clk"
#define		BCM2165X_CLK__STR_ID				"dsi_pll_o_dsi_pll_clk"
#define		BCM2165X_CLK__STR_ID				"dsi0_esc_clk"
#define		BCM2165X_CLK__STR_ID				"dsi1_esc_clk"
#define		BCM2165X_CLK__STR_ID				"csi0_lp_clk"
#define		BCM2165X_CLK__STR_ID				"csi1_lp_clk"
#define		BCM2165X_CLK__STR_ID				"csi0_pix_phy_clk"
#define		BCM2165X_CLK__STR_ID				"csi0_byte0_phy_clk"
#define		BCM2165X_CLK__STR_ID				"csi0_byte1_phy_clk"
#define		BCM2165X_CLK__STR_ID				"csi1_pix_phy_clk"
#define		BCM2165X_CLK__STR_ID				"csi1_byte0_phy_clk"
#define		BCM2165X_CLK__STR_ID				"csi1_byte1_phy_clk"
#define		BCM2165X_CLK__STR_ID				"dsi0_pix_phy_clk"
#define		BCM2165X_CLK__STR_ID				"dsi1_pix_phy_clk"
#define		BCM2165X_CLK__STR_ID				"testdebug_clk"

