/*****************************************************************************
* Copyright 2010 Broadcom Corporation.  All rights reserved.
*
* Unless you and Broadcom execute a separate written software license
* agreement governing use of this software, this software is licensed to you
* under the terms of the GNU General Public License version 2, available at
* http://www.broadcom.com/licenses/GPLv2.php (the "GPL").
*
* Notwithstanding the above, under no circumstances may you combine this
* software in any way with any other Broadcom software provided under a
* license other than the GPL, without Broadcom's express prior written
* consent.
*****************************************************************************/
#ifndef __ARM_ARCH_BCM2165X_CLOCK_MGR_H
#define __ARM_ARCH_BCM2165X_CLOCK_MGR_H

/* clock strings */
#define		BCM2165X_CLK_ARM_STR_ID				"arm_clk"
#define		BCM2165X_CLK_USBH_48M_STR_ID			"usbh_48m_clk"
#define		BCM2165X_CLK_KPM_CCU_STR_ID				"kpm_ccu_clk"
#define		BCM2165X_CLK_KPS_CCU_STR_ID				"kps_ccu_clk"
#define		BCM2165X_CLK_MM_CCU_STR_ID				"mm_ccu_clk"
#define		BCM2165X_CLK_KHUBAON_CCU_STR_ID				"khubaon_ccu_clk"
#define		BCM2165X_CLK_KHUB_CCU_STR_ID				"khub_ccu_clk"
#define		BCM2165X_CLK_SDIO1_AHB_STR_ID				"sdio1_ahb_clk"
#define		BCM2165X_CLK_SDIO2_AHB_STR_ID				"sdio2_ahb_clk"
#define		BCM2165X_CLK_SDIO3_AHB_STR_ID				"sdio3_ahb_clk"
#define		BCM2165X_CLK_SDIO4_AHB_STR_ID				"sdio4_ahb_clk"
#define		BCM2165X_CLK_SDIO1_SLEEP_STR_ID				"sdio1_sleep_clk"
#define		BCM2165X_CLK_SDIO2_SLEEP_STR_ID				"sdio2_sleep_clk"
#define		BCM2165X_CLK_SDIO3_SLEEP_STR_ID				"sdio3_sleep_clk"
#define		BCM2165X_CLK_SDIO4_SLEEP_STR_ID				"sdio4_sleep_clk"
#define		BCM2165X_CLK_BSC1_APB_STR_ID				"bsc1_apb_clk"
#define		BCM2165X_CLK_BSC2_APB_STR_ID				"bsc2_apb_clk"
#define		BCM2165X_CLK_HSM_AHB_STR_ID				"hsm_ahb_clk"
#define		BCM2165X_CLK_HSM_APB_STR_ID				"hsm_apb_clk"
#define		BCM2165X_CLK_SPUM_OPEN_APB_STR_ID				"spum_open_apb_clk"
#define		BCM2165X_CLK_SPUM_SEC_APB_STR_ID				"spum_sec_apb_clk"
#define		BCM2165X_CLK_APB1_STR_ID				"apb1_clk"
#define		BCM2165X_CLK_TIMERS_APB_STR_ID				"timers_apb_clk"
#define		BCM2165X_CLK_SSP0_APB_STR_ID				"ssp0_apb_clk"
#define		BCM2165X_CLK_DMAC_MUX_APB_STR_ID				"dmac_mux_apb_clk"
#define		BCM2165X_CLK_UARTB3_APB_STR_ID				"uartb3_apb_clk"
#define		BCM2165X_CLK_UARTB2_APB_STR_ID				"uartb2_apb_clk"
#define		BCM2165X_CLK_UARTB_APB_STR_ID				"uartb_apb_clk"
#define		BCM2165X_CLK_PWM_APB_STR_ID				"pwm_apb_clk"
#define		BCM2165X_CLK_SPI_APB_STR_ID				"spi_apb_clk"
#define		BCM2165X_CLK_MM_APB_STR_ID				"mm_apb_clk"
#define		BCM2165X_CLK_CSI0_AXI_STR_ID				"csi0_axi_clk"
#define		BCM2165X_CLK_CSI1_AXI_STR_ID				"csi1_axi_clk"
#define		BCM2165X_CLK_DSI0_AXI_STR_ID				"dsi0_axi_clk"
#define		BCM2165X_CLK_DSI1_AXI_STR_ID				"dsi1_axi_clk"
#define		BCM2165X_CLK_V3D_AXI_STR_ID				"v3d_axi_clk"
#define		BCM2165X_CLK_VCE_AXI_STR_ID				"vce_axi_clk"
#define		BCM2165X_CLK_ISP_AXI_STR_ID				"isp_axi_clk"
#define		BCM2165X_CLK_MM_DMA_AXI_STR_ID				"mm_dma_axi_clk"
#define		BCM2165X_CLK_SMI_AXI_STR_ID				"smi_axi_clk"
#define		BCM2165X_CLK_PWRMGR_AXI_STR_ID				"pwrmgr_axi_clk"
#define		BCM2165X_CLK_GPIOKP_APB_STR_ID				"gpiokp_apb_clk"
#define		BCM2165X_CLK_HUB_TIMER_APB_STR_ID				"hub_timer_apb_clk"
#define		BCM2165X_CLK_PMU_BSC_APB_STR_ID				"pmu_bsc_apb_clk"
#define		BCM2165X_CLK_CHIPREG_APB_STR_ID				"chipreg_apb_clk"
#define		BCM2165X_CLK_FMON_APB_STR_ID				"fmon_apb_clk"
#define		BCM2165X_CLK_HUB_TZCFG_APB_STR_ID				"hub_tzcfg_apb_clk"
#define		BCM2165X_CLK_SEC_WD_APB_STR_ID				"sec_wd_apb_clk"
#define		BCM2165X_CLK_SYSEMI_SEC_APB_STR_ID				"sysemi_sec_apb_clk"
#define		BCM2165X_CLK_SYSEMI_OPEN_APB_STR_ID				"sysemi_open_apb_clk"
#define		BCM2165X_CLK_VCEMI_SEC_APB_STR_ID				"vcemi_sec_apb_clk"
#define		BCM2165X_CLK_VCEMI_OPEN_APB_STR_ID				"vcemi_open_apb_clk"
#define		BCM2165X_CLK_ACI_APB_STR_ID				"aci_apb_clk"
#define		BCM2165X_CLK_SIM_APB_STR_ID				"sim_apb_clk"
#define		BCM2165X_CLK_SPM_APB_STR_ID				"spm_apb_clk"
#define		BCM2165X_CLK_SIM2_APB_STR_ID				"sim2_apb_clk"
#define		BCM2165X_CLK_DAP_STR_ID				"dap_clk"
#define		BCM2165X_CLK_DAP_SWITCH_STR_ID				"dap_switch_clk"
#define		BCM2165X_CLK_BROM_STR_ID				"brom_clk"
#define		BCM2165X_CLK_NOR_APB_STR_ID				"nor_apb_clk"
#define		BCM2165X_CLK_NOR_STR_ID				"nor_clk"
#define		BCM2165X_CLK_MDIOMASTER_STR_ID				"mdiomaster_clk"
#define		BCM2165X_CLK_APB5_STR_ID				"apb5_clk"
#define		BCM2165X_CLK_CTI_APB_STR_ID				"cti_apb_clk"
#define		BCM2165X_CLK_FUNNEL_APB_STR_ID				"funnel_apb_clk"
#define		BCM2165X_CLK_TPIU_APB_STR_ID				"tpiu_apb_clk"
#define		BCM2165X_CLK_VC_ITM_APB_STR_ID				"vc_itm_apb_clk"
#define		BCM2165X_CLK_SEC_VIO1_TRAP_4_APB_STR_ID				"sec_viol_trap_4_apb_clk"
#define		BCM2165X_CLK_SEC_VIO1_TRAP_5_APB_STR_ID				"sec_viol_trap_5_apb_clk"
#define		BCM2165X_CLK_SEC_VIO1_TRAP_7_APB_STR_ID				"sec_viol_trap_7_apb_clk"
#define		BCM2165X_CLK_HSI_APB_STR_ID				"hsi_apb_clk"
#define		BCM2165X_CLK_AXI_TRACE_19_APB_STR_ID				"axi_trace_19_apb_clk"
#define		BCM2165X_CLK_AXI_TRACE_11_APB_STR_ID				"axi_trace_11_apb_clk"
#define		BCM2165X_CLK_AXI_TRACE_12_APB_STR_ID				"axi_trace_12_apb_clk"
#define		BCM2165X_CLK_AXI_TRACE_13_APB_STR_ID				"axi_trace_13_apb_clk"
#define		BCM2165X_CLK_ETB_APB_STR_ID				"etb_apb_clk"
#define		BCM2165X_CLK_FINAL_FUNNEL_APB_STR_ID				"final_funnel_apb_clk"
#define		BCM2165X_CLK_APB10_STR_ID				"apb10_clk"
#define		BCM2165X_CLK_APB9_STR_ID				"apb9_clk"
#define		BCM2165X_CLK_ATB_FILTER_APB_STR_ID				"atb_filter_apb_clk"
#define		BCM2165X_CLK_BT_SLIM_AHB_APB_STR_ID				"bt_slim_ahb_apb_clk"
#define		BCM2165X_CLK_ETB2AXI_APB_STR_ID				"etb2axi_apb_clk"
#define		BCM2165X_CLK_SSP3_APB_STR_ID				"ssp3_apb_clk"
#define		BCM2165X_CLK_AUDIOH_APB_STR_ID				"audioh_apb_clk"
#define		BCM2165X_CLK_AUDIOH_156M_STR_ID				"audioh_156m_clk"
#define		BCM2165X_CLK_AUDIOH_2P4M_STR_ID				"audioh_2p4m_clk"
#define		BCM2165X_CLK_TMON_APB_STR_ID				"tmon_apb_clk"
#define		BCM2165X_CLK_VAR_SPM_APB_STR_ID				"var_spm_apb_clk"
#define		BCM2165X_CLK_SSP4_APB_STR_ID				"ssp4_apb_clk"
#define		BCM2165X_CLK_HUB_STR_ID				"hub_clk"
#define		BCM2165X_CLK_SDIO1_STR_ID				"sdio1_clk"
#define		BCM2165X_CLK_SDIO2_STR_ID				"sdio2_clk"
#define		BCM2165X_CLK_SDIO3_STR_ID				"sdio3_clk"
#define		BCM2165X_CLK_SDIO4_STR_ID				"sdio4_clk"
#define		BCM2165X_CLK_BSC1_STR_ID				"bsc1_clk"
#define		BCM2165X_CLK_BSC2_STR_ID				"bsc2_clk"
#define		BCM2165X_CLK_SMI_STR_ID				"smi_clk"
#define		BCM2165X_CLK_USB_OTG_STR_ID				"usb_otg_clk"
#define		BCM2165X_CLK_PWM_STR_ID				"pwm_clk"
#define		BCM2165X_CLK_APB2_STR_ID				"apb2_clk"
#define		BCM2165X_CLK_SSP0_STR_ID				"ssp0_clk"
#define		BCM2165X_CLK_UARTB3_STR_ID				"uartb3_clk"
#define		BCM2165X_CLK_UARTB2_STR_ID				"uartb2_clk"
#define		BCM2165X_CLK_UARTB_STR_ID				"uartb_clk"
#define		BCM2165X_CLK_TIMERS_STR_ID				"timers_clk"
#define		BCM2165X_CLK_SPUM_OPEN_STR_ID				"spum_open_clk"
#define		BCM2165X_CLK_SPUM_SEC_STR_ID				"spum_sec_clk"
#define		BCM2165X_CLK_HUB_TIMER_STR_ID				"hub_timer_clk"
#define		BCM2165X_CLK_PMU_BSC_STR_ID				"pmu_bsc_clk"
#define		BCM2165X_CLK_SIM_STR_ID				"sim_clk"
#define		BCM2165X_CLK_SIM2_STR_ID				"sim2_clk"
#define		BCM2165X_CLK_AUDIOH_26M_STR_ID				"audioh_26m_clk"
#define		BCM2165X_CLK_TMON_1M_STR_ID				"tmon_1m_clk"
#define		BCM2165X_CLK_CAPH_SRCMIXER_STR_ID				"caph_srcmixer_clk"
#define		BCM2165X_CLK_SSP3_STR_ID				"ssp3_clk"
#define		BCM2165X_CLK_SSP4_STR_ID				"ssp4_clk"
#define		BCM2165X_CLK_SSP3_AUDIO_STR_ID				"ssp3_audio_clk"
#define		BCM2165X_CLK_SSP4_AUDIO_STR_ID				"ssp4_audio_clk"
#define		BCM2165X_CLK_DSI_PLL_O_DSI_PLL_STR_ID				"dsi_pll_o_dsi_pll_clk"
#define		BCM2165X_CLK_DSI0_ESC_STR_ID				"dsi0_esc_clk"
#define		BCM2165X_CLK_DSI1_ESC_STR_ID				"dsi1_esc_clk"
#define		BCM2165X_CLK_CSI0_LP_STR_ID				"csi0_lp_clk"
#define		BCM2165X_CLK_CSI1_LP_STR_ID				"csi1_lp_clk"
#define		BCM2165X_CLK_CSI0_PIX_PHY_STR_ID				"csi0_pix_phy_clk"
#define		BCM2165X_CLK_CSI0_BYTE0_PHY_STR_ID				"csi0_byte0_phy_clk"
#define		BCM2165X_CLK_CSI0_BYTE1_PHY_STR_ID				"csi0_byte1_phy_clk"
#define		BCM2165X_CLK_CSI1_PIX_PHY_STR_ID				"csi1_pix_phy_clk"
#define		BCM2165X_CLK_CSI1_BYTE0_PHY_STR_ID				"csi1_byte0_phy_clk"
#define		BCM2165X_CLK_CSI1_BYTE1_PHY_STR_ID				"csi1_byte1_phy_clk"
#define		BCM2165X_CLK_DSI0_PIX_PHY_STR_ID				"dsi0_pix_phy_clk"
#define		BCM2165X_CLK_DSI1_PIX_PHY_STR_ID				"dsi1_pix_phy_clk"
#define		BCM2165X_CLK_TESTDEBUG_STR_ID				"testdebug_clk"

#endif /* __ARM_ARCH_BCM2165X_CLOCK_MGR_H  */
