# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
ifneq ($(TOP), )
LOCAL_DIR := $(TOP)/$(subst ../,,$(src))
else ifneq ($(ANDROID_BUILD_TOP), )
LOCAL_DIR := $(ANDROID_BUILD_TOP)/$(subst ../,,$(src))
else
$(warning "Can't find Android build top")
endif

cirrus_wm_adsp-objs = wm_adsp.o
obj-m += cirrus_wm_adsp.o

cirrus_cs35l41-objs = cs35l41.o cs35l41-tables.o
obj-m += cirrus_cs35l41.o
ccflags-y := -I $(LOCAL_DIR)/../../../include
ccflags-y += -I $(src)/../../../include

cirrus_cs35l41-objs += cs35l41-i2c.o

