/************************************************************************************************/
/*                                                                                              */
/*  Copyright 2011  Broadcom Corporation                                                        */
/*                                                                                              */
/*     Unless you and Broadcom execute a separate written software license agreement governing  */
/*     use of this software, this software is licensed to you under the terms of the GNU        */
/*     General Public License version 2 (the GPL), available at                                 */
/*                                                                                              */
/*          http://www.broadcom.com/licenses/GPLv2.php                                          */
/*                                                                                              */
/*     with the following added to such license:                                                */
/*                                                                                              */
/*     As a special exception, the copyright holders of this software give you permission to    */
/*     link this software with independent modules, and to copy and distribute the resulting    */
/*     executable under terms of your choice, provided that you also meet, for each linked      */
/*     independent module, the terms and conditions of the license of that module.              */
/*     An independent module is a module which is not derived from this software.  The special  */
/*     exception does not apply to any modifications of the software.                           */
/*                                                                                              */
/*     Notwithstanding the above, under no circumstances may you combine this software in any   */
/*     way with any other Broadcom software provided under a license other than the GPL,        */
/*     without Broadcom's express prior written consent.                                        */
/*                                                                                              */
/*     Date     : Generated on 4/10/2011 22:27:55                                             */
/*     RDB file : /projects/SAMOA/revA0                                                                   */
/************************************************************************************************/

#ifndef __BRCM_RDB_ANA_AUDIO_REG_H__
#define __BRCM_RDB_ANA_AUDIO_REG_H__

#define ANA_AUDIO_REG_AUD_SYS_CTRL_OFFSET                                 0x00000000
#define ANA_AUDIO_REG_AUD_SYS_CTRL_TYPE                                   UInt32
#define ANA_AUDIO_REG_AUD_SYS_CTRL_RESERVED_MASK                          0x00000000
#define    ANA_AUDIO_REG_AUD_SYS_CTRL_SYSCTRL_RESERVED_SHIFT              3
#define    ANA_AUDIO_REG_AUD_SYS_CTRL_SYSCTRL_RESERVED_MASK               0xFFFFFFF8
#define    ANA_AUDIO_REG_AUD_SYS_CTRL_I_D2C_IB_CTL_SHIFT                  1
#define    ANA_AUDIO_REG_AUD_SYS_CTRL_I_D2C_IB_CTL_MASK                   0x00000006
#define    ANA_AUDIO_REG_AUD_SYS_CTRL_I_CKIN_26M_EN_SHIFT                 0
#define    ANA_AUDIO_REG_AUD_SYS_CTRL_I_CKIN_26M_EN_MASK                  0x00000001

#define ANA_AUDIO_REG_AUD_ANALDO_CTRL_OFFSET                              0x00000004
#define ANA_AUDIO_REG_AUD_ANALDO_CTRL_TYPE                                UInt32
#define ANA_AUDIO_REG_AUD_ANALDO_CTRL_RESERVED_MASK                       0x00000000
#define    ANA_AUDIO_REG_AUD_ANALDO_CTRL_ANALDOCTRL_RESERVED_SHIFT        3
#define    ANA_AUDIO_REG_AUD_ANALDO_CTRL_ANALDOCTRL_RESERVED_MASK         0xFFFFFFF8
#define    ANA_AUDIO_REG_AUD_ANALDO_CTRL_I_ANALDO_LPM_SHIFT               2
#define    ANA_AUDIO_REG_AUD_ANALDO_CTRL_I_ANALDO_LPM_MASK                0x00000004
#define    ANA_AUDIO_REG_AUD_ANALDO_CTRL_I_ANALDO_ILIM_TEST_SHIFT         1
#define    ANA_AUDIO_REG_AUD_ANALDO_CTRL_I_ANALDO_ILIM_TEST_MASK          0x00000002
#define    ANA_AUDIO_REG_AUD_ANALDO_CTRL_I_ANALDO_PWRUP_SHIFT             0
#define    ANA_AUDIO_REG_AUD_ANALDO_CTRL_I_ANALDO_PWRUP_MASK              0x00000001

#define ANA_AUDIO_REG_AUD_ANALDO_TEST_OFFSET                              0x00000008
#define ANA_AUDIO_REG_AUD_ANALDO_TEST_TYPE                                UInt32
#define ANA_AUDIO_REG_AUD_ANALDO_TEST_RESERVED_MASK                       0x00000000
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_ANALDOTEST_RESERVED_SHIFT        18
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_ANALDOTEST_RESERVED_MASK         0xFFFC0000
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_VSEL_ILIM_SHIFT         16
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_VSEL_ILIM_MASK          0x00030000
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_VOUT_OK_SHIFT           15
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_VOUT_OK_MASK            0x00008000
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_VOKCOMP_PD_SHIFT        14
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_VOKCOMP_PD_MASK         0x00004000
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_VOKCOMP_HYS_SHIFT       12
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_VOKCOMP_HYS_MASK        0x00003000
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_VO1P2_SELB_SHIFT        11
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_VO1P2_SELB_MASK         0x00000800
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_SCF_DSBL_SHIFT          10
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_SCF_DSBL_MASK           0x00000400
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_VDSMAMP_PD_SHIFT        9
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_VDSMAMP_PD_MASK         0x00000200
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_ILIM_PD_SHIFT           8
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_ILIM_PD_MASK            0x00000100
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_OVICOMP_PD_SHIFT        7
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_OVICOMP_PD_MASK         0x00000080
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_OUTPROG_SHIFT           4
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_OUTPROG_MASK            0x00000070
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_DIS_PULLDN_SHIFT        3
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_DIS_PULLDN_MASK         0x00000008
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_CKSEL_SHIFT             1
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_CKSEL_MASK              0x00000006
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_RPOLE_SHIFT             0
#define    ANA_AUDIO_REG_AUD_ANALDO_TEST_I_ANALDO_RPOLE_MASK              0x00000001

#define ANA_AUDIO_REG_AUD_EPHSLDO_CTRL_OFFSET                             0x0000000C
#define ANA_AUDIO_REG_AUD_EPHSLDO_CTRL_TYPE                               UInt32
#define ANA_AUDIO_REG_AUD_EPHSLDO_CTRL_RESERVED_MASK                      0x00000000
#define    ANA_AUDIO_REG_AUD_EPHSLDO_CTRL_EPHSLDO_RESERVED_SHIFT          3
#define    ANA_AUDIO_REG_AUD_EPHSLDO_CTRL_EPHSLDO_RESERVED_MASK           0xFFFFFFF8
#define    ANA_AUDIO_REG_AUD_EPHSLDO_CTRL_I_EARHSLDO_LPM_SHIFT            2
#define    ANA_AUDIO_REG_AUD_EPHSLDO_CTRL_I_EARHSLDO_LPM_MASK             0x00000004
#define    ANA_AUDIO_REG_AUD_EPHSLDO_CTRL_I_EARHSLDO_ILIM_TEST_SHIFT      1
#define    ANA_AUDIO_REG_AUD_EPHSLDO_CTRL_I_EARHSLDO_ILIM_TEST_MASK       0x00000002
#define    ANA_AUDIO_REG_AUD_EPHSLDO_CTRL_I_EARHSLDO_PWRUP_SHIFT          0
#define    ANA_AUDIO_REG_AUD_EPHSLDO_CTRL_I_EARHSLDO_PWRUP_MASK           0x00000001

#define ANA_AUDIO_REG_AUD_EPHSLDO_TEST_OFFSET                             0x00000010
#define ANA_AUDIO_REG_AUD_EPHSLDO_TEST_TYPE                               UInt32
#define ANA_AUDIO_REG_AUD_EPHSLDO_TEST_RESERVED_MASK                      0x00000000
#define    ANA_AUDIO_REG_AUD_EPHSLDO_TEST_EPHSLDOTST_RESERVED_SHIFT       11
#define    ANA_AUDIO_REG_AUD_EPHSLDO_TEST_EPHSLDOTST_RESERVED_MASK        0xFFFFF800
#define    ANA_AUDIO_REG_AUD_EPHSLDO_TEST_I_EARHSLDO_VSEL_ILIM_SHIFT      9
#define    ANA_AUDIO_REG_AUD_EPHSLDO_TEST_I_EARHSLDO_VSEL_ILIM_MASK       0x00000600
#define    ANA_AUDIO_REG_AUD_EPHSLDO_TEST_I_EARHSLDO_VO1P2_SELB_SHIFT     8
#define    ANA_AUDIO_REG_AUD_EPHSLDO_TEST_I_EARHSLDO_VO1P2_SELB_MASK      0x00000100
#define    ANA_AUDIO_REG_AUD_EPHSLDO_TEST_I_EARHSLDO_PD_VDSMAMP_SHIFT     7
#define    ANA_AUDIO_REG_AUD_EPHSLDO_TEST_I_EARHSLDO_PD_VDSMAMP_MASK      0x00000080
#define    ANA_AUDIO_REG_AUD_EPHSLDO_TEST_I_EARHSLDO_PD_ILIM_SHIFT        6
#define    ANA_AUDIO_REG_AUD_EPHSLDO_TEST_I_EARHSLDO_PD_ILIM_MASK         0x00000040
#define    ANA_AUDIO_REG_AUD_EPHSLDO_TEST_I_EARHSLDO_OVICOMP_PD_SHIFT     5
#define    ANA_AUDIO_REG_AUD_EPHSLDO_TEST_I_EARHSLDO_OVICOMP_PD_MASK      0x00000020
#define    ANA_AUDIO_REG_AUD_EPHSLDO_TEST_I_EARHSLDO_OUTPROG_SHIFT        2
#define    ANA_AUDIO_REG_AUD_EPHSLDO_TEST_I_EARHSLDO_OUTPROG_MASK         0x0000001C
#define    ANA_AUDIO_REG_AUD_EPHSLDO_TEST_I_EARHSLDO_DIS_PULLDN_SHIFT     1
#define    ANA_AUDIO_REG_AUD_EPHSLDO_TEST_I_EARHSLDO_DIS_PULLDN_MASK      0x00000002
#define    ANA_AUDIO_REG_AUD_EPHSLDO_TEST_I_EARHSLDO_RPOLE_SHIFT          0
#define    ANA_AUDIO_REG_AUD_EPHSLDO_TEST_I_EARHSLDO_RPOLE_MASK           0x00000001

#define ANA_AUDIO_REG_AUD_EP_CTRL_OFFSET                                  0x00000014
#define ANA_AUDIO_REG_AUD_EP_CTRL_TYPE                                    UInt32
#define ANA_AUDIO_REG_AUD_EP_CTRL_RESERVED_MASK                           0x00000000
#define    ANA_AUDIO_REG_AUD_EP_CTRL_EP_RESERVED_SHIFT                    12
#define    ANA_AUDIO_REG_AUD_EP_CTRL_EP_RESERVED_MASK                     0xFFFFF000
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_SPK_PDN_SHIFT                   11
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_SPK_PDN_MASK                    0x00000800
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_SHUFFLER_DIS_SHIFT              10
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_SHUFFLER_DIS_MASK               0x00000400
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_PU_ENABLE_SHIFT                 9
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_PU_ENABLE_MASK                  0x00000200
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_PD_ENABLE_SHIFT                 8
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_PD_ENABLE_MASK                  0x00000100
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_LOAD_EXT_CTL_SHIFT              7
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_LOAD_EXT_CTL_MASK               0x00000080
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_END_PWRUP_SHIFT                 6
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_END_PWRUP_MASK                  0x00000040
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_END_PWRDN_SHIFT                 5
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_END_PWRDN_MASK                  0x00000020
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_EN_RAMP1_45M_SHIFT              4
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_EN_RAMP1_45M_MASK               0x00000010
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_EN_RAMP2_5M_SHIFT               3
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_EN_RAMP2_5M_MASK                0x00000008
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_RESETB_SHIFT                    2
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_RESETB_MASK                     0x00000004
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_PWRUP_DRV_TRIG_SHIFT            1
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_PWRUP_DRV_TRIG_MASK             0x00000002
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_PWRUP_SHIFT                     0
#define    ANA_AUDIO_REG_AUD_EP_CTRL_I_EP_PWRUP_MASK                      0x00000001

#define ANA_AUDIO_REG_AUD_EP_TEST_OFFSET                                  0x00000018
#define ANA_AUDIO_REG_AUD_EP_TEST_TYPE                                    UInt32
#define ANA_AUDIO_REG_AUD_EP_TEST_RESERVED_MASK                           0x00000000
#define    ANA_AUDIO_REG_AUD_EP_TEST_EPTST_RESERVED_SHIFT                 6
#define    ANA_AUDIO_REG_AUD_EP_TEST_EPTST_RESERVED_MASK                  0xFFFFFFC0
#define    ANA_AUDIO_REG_AUD_EP_TEST_I_EP_STARTUP_CTL_SHIFT               4
#define    ANA_AUDIO_REG_AUD_EP_TEST_I_EP_STARTUP_CTL_MASK                0x00000030
#define    ANA_AUDIO_REG_AUD_EP_TEST_I_EP_POPCLICK_BYPS_SHIFT             3
#define    ANA_AUDIO_REG_AUD_EP_TEST_I_EP_POPCLICK_BYPS_MASK              0x00000008
#define    ANA_AUDIO_REG_AUD_EP_TEST_I_EP_CM_CTL_SHIFT                    0
#define    ANA_AUDIO_REG_AUD_EP_TEST_I_EP_CM_CTL_MASK                     0x00000007

#define ANA_AUDIO_REG_AUD_HS_CTRL_OFFSET                                  0x0000001C
#define ANA_AUDIO_REG_AUD_HS_CTRL_TYPE                                    UInt32
#define ANA_AUDIO_REG_AUD_HS_CTRL_RESERVED_MASK                           0x00000000
#define    ANA_AUDIO_REG_AUD_HS_CTRL_HS_CTRL_RESERVED_SHIFT               19
#define    ANA_AUDIO_REG_AUD_HS_CTRL_HS_CTRL_RESERVED_MASK                0xFFF80000
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_POP_SHORTMAINAUX_SHIFT          18
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_POP_SHORTMAINAUX_MASK           0x00040000
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_POP_ONAUXFB_SHIFT               17
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_POP_ONAUXFB_MASK                0x00020000
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_POP_GROUNDOUT_SHIFT             16
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_POP_GROUNDOUT_MASK              0x00010000
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_LOADEXT_DAC_MUTE_SHIFT          15
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_LOADEXT_DAC_MUTE_MASK           0x00008000
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_LOAD_EXTSEQ_SHIFT               14
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_LOAD_EXTSEQ_MASK                0x00004000
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_DRV_SCCTL_SHIFT                 12
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_DRV_SCCTL_MASK                  0x00003000
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_DAC_SHUFFLE_DISBL_SHIFT         11
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_DAC_SHUFFLE_DISBL_MASK          0x00000800
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_DAC_MUTE_SHIFT                  10
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_DAC_MUTE_MASK                   0x00000400
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_CP_PWRUP_SHIFT                  9
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_CP_PWRUP_MASK                   0x00000200
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_DRV2AUX_PWRUP_SHIFT             8
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_DRV2AUX_PWRUP_MASK              0x00000100
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_DRV2MAIN_PWRUP_SHIFT            7
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_DRV2MAIN_PWRUP_MASK             0x00000080
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_DRV1_PWRUP_SHIFT                6
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_DRV1_PWRUP_MASK                 0x00000040
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_LF_PWRUP_SHIFT                  5
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_LF_PWRUP_MASK                   0x00000020
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_DAC_PWRUP_SHIFT                 4
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_DAC_PWRUP_MASK                  0x00000010
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_PWRUP_SC_R_SHIFT                3
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_PWRUP_SC_R_MASK                 0x00000008
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_PWRUP_SC_L_SHIFT                2
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_PWRUP_SC_L_MASK                 0x00000004
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_PWRUP_R_SHIFT                   1
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_PWRUP_R_MASK                    0x00000002
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_PWRUP_L_SHIFT                   0
#define    ANA_AUDIO_REG_AUD_HS_CTRL_I_HS_PWRUP_L_MASK                    0x00000001

#define ANA_AUDIO_REG_AUD_HS_TEST_OFFSET                                  0x00000020
#define ANA_AUDIO_REG_AUD_HS_TEST_TYPE                                    UInt32
#define ANA_AUDIO_REG_AUD_HS_TEST_RESERVED_MASK                           0x00000000
#define    ANA_AUDIO_REG_AUD_HS_TEST_HS_TEST_RESERVED_SHIFT               22
#define    ANA_AUDIO_REG_AUD_HS_TEST_HS_TEST_RESERVED_MASK                0xFFC00000
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_LOADEXT_DAC_RESET_SHIFT         21
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_LOADEXT_DAC_RESET_MASK          0x00200000
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_LF_RESET_SHIFT                  20
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_LF_RESET_MASK                   0x00100000
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_LF_IBCTL_SHIFT                  18
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_LF_IBCTL_MASK                   0x000C0000
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_LF_CMCTL_SHIFT                  16
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_LF_CMCTL_MASK                   0x00030000
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_DRV_SWLSUP_CTL_SHIFT            15
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_DRV_SWLSUP_CTL_MASK             0x00008000
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_DRV_SC_DSBL_SHIFT               14
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_DRV_SC_DSBL_MASK                0x00004000
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_DRV_IQCTL_SHIFT                 12
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_DRV_IQCTL_MASK                  0x00003000
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_DRV_CLAMP_DISBL_SHIFT           11
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_DRV_CLAMP_DISBL_MASK            0x00000800
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_DAC_RESET_SHIFT                 10
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_DAC_RESET_MASK                  0x00000400
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_DAC_REF_IBCTL_SHIFT             8
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_DAC_REF_IBCTL_MASK              0x00000300
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_DAC_REF_CTL_SHIFT               6
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_DAC_REF_CTL_MASK                0x000000C0
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_CP_NEGOUTSEL_SHIFT              4
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_CP_NEGOUTSEL_MASK               0x00000030
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_CP_EXTPOKEN_SHIFT               3
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_CP_EXTPOKEN_MASK                0x00000008
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_CP_EXTPOK_SHIFT                 2
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_CP_EXTPOK_MASK                  0x00000004
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_CP_CLKCTL_SHIFT                 0
#define    ANA_AUDIO_REG_AUD_HS_TEST_I_HS_CP_CLKCTL_MASK                  0x00000003

#define ANA_AUDIO_REG_AUD_IHF_CTRL_OFFSET                                 0x00000024
#define ANA_AUDIO_REG_AUD_IHF_CTRL_TYPE                                   UInt32
#define ANA_AUDIO_REG_AUD_IHF_CTRL_RESERVED_MASK                          0x00000000
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_BYPSW_PMU_TRIM_SHIFT          28
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_BYPSW_PMU_TRIM_MASK           0xF0000000
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_BYPSW_EXT_TRIM_SHIFT          24
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_BYPSW_EXT_TRIM_MASK           0x0F000000
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_BYPSW_EXT_TRIM_SEL_SHIFT      23
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_BYPSW_EXT_TRIM_SEL_MASK       0x00800000
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_LDO_LPM_SHIFT                 22
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_LDO_LPM_MASK                  0x00400000
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_LDO_ILIM_TEST_SHIFT           21
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_LDO_ILIM_TEST_MASK            0x00200000
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_GAIN_SHIFT                    16
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_GAIN_MASK                     0x001F0000
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_IHFCTRL_RESERVED_SHIFT              15
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_IHFCTRL_RESERVED_MASK               0x00008000
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_BYPSW_ENB_SHIFT               14
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_BYPSW_ENB_MASK                0x00004000
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_RCCAL_PWRUP_SHIFT             13
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_RCCAL_PWRUP_MASK              0x00002000
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_PWRDRV_PWRUP_SHIFT            12
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_PWRDRV_PWRUP_MASK             0x00001000
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_PWM_PWRUP_SHIFT               11
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_PWM_PWRUP_MASK                0x00000800
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_PGA_PWRUP_SHIFT               10
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_PGA_PWRUP_MASK                0x00000400
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_LF_PWRUP_SHIFT                9
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_LF_PWRUP_MASK                 0x00000200
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_LDO_PWRUP_SHIFT               8
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_LDO_PWRUP_MASK                0x00000100
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_FFPWM_PWRUP_SHIFT             7
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_FFPWM_PWRUP_MASK              0x00000080
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_FFCMP_LP_ENB_SHIFT            6
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_FFCMP_LP_ENB_MASK             0x00000040
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_FBAMP_PWRUP_SHIFT             5
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_FBAMP_PWRUP_MASK              0x00000020
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_DAC_PWRUP_SHIFT               4
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_DAC_PWRUP_MASK                0x00000010
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_BIAS_PWRUP_SHIFT              3
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_BIAS_PWRUP_MASK               0x00000008
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_CLK_EN_SHIFT                  2
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_CLK_EN_MASK                   0x00000004
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_ALL_PWRUP_SHIFT               1
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_ALL_PWRUP_MASK                0x00000002
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_PWRUP_SHIFT                   0
#define    ANA_AUDIO_REG_AUD_IHF_CTRL_I_IHF_PWRUP_MASK                    0x00000001

#define ANA_AUDIO_REG_AUD_HS_IHF_STAT_OFFSET                              0x00000028
#define ANA_AUDIO_REG_AUD_HS_IHF_STAT_TYPE                                UInt32
#define ANA_AUDIO_REG_AUD_HS_IHF_STAT_RESERVED_MASK                       0x00000000
#define    ANA_AUDIO_REG_AUD_HS_IHF_STAT_IHFSTAT1_RESERVED_SHIFT          11
#define    ANA_AUDIO_REG_AUD_HS_IHF_STAT_IHFSTAT1_RESERVED_MASK           0xFFFFF800
#define    ANA_AUDIO_REG_AUD_HS_IHF_STAT_O_IHF_RCCAL_R_SHIFT              8
#define    ANA_AUDIO_REG_AUD_HS_IHF_STAT_O_IHF_RCCAL_R_MASK               0x00000700
#define    ANA_AUDIO_REG_AUD_HS_IHF_STAT_IHFSTAT0_RESERVED_SHIFT          1
#define    ANA_AUDIO_REG_AUD_HS_IHF_STAT_IHFSTAT0_RESERVED_MASK           0x000000FE
#define    ANA_AUDIO_REG_AUD_HS_IHF_STAT_O_HS_CP_POK_SHIFT                0
#define    ANA_AUDIO_REG_AUD_HS_IHF_STAT_O_HS_CP_POK_MASK                 0x00000001

#define ANA_AUDIO_REG_AUD_IHF_TEST0_OFFSET                                0x0000002C
#define ANA_AUDIO_REG_AUD_IHF_TEST0_TYPE                                  UInt32
#define ANA_AUDIO_REG_AUD_IHF_TEST0_RESERVED_MASK                         0x00000000
#define    ANA_AUDIO_REG_AUD_IHF_TEST0_IHFTEST0_RESERVED_SHIFT            13
#define    ANA_AUDIO_REG_AUD_IHF_TEST0_IHFTEST0_RESERVED_MASK             0xFFFFE000
#define    ANA_AUDIO_REG_AUD_IHF_TEST0_IHF_SPARE_SHIFT                    8
#define    ANA_AUDIO_REG_AUD_IHF_TEST0_IHF_SPARE_MASK                     0x00001F00
#define    ANA_AUDIO_REG_AUD_IHF_TEST0_I_IHF_LF_RESET_SHIFT               7
#define    ANA_AUDIO_REG_AUD_IHF_TEST0_I_IHF_LF_RESET_MASK                0x00000080
#define    ANA_AUDIO_REG_AUD_IHF_TEST0_I_IHF_FFPGA_RESET_SHIFT            6
#define    ANA_AUDIO_REG_AUD_IHF_TEST0_I_IHF_FFPGA_RESET_MASK             0x00000040
#define    ANA_AUDIO_REG_AUD_IHF_TEST0_I_IHF_FFPGA_GAIN_SHFT_SHIFT        4
#define    ANA_AUDIO_REG_AUD_IHF_TEST0_I_IHF_FFPGA_GAIN_SHFT_MASK         0x00000030
#define    ANA_AUDIO_REG_AUD_IHF_TEST0_I_IHF_DAC_SHUFF_DSBL_SHIFT         3
#define    ANA_AUDIO_REG_AUD_IHF_TEST0_I_IHF_DAC_SHUFF_DSBL_MASK          0x00000008
#define    ANA_AUDIO_REG_AUD_IHF_TEST0_RESERVED_SHIFT                     2
#define    ANA_AUDIO_REG_AUD_IHF_TEST0_RESERVED_MASK                      0x00000004
#define    ANA_AUDIO_REG_AUD_IHF_TEST0_I_IHF_BIAS_CTL_SHIFT               0
#define    ANA_AUDIO_REG_AUD_IHF_TEST0_I_IHF_BIAS_CTL_MASK                0x00000003

#define ANA_AUDIO_REG_AUD_IHF_TEST1_OFFSET                                0x00000030
#define ANA_AUDIO_REG_AUD_IHF_TEST1_TYPE                                  UInt32
#define ANA_AUDIO_REG_AUD_IHF_TEST1_RESERVED_MASK                         0x00000000
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_IHFTEST1_RESERVED_SHIFT            23
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_IHFTEST1_RESERVED_MASK             0xFF800000
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_DIS_PULLDN_SHIFT         22
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_DIS_PULLDN_MASK          0x00400000
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_RSTR_PD_SHIFT            21
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_RSTR_PD_MASK             0x00200000
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_RBG_PD_SHIFT             20
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_RBG_PD_MASK              0x00100000
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_COMP_HYS_SHIFT           18
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_COMP_HYS_MASK            0x000C0000
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_VCLAMP_CTL_SHIFT         16
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_VCLAMP_CTL_MASK          0x00030000
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_VOUT_CTL_SHIFT           14
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_VOUT_CTL_MASK            0x0000C000
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_VSEL_ILIM_SHIFT          12
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_VSEL_ILIM_MASK           0x00003000
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_VOUT_OK_SHIFT            11
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_VOUT_OK_MASK             0x00000800
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_VOKCOMP_PD_SHIFT         10
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_VOKCOMP_PD_MASK          0x00000400
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_VOKCOMP_HYS_SHIFT        8
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_VOKCOMP_HYS_MASK         0x00000300
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_VO1P2_SELB_SHIFT         7
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_VO1P2_SELB_MASK          0x00000080
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_SCF_DSBL_SHIFT           6
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_SCF_DSBL_MASK            0x00000040
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_VDSMAMP_PD_SHIFT         5
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_VDSMAMP_PD_MASK          0x00000020
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_ILIM_PD_SHIFT            4
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_ILIM_PD_MASK             0x00000010
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_OVICOMP_PD_SHIFT         3
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_OVICOMP_PD_MASK          0x00000008
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_CKSEL_SHIFT              1
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_CKSEL_MASK               0x00000006
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_RPOLE_SHIFT              0
#define    ANA_AUDIO_REG_AUD_IHF_TEST1_I_IHF_LDO_RPOLE_MASK               0x00000001

#define ANA_AUDIO_REG_AUD_IHF_TEST2_OFFSET                                0x00000034
#define ANA_AUDIO_REG_AUD_IHF_TEST2_TYPE                                  UInt32
#define ANA_AUDIO_REG_AUD_IHF_TEST2_RESERVED_MASK                         0x00780000
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_IHFTEST2_RESERVED_SHIFT            27
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_IHFTEST2_RESERVED_MASK             0xF8000000
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_SSP_CTL_SHIFT                25
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_SSP_CTL_MASK                 0x06000000
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_RMP_SR_CTL_SHIFT             23
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_RMP_SR_CTL_MASK              0x01800000
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_RCCAL_W_SHIFT                16
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_RCCAL_W_MASK                 0x00070000
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_RCCAL_CLKSEL_SHIFT           15
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_RCCAL_CLKSEL_MASK            0x00008000
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_RCCAL_BYPS_SHIFT             14
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_RCCAL_BYPS_MASK              0x00004000
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_PWRDRV_SR_CTL_SHIFT          12
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_PWRDRV_SR_CTL_MASK           0x00003000
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_PWRDRV_DLY_CTL_SHIFT         10
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_PWRDRV_DLY_CTL_MASK          0x00000C00
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_PWRDRV_HVSS_CTL_SHIFT        8
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_PWRDRV_HVSS_CTL_MASK         0x00000300
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_PWM_WD_ENB_SHIFT             7
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_PWM_WD_ENB_MASK              0x00000080
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_IHF_PWM_SPARE_SHIFT                5
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_IHF_PWM_SPARE_MASK                 0x00000060
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_PWM_CMP_LP_ENB_SHIFT         4
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_PWM_CMP_LP_ENB_MASK          0x00000010
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_PWM_CMMOD_WD_ENB_SHIFT       3
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_PWM_CMMOD_WD_ENB_MASK        0x00000008
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_PWM_CMMOD_RESET_SHIFT        2
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_PWM_CMMOD_RESET_MASK         0x00000004
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_PWM_CMMOD_DSBL_SHIFT         1
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_PWM_CMMOD_DSBL_MASK          0x00000002
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_PWM_PULGEN_RESET_SHIFT       0
#define    ANA_AUDIO_REG_AUD_IHF_TEST2_I_IHF_PWM_PULGEN_RESET_MASK        0x00000001

#define ANA_AUDIO_REG_AUD_HVBG_CTRL_OFFSET                                0x00000038
#define ANA_AUDIO_REG_AUD_HVBG_CTRL_TYPE                                  UInt32
#define ANA_AUDIO_REG_AUD_HVBG_CTRL_RESERVED_MASK                         0x00000000
#define    ANA_AUDIO_REG_AUD_HVBG_CTRL_HVBG1_RESERVED_SHIFT               14
#define    ANA_AUDIO_REG_AUD_HVBG_CTRL_HVBG1_RESERVED_MASK                0xFFFFC000
#define    ANA_AUDIO_REG_AUD_HVBG_CTRL_I_HVBG_PADJ_SHIFT                  11
#define    ANA_AUDIO_REG_AUD_HVBG_CTRL_I_HVBG_PADJ_MASK                   0x00003800
#define    ANA_AUDIO_REG_AUD_HVBG_CTRL_I_HVBG_CADJ_SHIFT                  8
#define    ANA_AUDIO_REG_AUD_HVBG_CTRL_I_HVBG_CADJ_MASK                   0x00000700
#define    ANA_AUDIO_REG_AUD_HVBG_CTRL_HVBG0_RESERVED_SHIFT               2
#define    ANA_AUDIO_REG_AUD_HVBG_CTRL_HVBG0_RESERVED_MASK                0x000000FC
#define    ANA_AUDIO_REG_AUD_HVBG_CTRL_I_HVBGMULT_PWRUP_SHIFT             1
#define    ANA_AUDIO_REG_AUD_HVBG_CTRL_I_HVBGMULT_PWRUP_MASK              0x00000002
#define    ANA_AUDIO_REG_AUD_HVBG_CTRL_I_HVBG_PWRUP_SHIFT                 0
#define    ANA_AUDIO_REG_AUD_HVBG_CTRL_I_HVBG_PWRUP_MASK                  0x00000001

#define ANA_AUDIO_REG_AUD_REFBG_CTRL_OFFSET                               0x0000003C
#define ANA_AUDIO_REG_AUD_REFBG_CTRL_TYPE                                 UInt32
#define ANA_AUDIO_REG_AUD_REFBG_CTRL_RESERVED_MASK                        0x00000000
#define    ANA_AUDIO_REG_AUD_REFBG_CTRL_REFBG_RESERVED_SHIFT              2
#define    ANA_AUDIO_REG_AUD_REFBG_CTRL_REFBG_RESERVED_MASK               0xFFFFFFFC
#define    ANA_AUDIO_REG_AUD_REFBG_CTRL_I_REFBG_CHOP_DIS_SHIFT            1
#define    ANA_AUDIO_REG_AUD_REFBG_CTRL_I_REFBG_CHOP_DIS_MASK             0x00000002
#define    ANA_AUDIO_REG_AUD_REFBG_CTRL_I_REFBG_PWRUP_SHIFT               0
#define    ANA_AUDIO_REG_AUD_REFBG_CTRL_I_REFBG_PWRUP_MASK                0x00000001

#define ANA_AUDIO_REG_AUD_INT_STAT_OFFSET                                 0x00000040
#define ANA_AUDIO_REG_AUD_INT_STAT_TYPE                                   UInt32
#define ANA_AUDIO_REG_AUD_INT_STAT_RESERVED_MASK                          0x00000000
#define    ANA_AUDIO_REG_AUD_INT_STAT_AUDINTSTAT_RESERVED_SHIFT           5
#define    ANA_AUDIO_REG_AUD_INT_STAT_AUDINTSTAT_RESERVED_MASK            0xFFFFFFE0
#define    ANA_AUDIO_REG_AUD_INT_STAT_STS_IHFLDO_OVI_SHIFT                4
#define    ANA_AUDIO_REG_AUD_INT_STAT_STS_IHFLDO_OVI_MASK                 0x00000010
#define    ANA_AUDIO_REG_AUD_INT_STAT_STS_EARHSLDO_OVI_SHIFT              3
#define    ANA_AUDIO_REG_AUD_INT_STAT_STS_EARHSLDO_OVI_MASK               0x00000008
#define    ANA_AUDIO_REG_AUD_INT_STAT_STS_ANALDO_OVI_SHIFT                2
#define    ANA_AUDIO_REG_AUD_INT_STAT_STS_ANALDO_OVI_MASK                 0x00000004
#define    ANA_AUDIO_REG_AUD_INT_STAT_STS_HS_SC_R_SHIFT                   1
#define    ANA_AUDIO_REG_AUD_INT_STAT_STS_HS_SC_R_MASK                    0x00000002
#define    ANA_AUDIO_REG_AUD_INT_STAT_STS_HS_SC_L_SHIFT                   0
#define    ANA_AUDIO_REG_AUD_INT_STAT_STS_HS_SC_L_MASK                    0x00000001

#define ANA_AUDIO_REG_AUD_IP_INT_CLR_OFFSET                               0x00000044
#define ANA_AUDIO_REG_AUD_IP_INT_CLR_TYPE                                 UInt32
#define ANA_AUDIO_REG_AUD_IP_INT_CLR_RESERVED_MASK                        0x00000000
#define    ANA_AUDIO_REG_AUD_IP_INT_CLR_AUDINTCLR_RESERVED_SHIFT          5
#define    ANA_AUDIO_REG_AUD_IP_INT_CLR_AUDINTCLR_RESERVED_MASK           0xFFFFFFE0
#define    ANA_AUDIO_REG_AUD_IP_INT_CLR_CLR_IHFLDO_OVI_SHIFT              4
#define    ANA_AUDIO_REG_AUD_IP_INT_CLR_CLR_IHFLDO_OVI_MASK               0x00000010
#define    ANA_AUDIO_REG_AUD_IP_INT_CLR_CLR_EARHSLDO_OVI_SHIFT            3
#define    ANA_AUDIO_REG_AUD_IP_INT_CLR_CLR_EARHSLDO_OVI_MASK             0x00000008
#define    ANA_AUDIO_REG_AUD_IP_INT_CLR_CLR_ANALDO_OVI_SHIFT              2
#define    ANA_AUDIO_REG_AUD_IP_INT_CLR_CLR_ANALDO_OVI_MASK               0x00000004
#define    ANA_AUDIO_REG_AUD_IP_INT_CLR_CLR_HS_SC_R_SHIFT                 1
#define    ANA_AUDIO_REG_AUD_IP_INT_CLR_CLR_HS_SC_R_MASK                  0x00000002
#define    ANA_AUDIO_REG_AUD_IP_INT_CLR_CLR_HS_SC_L_SHIFT                 0
#define    ANA_AUDIO_REG_AUD_IP_INT_CLR_CLR_HS_SC_L_MASK                  0x00000001

#define ANA_AUDIO_REG_AUD_IP_INT_ENABLE_OFFSET                            0x00000048
#define ANA_AUDIO_REG_AUD_IP_INT_ENABLE_TYPE                              UInt32
#define ANA_AUDIO_REG_AUD_IP_INT_ENABLE_RESERVED_MASK                     0x00000000
#define    ANA_AUDIO_REG_AUD_IP_INT_ENABLE_AUDINTMSK_RESERVED_SHIFT       5
#define    ANA_AUDIO_REG_AUD_IP_INT_ENABLE_AUDINTMSK_RESERVED_MASK        0xFFFFFFE0
#define    ANA_AUDIO_REG_AUD_IP_INT_ENABLE_ENBL_IHFLDO_OVI_SHIFT          4
#define    ANA_AUDIO_REG_AUD_IP_INT_ENABLE_ENBL_IHFLDO_OVI_MASK           0x00000010
#define    ANA_AUDIO_REG_AUD_IP_INT_ENABLE_ENBL_EARHSLDO_OVI_SHIFT        3
#define    ANA_AUDIO_REG_AUD_IP_INT_ENABLE_ENBL_EARHSLDO_OVI_MASK         0x00000008
#define    ANA_AUDIO_REG_AUD_IP_INT_ENABLE_ENBL_ANALDO_OVI_SHIFT          2
#define    ANA_AUDIO_REG_AUD_IP_INT_ENABLE_ENBL_ANALDO_OVI_MASK           0x00000004
#define    ANA_AUDIO_REG_AUD_IP_INT_ENABLE_ENBL_HS_SC_R_SHIFT             1
#define    ANA_AUDIO_REG_AUD_IP_INT_ENABLE_ENBL_HS_SC_R_MASK              0x00000002
#define    ANA_AUDIO_REG_AUD_IP_INT_ENABLE_ENBL_HS_SC_L_SHIFT             0
#define    ANA_AUDIO_REG_AUD_IP_INT_ENABLE_ENBL_HS_SC_L_MASK              0x00000001

#define ANA_AUDIO_REG_AUD_IP_DGLTC_CTRL_OFFSET                            0x0000004C
#define ANA_AUDIO_REG_AUD_IP_DGLTC_CTRL_TYPE                              UInt32
#define ANA_AUDIO_REG_AUD_IP_DGLTC_CTRL_RESERVED_MASK                     0x00000000
#define    ANA_AUDIO_REG_AUD_IP_DGLTC_CTRL_AUDMISCCTRL_RESERVED_SHIFT     5
#define    ANA_AUDIO_REG_AUD_IP_DGLTC_CTRL_AUDMISCCTRL_RESERVED_MASK      0xFFFFFFE0
#define    ANA_AUDIO_REG_AUD_IP_DGLTC_CTRL_IHFLDO_OVI_DEGLITCH_DSBL_SHIFT 4
#define    ANA_AUDIO_REG_AUD_IP_DGLTC_CTRL_IHFLDO_OVI_DEGLITCH_DSBL_MASK  0x00000010
#define    ANA_AUDIO_REG_AUD_IP_DGLTC_CTRL_EARHSLDO_OVI_DEGLITCH_DSBL_SHIFT 3
#define    ANA_AUDIO_REG_AUD_IP_DGLTC_CTRL_EARHSLDO_OVI_DEGLITCH_DSBL_MASK 0x00000008
#define    ANA_AUDIO_REG_AUD_IP_DGLTC_CTRL_ANALDO_OVI_DEGLITCH_DSBL_SHIFT 2
#define    ANA_AUDIO_REG_AUD_IP_DGLTC_CTRL_ANALDO_OVI_DEGLITCH_DSBL_MASK  0x00000004
#define    ANA_AUDIO_REG_AUD_IP_DGLTC_CTRL_HS_SC_R_DEGLITCH_DSBL_SHIFT    1
#define    ANA_AUDIO_REG_AUD_IP_DGLTC_CTRL_HS_SC_R_DEGLITCH_DSBL_MASK     0x00000002
#define    ANA_AUDIO_REG_AUD_IP_DGLTC_CTRL_HS_SC_L_DEGLITCH_DSBL_SHIFT    0
#define    ANA_AUDIO_REG_AUD_IP_DGLTC_CTRL_HS_SC_L_DEGLITCH_DSBL_MASK     0x00000001

#define ANA_AUDIO_REG_AUD_IP_HZRD_MASK_OFFSET                             0x00000050
#define ANA_AUDIO_REG_AUD_IP_HZRD_MASK_TYPE                               UInt32
#define ANA_AUDIO_REG_AUD_IP_HZRD_MASK_RESERVED_MASK                      0x00000000
#define    ANA_AUDIO_REG_AUD_IP_HZRD_MASK_AUDMISC1CTRL_RESERVED_SHIFT     5
#define    ANA_AUDIO_REG_AUD_IP_HZRD_MASK_AUDMISC1CTRL_RESERVED_MASK      0xFFFFFFE0
#define    ANA_AUDIO_REG_AUD_IP_HZRD_MASK_IHFLDO_OVI_HZRD_MASK_SHIFT      4
#define    ANA_AUDIO_REG_AUD_IP_HZRD_MASK_IHFLDO_OVI_HZRD_MASK_MASK       0x00000010
#define    ANA_AUDIO_REG_AUD_IP_HZRD_MASK_EARHSLDO_OVI_HZRD_MASK_SHIFT    3
#define    ANA_AUDIO_REG_AUD_IP_HZRD_MASK_EARHSLDO_OVI_HZRD_MASK_MASK     0x00000008
#define    ANA_AUDIO_REG_AUD_IP_HZRD_MASK_ANALDO_OVI_HZRD_MASK_SHIFT      2
#define    ANA_AUDIO_REG_AUD_IP_HZRD_MASK_ANALDO_OVI_HZRD_MASK_MASK       0x00000004
#define    ANA_AUDIO_REG_AUD_IP_HZRD_MASK_HS_SC_R_HZRD_MASK_SHIFT         1
#define    ANA_AUDIO_REG_AUD_IP_HZRD_MASK_HS_SC_R_HZRD_MASK_MASK          0x00000002
#define    ANA_AUDIO_REG_AUD_IP_HZRD_MASK_HS_SC_L_HZRD_MASK_SHIFT         0
#define    ANA_AUDIO_REG_AUD_IP_HZRD_MASK_HS_SC_L_HZRD_MASK_MASK          0x00000001

#define ANA_AUDIO_REG_AUD_HZRD_RAW_OFFSET                                 0x00000054
#define ANA_AUDIO_REG_AUD_HZRD_RAW_TYPE                                   UInt32
#define ANA_AUDIO_REG_AUD_HZRD_RAW_RESERVED_MASK                          0x00000000
#define    ANA_AUDIO_REG_AUD_HZRD_RAW_AUDRAW_RESERVED_SHIFT               5
#define    ANA_AUDIO_REG_AUD_HZRD_RAW_AUDRAW_RESERVED_MASK                0xFFFFFFE0
#define    ANA_AUDIO_REG_AUD_HZRD_RAW_RAW_IHFLDO_OVI_SHIFT                4
#define    ANA_AUDIO_REG_AUD_HZRD_RAW_RAW_IHFLDO_OVI_MASK                 0x00000010
#define    ANA_AUDIO_REG_AUD_HZRD_RAW_RAW_EARHSLDO_OVI_SHIFT              3
#define    ANA_AUDIO_REG_AUD_HZRD_RAW_RAW_EARHSLDO_OVI_MASK               0x00000008
#define    ANA_AUDIO_REG_AUD_HZRD_RAW_RAW_ANALDO_OVI_SHIFT                2
#define    ANA_AUDIO_REG_AUD_HZRD_RAW_RAW_ANALDO_OVI_MASK                 0x00000004
#define    ANA_AUDIO_REG_AUD_HZRD_RAW_RAW_HS_SC_R_SHIFT                   1
#define    ANA_AUDIO_REG_AUD_HZRD_RAW_RAW_HS_SC_R_MASK                    0x00000002
#define    ANA_AUDIO_REG_AUD_HZRD_RAW_RAW_HS_SC_L_SHIFT                   0
#define    ANA_AUDIO_REG_AUD_HZRD_RAW_RAW_HS_SC_L_MASK                    0x00000001

#endif /* __BRCM_RDB_ANA_AUDIO_REG_H__ */


