ccflags-y += -DMHL_VERSION_MAJOR="$(PRODUCT_MHL_VER_MAJOR)"
ccflags-y += -DMHL_VERSION_MINOR="$(PRODUCT_MHL_VER_MINOR)"
ifneq ($(FEATURE_SUPPORT_UNPOWERED_DONGLE), true)
ccflags-y += -DMHL_SUPPORT_UNPOWERED_DONGLE
endif

ifeq ($(MHL_SUPPORT_CHG_TIMING), true)
ccflags-y += -DSUPPORT_CHG_TIMING
endif

ccflags-y += -DMHL2_DRIVE_STRENGTH_DP_CTL1="$(word 1, $(DS_PARAM))"
ccflags-y += -DMHL2_DRIVE_STRENGTH_DP_CTL6="$(word 2, $(DS_PARAM))"
ccflags-y += -DMHL2_DRIVE_STRENGTH_DP_CTL7="$(word 3, $(DS_PARAM))"
ccflags-y += -DMHL2_DRIVE_STRENGTH_DP_CTL8="$(word 4, $(DS_PARAM))"
ccflags-y += -DMHL2_DRIVE_STRENGTH_COC_CTL1="$(word 5, $(DS_PARAM))"
ccflags-y += -DMHL3_DRIVE_STRENGTH_DP_CTL1="$(word 6, $(DS_PARAM))"
ccflags-y += -DMHL3_DRIVE_STRENGTH_DP_CTL6="$(word 7, $(DS_PARAM))"
ccflags-y += -DMHL3_DRIVE_STRENGTH_DP_CTL7="$(word 8, $(DS_PARAM))"
ccflags-y += -DMHL3_DRIVE_STRENGTH_DP_CTL8="$(word 9, $(DS_PARAM))"
ccflags-y += -DMHL3_DRIVE_STRENGTH_COC_CTL1="$(word 10, $(DS_PARAM))"

obj-m +=  mhl_sii8620_8061_drv.o


#BIST Support
ifeq ($(CFG_MHL_BIST),true)
ccflags-y += -DMHL_BIST
mhl_sii8620_8061_drv-objs := mhl_sii8620_bist.o
endif

ccflags-$(SOMC_CFG_MHL_HPD_PUSH_PULL) += -DMHL_UPSTREAM_HPD_PUSH_PULL
ccflags-$(SOMC_CFG_MHL_HPD_ACTIVE_HIGH) += -DMHL_HPD_UPSTREAM_HDMI_IS_HIGH_TRIGGER

ccflags-y += -DMHL_DEVICE_ID="$(PRODUCT_MHL_DEVICE_ID)"

mhl_sii8620_8061_drv-objs += mhl_driver.o mhl_tx.o mhl_sii8620_8061_device.o mhl_sii8620_device_edid.o mhl_lib_edid.o mhl_cbus_control.o mhl_tx_rcp.o mhl_lib_infoframe.o mhl_lib_timer.o mhl_cbus_write_burst.o mhl_support_unpowered_dongle.o

