EXTRA_CFLAGS  += -Wall -Wstrict-prototypes -Wno-trigraphs
EXTRA_CFLAGS  += -Werror
EXTRA_CFLAGS  += -Idrivers/videocore/host_support/include

obj-$(CONFIG_VC_OVL) := vc-ovl.o

vc-ovl-objs := vc_ovl.o
